### ISSUE TITLE
seekToPlayer throwing exception on Android

### ISSUE THREAD

**Issue by derTuca** [dooboolab/flutter_sound#10]
### Version of flutter_sound
1.1.5
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14 18A391, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] VS Code (version 1.28.2)
[✓] Connected device (1 available)

• No issues found!

seekToPlayer throws exception on Android (because the Dart code sends the 'seekToPlayer' method name while the Android code listens for 'seekPlayer'. Problem only occurs on Android.

**Comment by dooboolab** [comment]
Sorry I can't handle this immediately since I'll be off for two weeks from now for personal schedule. Hope you can debug yourself and give `PR` for this one. It isn't hard to test in `Example` project.
