### ISSUE TITLE
Recording audio without access to external storage permission

### ISSUE THREAD

**Issue by pyzenberg** [dooboolab/flutter_sound#100]
### Version of flutter_sound
1.4.1

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Proxy Configuration
[✓] Connected device (1 available)

• No issues found!

### Platforms you faced the error (IOS or Android or both?)
Android and presumably IOS

### Expected behaviour
Write into temporary directory provided by `path_provider` without requiring access to external storage.

### Actual behaviour
`Unhandled Exception: Exception: PlatformException(FlutterSoundPlugin, NO PERMISSION GRANTED, android.permission.RECORD_AUDIO or android.permission.WRITE_EXTERNAL_STORAGE)`

### Tested environment (Emulator? Real Device?)
Real Device with Android 7.0

### Steps to reproduce the behavior
```
Directory tempDir = await getTemporaryDirectory();
final ms = DateTime.now().millisecondsSinceEpoch.toString();
final audioFileName = '${tempDir.path}/$ms.m4a';
_outputAudioPath = await flutterSound.startRecorder(audioFileName);

```

**Comment by hyochan** [comment]
This is expected. You should grant the permission before using `permission` plugin in flutter.

**Comment by pyzenberg** [comment]
Thanks for your reply and great work.
I'm new to mobile development and probably I'm unaware of some in depth concept but I used `path_provider` without any special permission before and want to know (if possible), to save `startRecorder()` output's into temp file provided by `path_provider` package. Is it possible?

**Comment by hyochan** [comment]
Try using permission plugin like [flutter_permission_handler](https://github.com/BaseflowIT/flutter-permission-handler)
```
Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler().requestPermissions([PermissionGroup.storage]);
```

Before saving it to storage.

**Comment by pyzenberg** [comment]
Sorry, I think I won't deliver my intention. You are right, I workaround the issue by asking permission from user.
But my original question was, is it possible to get a `File()` instance without writing it to storage? (i.e. in-memory file or a temp file using `getTemporaryDirectory()`)
