### ISSUE TITLE
May I ask, the error was reported when the file path was uploaded:：FileSystemException: Cannot retrieve length of file

### ISSUE THREAD

**Issue by Yxliam** [dooboolab/flutter_sound#101]
May I ask, the error was reported when the file path was uploaded:：FileSystemException: Cannot retrieve length of file

**Comment by hyochan** [comment]
Could you provide more detail? I can't be helpful with your question since I'm not getting any.

**Comment by ShshyDevooo** [comment]
I have also get the error. Did you solve this error?
