### ISSUE TITLE
How can I copy default file sound.m4a to another directory???

### ISSUE THREAD

**Issue by bunmengteang** [dooboolab/flutter_sound#102]
I cannot copy default sound file sound.m4a to my own directory.
How to do copy it??

**Comment by Igalsr** [comment]
did you try something like this? 

final directory = await getApplicationDocumentsDirectory();
    debugPrint('Application Documets doc ${directory.path}');

    int now = DateTime.now().millisecondsSinceEpoch;
    DateTime date = new DateTime.fromMillisecondsSinceEpoch(now, isUtc: true);
    String dateString = DateFormat('MMM_d_yyyy_HH_mm_ss', 'en_GB').format(date);

    setState(() {
      _mRecordingFileName = dateString+'.mp4';
    });

    _mRecordingLocation = '${directory.path}/$_mRecordingFileName';
    debugPrint('path $_mRecordingLocation');
