### ISSUE TITLE
playback not working as valid file

### ISSUE THREAD

**Issue by KsAmJ** [dooboolab/flutter_sound#105]
i used the recording but audio file was very garbage so i found on the issues a solution to use 

`flutterSound.startRecorder(null, androidEncoder: AndroidEncoder.AMR_NB, numChannels:2, bitRate:128000);`

which is recording nice but the playback is not working as a Normal Valid m4a 

previously was ok and playing on iTunes and even HTML5 audio tag before using the Encoder

how to fix this?

**Comment by hyochan** [comment]
Could you provide some code? I am confused with your question.

**Comment by ksamj** [comment]
well the file created on android is not playable with iTunes or HTML5 as an embed if i am using the `androidEncoder: AndroidEncoder.AMR_NB` but if i am not using this encoder the file is not in good quality and garaged sound

**Comment by MsXam** [comment]
@hyochan  I believe this is to do with what I have written here : 

https://github.com/dooboolab/flutter_sound/issues/95#issuecomment-506665704
