### ISSUE TITLE
'AudioSessionSetProperty' is deprecated: first deprecated in iOS 7.0 - no longer supported

### ISSUE THREAD

**Issue by darrenmothersele** [dooboolab/flutter_sound#106]
### Version of flutter_sound

1.4.1

### Platforms you faced the error (IOS or Android or both?)

Deprecation warning. 

### Actual behavior

```
pub.dartlang.org/flutter_sound-1.4.1/ios/Classes/FlutterSoundPlugin.m:207:3: 'AudioSessionSetProperty' is deprecated: first deprecated in iOS 7.0 - no longer supported
```

### Tested environment (Emulator? Real Device?)

xCode on MacOS (High Sierra). iPhone Simulator.

### Steps to reproduce the behavior

Build the project in xCode.

**Comment by junaidShaikh** [comment]
This solved the issue for me:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
```
^Setting the target swift version to 4.2.

To the author, this error mostly happened because of a swift 5.0 conflict.
