### ISSUE TITLE
音频格式问题

### ISSUE THREAD

**Issue by shuaiwang007** [dooboolab/flutter_sound#108]
iOS默认生成的音频是 .m4a格式的，我想把它改成其他格式的（比如：MP3等），在哪里改呢

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/59966120-70923e00-9552-11e9-95d0-fb4d704e353b.png)

You should do this currently in your backend using such library like [ffmpeg](https://ffmpeg.org/)

![image](https://user-images.githubusercontent.com/27461460/59966129-928bc080-9552-11e9-9468-cb8d4d005452.png)
