### ISSUE TITLE
How to convert the .m4a file to .mp4 or .mp3

### ISSUE THREAD

**Issue by VictorUvarov** [dooboolab/flutter_sound#109]
I was wondering if it is possible to use the default recording file and convert it to .mp3/.mp4 or write to a .mp3/.mp4 file when recording.

### Version of flutter_sound
flutter_sound: ^1.4.2

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by bhanuka96** [comment]
@Larpoux can convert into mp4?

**Comment by Larpoux** [comment]
Sure.
You can look to [the compatibility table](http://www.canardoux.xyz/tau_sound/doc/pages/flutter-sound/api/topics/guides_codec.html)

**Comment by Larpoux** [comment]
MP4 player is implemented : 
- On Android
- On iOS

MP4 recorder is implemented:
- on Android (with an internal format conversion)
- on iOS

MP3 player is supported 
- on iOS
- on Android

MP3 recorder is not supported.
You will have to record to Wave file and call the _convert()_ to convert the Wave to MP3

**Comment by Larpoux** [comment]
@bhanuka96 : 

MP4 player is implemented : 
- On Android
- On iOS

MP4 recorder is implemented:
- on Android (with an internal format conversion)
- on iOS

MP3 player is supported 
- on iOS
- on Android

MP3 recorder is not supported.
You will have to record to a Wave file and call the _convert()_ to convert the Wave to MP3
