### ISSUE TITLE
Android stop record 

### ISSUE THREAD

**Issue by bunmengteang** [dooboolab/flutter_sound#113]
I am using version : 1.4.2
In Android when click stop record, got error:

I/MediaRecorder(23863): stop
I/MediaRecorder(23863): enter in file frameworks/av/media/libmedia/mediarecorder.cpp, function stop, line 559
I/IMediaRecorder(23863): stop (BpMediaRecorder client) in file frameworks/av/media/libmedia/IMediaRecorder.cpp, function stop, line 293
I/MediaRecorder(23863): exit in file frameworks/av/media/libmedia/mediarecorder.cpp, function stop, line 585
I/HwMediaRecorderImpl(23863): sendStateChangedIntent, state=1
I/flutter (23863): stopRecorder: recorder stopped.

**Comment by hyochan** [comment]
Please try the recent version which is `1.4.4`. I've just tried and couldn't reproduce this.
