### ISSUE TITLE
Audio file not exist on IOS

### ISSUE THREAD

**Issue by Denmal1982** [dooboolab/flutter_sound#12]
File created by the library is not available in ios:

`String path = await flutterSound.startRecorder(null);
  _file = io.File(path);`
path in mobil file:///private/var/mobile/Containers/Data/Application/2272A03E-2497-416C-98EC-69109A431A8B/tmp/sound.m4a

If you need to specify permissions in ios or what path to add?

**Comment by dooboolab** [comment]
Thanks for sharing your experience. I might have to check this one out.
