### ISSUE TITLE
Updated doc to reflect that you must be playing before you can seek.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#120]
### ^1.4.2

Expected behaviour
Position the seek position before starting the player.

Actual behaviour
You must start the player before attempting to seek.

Ideally you should be able to pre-position the seek position before starting the player.
If this is not possible we should update the doco in the read me to reflect the fact that you need to be playing before you attempt to start the player.

The error message also needs to be improved as current message is not a all informative.

**Comment by bsutton** [comment]
I've sent a push request that attempts to resolve this issue.
#121

**Comment by alby97** [comment]
Hi, this feature will be implemented in the future? I think that is an useful feature for developers.
