### ISSUE TITLE
why audio format is mp4 ?

### ISSUE THREAD

**Issue by m4xb0** [dooboolab/flutter_sound#122]
Hello
a question
why the format of the audio is mp4 and not mp3

**Comment by hyochan** [comment]
`mp4` is `default` extension in `android` and `mp3` is not supported without any third-party library. Currently, we don't have that much resource in our plugin to dig into more `third-party` libraries that aren't sure if it works in all devices.

**Comment by m4xb0** [comment]
okay thank
