### ISSUE TITLE
if i  start recode and stop recode screen is flash  only first execution

### ISSUE THREAD

**Issue by jabonge** [dooboolab/flutter_sound#124]
From the second time on, the screen does not flash 
i give a url to startrecoder null (defalut) 
can you know Why does this happen?
i think it is not related rebuild and setstate

**Comment by jabonge** [comment]
my phone is android

**Comment by hyochan** [comment]
I couldn't reproduce this in `example` project which is only app I am debugging on. I hope you could provide more information that I can dig into. Writing something that runs on `example` would be best.

**Comment by jabonge** [comment]
sorry it is my mistake thx for your attention
