### ISSUE TITLE
Super weird conflict bug with Flutter video_player on iOS

### ISSUE THREAD

**Issue by GraphicSound** [dooboolab/flutter_sound#126]
First of all, this bug only shows on iOS.

I'm writing a language learning app. So on one page, I'll play a short video first using Flutter video_player. Then I use flutter_sound to record the user's voice which allows them to practice speaking.

But most of the time, right after I start the recorder, the app will play the previous video's audio! Sometimes it's the whole audio being played and other times it's just a portion of it. And if I stop recording, the video's audio will be played again.

I've already made sure that the video player controller has been disposed. It looks like a cache or buffer issue?

**Comment by hyochan** [comment]
I can't currently tell this `symptom`. I might have to have a chance of using both.

**Comment by ozzy1873** [comment]
I have noticed possibly related behavior on Android. When there are two players on the same page, they interact with each other. If you start playing one recording then start playing the second recording before the first is finished, the second recording does not play and the current position of both players seem to be synchronized.
