### ISSUE TITLE
Cannot play local audio file

### ISSUE THREAD

**Issue by Iamstanlee** [dooboolab/flutter_sound#129]
I can't seem to figure out how to play local audio files on android, playing remote files works fine.
I get this error when trying to play audio file from the app's temp directory

E/FlutterSoundPlugin(23217): Player is already running. Stop it first.
I/flutter (23217): result: player is already running.

**Comment by bsutton** [comment]
I had this problem if I wasn't shutting down the player correctly between invocations.

**Comment by hyochan** [comment]
@Iamstanlee Did the answer helped?

**Comment by Iamstanlee** [comment]
> @Iamstanlee Did the answer helped?

no, i shut down the player ,stilll didnt work

**Comment by hyochan** [comment]
@Iamstanlee Actually I've quickly reviewed all the remaining issues yesterday and I couldn't reproduce this one. Could you also try the `example` project?

**Comment by jabonge** [comment]
l also dont play my custom local audio file but default url play well

**Comment by Iamstanlee** [comment]
> @Iamstanlee Actually I've quickly reviewed all the remaining issues yesterday and I couldn't reproduce this one. Could you also try the `example` project?

I'm trying to play an audio file located at  `/data/com.application.id/app_flutter/audio.mp3` , I'm passing this path to the startPlayer method `_flutterSound.startPlayer(pathToLocalFile)`

**Comment by JaimilPatel** [comment]
I am facing issue while playing .m4a audio file on Android device as not able to play local audio file.So if anyone found a good work around to solve the issue then please  update here
