### ISSUE TITLE
Can we get a 1.2 release pushed to the repos?

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#130]
### 1.1.0

There are now quite a lot of code changes since the 1.1.0 release.

Would it be possible for you to push a new release?

**Comment by hyochan** [comment]
Currently, the released version is `1.4.4`. Am I not understanding something?

**Comment by bsutton** [comment]
Sorry wrong release no.

I gather you have just release 1.4.5 which I assume covers the latest pull requests.
If that is so, then you have resolved my question.
