### ISSUE TITLE
How to specify custom path to startRecorder method

### ISSUE THREAD

**Issue by alby97** [dooboolab/flutter_sound#134]
### Version of flutter_sound 
^1.4.4

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows
    [Versione 10.0.18362.356], locale it-IT)
 
[√] Android toolchain - develop for Android devices (Android SDK    
    version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific      
      functionality.
    X Dart plugin not installed; this adds Dart specific
      functionality.
[√] VS Code (version 1.38.1)
[√] VS Code, 64-bit edition
[√] Connected device (1 available)

! Doctor found issues in 1 category.

Hi, I'm trying to specify the path to startRecorder method but it didn't work. If I put "null" as parameter it works. There are any solutions for this? Thanks.

**Comment by hyochan** [comment]
Please try `1.4.7` which resolves this issue.

**Comment by alby97** [comment]
I upgraded at version 1.4.7 but it didn't resolve this issue. I tried to specify 'audio.m4a' in startRecord method but the recording didn't begins.

**Comment by alby97** [comment]
This is my code:
` _path = await flutterSound.startRecorder('audio.m4a');`
`print("Ok")`

It seems like startRecorder didn't work, like for older version when I try to specify a custom path, in fact it didn't print "Ok".By the other side I didn't modified anything like I see in the example folder. I didn't understand why.

**Comment by hyochan** [comment]
@alby97 Did you try the `example` project?

**Comment by alby97** [comment]
I tried now but it didn't started. This is the error:

 Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "C:\Users\alby9\Desktop\EsempiAppFlutter\flutter_sound\example\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\alby9\Desktop\EsempiAppFlutter\flutter_sound\example\android\app\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> versionCode not found. Define flutter.versionCode in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\Users\alby9\Desktop\EsempiAppFlutter\flutter_sound\example\android\gradlew.bat app:properties

**Comment by hyochan** [comment]
Ok~! `android` didn't have the `default` `dir` location provided. I've just put this now in `1.4.8`. Please try this.

**Comment by alby97** [comment]
Sorry but even with 1.4.8 didn't work, it gave me the same error that I posted in my previous answer.

**Comment by hyochan** [comment]
Please see the example project and see how I have specified the path!

**Comment by alby97** [comment]
I understand but this error keeps showing. I cloned the 1.4.8 version from your repository and triyng to run the example but this is the error when I try to run it.

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> 
> * Error running Gradle:
>   ProcessException: Process "C:\Users\alby9\Desktop\EsempiAppFlutter\flutter_sound\example\android\gradlew.bat" exited abnormally:
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'C:\Users\alby9\Desktop\EsempiAppFlutter\flutter_sound\example\android\app\build.gradle' line: 16
> * What went wrong:
>   A problem occurred evaluating project ':app'.
> 
> > versionCode not found. Define flutter.versionCode in the local.properties file.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> Command: C:\Users\alby9\Desktop\EsempiAppFlutter\flutter_sound\example\android\gradlew.bat app:properties

**Comment by hyochan** [comment]
Please see the readme https://github.com/dooboolab/flutter_sound#debug

**Comment by alby97** [comment]
Ok, now the example run properly and it seems now work properly also in my project with version 1.4.8. Thank you so much for helping me, I appreciate that. Have a good day.

**Comment by hyochan** [comment]
Great to hear that!
