### ISSUE TITLE
Pause/Resume playback is broken in the demo as of 1.4.4 (worked fine in 1.4.2)

### ISSUE THREAD

**Issue by jam33** [dooboolab/flutter_sound#135]
### Version of flutter_sound
1.4.4 and 1.4.5

## flutter doctor
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at D:\Business\Flutter\flutter_sdk178\flutter
    • Framework revision b712a172f9 (2 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\JM\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\JM\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • FRD L14 • 2DD0216C03001143 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Playback pauses, then resumes after clicking play

### Actual behavior
Playback pauses, when clicking play you get:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Instance of 'PlayerRunningException'`

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Use the demo against v1.4.4 of the plugin.  Record audio.  Hit play.  Pause while playing.  Try to resume playing by hitting play again.

**Comment by hyochan** [comment]
Thanks for the report! It's resolved in `1.4.6`.
