### ISSUE TITLE
Play an exception in IOS

### ISSUE THREAD

**Issue by hanj315** [dooboolab/flutter_sound#14]
In ios 12.0.1, in the example, the first recorded resource is always played.
(Besides the first play is normal, other play is noise)

**Comment by dooboolab** [comment]
@hanj315 Could you be more specific? I don't quite get your situation. What was your step to reproduce this?

**Comment by hanj315** [comment]
@dooboolab I'm sorry I didn't describe the problem clearly.
**run flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[!] VS Code (version 1.19.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**my operation steps：**
· Open example/ios/Runner.xcworkspace with Xcode, set up signing, open example with IntelliJ IDEA, connect Mac computer with IOS 12.0.1 mobile phone, and click to run and install.
Later operations such as:
· Click the Record button to display the recording time 00:02:57, click the play button, display and play 00:02:55 normally;
· Then, click the recording button, showing the recording time at 00:05:91, click the play button, showing the play at 00:02:55, actually playing more than two seconds of murmur;
· After that, click the recording button, showing the recording time at 00:00:78, click the playback button, showing the playback time at 00:02:55, actually playing less than a second of the murmur.

I use the simulator, when deleting files, it will still show the first playing time of the murmur. I just started learning about mobile development, but I don't know much about it. I feel it is caused by the default cache mechanism of ios. I think using new Builder with different keys should be able to solve this problem.

**Comment by Basim-Elayan** [comment]
I have the same issue.

**Comment by dooboolab** [comment]
Please try version above `1.2.0`. Thanks.

**Comment by Basim-Elayan** [comment]
Yes, It's working right now, Thanks.
