### ISSUE TITLE
startPlay very slow

### ISSUE THREAD

**Issue by 008v** [dooboolab/flutter_sound#149]
When the URL is a remote address, the playback is very slow.

After looking at the source code found that the need to download to the local first.

Doesn't it support streaming?

**Comment by hyochan** [comment]
It doesn't support streaming currently. Sorry for that 😢

**Comment by liaobushi520** [comment]
> It doesn't support streaming currently. Sorry for that 😢
it can play remote resource  ,but  block main thread

**Comment by hyochan** [comment]
We now support this from `1.9.0`. Start player from buffer!
