### ISSUE TITLE
PlatformException(FlutterSoundPlugin, NO PERMISSION GRANTED, android.permission.RECORD_AUDIO or android.permission.WRITE_EXTERNAL_STORAGE)

### ISSUE THREAD

**Issue by gabrielpacheco23** [dooboolab/flutter_sound#15]
I'm getting this error while trying to use **flutter_sound**. All others permissions are granted right, but "WRITE_EXTERNAL_STORAGE", it says:
```
I/flutter (18339): startRecorder error: Exception:
PlatformException(FlutterSoundPlugin, NO PERMISSION GRANTED,
android.permission.RECORD_AUDIO or android.permission.WRITE_EXTERNAL_STORAGE)
D/AndroidRuntime(18339): Shutting down VM
E/AndroidRuntime(18339): FATAL EXCEPTION: main
E/AndroidRuntime(18339): Process: com.example.nw, PID: 18339
E/AndroidRuntime(18339): java.lang.RuntimeException: Failure delivering result
ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent {
act=android.content.pm.action.REQUEST_PERMISSIONS
VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras)
}} to activity {com.example.nw/com.example.nw.MainActivity}:
java.lang.IllegalStateException: Reply already submitted
```
I've already tried append `tools:remove="androidSdkVersion"` or `tools:node="replace"` to `uses-permission` in AndroidManifest.xml.

**Comment by dooboolab** [comment]
Hi there. I've already replied through the LinkedIn message. Try to request permission on runtime. You can use [simple_permission](https://pub.dartlang.org/packages/simple_permissions) plugin for this.

**Comment by gabrielpacheco23** [comment]
Hello. I did request permissions on runtime, but it doesn't show the request dialog, just set denied (never ask). I was wondering if its needed to have a SD card in my phone to use this plugin, because i don't have one. If it is, what should I do to redirect the storage path for my phone internal storage?
Thanks for replying.

**Comment by dooboolab** [comment]
Then, the best way is to compare your sourcecode with that in example project. Check all the files like manifest, gradle and etc.

**Comment by gabrielpacheco23** [comment]
I've got it! I don't really know the real problem but I could fix it just creating a new Flutter project and copying all the files to the new one. Thanks for the support!
