### ISSUE TITLE
Make File() from record

### ISSUE THREAD

**Issue by kleinpetr** [dooboolab/flutter_sound#151]
When I am trying make File() from record path I have got exception on iOS like this

```
String _recordPath = await _flutterSound.startRecorder('record.m4a', iosQuality: IosQuality.MAX, androidEncoder: AndroidEncoder.AMR_WB);

...... //some logic

await _flutterSound.stopRecorder();

File recordFile = File(_recordPath);
print(recordFile.length());
```

`flutter: FileSystemException: Cannot retrieve length of file, path = 'path/to/record.m4a' (OS Error: No such file or directory, errno = 2)`

On Android working fine.

**Comment by db-rdz** [comment]
It looks like the flutter_sound package returns a path like this "file:///var/mobile/Containers/Data/Application/A2251D....." if you take off "file://" I think you should be able to open the file using the File class. 

You could maybe do something like the following:

`final File _audio = Platform.isIOS ? File(location.replaceAll("file://", '')) : File(location);`

**Comment by kleinpetr** [comment]
This is because the plugin returns URI instead of PATH. It is in documentation, but I didn't know that's different. So the solution is 

`File.fromUri(Uri.parse(recordedUri))`

this is worked for both platforms
