### ISSUE TITLE
Get audio samples instead of writing to a temp file

### ISSUE THREAD

**Issue by sysebert** [dooboolab/flutter_sound#154]
### Request
I'm looking to get the microphone stream's raw samples so that I can pass it on to streaming speech-to-text in real time vs. having to record the audio and then send it.

I assume it shouldn't be too tricky since you're already encoding those audio samples to a file, but it would be great to expose that functionality.

### Version of flutter_sound
1.5.2

**Comment by ChandlerParsons** [comment]
Do you have any alternative plugins to achieve this function?

**Comment by hyochan** [comment]
Ok the streaming isn't supported yet. Sorry about that. I'd be happy if someone gives it a try.

**Comment by Larpoux** [comment]
Maybe I could look to this in the next few weeks, and report what would be possible to do for that

**Comment by Larpoux** [comment]
Hi @sysebert,

Please, tell me a few things:
- What "speech-to-text" library, or cloud service you want to use ?
- Do you need to encode your stream, and with which encoder ?
- Do you have a time dead-line limit to have an implementation ? (we can have an interface specification soon, but probably an implementation much later)

**Comment by sysebert** [comment]
I’m sad I missed this message :(

I'm looking to use the Google one. I don't need to encode it other than it's 16bit 16khz/mono. 

Time is flexible, but for all I know you have done it already!

**Comment by Larpoux** [comment]
Yes, I think also that it would be very useful to have access to the audio-stream during the recording, and not after.
Maybe in a future version ?
