### ISSUE TITLE
Can't record sound on ios.

### ISSUE THREAD

**Issue by ShshyDevooo** [dooboolab/flutter_sound#158]
### Version of flutter_sound
1.5.2
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
Can record the sound successful and the record file can reach.
### Actual behavior
After i record the sound and i check if the file is exists by invoke File.exists() the result is always false
### Tested environment (Emulator? Real Device?)
Real Device iphone 6
### Steps to reproduce the behavior
StartRecord:
` Future<String> record(String path) async{
    return  _flutterSound.startRecorder(path,
        androidEncoder: AndroidEncoder.AMR_WB,
        androidOutputFormat: AndroidOutputFormat.AMR_WB,
        iosQuality: IosQuality.MEDIUM);
  }`
StopRecord and check
`FlutterSoundPlayer.getInstance().stopRecord();
    if (!cancelSend) {
      if (recordFilePath != null && recordFilePath.isNotEmpty) {
        if (Platform.isIOS) {
          appPrint("ios:$recordFilePath");
          File file = File(recordFilePath);
          if (await file.exists()) {
            widget.sendFileCallback(recordFilePath);
          } else {
            Fluttertoast.showToast(msg: "failed");
          }
        } else if (Platform.isAndroid) {
          appPrint("android:$recordFilePath");
          String fullDirPath = (await getExternalStorageDirectory()).path;
          String prefixPath =
              fullDirPath.substring(0, fullDirPath.indexOf("/Android"));
          String filePath = "$prefixPath/$recordFilePath";
          File file = File(filePath);
          if (await file.exists()) {
            widget.sendFileCallback("$prefixPath/$recordFilePath");
          } else {
            Fluttertoast.showToast(msg: "failed");
          }
        }
      }
    }`

**Comment by kbanta11** [comment]
I'm running into the same issue and it seems to only be affecting ios (it works on android).  On ios the file doesn't seem to save (or seems to save to a different location other than the path provided to the startRecorder() function.

**Comment by Quving** [comment]
Im having the same problem. On my Android phone everything works fine but on ios it does not. I dug on that problem and discovered, that the file. (``` File file = File('path'```) is going to stuck at that line. Maybe ios does have another handling of permissions on the newest ios-versions? 
Or other/new path and directory handling? I dont know. :))

**Comment by hyochan** [comment]
<img width="296" alt="Screen Shot 2019-12-07 at 11 30 07 PM" src="https://user-images.githubusercontent.com/27461460/70376183-8604f400-1949-11ea-8ca0-d18a9a0c6070.png">

Tested in ios 12 and 13 and seems to be working. Have you tried our example project?

**Comment by Quving** [comment]
I think, that does not work on myphone because I pass the Android-Encoder....

**Comment by AdnanKazi** [comment]
`MissingPluginException(No implementation found for method isEncoderSupported on channel flutter_sound)`

Cannot record in IOS 13
