### ISSUE TITLE
Error "stop failed: -1007" when trying to stop recording suddenly

### ISSUE THREAD

**Issue by sayhicoelho** [dooboolab/flutter_sound#159]
### Version of flutter_sound
1.5.2

## flutter doctor
OK

### Platforms you faced the error (IOS or Android or both?)
Android (not tested in iOS)

### Expected behavior
The recorder should stops instead of suddenly throws an error.

### Actual behavior
The lib throws an error "stop failed: -1007" if you stop recording after starting it (in a range of milliseconds)

### Tested environment (Emulator? Real Device?)
Emulator and real device

### Steps to reproduce the behavior
Just create a button to start recording when holding it and stop recording after released it. Try to tap the button many times and you'll see the "stop failed: -1007" error.

### Screenshot
![image](https://user-images.githubusercontent.com/8188365/69457069-fc4f0700-0d4a-11ea-9e4b-b16e284a06b1.png)

**Comment by sayhicoelho** [comment]
The lib "audio_recorder" has the same issue. You can see it here: https://github.com/ZaraclaJ/audio_recorder/issues/40

**Comment by hyochan** [comment]
![8UL05vbSVR](https://user-images.githubusercontent.com/27461460/70376094-a3858e00-1948-11ea-8737-4d3c583fa031.gif)

How can I reproduce this again?
