### ISSUE TITLE
Getting wrong time

### ISSUE THREAD

**Issue by deepak-gehlot** [dooboolab/flutter_sound#16]
minute is always 30.

**Comment by dooboolab** [comment]
Could you be more specific? I need to understand the problem to help this out.

**Comment by deepak-gehlot** [comment]
![device-2018-12-01-144151](https://user-images.githubusercontent.com/21275502/49326382-69382280-f577-11e8-9783-7519724cadaf.png)
 see in red circle, getting 30 but its wrong

**Comment by deepak-gehlot** [comment]
And one more thing recording not starting first time when click on icon, it ask for permission and if you allow permission after that nothing happen, you need to click twice first time.

**Comment by dooboolab** [comment]
Related #14
