### ISSUE TITLE
example doesn't build android

### ISSUE THREAD

**Issue by sgehrman** [dooboolab/flutter_sound#163]
I added 
flutter.versionCode=1.2.2
flutter.versionName=32

but it still didn't build

$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.4s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/home/steve/google/flutter_sound/example/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/steve/google/flutter_sound/example/android/app/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> versionCode not found. Define flutter.versionCode in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /home/steve/google/flutter_sound/example/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.
steve@tr4:~/google/flutter_sound/example$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.4s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/home/steve/google/flutter_sound/example/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/steve/google/flutter_sound/example/android/app/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':app'.
> versionName not found. Define flutter.versionName in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /home/steve/google/flutter_sound/example/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.
steve@tr4:~/google/flutter_sound/example$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.4s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/home/steve/google/flutter_sound/example/android/gradlew" exited abnormally:

  Command: /home/steve/google/flutter_sound/example/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.

**Comment by hyochan** [comment]
This is issue on flutter side not ours. Try to add below in `local.properties`
```
flutter.versionName=1.0.0
flutter.versionCode=1
flutter.buildMode=debug
```
