### ISSUE TITLE
Cannot repeat play or recording

### ISSUE THREAD

**Issue by DoctorVirginia** [dooboolab/flutter_sound#164]
### Version of flutter_sound
^1.5.2
### Platforms you faced the error (IOS or Android or both?)
Android emulator VSCode
### Expected behavior
Expect to be able to replay recorded audio repeatedly until a new recording overwrites it. could utilise seekToPlay (does nothing) or PlayerStatus properties (ca't access at all), or _isPlaying or _isRecording property, but these do not work. 
### Actual behavior
recorded audio can only be played once. Repeat startPlayer does not play anything. It seems recording s to buffer,and this is cleared immediately after playing. How can this be avoided,or reset?
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
as above. tried all.

**Comment by hyochan** [comment]
Could you try to `stopPlayer` before `startPayer`?

**Comment by hyochan** [comment]
Also try out for our `example`
