### ISSUE TITLE
为什么不生成mp3文件呢

### ISSUE THREAD

**Issue by ztj666** [dooboolab/flutter_sound#17]
mp4后端无法直接播放

**Comment by ginoz** [comment]
是遇到android录制的在web或者ios上面无法播放的问题。留意一下安卓端录制使用的默认格式，换成AAC可能会解决这个问题。
![image](https://user-images.githubusercontent.com/622877/49567630-420f9580-f969-11e8-8906-1c02f9d74aad.png)

**Comment by dooboolab** [comment]
Sorry I can't understand your language.
