### ISSUE TITLE
Audio does not record when screen locks

### ISSUE THREAD

**Issue by efhilton** [dooboolab/flutter_sound#171]
### Version of flutter_sound
1.5.2

### Platforms you faced the error (IOS or Android or both?)
Android 

### Expected behavior
Keep recording even when the screen times out.

### Actual behavior
Recording continues, but mic audio cuts off when Android times out .   For example, if you record an hour long presentation, you'll find that the output file is one hour long, but there is only 1 minute of usable audio, and 59 minutes of total silence.

### Tested environment (Emulator? Real Device?)
Real Device.

### Steps to reproduce the behavior
Start recording, let Android time out while you are recording.  After  a few minutes, stop the recording, and listen to the output.

**Comment by hyochan** [comment]
In progress #202

**Comment by hyochan** [comment]
The current feature is released in `3.0.0`

**Comment by efhilton** [comment]
U rock! Than you! Will try in a few days and let you know if there are any other problems.

**Comment by akshay-kapase** [comment]
Facing the same issue in 9.10.4
