### ISSUE TITLE
No sound on Android Simulator

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#173]
Just a stupid question, but I did not found the answer on Google:

I do not have audio on an Android Simulator when I play from flutter_sound.
The UI works fine, showing the time elapsed, but no sound. I can live with that, but if someone has an answer to this question I will congratulate him/her

**Comment by hyochan** [comment]
Can you try [this](https://stackoverflow.com/a/8262747)?

**Comment by Larpoux** [comment]
My problem is fixed. It was not a problem with playback audio but a problem with the microphone which was not enabled on my virtual device.
