### ISSUE TITLE
run in ios  async is blocking

### ISSUE THREAD

**Issue by shoushouxiongying** [dooboolab/flutter_sound#176]
run demo is this question,run in my project is also

**Comment by shoushouxiongying** [comment]
I will pop up a pop-up box when recording, and a problem will appear at this time. The pop-up box will wait for the recording stoprecord event to complete before executing the UI update

**Comment by shoushouxiongying** [comment]
Blocking UI updates,no async

**Comment by shoushouxiongying** [comment]
I'll record a video. Please watch it

https://pan.baidu.com/s/1Ww9eySknppNMtfLctjdTNQ

**Comment by shoushouxiongying** [comment]
Android doesn't have this problem

**Comment by shoushouxiongying** [comment]
The IOS simulator does not have this problem. The test shows this problem in IOS 12.2 real environment. Other IOS versions are not tested

**Comment by shoushouxiongying** [comment]
I will pop up a pop-up box when recording, and a problem will appear at this time. The pop-up box will wait for the recording stoprecord event to complete before executing the UI update

Blocking UI updates,no async

I'll record a video. Please watch it

https://pan.baidu.com/s/1Ww9eySknppNMtfLctjdTNQ

Android doesn't have this problem

The IOS simulator does not have this problem. The test shows this problem in IOS 12.2 real environment. Other IOS 13 versions are not  this problem

**Comment by hyochan** [comment]
I couldn't see your video. Please provide an actual URL that directs to actual file without linking to any other third party platform.
