### ISSUE TITLE
this.model.getMediaRecorder() always null

### ISSUE THREAD

**Issue by gkhristian** [dooboolab/flutter_sound#178]
### Version of flutter_sound
1.6.0 or 1.7.0
## flutter doctor
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Plays and Stops w/o exceptions
### Actual behavior
Plays, it works fine but whenever stops an exception happens: Unhandled Exception: PlatformException(ERR_PLAYER_IS_NULL, ERR_PLAYER_IS_NULL, ERR_PLAYER_IS_NULL)

Same for recording and stop recording. It seems that this.model.getMediaRecorder() it is always null...

### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
Start and Stop any audio file or Start recording and Stop recording

**Comment by hyochan** [comment]
Please try to use `try` and `catch` statements whenever you call our `async` function. This is expected.
