### ISSUE TITLE
flutterSound.onPlayerStateChanged.listen  not work

### ISSUE THREAD

**Issue by dio17337548611** [dooboolab/flutter_sound#180]
when  the sound   finish, this method not work 
![image](https://user-images.githubusercontent.com/58875519/71613753-151cc900-2be3-11ea-8be2-9720a1b4ab44.png)
i can get callback

**Comment by hyochan** [comment]
@dio17337548611 I've recently tested [this](https://github.com/dooboolab/flutter_sound/blob/8e1f7707c0cd0ca012839448e3c6bfb241b499b5/example/lib/main.dart#L156-L171) in our example. Could you try this and come back?

**Comment by Josue10599** [comment]
I am experiencing this same problem. 

I opened another issue where I reported the details: #235
