### ISSUE TITLE
How to restrict max recording duration?

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#184]
### Version of flutter_sound
  flutter_sound: ^1.8.0

## flutter doctor
[✓] Flutter (Channel master, v1.13.7-pre.42, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.7-pre.42 at /Users/kmusham/Library/flutter
    • Framework revision 4f9b6cf017 (25 hours ago), 2020-01-07 16:32:04 +0100
    • Engine revision 3851981b86
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2f57602411)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kmusham/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1C80B066-BAAE-4CC6-B815-60BC7A20998F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
I would like to set or restrict the max recoding duration to 1 min. Do you have any API to restrict time? 
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
I'm using your example project.

**Comment by kmusham** [comment]
Can you please respond. We have a release soon and without this restriction, we can not release a build.
Thanks.

**Comment by hyochan** [comment]
@kmusham It isn't supported inside our plugin. However, this is really easy to restrict the duration outside the plugin. You can set the `MAX_RECORD_DURATION` and when it exceeds, you can just stop the recorder manually.
