### ISSUE TITLE
在Android 项目中使用 停止录音出现bug

### ISSUE THREAD

**Issue by tianzhiguo123** [dooboolab/flutter_sound#188]
我在我的项目中使用插件 暂停录音时出现这种错误，
请问怎么解决  ？Thank U
![捕获](https://user-images.githubusercontent.com/44284679/72057022-a9d0a680-3308-11ea-956e-73af67de3e69.PNG)

**Comment by hyochan** [comment]
Closed due to lack of information and lack of translation.
