### ISSUE TITLE
If the time interval between starting and stopping recording is very short, for example, when you click and lift the mouse, it will always be in recording state. How to deal with it

### ISSUE THREAD

**Issue by tianshangwuyun** [dooboolab/flutter_sound#195]
If the time interval between starting and stopping recording is very short, for example, when you click and lift the mouse, it will always be in recording state. How to deal with it

**Comment by hyochan** [comment]
Could you kindly capture some gif for us so we can investigate? I still feel abstract.

**Comment by Larpoux** [comment]
Hi @tianshangwuyun 

Is your issue still relevant, or it has been fixed by recent releases ?

**Comment by Larpoux** [comment]
Please re-open this issue if this point is still relevant in recent Flutter Sound version.
