### ISSUE TITLE
New Logo/Icon proposal

### ISSUE THREAD

**Issue by mansya** [dooboolab/flutter_sound#2]
hi sir, I am happy to design the logo for this project. because you have offered me this project in the react-native-audio-recorder-player [issues](https://github.com/dooboolab/react-native-audio-recorder-player/issues/3) project. thanks sir. I will design it.

**Comment by dooboolab** [comment]
@mansya my pleasure! 🙏

**Comment by mansya** [comment]
hi sir. sorry about this long time. I'm a little busy with activities in my environment. by the way this is my design result. are you interested ? if yes. which one do you like? You can tell me if there are changes.
![flutter sound](https://user-images.githubusercontent.com/33461607/44768326-27b86580-ab8b-11e8-8cbc-7f8d77fc9d28.png)

**Comment by dooboolab** [comment]
@mansya Dude! Totally no problem~ I am totally pleased with your work. Since Flutter is blue, I prefer no 1. Thank you so much!

**Comment by dooboolab** [comment]
@mansya Thanks so much for taking your time with beautiful work!

**Comment by mansya** [comment]
I have uploaded all files to this [**drive**](https://drive.google.com/open?id=1PEPARRwuXLng8Zu20zEo6SRT8y8dKxhf). thank you too sir. I will design the logo again for your other project sir.

**Comment by dooboolab** [comment]
@mansya What do you mean my other projects? I've already got so much from you.

**Comment by mansya** [comment]
I want to design a logo for your other project. that if only you allow it.

**Comment by dooboolab** [comment]
@mansya It's your choice. I always love to see your work!
