### ISSUE TITLE
startRecording doesn't allow absolute paths.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#201]
### Version of flutter_sound
2.0.1

### Expected behavior
When calling startRecording with an absolute path (e.g. /xxxx) then providing the path is valid the recording should record to that path.
If the path isn't valid then startRecording should return a suitable error such as:
1) permission denied for /xxx
2) file not found

I would also expect to see documentation on what a valid values for the path variable.
e.g. what system directories can a path be saved to.
Does the provide directory have to exist?
Does the file have to exist?

### Actual behavior
startRecording fails silently.
There is no documentation on the path argument.

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
call startRecording

**Comment by bsutton** [comment]
Looks like I'm having some additional problems as well as even leaving the path empty results in the same symptoms. Will report back. The above statements are still valid.

**Comment by bsutton** [comment]
I've just added some logging that shows the path double slash issue:
startRecorder path:/arecording.wav
updatedPath:/data/user/0/com.dooboolab.fluttersoundexample/app_flutter//arecording.wav

The double slash however doesn't stop the recorder from working.
Many OS' will ignore a double slash. We should still fix the issue.

**Comment by bsutton** [comment]
Still looking into the underlying cause of the first noted issue.
Can I suggest that we change the code so that if the passed path starts with a leading / then we treated it as an absolute path and if it doesn't start with a leading slash that we then append it to the current base dir.

**Comment by hyochan** [comment]
@bsutton Sounds pretty reasonable. Could to try to give us a `PR` on your roadmap?

**Comment by hyochan** [comment]
Looks like this is in progress in #199. @bsutton Would you like to review this approach?

**Comment by bsutton** [comment]
Looks fine to me.
Thanks.

**Comment by Larpoux** [comment]
@hyochan : I think you can close this issue.
With last versions of flutter_sound, a correct complete path must be provided to StartRecorder() and StartPlayer().

**Comment by Larpoux** [comment]
Please, feel free to re-open this issue if you think that recent versions of flutter_sound do not fix your problem
