### ISSUE TITLE
[enh] Incompatiblility with FCM

### ISSUE THREAD

**Issue by ezfuncreations** [dooboolab/flutter_sound#212]
### Version of flutter_sound
2,0.4
## flutter doctor
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18363.592], locale pl-PL)
    • Flutter version 1.12.13+hotfix.7 at C:\src\flutter
    • Framework revision 9f5ff2306b (7 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM J730F • 5200daf5ece694ff • android-arm • Android 8.1.0 (API 27)

### Platforms you faced the error (IOS or Android or both?)
Android, sdk 28.

### ISSUE
When using this plugin alongside fully configured Firebase Cloud Messaging plugin, startRecorder() fails to do anything. 

I believe its because of the following being added to Application.java :

``
```
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```
``

It's part of the FCM plugin configuration. I think the same problem may occur on similar plugins that fiddle with the application class similarly. Here's the problematic plugin for reference:

https://pub.dev/packages/firebase_messaging

**Comment by hyochan** [comment]
Could you share more information on where exactly is the error occurring?

**Comment by juani15151** [comment]
Im having the same issue on flutter_sound: 2.1.0 & firebase_messaging: 5.1.6  - Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale es_AR.UTF-8). Tested on Android (real device).

The error is that startRecorder() never returns not throws an exception.
Digging a little more, code stops at flutter_sound:282 `String result = await _channel.invokeMethod('startRecorder', param);` and never reachs the next line.

When disabling the `@Override onCreate()` of the Application.java class (same as described), it works as expected.

**Comment by Larpoux** [comment]
Hi,

This issue had been filled several months ago (sorry for the delay). I am wondering what is the current state of this issue.
Is it still relevant ?
If yes, I think it would be very interesting to go deeper in it.

**Comment by Larpoux** [comment]
I think that this issue is tied to #235

**Comment by Larpoux** [comment]
@ezfuncreations, @juani15151  : 

Yes, I confirm that Flutter Sound and FCM are not good friends together.
I tried to run the Flutter Sound Example with a special APP linked with Firebase Messaging, and it does not work.
Android Media Player is really painful (I have many problems in Flutter Sound not correctly solved because of Android Media Player).
I think it is time, now, to consider rewriting the Flutter Sound Recorder using other native tools.
Just be patient ... time is the bottle neck.

**Comment by UttamPanchasara** [comment]
Hello, I'm facing the kind of similar issue on iOS, 
While using plugin with flutter_downloader plugin, when we start download and by the time when the file is downloading, I'm not getting onPlayerStateChanged states on iOS only.

**Comment by Larpoux** [comment]
Dear "bot", please keep this issue open

**Comment by Larpoux** [comment]
Dear "bot", please keep this issue open 😡

**Comment by juani15151** [comment]
I guess the bot ignores comments from collaborators, so I'm adding another one so Larpoux doesn't fight the bot...

**Comment by Larpoux** [comment]
👍 Thanks @juani15151 😄

**Comment by Larpoux** [comment]
Registered in [the Flutter Sound Project](https://github.com/dooboolab/flutter_sound/projects/3)
