### ISSUE TITLE
onRecorderStateChanged is null

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#213]
### Version of flutter_sound
a private fork  #207 

### Platforms you faced the error (IOS or Android or both?)
iOS emulator

### Actual behavior
Crash in flutter_sound example, function startRecorder : 
```
_recorderSubscription = flutterSound.onRecorderStateChanged.listen((e) 
```
Crash because variable `e` was null

{### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
Cannot reproduce

**Comment by Larpoux** [comment]
I think that ```_recorderController.add(null)``` in _removeRecorderCallback()``` is a problem.
I do not understand the reason of this line.

I am removing this line in my #207 fork, but I am not sure.
@hyochan ? What is the reason of this instruction ?

**Comment by hyochan** [comment]
@Larpoux I think, I wanted to ensure that the recording has ended just by passing the `null` value. Would there be any better way?

**Comment by Larpoux** [comment]
In Flauto I added an optional parameter in startPlayer  : 

startPlayer(   ... , whenFinished: (){ doSomething; }    );
