### ISSUE TITLE
Call back when Player Status changes

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#215]
### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Need a callback when play is finished

### Actual behavior
Callback every 10ms without interesting information

### Steps to reproduce the behavior
Actually I can have a callback every n milli-seconds, but for me it is just CPU eating.
I need just **one** callback when my sound is finished to be played.

**Comment by salvatore373** [comment]
In my PR (#202) you can subscribe to ```onPlaybackStateChanged``` ```Stream```, that notifies the listener whenever the player is started, paused, stopped or completes playing the current sound. So this should cover and fix your issue.

**Comment by Larpoux** [comment]
Very good !!!

**Comment by Larpoux** [comment]
Please tell me when you are ready for a deep review from me.

**Comment by Larpoux** [comment]
This request is addressed in Flauto
