### ISSUE TITLE
Wont start recording when using custom URI 

### ISSUE THREAD

**Issue by MATTYGILO** [dooboolab/flutter_sound#221]
### Version of flutter_sound
2.0.4
## flutter doctor
No issues
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Should create a recording file at path /storage/emulated/0/myApp/sound.aac
### Actual behavior
Doesn't start recording
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
`      String path = await flutterSound.startRecorder(
        uri: "/storage/emulated/0/myApp/sound.aac",
        androidEncoder: AndroidEncoder.AAC,
        bitRate: 256000,
        sampleRate: 96000,
      ).catchError((error) {
        print(error);
      });`

**Comment by mdrideout** [comment]
This is not a "solution" to your issue, but my preferred approach is to move the file from the default cache location to a more permanent location after the stopRecorder() function.

I have a file utility function that uses path_provider to move the file to the app's folder.

Example

```
void stopRecorder() async {
    try {
      print("Stopping recording...");

      // Get date for file name
      int _date = DateTime.now().millisecondsSinceEpoch;

      // Create the destination file path
      String recordingFileName = "item_recording_" + _date.toString() + ".aac";

      // Stop the recording and get the cached sound file path
      String recordingFileLocation = await _flutterSound.stopRecorder();

      // Move the file to the recordings directory
      File savedRecording = await moveToDocumentsFolder(
        sourceFilePath: _savePath,
        subFolder: "recordings",
        fileName: recordingFileName,
      );
```

## Utility Function To Move The File
```
/// Move To Documents Folder
/// Moves the file to the documents folder, and optionally a subfolder.
/// If the subfolder does not exist, it will be created
/// [sourceFile] is the path of the file at its current location
/// [subFolder] is the optional subfolder we're moving the item to
/// [fileName] is the name of the file, with extension
Future<File> moveToDocumentsFolder(
    {String sourceFilePath, String subFolder, String fileName}) async {
  try {
    // Get reference to documents folder
    var dir = await getApplicationDocumentsDirectory();

    // Check if subFolder exists, if not create it
    bool exists = await Directory(dir.path + "/" + subFolder).exists();

    // Create the subfolder if it doesn't exist
    if (!exists) {
      await Directory(dir.path + "/" + subFolder).create();
    }

    // Get file reference from sourceFilePath
    File sourceFile = File(sourceFilePath);

    print("Moving recording to full path of: " +
        dir.path +
        "/" +
        subFolder +
        "/" +
        fileName);

    // Attempt to move the file with rename
    return await sourceFile.rename(dir.path + "/" + subFolder + "/" + fileName);
  } on FileSystemException catch (e) {
    // if rename fails, copy the source file and then delete it

    // Get reference to documents folder
    var dir = await getApplicationDocumentsDirectory();

    // Get file reference from sourceFilePath
    File sourceFile = File(sourceFilePath);

    // Copy then delete
    final newFile =
        await sourceFile.copy(dir.path + "/" + subFolder + "/" + fileName);
    await sourceFile.delete();
    return newFile;
  }
}
```

**Comment by MATTYGILO** [comment]
> This is not a "solution" to your issue, but my preferred approach is to move the file from the default cache location to a more permanent location after the stopRecorder() function.
> 
> I have a file utility function that uses path_provider to move the file to the app's folder.
> 
> Example
> 
> ```
> void stopRecorder() async {
>     try {
>       print("Stopping recording...");
> 
>       // Get date for file name
>       int _date = DateTime.now().millisecondsSinceEpoch;
> 
>       // Create the destination file path
>       String recordingFileName = "item_recording_" + _date.toString() + ".aac";
> 
>       // Stop the recording and get the cached sound file path
>       String recordingFileLocation = await _flutterSound.stopRecorder();
> 
>       // Move the file to the recordings directory
>       File savedRecording = await moveToDocumentsFolder(
>         sourceFilePath: _savePath,
>         subFolder: "recordings",
>         fileName: recordingFileName,
>       );
> ```
> 
> ## Utility Function To Move The File
> ```
> /// Move To Documents Folder
> /// Moves the file to the documents folder, and optionally a subfolder.
> /// If the subfolder does not exist, it will be created
> /// [sourceFile] is the path of the file at its current location
> /// [subFolder] is the optional subfolder we're moving the item to
> /// [fileName] is the name of the file, with extension
> Future<File> moveToDocumentsFolder(
>     {String sourceFilePath, String subFolder, String fileName}) async {
>   try {
>     // Get reference to documents folder
>     var dir = await getApplicationDocumentsDirectory();
> 
>     // Check if subFolder exists, if not create it
>     bool exists = await Directory(dir.path + "/" + subFolder).exists();
> 
>     // Create the subfolder if it doesn't exist
>     if (!exists) {
>       await Directory(dir.path + "/" + subFolder).create();
>     }
> 
>     // Get file reference from sourceFilePath
>     File sourceFile = File(sourceFilePath);
> 
>     print("Moving recording to full path of: " +
>         dir.path +
>         "/" +
>         subFolder +
>         "/" +
>         fileName);
> 
>     // Attempt to move the file with rename
>     return await sourceFile.rename(dir.path + "/" + subFolder + "/" + fileName);
>   } on FileSystemException catch (e) {
>     // if rename fails, copy the source file and then delete it
> 
>     // Get reference to documents folder
>     var dir = await getApplicationDocumentsDirectory();
> 
>     // Get file reference from sourceFilePath
>     File sourceFile = File(sourceFilePath);
> 
>     // Copy then delete
>     final newFile =
>         await sourceFile.copy(dir.path + "/" + subFolder + "/" + fileName);
>     await sourceFile.delete();
>     return newFile;
>   }
> }
> ```

Thanks for the suggestion however this is still not giving me the desired outcome. I hope that they fix this as it use to work for me in earlier versions of flutter sound.

**Comment by MATTYGILO** [comment]
@hyochan Can you have a look at this I really need this fixed soon.

**Comment by hyochan** [comment]
@Larpoux Could you tell me how to resolve this issue? I've seen [this line](https://github.com/dooboolab/flutter_sound/blob/e1db703de14b61a0b4e52c6d1884b35a5876d4d9/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java#L265), therefore we need additional directory path to append which app would have permission.

**Comment by Larpoux** [comment]
```
    // path = PathUtils.getDataDirectory(reg.context()) + "/" + path; // SDK 29 : you may not write in getExternalStorageDirectory() [LARPOUX]
```

Previous version of Diglot Sound created a file on the SD/Card. The developer specified the name of this file, and flutter_sound concatenated the SD-Card path with this file name.

For me it was bad for two reasons : 
- Since SDK 29, we are not allowed to write directly on the SD-card. Android manage sand-boxes directory inside /sdcard/android/<app-name>, and protects each App from others
- The developer must be able to specify not only the file name, but also where he wants to store this file (so a complete path must be provided).

```Diglot Korean```, for example, records his file in a temporary directory, before storing it inside a SQL database

**Comment by Larpoux** [comment]
```
String path = await flutterSound.startRecorder( uri: "/storage/emulated/0/myApp/sound.aac", androidEncoder: AndroidEncoder.AAC, bitRate: 256000, sampleRate: 96000, ).catchError((error) { print(error); });
```
For me, this does not seem too bad.
Of course this instruction is not correctly compatible with iOS (and with Android when it does not have a */storage/emulated/0/myApp/* directory).
There is certainly better way to do that with compatibility.

Still, this bug can be investigated. Because for me it should be OK.

**Comment by Larpoux** [comment]
Oh, I see : 
the correct path should be : 
```"/storage/emulated/0/Android/data/com.toto.app/files"```

You may not create a file anywhere you want without security issu

**Comment by Larpoux** [comment]
Or your app must be rooted 😆

**Comment by hyochan** [comment]
I've managed to resolve this one with android's [app specific path](https://developer.android.com/training/data-storage/app-specific). I will release this to `2.0.5`. Hope you like it @Larpoux

**Comment by hyochan** [comment]
Just release `2.0.5`. I gotta go to sleep now 🛏 (2:40 AM)

**Comment by MATTYGILO** [comment]
Thanks a lot I'll give it a go. Anyway get some sleep.

**Comment by Larpoux** [comment]
> I've managed to resolve this one with android's [app specific path]. Hope you like it @Larpoux

Heuh! not really 🙄 
with your patch : 
- The developer cannot specify correctly where to store is record (perhaps he wants to store it in a temporary directory).
- It will not fix this PR : ```/storage/emulated/0/myApp/sound.aac``` is still not a good place to store a file.
I really think that if the user wants to store his file on a sdcard, it is his job to find the correct directory path.
Probably ```"/storage/emulated/0/Android/data/com.toto.myApp/files"``` will solve @MATTYGILO problem.

**Comment by Larpoux** [comment]
```import 'package:path_provider/path_provider.dart';```

I think that this package can be very useful for the developer if he wants to keep iOS/android compatibility. But I insist, this is his job to specify where to store its records.
And not good to have to always add "storage rights" to an application which does not really need it.

**Comment by hyochan** [comment]
@Larpoux Hey, I was rushing yesterday to go to sleep. Forgive me 😭 . I am working on the enhancement in #225. Also, I'm trying to remove the below line in `flutter_sound`.
![image](https://user-images.githubusercontent.com/27461460/75085058-9439d800-5568-11ea-981d-5fbc72117659.png)

I've checked the code and it looks like the above line is the only line that uses `path_provider`.
Removing package dependencies and making it independent help the plugin maintenance. I think this can be replaced with the code you don't like since this is just the `temporary` dir.

**Comment by Larpoux** [comment]
flutter_sound should not depend on path_provider.
It would be great 👍  to remove this dependence. Just the **example** should depend on this plugin.
(flutter_sound must not deal with disk paths. This is not its responsibility).

**Comment by hyochan** [comment]
@Larpoux We should think of removing it in the future by generating `default` paths in each `ios` and `android` as it was given previously. I've not done it yet.

**Comment by Larpoux** [comment]
Yes my friend 👍
