### ISSUE TITLE
Record Exception 

### ISSUE THREAD

**Issue by UnluckyY1** [dooboolab/flutter_sound#222]
D/FlutterSoundPlugin(31699): startRecorder
E/FlutterSoundPlugin(31699): Exception:
E/FlutterSoundPlugin(31699): java.lang.RuntimeException: Methods marked with @UiThread must be executed
on the main thread. Current thread: pool-1-thread-1
E/FlutterSoundPlugin(31699):    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
E/FlutterSoundPlugin(31699):    at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:740)
E/FlutterSoundPlugin(31699):    at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:156)
E/FlutterSoundPlugin(31699):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/FlutterSoundPlugin(31699):    at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:198)
E/FlutterSoundPlugin(31699):    at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:65)
E/FlutterSoundPlugin(31699):    at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin(31699):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/FlutterSoundPlugin(31699):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin(31699):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin(31699):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin(31699):    at java.lang.Thread.run(Thread.java:764)

code : 
void startRecorder() async {
    try {
      String path = await flutterSound.startRecorder(null);
      print('startRecorder: $path');

      _recorderSubscription = flutterSound.onRecorderStateChanged.listen((e) {
        DateTime date = new DateTime.fromMillisecondsSinceEpoch(
            e.currentPosition.toInt(),
            isUtc: true);
        String txt = DateFormat('mm:ss:SS', 'pt_BR').format(date);

        this.setState(() {
          this._recorderTxt = txt.substring(0, 8);
        });
      });
   //   _dbPeakSubscription =
         // flutterSound.onRecorderDbPeakChanged.listen((value) {
      //  print("got update -> $value");
     //   setState(() {
       //   this._dbLevel = value;
      //  });
     // });

      this.setState(() {
        this._isRecording = true;
      });
    } catch (err) {
      print('startRecorder error: $err');
    }
  }

**Comment by hyochan** [comment]
What version are you using? Please try out `example` project to and come back. Without any further investigation or any other information, we can't help you out.
