### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: A problem occurred configuring root project 'flutter_sound'. > SDK location not found.

### ISSUE THREAD

**Issue by abbas-25** [dooboolab/flutter_sound#223]
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_sound'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/abbas/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sound-2.0.4/android/local.properties'.

```

### Version of flutter_sound
2.0.4 (tried 2.0.0 also) 

## flutter doctor
All Good.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

### Platforms you faced the error (IOS or Android or both?)
Only checked with Android

### Expected behavior
Can't even get it to work

### Actual behavior
It works :/

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Added dependency and permissions, now getting this error on flutter run
Other projects & packages are working fine. If I remove flutter_sound package, this project works fine too.

**Comment by hyochan** [comment]
This looks like the problem on flutter and not on our plugin. It looks like you don't have the proper configuration. Can you read our [readme on debugging](https://github.com/dooboolab/flutter_sound#debug)? If this is still occurring tell us again.

Also, checking `example` project and comparing might help. This is the reason why we develop our `example`.
