### ISSUE TITLE
My problem

### ISSUE THREAD

**Issue by duhualong** [dooboolab/flutter_sound#226]
### Version of flutter_sound
 flutter_sound: ^2.1.0
## flutter doctor
Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.14393], locale zh-CN)

### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
E/FlutterSoundPlugin( 5627): java.io.FileNotFoundException: android_1582523614.mp4: open failed: EROFS (Read-only file system)
E/FlutterSoundPlugin( 5627): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/FlutterSoundPlugin( 5627): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
E/FlutterSoundPlugin( 5627): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
E/FlutterSoundPlugin( 5627): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:1060)
E/FlutterSoundPlugin( 5627): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:305)
E/FlutterSoundPlugin( 5627): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:190)
E/FlutterSoundPlugin( 5627): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin( 5627): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/FlutterSoundPlugin( 5627): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 5627): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin( 5627): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin( 5627): 	at java.lang.Thread.run(Thread.java:919)
E/FlutterSoundPlugin( 5627): Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
E/FlutterSoundPlugin( 5627): 	at libcore.io.Linux.open(Native Method)
E/FlutterSoundPlugin( 5627): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/FlutterSoundPlugin( 5627): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/FlutterSoundPlugin( 5627): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/FlutterSoundPlugin( 5627): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7419)
E/FlutterSoundPlugin( 5627): 	at libcore.io.IoBridge.open(IoBridge.java:482)

**Comment by duhualong** [comment]
you remove "WRITE_EXTERNAL_STORAGE" permission,cause  this problem .

**Comment by hyochan** [comment]
Have you through the [post installation guide](https://github.com/dooboolab/flutter_sound#post-installation)?

**Comment by oreo** [comment]
I also encountered this bug,Please

**Comment by duhualong** [comment]
> Have you through the [post installation guide](https://github.com/dooboolab/flutter_sound#post-installation)?

Android   "FlutterSoundPlugin.java" file;you remove  "WRITE_EXTERNAL_STORAGE" permission,you should add it;

**Comment by duhualong** [comment]
> Have you through the [post installation guide](https://github.com/dooboolab/flutter_sound#post-installation)?

you should add permission "WRITE_EXTERNAL_STORAGE"  ; 

@Override
  public void startRecorder(int numChannels, int sampleRate, Integer bitRate, int androidEncoder, int androidAudioSource, int androidOutputFormat, String path, final Result result) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {

      if (
          reg.activity().checkSelfPermission(Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED
              || reg.activity().checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED
          ) {
        reg.activity().requestPermissions(new String[]{
            Manifest.permission.RECORD_AUDIO,
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
        }, 0);
        result.error(TAG, "NO PERMISSION GRANTED", Manifest.permission.RECORD_AUDIO + " or " + Manifest.permission.WRITE_EXTERNAL_STORAGE);
        return;
      }
    }

**Comment by oreo** [comment]
Yes,I added this code, But the above error will still occur. Please!
` if(Build.VERSION.SDK_INT>= Build.VERSION_CODES.M){
      if (
              reg.activity().checkSelfPermission(Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED
                      || reg.activity().checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED
      ) {
        reg.activity().requestPermissions(new String[]{
                Manifest.permission.RECORD_AUDIO,
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
        }, 0);
        result.error(TAG, "NO PERMISSION GRANTED", Manifest.permission.RECORD_AUDIO + " or " + Manifest.permission.WRITE_EXTERNAL_STORAGE);
        return;
      }
    }else {
      if ( sdkCompat.checkRecordPermission(reg) != PackageManager.PERMISSION_GRANTED) {
        result.error(TAG, "NO PERMISSION GRANTED", Manifest.permission.RECORD_AUDIO + " or " + Manifest.permission.WRITE_EXTERNAL_STORAGE);
        return;
      }
    }
`

**Comment by oreo** [comment]
我解决了它，因为我没有写正确的路径，只是传递文件名，而不是目录+文件名，不是完整的路径，所以错误，不是插件问题，抱歉

**Comment by oreo** [comment]
I solved it, because I didn't write the correct path, just passed the file name, not the directory + file name, not the full path, so the error, not the plugin problem, sorry

**Comment by Larpoux** [comment]
@hyochan : I suggest to close this issue, which is not relevant anymore.
