### ISSUE TITLE
Error occurs when attempting to record audio via PCM

### ISSUE THREAD

**Issue by DreamsInCS** [dooboolab/flutter_sound#229]
### Version of flutter_sound
flutter_sound: ^2.1.0
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.15.4-pre.175, on Microsoft Windows [Version 10.0.18362.657], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (1 available)

• No issues found!
### Platforms you faced the error (IOS or Android or both?)
Android.
### Expected behavior
Recorder properly records audio.
### Actual behavior
No recording occurs. A RecorderRunningException is thrown.
### Tested environment (Emulator? Real Device?)
Emulator.
### Steps to reproduce the behavior
Set up the flutter_sound example. Select File as Media and PCM as Codec. Press the record button.

**Comment by Larpoux** [comment]
Actually, PCM recording is not supported, neither on Android nor in iOS.
Probably we will do it in the future ...
Please, refer to the encoder compatibility in the README

**Comment by DreamsInCS** [comment]
> Actually, PCM recording is not supported, neither on Android nor in iOS.
> Probably we will do it in the future ...
> Please, refer to the encoder compatibility in the README

May I ask why the encoder is necessary in order to initiate a recording process with the audio format?

**Comment by DreamsInCS** [comment]
@Larpoux I also notice that in the console, a .wav file is produced, despite selecting the .aac codec to initiate recording with. May I ask why this is the case? If there is documentation on this process, may I be shown where the documentation is?

**Comment by Larpoux** [comment]
Do not try to record LINEAR-16, MP3 or PCM with flutter_sound. You will not success.
We will improve the codec supported in the future. Probably the next encoder supported by flutter_sound will be OPUS on Android.

You can refer to the README to know which encoder are supported.
If you need to know during runtime, you can use the function : ```isEncoderSupported()```

**Comment by Larpoux** [comment]
> @Larpoux I also notice that via the console, a .wav file is produced, despite selecting the .aac codec to initiate recording with.

You may name your files as you want. A file name has nothing to do with its contents.
You are free to store your AAC record in toto.foo, toto.bla, toto.dummy or toto.wav.

But I do not recommend to use an extension *.wav to store an ACC record.It would be very confusing.

**Comment by Larpoux** [comment]
@hyochan : I suggest to close this issue.
I think that Flauto is clean on this point.
