### ISSUE TITLE
Request permission on seperate method

### ISSUE THREAD

**Issue by spideythewebhead** [dooboolab/flutter_sound#230]
### Version of flutter_sound

2.1.0

## flutter doctor

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.592], locale en-US)

### Platforms you faced the error (IOS or Android or both?)

Android (havent tested this on IOS)

### Tested environment (Emulator? Real Device?)

Both

### Issue

When using the recorder functionally if there is no permission it asks thro the same call for permissions and the same call ends with an error.

FlutterSoundPlugin :line 259
      if ( sdkCompat.checkRecordPermission(reg) != PackageManager.PERMISSION_GRANTED) {
          result.error(TAG, "NO PERMISSION GRANTED", Manifest.permission.RECORD_AUDIO + " or "  Manifest.permission.WRITE_EXTERNAL_STORAGE);
          return;
      }

I think its better to extract it in a new seperate functions and the users have to manually ask for permissions and act as if needed

**Comment by Larpoux** [comment]
Recording permission has been rewrote in a future flutter_sound version.
The recording permission will be done in the Flutter side, and not anymore in the ios/Android specific code.
Probably it will help for this issue.
Unfortunately this new versions is actually stalled, because of a major bug on Android...(#227)
Actually we have no date for this new version.
@salvatore373 : do you have something to say for #227 ?

**Comment by spideythewebhead** [comment]
Hi and thanks for the response. But i cant understand, what do u mean from the flutter side? dont u still need to call the specific code from both flutter and native?

also what is Flauto? i didnt underthat either? could i look at the code maybe i can provide some help

**Comment by Larpoux** [comment]
Hi @spideythewebhead ,

Flauto is just a code name for a possible future version of flutter_sound.
This version is eventually supposed to let the user control his playback from the lock screen.
(Thanks to @salvatore373 who wrote this code).

Unfortunately, this code has a major bug on Android (#227), and neither @salvatore373 nor me have enough time to solve this issue.

Of course, if you can help it would be very great.
Salvatore's code is on [this branch](https://github.com/salvatore373/flutter_sound/tree/lock-screen-controls2).
Mine is on [this branch](https://github.com/Canardoux/flutter_sound/tree/flauto).
Probably better to work on my branch, but both branches have the same Android problem.
If you can figure what happens, both branches will be fixed.

Note: There is some part on my branche that I am not very proud of.
Do not blame me : I will clean everything if someone can understand #227. I promise.

**Comment by spideythewebhead** [comment]
Yeah sure I can give it a try I will check it out this Friday/saturday

Στις Δευ, 2 Μαρ 2020, 7:25 μ.μ. ο χρήστης Larpoux <notifications@github.com>
έγραψε:

**Comment by Larpoux** [comment]
OK @spideythewebhead ,
Flauto release is probably ready to be released.
You will see if your problem is correctly addressed.
@hyochan : we really need Flauto, now. We hope that it will be released soon 😺

**Comment by spideythewebhead** [comment]
hi thanks for the response. i am sorry i couldnt check it, happend to have much work nowdays..

**Comment by hyochan** [comment]
`flauto` has been released as version `3.0.0`
