### ISSUE TITLE
Cannot find symbol ActivityCompat.requestPermission

### ISSUE THREAD

**Issue by alby97** [dooboolab/flutter_sound#231]
### Version of flutter_sound
2.0.0 (but I also tried with, 2.1.0, 1.7.0, 1.9.0, my original version was 1.5.2)

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.9.1+hotfix.6, on Microsoft Windows [Versione 10.0.18362.657], locale it-IT)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.42.1)
[√] VS Code, 64-bit edition
[√] Connected device (1 available)

! Doctor found issues in 1 category.

### Platforms you faced the error (IOS or Android or both?)
Android

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
I'm trying to run my app, last days it works perfectly, but today suddenly it gives me this error (originally with the 1.5.2 version and now with 2.0.0/2.1.0).
The log is the following:

C:\Users\alby9\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound-2.1.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:12: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
C:\Users\alby9\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound-2.1.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:47: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  symbol:   variable ActivityCompat
  location: class sdkCompat
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sound:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 35s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

With 1.5.2 version the error was with import android.support.v4.app.

**Comment by Larpoux** [comment]
Flauto branch is now compatible with AndroidX and Android embbeded V2.
@hyochan : 
You probably will be allowed to close this issue when Flauto will be released (I hope soon 😺 )

**Comment by VitosPyatak** [comment]
I've got the same issue on flutter_sound 1.8.0

**Comment by UttamPanchasara** [comment]
Same issue on v2.1.1, @Larpoux @hyochan When can we expect the new release with Flauto branch fix?

**Comment by Larpoux** [comment]
@UttamPanchasara , 
@VitosPyatak 
@alby97  : 

Hi, guys,
May I ask you a favour ? Please give a try to the [`flauto` branch](https://github.com/Canardoux/flutter_sound/tree/flauto), so that we will be sure that your problems will be fixed when the `flauto` branch will be released.
If not, I will fix it before release.

**Comment by VitosPyatak** [comment]
@Larpoux There are some warnings of deprecated api this plugin is using but everything worked just fine

**Comment by UttamPanchasara** [comment]
@Larpoux Sorry but I can not give a try now as we on production with this plugin, will try with demo run but not sure about.

**Comment by Larpoux** [comment]
> @Larpoux There are some warnings of deprecated api this plugin is using but everything worked just fine

Thank you for the time you spent on this. I am glad that you confirm that this next flauto_sound release is OK for you. 
@hyochan : end of march ?

**Comment by hyochan** [comment]
#243 has been merged and released in `3.0.0` 🎉
