### ISSUE TITLE
startPlayerFromBuffer failure

### ISSUE THREAD

**Issue by wigy-opensource-developer** [dooboolab/flutter_sound#233]
### Version of flutter_sound

2.1.1

## flutter doctor

[✓] Flutter (Channel dev, v1.15.3, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!

### Platforms you faced the error (IOS or Android or both?)

Android 9

### Expected behavior

Play sound from a flutter asset.

### Actual behavior

`PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)`

### Tested environment (Emulator? Real Device?)

Real device, Poco F1 with OmniROM

### Steps to reproduce the behavior

I was trying to play an audio file from a small asset. The temporary file created in the Java backend [is not world readable](http://blog.weston-fl.com/android-mediaplayer-prepare-throws-status0x1-error1-2147483648/), so Android cannot prepare the playback session.

```dart
  Future<void> _playBeep(BuildContext context) async {
    final beep = await DefaultAssetBundle.of(context).load('assets/scanner_beep.ac3');
    final flutterSound = new FlutterSound();
    final playback = new Completer.sync();
    await flutterSound.startPlayerFromBuffer(beep.buffer.asUint8List(), codec: t_CODEC.CODEC_AAC);
    final subscription = flutterSound.onPlayerStateChanged.listen((event) {
      if (event == null) {
        return;
      }
      if (event.currentPosition == event.duration) {
        playback.complete();
      }
    });
    await playback.future;
    subscription.cancel();
  }
```

**Comment by Larpoux** [comment]
Is this possible to have the logs ?
startPlayerFromBuffer() may use a temporary file (it can be changed in the future) for its own needs, but should not give any error.
At first seeing your code is perfect : flutter_sound should be very good to play a small sound from an asset.
The logs would be very useful to understand more your problem.

**Comment by wigy-opensource-developer** [comment]
I have created a minimal integration code at https://github.com/wigy-opensource-developer/flutter-sample-beep and ran it on a real device + emulated Android 10 + emulated Android 6 device. All experiments produced the same logcat messages:

```
E/MediaPlayerNative(25039): error (1, -2147483648)
E/FlutterSoundPlugin(25039): startPlayer() exception
E/flutter (25039): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)
E/flutter (25039): #0      FlutterSound._startPlayer (package:flutter_sound/flutter_sound.dart:378:7)
E/flutter (25039): <asynchronous suspension>
E/flutter (25039): #1      FlutterSound.startPlayerFromBuffer (package:flutter_sound/flutter_sound.dart:398:20)
E/flutter (25039): #2      _MyHomePageState._playBeep (package:beep/main.dart:47:24)
E/flutter (25039): <asynchronous suspension>
E/flutter (25039): #3      _MyHomePageState.build.<anonymous closure> (package:beep/main.dart:35:26)
E/flutter (25039): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter (25039): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter (25039): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (25039): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (25039): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (25039): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (25039): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (25039): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (25039): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (25039): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (25039): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (25039): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (25039): #16     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (25039): #17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (25039): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (25039): #19     _invoke1 (dart:ui/hooks.dart:274:10)
E/flutter (25039): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
```

The temporary file permissions are 0600, so they are not readable by the MediaPlayerNative service.

**Comment by Larpoux** [comment]
I am not convinced that your problem is with file protection.
0600 is probably correct : the file owner and the processus doing the open are same (110 is OK)
Why do you think that you have a problem with access rights ?

```
E/FlutterSoundPlugin(25039): startPlayer() exception
E/flutter (25039): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)
E/flutter (25039): #0      FlutterSound._startPlayer (package:flutter_sound/flutter_sound.dart:378:7)
```
The problem is that you have an unhandled exception, and flutter_sound gives no clue of what is wrong. 

@hyochan : is it possible to add some diagnostics when problems ?

@wigy-opensource-developer : are you really sure of your asset quality ?
(I think that Android does not like your buffer).

**Comment by wigy-opensource-developer** [comment]
Well, I never got it working, have no idea about all codec quirks on Android, but that is why I commited the code so it gets easier to debug what goes wrong.

**Comment by Larpoux** [comment]
Please, could you upload your file ```assets/scanner_beep.ac3``` ?

**Comment by wigy-opensource-developer** [comment]
https://github.com/wigy-opensource-developer/flutter-sample-beep/blob/master/asset/scanner_beep.ac3

**Comment by Larpoux** [comment]
Your problem is that your sound is not AAC but AC3 (Dolby stereo).
Please refer to the flutter_sound README to know the codecs supported by flutter_sound.

**Comment by wigy-opensource-developer** [comment]
Wow, so Android gives the same useless 0x1 for
- file does not exist
- file has invalid access rights
- unsupported codec
- invalid data for a supported codec?

Well, thanks for helping out, I will try to convert it to a few formats until it gives a different error message 😉

**Comment by jigarfumakiya** [comment]
Hey @wigy-opensource-developer, How are you converting formats? Can you please let me know?
I am getting the same issue.
Thanks

**Comment by wigy-opensource-developer** [comment]
Personally I have used the `audacity` open-source application to convert the assets.

**Comment by jigarfumakiya** [comment]
Is there any to do in the app? Like realtime we convert the codec and then play

**Comment by wigy-opensource-developer** [comment]
Sorry, I doubt I can help you in your problem. I made this experiment a year ago and I was not really happy with what I found about Android codec support and the specificity of error codes. If you are planning to integrate conversion into your application, the `ffmpeg` library is a good place to start with.

**Comment by jigarfumakiya** [comment]
Thanks for the info. @wigy-opensource-developer
