### ISSUE TITLE
[FLAUTO] Infinite loop after pause/resume on flauto

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#234]
### Version of flutter_sound
flauto and 2.1.1

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
Pause and resume should work

### Actual behavior
sometimes the app goes in an infinite loop

### Tested environment (Emulator? Real Device?)
Real ios device and ios emulator

### Steps to reproduce the behavior
pause/resume/pause/resume/pause/resume/pause/resume/pause/resume/pause/resume

This is a strange bug. ios enter a loop where it looks like playing a sound. But in reality nothing is played. The progress bar progress, and when finished, restarts.
Except the progress callbacks, my App does not have control.

Actually I do not have identified if it is : 
- a bug in flauto
- a bug of my implementation of flauto
- a bug inside my App itself

This issue must be understood before releasing flauto.
@salvatore373 : if you have any idea, just tell me 😺

**Comment by salvatore373** [comment]
@Larpoux , I'm sorry but I can't reproduce the issue hitting play and pause repeatedly. Could you please post a video of the actual behaviour and, if anything gets printed, a what the console thinks about it?

**Comment by Larpoux** [comment]
@salvatore373 : I do not think this is **your** job to debug **my** bugs.
But of course, if you can help, you are welcome.
Here is [a video](https://github.com/Canardoux/flutter_sound/blob/flauto/Screen%20Recording%202020-03-08%20at%2018.10.57.mov) Unfortunately, this will probably not be very useful.

**Comment by salvatore373** [comment]
@Larpoux , I think that this problem is not related to my code, because, even creating a single play/pause button to perform a faster repeated switch, nothing occurs in my version of the plug-in. So I think that it is related to your flauto code, and I encourage you to double check it to find the line that causes the issue 😉.

**Comment by Larpoux** [comment]
Hi @salvatore373 , hi @hyochan ,

I reproduce this bug without difficulty on the **flutter_sound example**, and **regular plugin 2.1.1**.
This bug is not related to ```flauto```, but is an ancient bug. A very serious bug.

I do not see any raison to delay anymore the ```flauto``` release because of this bug.
Flauto is not worst that the current flutter_sound actually released.

Now I will 
- check @salvatore373  code
- clean my code, 
- do a beta-test with ```Diglot Korean``` (my app)

and if everything ok, we will be able to release ```flauto``` this week 😃

**Comment by Larpoux** [comment]
This bug is always here on FS-V5. This is certainly a bug in IOS.
I prepared a patch that fix that.

**Comment by Larpoux** [comment]
Fixed in 5.1.0
