### ISSUE TITLE
No listening changes in PlayStatus on Android

### ISSUE THREAD

**Issue by Josue10599** [dooboolab/flutter_sound#235]
### Version of flutter_sound
2.1.1
## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale pt-BR)
    • Flutter version 1.12.13+hotfix.8 at /Users/josuelopes/Downloads/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/josuelopes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Report the playback data to start a listener and observe the changes.

```
[Flutter Sound - Start Player] Player resumed
I/flutter (22476):  duration: 1, currentPosition: 0.203
I/flutter (22476):  duration: 1, currentPosition: 0.389
I/flutter (22476):  duration: 1, currentPosition: 0.541
I/flutter (22476):  duration: 1, currentPosition: 0.812
D/FlutterSoundPlugin(22476): Plays completed.
```

### Actual behavior

On Android I am not receiving the data in the PlayStatus Stream listener, due to this I cannot verify the maximum and current audio time and whether it has finished.

```
[Flutter Sound - Start Player] Player resumed
D/FlutterSoundPlugin(22476): Plays completed.
```

### Tested environment (Emulator? Real Device?)

Both (Emulator and Xiaomi Note 8)

### Steps to reproduce the behavior

I'm using Flutter Sound in conjunction with [Flutter Bloc](https://github.com/felangel/bloc).

The methods that correspond to the events are as follows:

- First the download is performed:

```dart
  Stream<ChatState> _mapDownloadAudio(DownloadAudioChatEvent event) async* {
    Directory dir = await getTemporaryDirectory();
    String pathFile = '${dir.path}/${event.audio.fileName}.aac';
    String bucket =
        '${event.audio.path}/${detailsTalk.idTalk}/${event.audio.fileName}';
    File checkFile = File(pathFile);
    if (!await checkFile.exists()) {
      var response = await awsGet.getObject(bucket, pathFile);
      if (response.statusCode >= 200) {
        event.audio.file = File(pathFile);
        _updateAudioData(event.audio);
      }
    } else {
      event.audio.file = checkFile;
      _updateAudioData(event.audio);
    }
    yield DownloadedAudioChatState(conversations, event.audio);
  }
```

- After the download, you can start the audio:

```dart
  Stream<ChatState> _mapEventPlayAudio(PlayAudioChatEvent event) async* {
    if (_sound != null && playerIsPlaying()) {
        await player.stopPlayer();
        _canceledPlayer(_sound);
        _updateAudioData(_sound);
        yield StopAudioChatState(conversations, _sound);
    }
    await _startPlayer(event.audio);
    _updateAudioData(event.audio);
    yield PlayAudioChatState(conversations, event.audio);
  }
```

```dart
  Future<void> _startPlayer(ExtraData audio) async {
    try {
      player.startPlayer(audio.file.path).then((message) {
        log(message, name: 'Flutter - Start Player');
        _onPlay = player.onPlayerStateChanged
            .listen((status) => listeningStatus(status));
      });
      audio.isPlaying = true;
      _sound = audio;
    } catch (e) {
      log(e.toString(), name: 'Flutter Sound - Error');
    }
  }
```

```dart
  void listeningStatus(PlayStatus status) {
    log(status.toString(), name: 'Player - PlayStatus');
    if (status != null) {
      _sound.timeStatus = status;
      add(UpdatePlayStatusChatEvent(_sound));
    } else {
      add(PauseAudioChatEvent(_sound));
    }
  }
```

```dart  
bool playerIsPlaying() => player.audioState == t_AUDIO_STATE.IS_PLAYING;
```

**Comment by Josue10599** [comment]
When analyzing Crashlytics I received the following exception:

```
Fatal Exception: java.lang.IllegalStateException
   at android.media.MediaPlayer.getCurrentPosition(MediaPlayer.java)
   at com.dooboolab.fluttersound.FlutterSoundPlugin$3.run(FlutterSoundPlugin.java:442)
   at java.util.TimerThread.mainLoop(Timer.java:562)
   at java.util.TimerThread.run(Timer.java:512)
```

**Comment by Josue10599** [comment]
I'm only getting the following return in the Logs

```
I/flutter (27643): startPlayer result: /data/user/0/br.com.fulltime.rondafullcenter.mobile/cache/sound.aac
D/FlutterSoundPlugin(27643): Plays completed.
```

I don't know if the reason for the problem is due to migration to AndroidX or my main class in Kotlin or to be using Application for FirebaseMessage.

**Comment by hyochan** [comment]
Would you try `3.0.0` and come back?

**Comment by Josue10599** [comment]
I found out why it wasn't working! I added FirebaseMessaging and it requested a change to AndroidManifest.xml:

```xml
<application
android: name = ". Application"
...>
```

When making this change, the plug-in did not respond correctly.
I tested it back to default and it worked perfectly.

I'm using version 3.1.0

**Comment by Larpoux** [comment]
I feel that this issue is the same as #212

**Comment by Larpoux** [comment]
@Josue10599 ,

Yes, I confirm that Flutter Sound and FCM are not good friends together.
I tried to run the Flutter Sound Example with a special APP linked with Firebase Messaging, and it does not work.
Android Media Player is really painful (I have many problems in Flutter Sound not correctly solved because of Android Media Player).
I think it is time, now, to consider rewriting the Flutter Sound Recorder using other native tools.
Just be patient ... time is the bottle neck.

**Comment by Shakle** [comment]
> I found out why it wasn't working! I added FirebaseMessaging and it requested a change to AndroidManifest.xml to make backgroundMessage work, as shown below:
> 
> ```
> <application
> android: name = ". Application"
> ...
> >
> ```
> 
> When making this change, the plug-in did not respond correctly.
> I tested it back to default and it worked perfectly.
> 
> I'm using version 3.1.0
> 
> In my case for it to work properly I had to leave it like this:
> 
> ```
> <application
> android: name = "io.flutter.app.FlutterApplication"
> ...
> >
> ```
> 
> I'll see how I should implement the changes in FirebaseMessage and upload the code here

Confirm, the same problem on last version.. please do something

**Comment by Larpoux** [comment]
> Confirm, the same problem on last version.. please do something

Yes, someone must do something 😆  .
Who ?

**Comment by Shakle** [comment]
> > Confirm, the same problem on last version.. please do something
> 
> Yes, someone must do something 😆 .
> Who ?

Maybe one of the developers of the plugin.
So the problem is that it can't initialize the recorder if the app has a custom .Application in manifest. A lot of scenarios require this custom .App

Maybe you know some temporary workaround that will allow me to use the recorder in such case now? Please help

**Comment by Larpoux** [comment]
> Maybe one of the developers of the plugin.

Flutter Sound is Free and Open Source. Every body can contribute to improve it. You, for example

**Comment by Larpoux** [comment]
Dear "Bot" : keep this issue open

**Comment by Larpoux** [comment]
Dear "Bot" : keep this issue open 😠

**Comment by Larpoux** [comment]
This duplicates [#212]
