### ISSUE TITLE
add dispose method

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_sound#247]
Would be helpful to have a dispose method which closes up the stream controllers. Thanks.

**Comment by lukepighetti** [comment]
backed by PR https://github.com/dooboolab/flutter_sound/pull/248

**Comment by Larpoux** [comment]
In version 3.1.6, the function release() closes all the stream controllers.

Please feel free to re-open this issue if you think that recent versions of Flutter Sound does not solve your problem.
