### ISSUE TITLE
Feature request, decibel meter sample time

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_sound#251]
Hello! I am trying to capture loud noises (clipping) with a 1/100 sec precision and a 1/10 sec refractory period. I've been able to capture these noises at a rate close to 1/100 sec and a refractory period of 1/2 sec with this project. Do you have any guidance for how we can improve the performance for my use case?

TLDR: I would like to be able to set the decibel meter sample time to 0.05 sec. ie. `FlutterSound.setDbPeakLevelUpdate(intervalTime: 0.01, sampleTime: 0.05)`

**Comment by lukepighetti** [comment]
Handled by https://github.com/dooboolab/flutter_sound/pull/252

**Comment by Larpoux** [comment]
Is your request for iOS or Android ?
Flutter Sound 3.1.6 changed a little bit its code for iOS (#252).

Could you try, and tell us if your request is completely addressed ?
