### ISSUE TITLE
Does the API work if the UIBackgroundModes 'audio' is  not defined?

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#253]
Hi,
Apple rejected our application because of 'audio' was specified in the background mode and they need an explanation I just followed your instructions below and added.

<key>NSMicrophoneUsageDescription</key>
<string>This sample uses the microphone to record your speech and convert it to text.</string>
<key>UIBackgroundModes</key>
<array>
	<string>audio</string>
</array>

 I 'm using these APIs to capture a voice clip and listen to the  clip while user is looking at the screen. I don't have to listen when the application is running in the background.
So my question is, should I remove 'audio' from the UIBackgroundModes? if so, does the API work properly on all device models and OS versions?

Thanks.

**Comment by Larpoux** [comment]
@kmusham : which flutter_sound version do you use ?
@hyochan : I will take care of this issue.

**Comment by Larpoux** [comment]
@kmusham : 
I did some tests on iOS without "Background mode Audio" and flutter_sound seems happy.
You probably can securely  check off this option.
When flutter_sound goes background, its sound is stopped.
When flutter_sound return foreground, its sound resumes.

**Comment by Larpoux** [comment]
Be free to re-open this issue if you think that it has not been solved.
