### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object

### ISSUE THREAD

**Issue by sgehrman** [dooboolab/flutter_sound#254]
### Version of flutter_sound
3.0.0

## flutter doctor
 isAudioOn: The number of audio connected devices 0
03-26 16:08:17.714  2200  3152 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
03-26 16:08:17.714  2200  3152 D HeadsetService:  isAudioOn: The number of audio connected devices 0
03-26 16:08:17.717 21074 21074 D AndroidRuntime: Shutting down VM
03-26 16:08:17.717 21074 21074 E AndroidRuntime: FATAL EXCEPTION: main
03-26 16:08:17.717 21074 21074 E AndroidRuntime: Process: re.distantfutu.journal, PID: 21074
03-26 16:08:17.717 21074 21074 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:231)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1968)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.initMediaSession(BackgroundAudioService.java:483)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.onCreate(BackgroundAudioService.java:402)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4070)
03-26 16:08:17.717 21074 21074 E AndroidRuntime: 	... 8 more

**Comment by sgehrman** [comment]
FATAL EXCEPTION: main
03-26 16:38:35.854 17420 17420 E AndroidRuntime: Process: re.distantfutu.journal, PID: 17420
03-26 16:38:35.854 17420 17420 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:231)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1968)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.initMediaSession(BackgroundAudioService.java:483)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.onCreate(BackgroundAudioService.java:402)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4070)
03-26 16:38:35.854 17420 17420 E AndroidRuntime: 	... 8 more

**Comment by Larpoux** [comment]
@hyochan : I will take care of this issue.

**Comment by Larpoux** [comment]
OK, I encounter this bug myself.
I am currently fixing that.
(This post is just an information so that you know someone working on this bug)

**Comment by Larpoux** [comment]
Pull Request #256 will probably cure this problem.
@hyochan , we need your intervention 😺 to apply this patch in the Master branch.

**Comment by sgehrman** [comment]
awesome, thanks.  Please merge it soon.
