### ISSUE TITLE
acc Conversion pcm

### ISSUE THREAD

**Issue by eric-5512** [dooboolab/flutter_sound#258]
file acc Conversion pcm?

**Comment by Larpoux** [comment]
Actually, flutter_sound cannot record PCM. This will eventually change later.
Converting ACC to PCM is not recommended :  ACC is a compress format, and you will not get a perfect PCM after converting your record.

**Comment by eric-5512** [comment]
I have a requirement, I need to convert aac to pcm, I don't need to play him, I just need to convert pcm to base64 and upload it to the server.

**Comment by Larpoux** [comment]
You can use flutter_ffmpeg for that.
Actually, there is an API verb on flutter_sound 3.0.0 to call a flutter_ffmpeg file conversion.
This is very simple, and we use this feature internally to convert the Apple specific format CAF to OGG/OPUS.

**Comment by eric-5512** [comment]
OK,Thanks

**Comment by Larpoux** [comment]
This verb is not documented because I plan to change a little the way flutter_sound interface with flutter_ffmpeg. But you can freely use it, because the future versions of flutter_sound will depend more and more on flutter_ffmpeg. Many other developers will want flutter_ffmpeg. Sure 😃

**Comment by eric-5512** [comment]
To be honest, I don't know how to use flutter_ffmpeg ...  😃

**Comment by Larpoux** [comment]
wait a few minutes ...

**Comment by eric-5512** [comment]
OK!!!

**Comment by Larpoux** [comment]
Here is an extract from flutter_sound code:  
```if (isOggOpus) {
      // delete the target if it exists (ffmpeg gives an error if the output file already exists)
      File f = File(savedUri);
      if (f.existsSync()) await f.delete();
      // The following ffmpeg instruction re-encode the Apple CAF to OPUS. Unfortunatly we cannot just remix the OPUS data,
      // because Apple does not set the "extradata" in its private OPUS format.
      // It will be good if we can improve this...
      int rc = await executeFFmpegWithArguments([
        '-loglevel',
        'error',
        '-y',
        '-i',
        tmpUri,
        '-c:a',
        'libopus',
        savedUri,
      ]); // remux CAF to OGG
      if (rc != 0) return null;
      return savedUri;
    }
```

**Comment by eric-5512** [comment]
OK,Thanks!!!!

**Comment by liyang1518** [comment]
> Actually, flutter_sound cannot record PCM. This will eventually change later.
> Converting ACC to PCM is not recommended : ACC is a compress format, and you will not get a perfect PCM after converting your record.

Waitting for flutter_sound record PCM.

**Comment by eric-5512** [comment]
> > Actually, flutter_sound cannot record PCM. This will eventually change later.
> > Converting ACC to PCM is not recommended : ACC is a compress format, and you will not get a perfect PCM after converting your record.
> 
> Waitting for flutter_sound record PCM.

in fact. I found that I just need to change the generated audio format to use it normally.

**Comment by liyang1518** [comment]
> > > Actually, flutter_sound cannot record PCM. This will eventually change later.
> > > Converting ACC to PCM is not recommended : ACC is a compress format, and you will not get a perfect PCM after converting your record.
> > 
> > 
> > Waitting for flutter_sound record PCM.
> 
> in fact. I found that I just need to change the generated audio format to use it normally.

What does it mean ‘the generated audio format’，I need to upload the voice file to the server for voice recognition，the voice file must be encoded。

**Comment by liyang1518** [comment]
> > > > Actually, flutter_sound cannot record PCM. This will eventually change later.
> > > > Converting ACC to PCM is not recommended : ACC is a compress format, and you will not get a perfect PCM after converting your record.
> > > 
> > > 
> > > Waitting for flutter_sound record PCM.
> > 
> > 
> > in fact. I found that I just need to change the generated audio format to use it normally.
> 
> What does it mean ‘the generated audio format’，I need to upload the voice file to the server for voice recognition，the voice file must be encoded。[@Larpoux](https://github.com/Larpoux)

**Comment by Larpoux** [comment]
OK. More and more I think that we sould implement PCM recording in flutter_sound.
I am going to work on that. Be patient ...
