### ISSUE TITLE
pubspec version conflict with permission_handler and flutter_sound

### ISSUE THREAD

**Issue by sgehrman** [dooboolab/flutter_sound#259]
### Version of flutter_sound
3.0.0

Running "flutter pub get" in therapist_training...              
Because flutter_sound 3.0.0 depends on permission_handler ^4.4.0 and no versions of flutter_sound match >3.0.0 <4.0.0, flutter_sound ^3.0.0 requires permission_handler ^4.4.0.
So, because therapist_training depends on both flutter_sound ^3.0.0 and permission_handler ^5.0.0+hotfix.1, version solving failed.

pub get failed (1; So, because therapist_training depends on both flutter_sound ^3.0.0 and permission_handler ^5.0.0+hotfix.1, version solving failed.)
exit code 1

**Comment by sgehrman** [comment]
permission_handler just updated to   permission_handler: ^5.0.0+hotfix.1
 today

**Comment by Larpoux** [comment]
I do not see any reason for flutter_sound to request ```permission_handler ^4.4.0``` and not ```permission_handler ^5.0.0```.

I will change that in next release.

**Comment by Larpoux** [comment]
@sgehrman : 
Flutter_sound beta version 3.1.1  now accept to depends on permission_handler until 6.0.0.
This beta version is not yet merged in flutter_sound master branch, but you can test it on : 
https://github.com/Canardoux/flauto . (#257)

**Comment by sgehrman** [comment]
I haven't written a library before, but could you just leave the version numbers blank for packages a libaray depends on?  I wonder if that is a solution?

**Comment by Larpoux** [comment]
Yes, we can do that. But I think that it would not be good.
Major version number (4.x.x, 5.x.x, 6.x.x, ...) are supposed to be incremented when there is changes in the API, and when the plugin is not any more backward compatible.

Version 6.x.x will have breaking changes form 5.0.0, and actually we cannot know if those changes will be OK for flutter_sound.
So the rules are to always specify which versions are known to be compatible.

**Comment by hyochan** [comment]
Please come back after trying `3.1.0`! Closes this for now~
