### ISSUE TITLE
3.0.0+1, still seeing crash randomly. Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object

### ISSUE THREAD

**Issue by sgehrman** [dooboolab/flutter_sound#260]
isAudioOn: The number of audio connected devices 0
03-30 14:58:07.733  6082  6082 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-30 14:58:07.734  6082  6082 E AndroidRuntime: FATAL EXCEPTION: main
03-30 14:58:07.734  6082  6082 E AndroidRuntime: Process: re.distantfutu.journal, PID: 6082
03-30 14:58:07.734  6082  6082 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:231)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1968)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.initMediaSession(BackgroundAudioService.java:483)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at com.dooboolab.fluttersound.BackgroundAudioService.onCreate(BackgroundAudioService.java:402)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4070)
03-30 14:58:07.734  6082  6082 E AndroidRuntime: 	... 8 more

**Comment by Larpoux** [comment]
OK. I am going to look to this serious problem.

**Comment by Larpoux** [comment]
Are you sure that it is 3.0.0+1  and not Flauto Beta 3.1.0  ?
(unfortunately I had a regression in Flauto Beta 3.1.0, and I just fix it)

**Comment by sgehrman** [comment]
I'm sure it was 3.0.0+1.  I tried flutter clean and flutter pub get to make sure it was using that new version.  I tested a few times to make sure, since it was acting the same as 3.0.0

**Comment by Larpoux** [comment]
Thank you.  Bad bug :-(
I am going to work on it. But probably I will ask you to do other tests after some modifications, because I do not encounter this bug any more myself.

**Comment by Larpoux** [comment]
@sgehrman : 
Please, could you check [my beta branch](https://github.com/Canardoux/flauto/tree/beta/android/src/main/java/com/dooboolab/fluttersound). I added a few traps in the code to understand better what is the problem.

Thank you.

**Comment by hyochan** [comment]
`3.1.0` has been released just now. @sgehrman Could you try that?

**Comment by sgehrman** [comment]
same problem.  I have bluetooth headphones.  If they are off, it crashes, if I turn them on it doen't crash.

Also saw this: with 3.1.0

Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'invokeMethod' was called on null.
Receiver: null
Tried calling: invokeMethod("setSubscriptionDuration", _LinkedHashMap len:2))

And I had to update my minSdkVersion to 24.  

Launching lib/main/main_journal.dart on HD1905 in debug mode...
/home/steve/Documents/GitHub/therapist_training/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:flutter_ffmpeg] /home/steve/Documents/GitHub/therapist_training/build/flutter_ffmpeg/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.arthenica.flutter.ffmpeg" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processJournalDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:flutter_ffmpeg] /home/steve/Documents/GitHub/therapist_training/build/flutter_ffmpeg/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.arthenica.flutter.ffmpeg" to force usage (may lead to runtime failures)

**Comment by Larpoux** [comment]
This is because you use the ffmpeg ```audio``` module.
If you want a minSdkVersion < 24, just replace the ffmpeg module by ```audio-lts``` in your build.gradle.
```
ext.flutterFFmpegPackage = 'audio-lts'
```

**Comment by Larpoux** [comment]
1. The Exception that you get is not the same issue than the one you got previously.
Are you sure that you called ```myFlutterSoundPlayer.initialize()``` ?
Also I need your complete logs to understand better.
2. Your minSdkVersion problem is because you use the ffmpeg ```audio``` module.
If you want a minSdkVersion < 24, just replace the ffmpeg module by ```audio-lts``` in your build.gradle.
```
ext.flutterFFmpegPackage = 'audio-lts'
```

**Comment by sgehrman** [comment]
I wasn't calling initialize, but I added that and it still crashes if my bluetooth headphones are turned off.

**Comment by Larpoux** [comment]
We need your logs when you have crash.

**Comment by Larpoux** [comment]
Is your problem solved ?

**Comment by Larpoux** [comment]
Please, re-open this issue if you still have crashes with Flutter Sound 3.1.10
