### ISSUE TITLE
1.7.0 以上的版本会报错  找不到   ActivityCompat.requestPermissions

### ISSUE THREAD

**Issue by wang709693972wei** [dooboolab/flutter_sound#264]
C:\Users\Administrator\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:43: ����: �Ҳ�������
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  ����:   ��� ActivityCompat
  λ��: �� sdkCompat
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sound:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

是否有依赖这个包     api 'androidx.appcompat:appcompat:1.1.0-rc01'

**Comment by Larpoux** [comment]
@wang709693972wei : 
This issue is fixed in version patched 3.1.2
Please, check that it works fine.

**Comment by Larpoux** [comment]
Please re-open this issue, if you think that it has not been solved correctly.
