### ISSUE TITLE
isRecording and isPlaying

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#266]
### Version of flutter_sound
3.1.2

### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
A homogeneous behavior

### Actual behavior
Not a homogeneous behavior

Actually, 
- isRecording is true when the recorder is in paused mode
- isPlaying is false when the player is in paused mode

We must have a homogeneous behavior with those 2 verbs.
I do not have really an opinion on which of those 2 behaviors is better.
Does someone has an opinion on that ?

**Comment by Larpoux** [comment]
@hyochan : 
please look to this issue. We need to change that **very very quickly**, because it will be a breaking change.
I think that isRecording must be false when paused : probably very few developers already use the function pauseRecorder().

I suggest to do it tomorrow, if you are OK.

**Comment by hyochan** [comment]
Agree on isRecording to be false when paused!

**Comment by Larpoux** [comment]
Fixed in 3.1.3
