### ISSUE TITLE
MissingPluginException(No implementation found for method initializeFlautoRecorder on channel com.dooboolab.flutter_sound_recorder)

### ISSUE THREAD

**Issue by xia-weiyang** [dooboolab/flutter_sound#267]
### Platforms you faced the error

 Android

please help me, thanks!

I don't know why I can't find this method, this is log.

```
I/flutter ( 8046): MissingPluginException(No implementation found for method initializeFlautoRecorder on channel com.dooboolab.flutter_sound_recorder)
I/flutter ( 8046): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
I/flutter ( 8046): <asynchronous suspension>
I/flutter ( 8046): #1      FlautoRecorderPlugin.invokeMethod 
package:flutter_sound/flutter_sound_recorder.dart:72
I/flutter ( 8046): #2      FlutterSoundRecorder.invokeMethod 
package:flutter_sound/flutter_sound_recorder.dart:137
I/flutter ( 8046): #3      FlutterSoundRecorder.initialize 
package:flutter_sound/flutter_sound_recorder.dart:145
I/flutter ( 8046): #4      _MoodAddPageState._recordVoice 
package:oldtime/ui/mood_add.dart:402
I/flutter ( 8046): #5      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
I/flutter ( 8046): #6      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
I/flutter ( 8046): #7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
I/flutter ( 8046): #8      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
I/flutter ( 8046): #9      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:264
I/flutter ( 8046): #10     BaseTapGestureRecognizer.acceptGesture (package:fl
```

**Comment by Larpoux** [comment]
You seems to have a bad mix between the beta version/3.0.0 version and 3.1.3

You can try 
```
flutter pub get
flutter clean
```

If the problem persists send us the result of ```flutter pub deps```

**Comment by Larpoux** [comment]
Post also your pubspec.yaml with the result of ```flutter pub deps```

**Comment by xia-weiyang** [comment]
https://github.com/dooboolab/flutter_sound/blob/master/android/src/main/java/com/dooboolab/fluttersound/Flauto.java#L116 

Did you forget to register ？

```
FlautoRecorderPlugin.attachFlautoRecorder ( ctx, registrar.messenger () );
```

It's ok now, when I add it.

**Comment by Larpoux** [comment]
👍  You are perfectly right. Two lines are missing : 
```
		FlautoRecorderPlugin.attachFlautoRecorder ( ctx, registrar.messenger ()  );
		TrackPlayerPlugin.attachTrackPlayer ( ctx, registrar.messenger ()  );
```
Until now, we have never tested this function because we always use the new 'Flutter Embedded V2'

I am going to push a patch V3.1.4 this after noon.
Thank you for your contribution. 👍

**Comment by Larpoux** [comment]
@xia-weiyang 

Patch Release 3.1.5 is supposed to fix this bug.
Thank you again

**Comment by xia-weiyang** [comment]
Thanks for your patch.

**Comment by lancer1993** [comment]
I got this MissingPluginException. This is an **Android** platform.
Here is my **flutter pub deps**

Dart SDK 2.15.1
Flutter SDK 2.8.1
|-- audio_session 0.1.6+1
|   |-- flutter...
|   |-- flutter_web_plugins 0.0.0
|   |   |-- characters...
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- js...
|   |   |-- meta...
|   |   |-- typed_data...
|   |   '-- vector_math...
|   |-- meta...
|   '-- rxdart...
|-- audioplayers 0.19.1
|   |-- flutter...
|   |-- flutter_web_plugins...
|   |-- http...
|   |-- path_provider...
|   '-- uuid...
|-- cached_network_image 3.2.0
|   |-- cached_network_image_platform_interface 1.0.0
|   |   |-- flutter...
|   |   '-- flutter_cache_manager...
|   |-- cached_network_image_web 1.0.1
|   |   |-- cached_network_image_platform_interface...
|   |   |-- flutter...
|   |   '-- flutter_cache_manager...
|   |-- flutter...
|   |-- flutter_cache_manager...
|   '-- octo_image 1.0.0+1
|       |-- flutter...
|       '-- flutter_blurhash 0.6.0
|           |-- flutter...
|           |-- meta...
|           '-- pedantic...
|-- camera 0.5.0
|   '-- flutter...
|-- carousel_slider 4.0.0
|   '-- flutter...
|-- chewie 1.1.0
|   |-- cupertino_icons...
|   |-- flutter...
|   |-- video_player...
|   '-- wakelock 0.5.6
|       |-- flutter...
|       |-- meta...
|       |-- wakelock_macos 0.4.0
|       |   |-- flutter...
|       |   |-- flutter_web_plugins...
|       |   '-- wakelock_platform_interface...
|       |-- wakelock_platform_interface 0.3.0
|       |   |-- flutter...
|       |   '-- meta...
|       |-- wakelock_web 0.4.0
|       |   |-- flutter...
|       |   |-- flutter_web_plugins...
|       |   |-- js...
|       |   '-- wakelock_platform_interface...
|       '-- wakelock_windows 0.2.0
|           |-- flutter...
|           |-- wakelock_platform_interface...
|           '-- win32...
|-- connectivity 3.0.0
|   |-- connectivity_macos 0.2.0
|   |   '-- flutter...
|   |-- connectivity_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- connectivity_platform_interface 2.0.1
|   |-- flutter...
|   |-- meta...
|   '-- plugin_platform_interface...
|-- cupertino_icons 1.0.3
|-- dio 2.2.2
|   '-- cookie_jar 1.0.1
|-- flushbar 1.10.4
|   '-- flutter...
|-- flutter 0.0.0
|   |-- characters 1.2.0
|   |-- collection...
|   |-- meta...
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0
|   |   '-- collection...
|   '-- vector_math 2.1.1
|-- flutter_cache_manager 3.3.0
|   |-- clock 1.1.0
|   |-- collection 1.15.0
|   |-- file 6.1.2
|   |   |-- meta...
|   |   '-- path...
|   |-- flutter...
|   |-- http...
|   |-- path...
|   |-- path_provider...
|   |-- pedantic...
|   |-- rxdart 0.27.1
|   |-- sqflite 2.0.0+3
|   |   |-- flutter...
|   |   |-- path...
|   |   '-- sqflite_common 2.0.0+2
|   |       |-- meta...
|   |       |-- path...
|   |       '-- synchronized...
|   '-- uuid...
|-- flutter_image 4.1.0
|   '-- flutter...
|-- flutter_lints 1.0.4
|   '-- lints 1.0.1
|-- flutter_map 0.12.0
|   |-- async...
|   |-- collection...
|   |-- flutter...
|   |-- flutter_image...
|   |-- latlong 0.6.1
|   |   |-- console_log_handler 1.1.6
|   |   |   |-- ansicolor 1.1.1
|   |   |   |-- intl...
|   |   |   '-- logging...
|   |   |-- intl...
|   |   |-- logging 0.11.4
|   |   '-- validate 1.7.0
|   |-- meta...
|   |-- positioned_tap_detector 1.0.3
|   |   '-- flutter...
|   |-- proj4dart 1.0.5
|   |   |-- meta...
|   |   |-- mgrs_dart 1.0.1
|   |   |   '-- unicode 0.2.4
|   |   |       '-- lists 0.1.6
|   |   '-- wkt_parser 1.0.7
|   |-- transparent_image 1.0.0
|   |-- tuple 1.0.3
|   |   '-- quiver 2.1.5
|   |       |-- matcher...
|   |       '-- meta...
|   '-- vector_math...
|-- flutter_sound 9.1.2
|   |-- flutter...
|   |-- flutter_sound_platform_interface 9.1.2
|   |   |-- flutter...
|   |   |-- logger...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter_sound_web 9.1.2
|   |   |-- flutter...
|   |   |-- flutter_sound_platform_interface...
|   |   |-- flutter_web_plugins...
|   |   |-- js 0.6.3
|   |   |-- logger...
|   |   '-- meta...
|   |-- logger 1.1.0
|   |-- path...
|   |-- path_provider...
|   |-- provider 6.0.2
|   |   |-- collection...
|   |   |-- flutter...
|   |   '-- nested 1.0.0
|   |       '-- flutter...
|   |-- recase 4.0.0
|   |-- synchronized 3.0.0
|   '-- uuid...
|-- flutter_test 0.0.0
|   |-- async...
|   |-- boolean_selector 2.1.0
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- charcode 1.3.1
|   |-- clock...
|   |-- collection...
|   |-- fake_async 1.2.0
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.11
|   |   '-- stack_trace...
|   |-- meta...
|   |-- path...
|   |-- source_span 1.8.1
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.10.0
|   |   '-- path...
|   |-- stream_channel 2.1.0
|   |   '-- async...
|   |-- string_scanner 1.1.0
|   |   |-- charcode...
|   |   '-- source_span...
|   |-- term_glyph 1.2.0
|   |-- test_api 0.4.3
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- typed_data...
|   '-- vector_math...
|-- http 0.13.3
|   |-- async 2.8.2
|   |   |-- collection...
|   |   '-- meta...
|   |-- http_parser 4.0.0
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- source_span...
|   |   |-- string_scanner...
|   |   '-- typed_data...
|   |-- meta 1.7.0
|   |-- path...
|   '-- pedantic...
|-- image_picker 0.6.5+3
|   |-- flutter...
|   '-- flutter_plugin_android_lifecycle 1.0.11
|       '-- flutter...
|-- intl 0.17.0
|   |-- clock...
|   '-- path...
|-- just_audio 0.9.18
|   |-- async...
|   |-- audio_session...
|   |-- crypto...
|   |-- flutter...
|   |-- just_audio_platform_interface 4.0.0
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- just_audio_web 0.4.3
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- just_audio_platform_interface...
|   |-- meta...
|   |-- path...
|   |-- path_provider...
|   |-- rxdart...
|   '-- uuid...
|-- new_gradient_app_bar 0.2.0
|   '-- flutter...
|-- path 1.8.0
|-- path_provider 2.0.8
|   |-- flutter...
|   |-- path_provider_android 2.0.11
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_ios 2.0.7
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_linux 2.1.5
|   |   |-- ffi 1.1.2
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   '-- xdg_directories 0.2.0
|   |       |-- meta...
|   |       |-- path...
|   |       '-- process 4.2.1
|   |           |-- file...
|   |           |-- path...
|   |           '-- platform...
|   |-- path_provider_macos 2.0.0
|   |   '-- flutter...
|   |-- path_provider_platform_interface 2.0.1
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- platform 3.0.0
|   |   '-- plugin_platform_interface...
|   '-- path_provider_windows 2.0.5
|       |-- ffi...
|       |-- flutter...
|       |-- path...
|       |-- path_provider_platform_interface...
|       '-- win32 2.2.5
|           '-- ffi...
|-- pedantic 1.11.1
|-- permission_handler 8.3.0
|   |-- flutter...
|   |-- meta...
|   '-- permission_handler_platform_interface 3.7.0
|       |-- flutter...
|       |-- meta...
|       '-- plugin_platform_interface...
|-- photo_view 0.13.0
|   '-- flutter...
|-- pinch_zoom_image_last 0.4.1
|   '-- flutter...
|-- plugin_platform_interface 2.1.2
|   '-- meta...
|-- rflutter_alert 2.0.4
|   '-- flutter...
|-- shared_preferences 2.0.0
|   |-- flutter...
|   |-- meta...
|   |-- shared_preferences_linux 2.0.0
|   |   |-- file...
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- path_provider_linux...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_macos 2.0.0
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_platform_interface 2.0.0
|   |   '-- flutter...
|   |-- shared_preferences_web 2.0.0
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- meta...
|   |   '-- shared_preferences_platform_interface...
|   '-- shared_preferences_windows 2.0.0
|       |-- file...
|       |-- flutter...
|       |-- meta...
|       |-- path...
|       |-- path_provider_platform_interface...
|       |-- path_provider_windows...
|       '-- shared_preferences_platform_interface...
|-- sticky_headers 0.1.8+1
|   |-- flutter...
|   '-- meta...
|-- url_launcher 6.0.0
|   |-- flutter...
|   |-- url_launcher_linux 2.0.0
|   |   '-- flutter...
|   |-- url_launcher_macos 2.0.0
|   |   '-- flutter...
|   |-- url_launcher_platform_interface 2.0.4
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- url_launcher_web 2.0.1
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- meta...
|   |   '-- url_launcher_platform_interface...
|   '-- url_launcher_windows 2.0.0
|       '-- flutter...
|-- uuid 3.0.4
|   '-- crypto 3.0.1
|       |-- collection...
|       '-- typed_data...
|-- video_player 2.2.16
|   |-- flutter...
|   |-- html 0.15.0
|   |   |-- csslib 0.17.1
|   |   |   '-- source_span...
|   |   '-- source_span...
|   |-- video_player_platform_interface 5.0.1
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   '-- video_player_web 2.0.6
|       |-- flutter...
|       |-- flutter_web_plugins...
|       |-- pedantic...
|       '-- video_player_platform_interface...
|-- webview_flutter 2.0.0
|   '-- flutter...
'-- zoomable_image 1.3.1
    '-- flutter...

And this is the exception,

E/flutter ( 7360): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method resetPlugin on channel com.dooboolab.flutter_sound_recorder)
E/flutter ( 7360): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360): #1      FlutterSoundRecorder._openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart:398:9)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360): #2      FlutterSoundRecorder.openRecorder.<anonymous closure> (package:flutter_sound/public/flutter_sound_recorder.dart:374:11)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360): #4      FlutterSoundRecorder.openRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:373:5)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360): #5      _StepTwoEnglishState.openTheRecorder (package:coco_App/page/english/apata_kiyanna/step_two.dart:244:5)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360): #6      _StepTwoEnglishState.init (package:coco_App/page/english/apata_kiyanna/step_two.dart:200:5)
E/flutter ( 7360): <asynchronous suspension>
E/flutter ( 7360):
