### ISSUE TITLE
document the result value of startPlayer and startPlayerFromBuffer

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#269]
The methods startPlayer,  startPlayerFromBuffer and startRecorder all  return a Future<String>.

There is no documentation on what that string contains.

**Comment by Larpoux** [comment]
Yes, @bsutton ,
You are right with #269 #270 #265 : FlutterSound documentation must be improved.

My feeling is that all the doc should be rewritten.
I think that the README should not document the API itself, but better to link to
several pages : 
- API for FlutterSoundRecorder
- API for FlutterSoundPlayer
- API for TrackPlayer
- API for FlutterSoundHelper

Of course, if you can do something for the documentation, it would be fantastic.
A native English spoken is very precious.

**Comment by bsutton** [comment]
If you want to draft something I'm happy to go over the grammar.

**Comment by bsutton** [comment]
The readme should have an overview of how to use the methods and some
examples but the details should be left to the library doco.

**Comment by Larpoux** [comment]
OK, that sounds good.
I will try to do something better than now.
But later, because I am currently overbooked.

**Comment by Larpoux** [comment]
done
