### ISSUE TITLE
Need to throw an exception if initialize not called.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#271]
I've just upgraded to 3.x.

My code did not call the initialize method before calling startRecorder.

The result was a no suchMethodError.

It would be helpful if the public api threw an exception if initialize hadn't been called.

On the other hand why can't this be handled internally? Why do we need to force the user to call it when the package could initialise itself?

**Comment by Larpoux** [comment]
Yes, you are right.
I will add this check in next release.

**Comment by Larpoux** [comment]
Flutter Sound 3.1.6 calls initialise() itself if the App did not do it.
