### ISSUE TITLE
How to play a file list one by one?

### ISSUE THREAD

**Issue by kunnetcn** [dooboolab/flutter_sound#275]
### Version of flutter_sound
2.1.1
### Platforms you faced the error (IOS or Android or both?)
android
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
error: player is running, stop it first... 
i tried to stop it, but it's not worked!

i just try to play a file address list by flutter_sound player.when i tried to play one file,it worked...but when i try to invoke the player one by one file,it did not work....anyone can tell me how to play sound one by one?thank you very much!

**Comment by Larpoux** [comment]
On flutter_sound 3.1.x you can do something like that : 
```
void playAnotherSound()
{
        String fileUri = ......
        String result = await flutterSoundPlayer.startPlayer
	       (
		      fileUri,
		      whenFinished:  playAnotherSound
	       );
}
```

**Comment by kunnetcn** [comment]
thanks for your answer...may i use 2.1.1 version to do this loop?if i use 3.1.x,firstly,i need to update android version to androidX which i don't want to do that!

**Comment by Larpoux** [comment]
I think you can use 3.1.x without androidX if you do not use the module ```TrackPlayer```.
If you try that , we will be glad to know if it's OK or not.

**Comment by Larpoux** [comment]
Depending on your result, we will update the README.

**Comment by kunnetcn** [comment]
Hi friend,i tried to use 3.1.x to play a sound on anroid9, it's worked...but when i want to loop another sound file by whenfinished method as you talk.it's not worked.
i print whenfinished method, and i found that, the method print before sound completed.maybe there is something wrong....

I/flutter (26917): pressed play....
I/flutter (26917): **whenFinished invoke 22222222222222**
D/FlutterSoundPlugin(26917): mediaPlayer prepared and start
I/flutter (26917): startPlayer result: /storage/emulated/0/xxxxxx/m01/cn/1.mp3
D/FlutterSoundPlugin(26917): **Plays completed.**
V/MediaPlayer(26917): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(26917): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(26917): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false      
V/MediaPlayer(26917): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by Larpoux** [comment]
Could you send us your code ?
Perhaps an ```await``` is missing somewhere ?
I guess that it is a problem in your code and not in Flutter Sound.
But of course, not sure... ;-)

**Comment by kunnetcn** [comment]
==========My test source follow this:
playRecord() async {
    flutterSoundPlayer = await new FlutterSoundPlayer().initialize();
    String result = await flutterSoundPlayer.startPlayer
	       (
		      '/storage/emulated/0/chaojiriyu/m01/cn/1.mp3',
		      whenFinished: await playAnotherRecord('/storage/emulated/0/chaojiriyu/m01/cn/2.mp3')
	       );
  }

  playAnotherRecord(file) async {
    print('whenFinished invoke 22222222222222');
    String result = await flutterSoundPlayer.startPlayer
	       (
		      file,
	       );
    // flutterSoundPlayer.release();
  }

**Comment by kunnetcn** [comment]
It's only can play the first sound on my device.
=============this is my console info:
I/flutter ( 9034): pressed play....
I/flutter ( 9034): whenFinished invoke 22222222222222
D/FlutterSoundPlugin( 9034): mediaPlayer prepared and start
I/flutter ( 9034): startPlayer result: /storage/emulated/0/chaojiriyu/m01/cn/2.mp3
V/MediaPlayer( 9034): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9034): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 9034): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9034): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/FlutterSoundPlugin( 9034): mediaPlayer prepared and start
I/flutter ( 9034): startPlayer result: /storage/emulated/0/chaojiriyu/m01/cn/1.mp3
D/FlutterSoundPlugin( 9034): Plays completed.
V/MediaPlayer( 9034): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9034): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 9034): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9034): cleanDrmObj: mDrmObj=null mDrmSessionId=null

**Comment by Larpoux** [comment]
First impression  :  
You must not call ```'initialise()'``` and ```'realease()'``` during your process.
You must call ```initialize()``` before your process and ```release()``` when your audio process is finished.

But ```release()``` is commented, so I think that flutter_sound does not execute ```initialise()```.

**Comment by Larpoux** [comment]
whenFinished: is a lambda function (a closure as young people call that).

Your code is not correct : 
```
String result = await flutterSoundPlayer.startPlayer
(
'/storage/emulated/0/chaojiriyu/m01/cn/1.mp3',
whenFinished: await playAnotherRecord('/storage/emulated/0/chaojiriyu/m01/cn/2.mp3')
);
```

You must use : 
```
String result = await flutterSoundPlayer.startPlayer
(
'/storage/emulated/0/chaojiriyu/m01/cn/1.mp3',
whenFinished: (){ playAnotherRecord('/storage/emulated/0/chaojiriyu/m01/cn/2.mp3');}
);

**Comment by kunnetcn** [comment]
I think the problem is not initialise method.when i run the playRecord method.firstly, the first sound is palying,and at the same time,whenfinished method is invoked,but ths first sound is not complete,so someting wrong there.

**Comment by Larpoux** [comment]
```playAnotherRecord(file) ``` does not need to be async, and no need to do ```await``` inside.

**Comment by kunnetcn** [comment]
it's ok,thanks for your answer!Best Regards!

**Comment by Larpoux** [comment]
No problem. It was a pleasure.
Do not hesitate to come back if you have more problems.

**Comment by Larpoux** [comment]
Do not hesitate to come back if you have more problems.
