### ISSUE TITLE
remove permissions requests from flutter sound.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#277]
I'm wondering if we would be better off removing the permission requests from flutter sound.

Leaving the permissions requests to the call allows more flexiblity on how the permissions are requested and removes permission_handler as a dependency.

I've just tried to upgrade to permission_handler 5.0 which has a cleaner api and flutter_sound is stopping the upgrade. 
Further I want to control when and how permissions are requested.

**Comment by Larpoux** [comment]
Yes, I think that your right.
Generally, flutter_sound should not do anything which is not his direct responsibility.
But problem with backward compatibility.
I think that we sould implement #274

**Comment by Larpoux** [comment]
Flutter Sound Version 3.1.6 is now compatible with 
permission_handler 5.0.
