### ISSUE TITLE
Pausing a recording doesn't 'pause' the duration.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#278]
If you pause a recording the duration listener stops sending events.

As soon as you resume recording the listener correctly starts sending events however it includes the 'paused' time in the duration.

We need to subtract the paused periods (one or more) from the duration.

**Comment by Larpoux** [comment]
Yes @bsutton . We are going to fix that.
Thank you for your PR (Problem Report).

**Comment by Larpoux** [comment]
I do not see any problem on the Example App.

**Comment by bsutton** [comment]
I've implemented this in the 4.x branch.
Will push later today.

**Comment by Larpoux** [comment]
Is this issue still open on 3.x.x ?

**Comment by bsutton** [comment]
I've not back ported the fix as I've been concentrating of the 4.0 release.
The latest PR has the fix for 4.0.

**Comment by develappsoftwaresolutions** [comment]
Hi Larpoux, I'm facing the same issue. 
Kindly provide an update on this, when can we expect this fix?

**Comment by chpraneeth1539** [comment]
Hi Larpoux, I'm facing the same issue.
Kindly provide an update on this, when can we expect this fix?

**Comment by Larpoux** [comment]
Fixed in Release Version 4.0.3+1

Please re-open this issue if still problems in this area.
