### ISSUE TITLE
PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)

### ISSUE THREAD

**Issue by theecn** [dooboolab/flutter_sound#280]
### Version of flutter_sound
3.1.0
## flutter doctor
![image](https://user-images.githubusercontent.com/22100544/79044979-1d04f400-7c3b-11ea-96df-d9712b37350b.png)

### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
play remote aac file
### Actual behavior
get  error
![image](https://user-images.githubusercontent.com/22100544/79044918-c26b9800-7c3a-11ea-9011-fd30af61034a.png)

### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
followed the example ,I`ve done this .
![image](https://user-images.githubusercontent.com/22100544/79044965-078fca00-7c3b-11ea-8bfa-a8c2f31ac815.png)

# I use the http protocol to get remote file, will this be the cause of the problem？

**Comment by Larpoux** [comment]
The flutter_sound example can play https://...  sound without any problem.
So I do not think that your problem is caused by the http protocol.

At first seeing your initialization seems correct.
Your logs show that the problem occurs during the prepare() statement on the Android Audio Player.
Are you sure of your source (file accessible, and with a format supported by flutter sound ?).

Actually I have no time to look deeper in your issue. Probably i will do it in a few days.

**Comment by theecn** [comment]
yep ,the aac audio file was created by the flutter_sound.And I downloaded it from server ,it works on mac system player

**Comment by Larpoux** [comment]
Just a remark : ```playerModule.initialize()``` is called two times.
The second call is ignored by flutter_sound, but maybe you can remove it.

**Comment by Larpoux** [comment]
What is ```advancePlayer``` used for ?  Are you sure that there is no conflict with flutter_sound ?

**Comment by Larpoux** [comment]
Can you post your code for ```startPlayer()``` ?

Note : Android Media Player is very very hard to be pleased with the prepare() function arguments, and does not give us any usefull information except that it is not called in a good state ... Not easy to debug.
Please try again with last flutter_sound version 3.1.7.

**Comment by theecn** [comment]
Thanks,I changed other phone to test it,it works well. the Android Version is 8.0.0, core is 4.4.23+. by the same,fk the bad manufator

**Comment by Larpoux** [comment]
I am very glad that you solved your PR (Problem Report).
Do not hesitate to come back if you have problems.

**Comment by sedobrengocce** [comment]
@Larpoux
I've se same problem on a Emulated Device
I'm using flutter_sound_lite
the player state is "Fully initialized" and "Stopped" when i call 
``` dart
startPlayer(uri)
```

**Comment by Larpoux** [comment]
@sedobrengocce 
Please fill a new issue (with logs, and your plugin version) if you have problems with Flutter Sound.
