### ISSUE TITLE
Can't show skip backward and skip forward buttons on lock screen

### ISSUE THREAD

**Issue by lstimac** [dooboolab/flutter_sound#281]
### Version of flutter_sound
3.1.6
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.0)
[√] Connected device (1 available)

• No issues found!

### Problem
I'm trying to show skip forward and skip backward buttons on lock screen (currently only play/pause is available), however I can't seem to find a way to pass canSkipForward and canSkipBackward which are necessary for these functionalities to be visible and usable. I tried adding onSkipBackward and onSkipForward to startPlayerFromTrack method, looked if I can pass canSkipBackward and canSkipForward to Track, TrackPlayer or their methods, but none of it worked. Any help would be appreciated!

Btw. this is an awesome and easy to use plugin, great job 😄

**Comment by lstimac** [comment]
Solved: It is working, I just had to expand notification card on the lock screen to expose the skip functions.

**Comment by Larpoux** [comment]
Hi @lstimac .
Thank you for your encouragements. 😸 
Glad to know that you fixed your issue.
Do not hesitate to come back if you have other problems.
