### ISSUE TITLE
Resume issue

### ISSUE THREAD

**Issue by vernalclareai** [dooboolab/flutter_sound#285]
### Version of flutter_sound
3.1.6
## flutter doctor
 flutter_sound: ^3.1.6

### Platforms you faced the error (IOS or Android or both?)
on both platform
### Expected behavior
Playing the remote audio file is okay, but after finishing the file, if I start playing on the file, it seems downloading the file and playing again.
I was playing *.oga file with OPUS codec from my server.
It should resume from 0.0 position, because the file was loaded.
right?

### Actual behavior
after finishing the file, if I start playing on the file, it seems downloading the file and playing again.
I was playing *.oga file with OPUS codec from my server.

### Tested environment (Emulator? Real Device?)
on ios real device.
### Steps to reproduce the behavior
after finishing the remote oga file,  if I start playing on the file, it seems downloading the file and playing again.
I was playing *.oga file with OPUS codec from my server.

**Comment by Larpoux** [comment]
What do you expect ? Playing again your file without downloading it ?

**Comment by vernalclareai** [comment]
I think it should be played without any delay again.

**Comment by bsutton** [comment]
There is an argument that we should leave to the user to cache the file themselves.
If we start caching files pulled from a url there are then management questions about how many files we should cache and for how long.

**Comment by Larpoux** [comment]
I agree with the @bsutton answer.

**Comment by vernalclareai** [comment]
You can give the count limited for the cache files.
and  files cached will be cleared automatically when the app close.

**Comment by bsutton** [comment]
There would need to be a size limit not just a count limit. The concept of an app closing is also not so much a thing.
Most people don't 'close' an app but leaving it hanging. I assume we can probably detect this state but if the user just 'moves' away from the app then comes back should we have cleared the cache?
These feel like decisions that should be made by the app developer not by a plugin developer.

**Comment by vernalclareai** [comment]
okay, I see.
Another issue: 
When can this framework support for all codecs?

For example: OGG/Vorbis

**Comment by Larpoux** [comment]
OGG/Vorbis is in the pipe-line, somewhere.
Personally, I consider th OGG/Vorbis almost as important than OGG/OPUS
But this pipe-line is completely full and I worry that it will explode soon ;-)

**Comment by vernalclareai** [comment]
okay, I see.

I have a quick question.
/full & /audio-lts has some different modules?
because I have big problem on ios when switched to the /audio-lts to publish.
Ios was playing ogg.opus file with /full module, but not with /audio-lts.

**Comment by Larpoux** [comment]
Flutter Sound can play OGG/OPUS with the audio-lts module .
You can look to [flutter_ffmpeg documentation](https://pub.dev/packages/flutter_ffmpeg) .
`audio-lts` is fine if you do not deal with video.

You can also look to [our README doc](https://github.com/dooboolab/flutter_sound) to know what is supported by flutter_sound, using the `audio-lts` module.
I can play OGG/OPUS, both on Android and iOS, but it still cannot record OGG/OPUS on Android.

This will be changed in a near future .... because I need this feature myself for my own App 😄 .
So I will put this development somewhere in the top of the list of things to do ;-)

**Comment by vernalclareai** [comment]
Sounds good.
May I use the full-gpl module also for ffmpeg to publish?
because I have a build issue with full module.

**Comment by Larpoux** [comment]
I do not know if anybody already published something using audio-lts.
Probably yes. What kind of problems ?

You could also have a look to version : [flutter_sound: ^4.0.0-beta.2](https://github.com/dooboolab/flutter_sound/tree/4.0.0-beta)

In this beta version, `mobile_ffmpeg` is directely linked with `mobile_ffmpeg`.
The App do not have anymore to make a dependency to `flutter_ffmpeg` .
- You will remove that dependency from `pubspec.yaml`
- You will remove the line you added into `build.gradle`
- And you will remove this horrible lines from your Podfile.

I think that this beta version will be the next 3.2.0 version, so probably not so bad to begin looking to it.

**Comment by vernalclareai** [comment]
4.0.0-beta.2 will not removed later?
So I will not have big problem for the app published later.
Thanks.

**Comment by Larpoux** [comment]
Actually, our plan is to publish the actual Beta version as `Flutter Sound V3.2.0` very soon.
Unfortunately, this version has not been very much tested by the developers.
But personally, I want to publish it in a matter of a few weeks.

**Comment by vernalclareai** [comment]
Just installed the beta version
I will test and let you know.

**Comment by Larpoux** [comment]
That's great. Thank you very much to help us to validate this version.

**Comment by vernalclareai** [comment]
I have build issue with beta version on ios.

https://whatsapp-inbox-server.clare.a/data/audios/d038130c-60ff-49f4-bc62-0673871e7816.oga

Can you please play on your side for 3.1.10 with audio-lts module?
I am getting playing error for 3.1.10.
Thanks.

**Comment by vernalclareai** [comment]
but with full module, it can be played.

**Comment by vernalclareai** [comment]
Android is playing the file with audio-lts, but not ios.

**Comment by vernalclareai** [comment]
I am using Codec_OPUS.

**Comment by Larpoux** [comment]
Android is able to play OGG/OPUS natively without FFmpeg.
We use FFmpeg to play OGG/OPUS on ios.

So there is probably something wrong when linking to flutter_ffmpeg.

What does `flutter pub deps` show ?

**Comment by vernalclareai** [comment]
3.1.10

**Comment by Larpoux** [comment]
No, the complete result from flutter pub deps : did you verified the link-edit with flutter_ffmpeg ?

**Comment by vernalclareai** [comment]
system('rm -rf .symlinks')
      system('mkdir -p .symlinks/plugins')
      plugin_pods = parse_KV_file('../.flutter-plugins')
      plugin_pods.each do |name, path|
        symlink = File.join('.symlinks', 'plugins', name)
        File.symlink(path, symlink)
        if name == 'flutter_ffmpeg'
            pod name+'/audio-lts', :path => File.join(symlink, 'ios')
        else
            pod name, :path => File.join(symlink, 'ios')
        end
      end

I verified the pod file in ios.

**Comment by Larpoux** [comment]
That seems correct.
I have no idea what is the problem.
I guess that there not many people who tried to publish and verified that OGG/OPUS works correctly. Most people wants MP3 !!! But personally I really need that it will work when I will have finished my own App (later this summer).

I suggest that you try 4.0.0-beta.2 . But I understand that your App is going to be released very soon and is not actually in develop state.

**Comment by vernalclareai** [comment]
I will use /full-gpl module with 3.1.10 for now.
It is working well for OGG/OPUS.
Thanks.

**Comment by Larpoux** [comment]
That think this is the good solution for you.
Re-open this issue if the problem still occurs when we will switch to 4.0.0
