### ISSUE TITLE
albumArtAsset is not showing in notification on TrackPlayer

### ISSUE THREAD

**Issue by noobcoder17** [dooboolab/flutter_sound#286]
albumArtAsset is not showing in notification. 

I provided the Asset path as an .png image form local device storage. But it is not showing in the notification of TrackPlayer.

Can anyone give an example how to implement that ?

**Comment by Larpoux** [comment]
This is an extract from ```Dyglot``` App.
It shows the App Icon on the lock screen : 
```
               try
                {
                        soundPlaying = data;
                        if (soundModule is TrackPlayer)
                        {
                                String albumArt;
                                if (Platform.isIOS)
                                {
                                        albumArt = 'AppIcon';
                                } else if (Platform.isAndroid)
                                {
                                        albumArt = 'AppIcon.png';
                                }
                                Track track = Track( codec: t_CODEC.CODEC_OPUS, dataBuffer: data, trackAuthor: author, trackTitle: title, albumArtAsset: albumArt /*albumArtPath*/ );
                                TrackPlayer module = soundModule;
                                await module.startPlayerFromTrack
                                        (
                                        track,
                                        onSkipBackward: onSkipBackward,
                                        onSkipForward: onSkipForward,
                                        whenFinished: whenFinished,
                                        whenPaused: whenPaused,
                                        );
                        } else
                                await soundModule.startPlayerFromBuffer( data, codec: t_CODEC.CODEC_OPUS, whenFinished: whenFinished );
                        thePracticeForm.setState( ( )
                                                  {} );
                }
                catch (e)
                {
                        print( "startPlayer failure : " + e.toString( ) );
                        return soundModule.stopPlayer( );
                }
```

**Comment by noobcoder17** [comment]
I got the image path like - /data/user/0/com.example.player/cache/albumArt.png
and i set this as the albumArtAsset of Track. 
But the album art is not showing on the notification. 
What to do?

Track track = Track (
      trackTitle: songInfo.title,
      trackAuthor: songInfo.artist,
      trackPath: file.path,
      albumArtAsset: "/data/user/0/com.example.player/cache/albumArt.png"
);

**Comment by Larpoux** [comment]
@noobcoder17 ,
Your .png file is not an asset. So you must not use the parameter ```albumArtAsset:``` .
You can try to use : 
```albumArtUrl:  '//file: /data/user/0/com.example.player/cache/albumArt.png'```
but I am not sure that it will work.

Please tell us if OK or not OK. If not OK, I will tag your issue as 'Enhancement'

**Comment by noobcoder17** [comment]
I added this <b>file:///storage/emulated/0/Android/data/com.android.providers.media/albumthumbs/1502372031642.png</b> and without .png as the albumArt.


in albumArtUrl - the app crashes.
in albumArtAsset - image not showing.

What to do?

**Comment by Larpoux** [comment]
Actually, I think that Flutter Sound cannot display an arbitrary file *.png
It just can display a specific asset or a remote image (using HTTP).

I agree that it is weak. I am flagging this issue as a needed enhancement.

**Comment by Larpoux** [comment]
@noobcoder17 : 
I will do something tomorrow for your request.
This is really stupid that Flutter Sound cannot display a png image.

This enhancement will be filled tomorrow or thursday.

**Comment by Larpoux** [comment]
Hi @noobcoder17 ,

In the future version 4.0.0 we will have a new parameter in the Track structure : 
`albumArtFile` which is a String representing a local file that points to the image to display in the notification as album art.

You can specify just one field for the Album Art to display on the lock screen. Either : 
- albumArtUrl
- albumArtFile
- albumArtFile

If no Album Art field is specified, Flutter Sound will try to display the App icon.

You can try this new feature in `flutter_sound: ^4.0.0-beta.2`.
But be aware that it **is not released version**, and probably not good to use it in a released App. **The API is actually to stabilized** and will change very soon.

**Comment by Whfall** [comment]
@Larpoux, 
Hi, thanks for the library! What can I do wrong? The album icon is displayed only after you click the pause button

**Comment by Larpoux** [comment]
Yes, I saw that when the Album Art is a remote file.
It is possible that it is a problem in Flutter Sound and not your fault.
I am going to look to that very soon.

Please keep this issue Open.

**Comment by Whfall** [comment]
@Larpoux,
OK, thanks for the answer! But can I change the standard Flutter icon to my own if the album photo didn't load?

**Comment by Larpoux** [comment]
You will be able to specify your own local xxx.png  in version 4.0.0 .
You can try ^4.0.0-beta.2

Yes, you are right : if we cannot load a remote Album Art, flutter_sound should try to use the AppIcon.png (on Android) and AppIcon(on iOS).

If not successful, then flutter_sound should let the OS handle itself this image.

**Comment by Whfall** [comment]
@Larpoux,
Thank you again, you are very responsive. Last 2 questions: can I set the progress bar to play a track? And why does the lock screen only display the pause button?

**Comment by Larpoux** [comment]
If you want to have the `skipForward` and `skipBackward` buttons, you must specify the arguments `onSkipForawrd:` and `onSkipBackward` during your `startPlayerFromTrack()`

**Comment by Whfall** [comment]
@Larpoux,
Ok, ty.
