### ISSUE TITLE
PlatformException when calling startPlayerFromTrack method 

### ISSUE THREAD

**Issue by lstimac** [dooboolab/flutter_sound#287]
### Version of flutter_sound
3.1.7
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.0)
[√] Connected device (1 available)

• No issues found!

### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
I expect track player to initialize MediaController and start playing music after calling startPlayerFromTrack method. 

### Actual behavior
I get an error regarding the MediaControllerCompat, it always happens on release version and on debug only when calling startPlayerFromTrack a first few times. 

> Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.support.v4.media.session.MediaControllerCompat$TransportControls android.support.v4.media.session.MediaControllerCompat.getTransportControls()' on a null object reference, null)

I should also add that it works when putting a breakpoint on await _trackPlayer.startPlayerFromTrack( ... ) and then doing step overs, it seems like this occurs because of MediaControllerCompat not having enough time to succesfully establish a session (maybe?).

### Tested environment (Emulator? Real Device?)
Real device
### Snippet of code (deleted irrelevant parts)

```
class AudioPlayer{

  final BuiltList<Song> songList;
  TrackPlayer _trackPlayer;
  StreamController<Map<String, String>> streamSongInfo;
  StreamController<double> streamProgress;

  AudioPlayer(this.songList){
    _init();
  }

  void _init() async{
    _trackPlayer = TrackPlayer();
    streamSongInfo = new StreamController<Map<String, String>>();
    streamProgress = new StreamController<double>();
  }

  void startPlayer(){
    playSong(
      songList[_songIndex].songURL, 
      songList[_songIndex].name, 
      songList[_songIndex].artist
    );
  }

  void playSong(String song, String name, String artist) async{
    //generateWaveData();
    
    Track track = new Track(
      trackPath: song,
      trackTitle: name,
      trackAuthor: artist,
    );

    streamSongInfo.add(
      {
        "name": name, 
        "artist": artist
      }
    );
    
    await _trackPlayer.startPlayerFromTrack(
      track,
      whenFinished: (){
        playNextSong();
      },
      onSkipForward: (){
        print("SKIP FORWARD");
        playNextSong();
      },
    ).then((_){
      _addListeners();
    });
  }
}
```

**Comment by lstimac** [comment]
### Expanded error

> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): Failed to handle method call
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.media.session.MediaControllerCompat$TransportControls android.support.v4.media.session.MediaControllerCompat.getTransportControls()' on a null object reference
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at com.dooboolab.fluttersound.TrackPlayer.startPlayerFromTrack(TrackPlayer.java:331)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at com.dooboolab.fluttersound.TrackPlayerPlugin.onMethodCall(TrackPlayer.java:152)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at android.os.MessageQueue.next(MessageQueue.java:363)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at android.os.Looper.loop(Looper.java:173)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> E/MethodChannel#com.dooboolab.flutter_sound_track_player(26540): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by Larpoux** [comment]
OK. I am going to look to that.

**Comment by lstimac** [comment]
I must be doing something wrong, but I tried using FlutterSoundPlayer and everything works as expected, only TrackPlayer produces these issues :/ 

I've tried putting startPlayerFromTrack inside a try/catch block, and calling playSong again on catch. It works on debug since it errors the first time but works the second time when MediaControllerCompat is no longer null. The problem is release mode, where it won't start player no matter what I do :joy:

**Comment by Larpoux** [comment]
OK @lstimac .
It seems that there is a little bug in Flutter Sound when the App does not initialize correctly its Flutter Sound module. I am going to fix this bug in 3.1.8
You probably can avoid this bug if you do : 
```
_trackPlayer = TrackPlayer().initialize();
```
in your ```_init()``` procedure.
Please, tell us if you success or not.

**Comment by Larpoux** [comment]
Sorry, the correct line tou use is : 
```
_trackPlayer = await TrackPlayer().initialize();
```

**Comment by Larpoux** [comment]
OK @lstimac : 
Flutter Sound 3.1.8 probably fix your bug.
But still better to initialize your self the Flutter Sound module as expalin above.

**Comment by lstimac** [comment]
It's working great now on debug when I initialize it myself, but player still won't start in release mode (after doing initialization myself, there is no longer an error in debug console but nothing happens). Does TrackPlayer usually work in release mode? 

I am extremely grateful for your fast responses and your time spent on looking into this! 😄

**Comment by Larpoux** [comment]
Thank you for your congratulations.
We are trying to answer to issues, as faster than we can.
But sometimes we can't because it will need times ... and we do not really have times.

This little bug in Flutter Sound was simple to fix.

**Comment by Larpoux** [comment]
Of course Flutter Sound is supposed to work on released App !

**Comment by Larpoux** [comment]
Do you have problem when playing the first song, or after ```playNextSong```

**Comment by lstimac** [comment]
The problem occurs when starting the player and playing the first song, there is no music whatsoever on release mode for some reason (and no error either) :/

**Comment by Larpoux** [comment]
Real device or Emulator ?

**Comment by Larpoux** [comment]
Do you have logs, when running in release Mode ?

**Comment by lstimac** [comment]
Everything is run on a real device (Huawei Honor 10 Lite). I have no logs in release mode, tried putting startPlayerFromTrack inside a try/catch but it never enters catch since there is no error (it just doesn't start playing).

**Comment by Larpoux** [comment]
Without the logs it is very difficult to understand what happens.
Do you have a return from "StartPlayerFromTrack()" ?
If yes, what is the value returned ?

**Comment by lstimac** [comment]
I think it gets stuck in the await startPlayerFromTrack, because no result gets printed and there is no error. Can you tell me would be the best way to log what happens in the app so we can see what happens during that method call?

**Comment by Larpoux** [comment]
What I would do with Android Studio would be : 
- Open your project
- Click on the root of your project
- With the right mouse button : select "Flutter" > "Open Android Module in Android Studio"
- Run your project in Release Mode (Green triangle pointing to the right)
- Open 6: Logcat tab (bottom left of your screen)
- In Logcat tab : select your device in the combo-box
- In Logcat tab : select the correct main process
- In logcat tab : select "error" , "warn"  or "info"

**Comment by lstimac** [comment]
Good idea, I'm currently in VS Code, I'm gonna try running the app in Android Studio. TrackPlayer works fine for you in release mode?

**Comment by Larpoux** [comment]
Yes, sure it does.

---------
/Larpoux

**Comment by lstimac** [comment]
I just found out what the issue was, ran the app through Android Studio and Logcat error said MediaPlayerService requires Internet permission (obviously) to start this service in a release version of the app. I thought about the possibility this occurs because of a permission issue, but it's strange that debug worked fine without this permission. Everything is working as expected now, and I should probably start using Android Studio and it's logcat instead of VS Code haha

Thank you so much for your help!

### Log

> 2020-04-14 16:03:42.136 16089-16089/? E/MediaPlayerService: Request requires android.permission.INTERNET
> 2020-04-14 16:03:42.136 13361-13361/? E/MediaPlayerNative: Unable to create media player
> 2020-04-14 16:03:42.141 13361-13361/? E/BackgroundAudioService: The following error occurred while trying to set the track to play in the audio player.
>     java.io.IOException: setDataSource failed.: status=0x80000000
>         at android.media.MediaPlayer.nativeSetDataSource(Native Method)
>         at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1255)
>         at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1208)
>         at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1173)
>         at com.dooboolab.fluttersound.BackgroundAudioService$2.onPlayFromMediaId(BackgroundAudioService.java:183)
>         at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlayFromMediaId(MediaSessionCompat.java:1410)
>         at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlayFromMediaId(MediaSessionCompatApi21.java:202)
>         at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1596)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:213)
>         at android.app.ActivityThread.main(ActivityThread.java:8147)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by Larpoux** [comment]
You are welcome. It was a pleasure.
Do not hesitate to come back if you have other issues.

**Comment by kelrigor** [comment]
Hello guys, maybe someone can help me, 

But i'm getting error, 

E/SoundStreamPlugin( 9527): Unexpected exception
E/SoundStreamPlugin( 9527): java.lang.NullPointerException
E/SoundStreamPlugin( 9527): 	at vn.casperpas.sound_stream.SoundStreamPlugin.startRecording(SoundStreamPlugin.kt:267)
E/SoundStreamPlugin( 9527): 	at vn.casperpas.sound_stream.SoundStreamPlugin.onMethodCall(SoundStreamPlugin.kt:108)
E/SoundStreamPlugin( 9527): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/SoundStreamPlugin( 9527): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/SoundStreamPlugin( 9527): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/SoundStreamPlugin( 9527): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/SoundStreamPlugin( 9527): 	at android.os.Handler.handleCallback(Handler.java:789)
E/SoundStreamPlugin( 9527): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/SoundStreamPlugin( 9527): 	at android.os.Looper.loop(Looper.java:164)
E/SoundStreamPlugin( 9527): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/SoundStreamPlugin( 9527): 	at java.lang.reflect.Method.invoke(Native Method)
E/SoundStreamPlugin( 9527): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/SoundStreamPlugin( 9527): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
I/flutter ( 9527): PlatformException(Unknown, Unexpected exception, null, null)

This happen's on first load of the app, after user allowing audio/mic permission. after the app is restarted, the issue will be resolved, anyone expertise this?

i've already check the .kit, and the above solution is there. 

hope someone can help me with this.


![image](https://user-images.githubusercontent.com/9277458/213211171-6b060f5b-7de2-4ea7-9007-7b192477e43a.png)
