### ISSUE TITLE
app crash when call trackPlayer.release

### ISSUE THREAD

**Issue by chenft** [dooboolab/flutter_sound#289]
### Version of flutter_sound
3.1.8
### Platforms you faced the error (IOS or Android or both?)
android

### Actual behavior
sometimes when I release the trackerPlayer, app will crash.

such as: 
await audioPlayer.release();

### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
1.initialize the trackplayer
2.startPlayerFromTrack
3. switch play、 pause、next on notification or foregraund
4.repeatly
5.call release when page is dispose
6.sometimes whill crash

**Comment by Larpoux** [comment]
We need your logs.

**Comment by chenft** [comment]
> We need your logs.

I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
D/MediaPlayerNative(32165): Action:stop, CurrentState:MEDIA_PLAYER_STOPPED
D/MediaPlayerNative(32165): Message: Unknown MediaEventType(8), ext1=0, ext2=0x0
D/MediaPlayerNative(32165): [notify] : [1204] callback app listenerNotNull=1, send=1
D/MediaPlayerNative(32165): [notify] : [1216] callback application
I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
D/MediaPlayerNative(32165): Action:reset_l, CurrentState:MEDIA_PLAYER_IDLE
V/MediaPlayer(32165): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32165): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
V/MediaPlayer(32165): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32165): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
V/MediaPlayer(32165): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32165): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayerNative(32165): Pid:32165 MediaPlayer destructor
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-11
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): 	at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): 	at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-12
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): 	at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): 	at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-8
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): 	at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): 	at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-10
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): 	at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): 	at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-9
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): 	at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): 	at java.util.TimerThread.run(Timer.java:505)
E/CrashReport(32165): Java Crash Happen cause by Timer-11(3881)
W/CrashReport(32165): no read_log permission!
I/CrashReport(32165): [LogUtil] Get user log from native.
I/CrashReport-Native(32165): Native log has not been initiated.
I/CrashReport(32165): user log size:0
E/CrashReport(32165): stack frame :3, has cause false
E/CrashReport(32165): #++++++++++Record By Bugly++++++++++#
E/CrashReport(32165): # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
E/CrashReport(32165): # PKG NAME: im.weshine.haipei
E/CrashReport(32165): # APP VER: 1.4.7
E/CrashReport(32165): # LAUNCH TIME: 2020-04-15 16:40:00
E/CrashReport(32165): # CRASH TYPE: JAVA_CRASH
E/CrashReport(32165): # CRASH TIME: 2020-04-15 16:44:12
E/CrashReport(32165): # CRASH PROCESS: im.weshine.haipei
E/CrashReport(32165): # CRASH THREAD: Timer-11
E/CrashReport(32165): # REPORT ID: 3912eae0-b8f6-491d-8317-30bd2976e2fd
E/CrashReport(32165): # CRASH DEVICE: LND-AL30 UNROOT
E/CrashReport(32165): # RUNTIME AVAIL RAM:1882349568 ROM:46796922880 SD:46775926784
E/CrashReport(32165): # RUNTIME TOTAL RAM:3752538112 ROM:57602437120 SD:57581465600
E/CrashReport(32165): # CRASH STACK:
E/CrashReport(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/CrashReport(32165): 	at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/CrashReport(32165): 	at java.util.TimerThread.mainLoop(Timer.java:555)
E/CrashReport(32165): 	at java.util.TimerThread.run(Timer.java:505)
E/CrashReport(32165): #++++++++++++++++++++++++++++++++++++++++++#
D/CrashReport(32165): [Database] deleted t_lr data 1
D/CrashReport(32165): [Database] insert t_lr success.
I/CrashReportInfo(32165): [crash] a crash occur, handling...
D/CrashReport(32165): [Database] insert t_cr success.
D/CrashReport(32165): insert t_cr success!
I/CrashReportInfo(32165): [crash] save crash success
I/CrashReport(32165): try to upload right now
D/CrashReport(32165): attach pageTracingList
D/CrashReport(32165): java.lang.NullPointerException rid:3912eae0-b8f6-491d-8317-30bd2976e2fd sess:9355a784-1e65-4ff4-afdf-c9d9433951c9 ls:251s isR:false isF:true isM:false isN:false mc:0 ,null ,isUp:false ,vm:34
W/Timer-11(32165): type=1400 audit(0.0:499293): avc: denied { read } for name="type" dev="sysfs" ino=30308 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/Timer-11(32165): type=1400 audit(0.0:499294): avc: denied { search } for name="usb" dev="sysfs" ino=33742 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=dir permissive=0
I/CrashReport(32165): Failed to get boot time of device.
D/CrashReport(32165): [UploadManager] Add upload task (pid=32165 | tid=32738)
D/CrashReport(32165): [UploadManager] Sucessfully got session ID, try to execute upload task now (pid=32165 | tid=32738)
D/CrashReport(32165): [UploadManager] Execute synchronized upload task (pid=32165 | tid=32738)
D/CrashReport(32165): [Upload] Run upload task with cmd: 830
D/CrashReport(32165): [UploadManager] Integrate security to HTTP headers (pid=32165 | tid=620)
D/CrashReport(32165): [Util] Zip 40698 bytes data with type Gzip
D/CrashReport(32165): [Database] deleted t_lr data 1
D/CrashReport(32165): [Database] insert t_lr success.
D/CrashReport(32165): [UploadManager] Uploading(ID:1004) time: 2020-04-15 16:44:12
D/CrashReport(32165): [Upload] Send 4089 bytes
D/CrashReport(32165): [Upload] Upload to http://android.bugly.qq.com/rqd/async?aid=d643c81d-c806-469e-8110-bef45785c441 with cmd 830 (pid=32165 | tid=620).
D/CrashReport(32165): request: http://android.bugly.qq.com/rqd/async?aid=d643c81d-c806-469e-8110-bef45785c441, send: 4089 (pid=32165 | tid=620)
D/CrashReport(32165): [Upload] Bugly version from headers is: bugly/1.0
D/CrashReport(32165): [Upload] Status from server is 0 (pid=32165 | tid=620).
D/CrashReport(32165): [Upload] Received 146 bytes
D/CrashReport(32165): [Util] Unzip 130 bytes data with type Gzip
D/CrashReport(32165): [Upload] Response cmd is: 0, length of sBuffer is: 0
I/CrashReport(32165): [Upload] Success: crash
D/CrashReport(32165): [UploadManager] Local network consume: 66 KB
D/CrashReport(32165): [Database] deleted t_lr data 1
D/CrashReport(32165): [Database] insert t_lr success.
D/CrashReport(32165): [UploadManager] Network total consume: 71 KB
D/CrashReport(32165): up finish update state true
D/CrashReport(32165): pre uid:3912eae0-b8f6-491d-8317-30bd2976e2fd uc:0 re:false me:false
D/CrashReport(32165): set uid:3912eae0-b8f6-491d-8317-30bd2976e2fd uc:1 re:true me:false
D/CrashReport(32165): [Database] insert t_cr success.
D/CrashReport(32165): insert t_cr success!
D/CrashReport(32165): update state size 1
E/CrashReport(32165): sys default last handle start!
D/CrashReport(32165): >>> im.weshine.haipei.MainActivity onPaused <<<
I/CrashReport-Native(32165): Set native info: isAppForeground(false)
D/HMSAgent(32165): Activity(1795)->Application(236)->ActivityMgr(205)->onActivityPaused
D/HMSAgent(32165): onPaused:im.weshine.haipei.MainActivity@6859740
I/Process (32165): Sending signal. PID: 32165 SIG: 9
Lost connection to device.




Here is the buggly log.
![1586941393816](https://user-images.githubusercontent.com/17562266/79319591-1a581680-7f3b-11ea-91c5-44c4cfc0058d.jpg)

**Comment by chenft** [comment]
@Larpoux 

I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
D/MediaPlayerNative(32165): Action:stop, CurrentState:MEDIA_PLAYER_STOPPED
D/MediaPlayerNative(32165): Message: Unknown MediaEventType(8), ext1=0, ext2=0x0
D/MediaPlayerNative(32165): [notify] : [1204] callback app listenerNotNull=1, send=1
D/MediaPlayerNative(32165): [notify] : [1216] callback application
I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
D/MediaPlayerNative(32165): Action:reset_l, CurrentState:MEDIA_PLAYER_IDLE
V/MediaPlayer(32165): resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32165): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
V/MediaPlayer(32165): resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32165): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayer(32165): [HSM] stayAwake false uid: 10155, pid: 32165
V/MediaPlayer(32165): resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(32165): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/MediaPlayerNative(32165): Pid:32165 MediaPlayer destructor
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-11
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-12
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-8
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-10
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): at java.util.TimerThread.run(Timer.java:505)
E/AndroidRuntime(32165): FATAL EXCEPTION: Timer-9
E/AndroidRuntime(32165): Process: im.weshine.haipei, PID: 32165
E/AndroidRuntime(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/AndroidRuntime(32165): at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/AndroidRuntime(32165): at java.util.TimerThread.mainLoop(Timer.java:555)
E/AndroidRuntime(32165): at java.util.TimerThread.run(Timer.java:505)
E/CrashReport(32165): Java Crash Happen cause by Timer-11(3881)
W/CrashReport(32165): no read_log permission!
I/CrashReport(32165): [LogUtil] Get user log from native.
I/CrashReport-Native(32165): Native log has not been initiated.
I/CrashReport(32165): user log size:0
E/CrashReport(32165): stack frame :3, has cause false
E/CrashReport(32165): #++++++++++Record By Bugly++++++++++#
E/CrashReport(32165): # You can use Bugly(http:\bugly.qq.com) to get more Crash Detail!
E/CrashReport(32165): # PKG NAME: im.weshine.haipei
E/CrashReport(32165): # APP VER: 1.4.7
E/CrashReport(32165): # LAUNCH TIME: 2020-04-15 16:40:00
E/CrashReport(32165): # CRASH TYPE: JAVA_CRASH
E/CrashReport(32165): # CRASH TIME: 2020-04-15 16:44:12
E/CrashReport(32165): # CRASH PROCESS: im.weshine.haipei
E/CrashReport(32165): # CRASH THREAD: Timer-11
E/CrashReport(32165): # REPORT ID: 3912eae0-b8f6-491d-8317-30bd2976e2fd
E/CrashReport(32165): # CRASH DEVICE: LND-AL30 UNROOT
E/CrashReport(32165): # RUNTIME AVAIL RAM:1882349568 ROM:46796922880 SD:46775926784
E/CrashReport(32165): # RUNTIME TOTAL RAM:3752538112 ROM:57602437120 SD:57581465600
E/CrashReport(32165): # CRASH STACK:
E/CrashReport(32165): java.lang.NullPointerException: Attempt to read from field 'android.support.v4.media.session.MediaControllerCompat com.dooboolab.fluttersound.MediaBrowserHelper.mediaControllerCompat' on a null object reference
E/CrashReport(32165): at com.dooboolab.fluttersound.TrackPlayer$MediaPlayerOnPreparedListener$1.run(TrackPlayer.java:620)
E/CrashReport(32165): at java.util.TimerThread.mainLoop(Timer.java:555)
E/CrashReport(32165): at java.util.TimerThread.run(Timer.java:505)
E/CrashReport(32165): #++++++++++++++++++++++++++++++++++++++++++#
D/CrashReport(32165): [Database] deleted t_lr data 1
D/CrashReport(32165): [Database] insert t_lr success.
I/CrashReportInfo(32165): [crash] a crash occur, handling...
D/CrashReport(32165): [Database] insert t_cr success.
D/CrashReport(32165): insert t_cr success!
I/CrashReportInfo(32165): [crash] save crash success
I/CrashReport(32165): try to upload right now
D/CrashReport(32165): attach pageTracingList
D/CrashReport(32165): java.lang.NullPointerException rid:3912eae0-b8f6-491d-8317-30bd2976e2fd sess:9355a784-1e65-4ff4-afdf-c9d9433951c9 ls:251s isR:false isF:true isM:false isN:false mc:0 ,null ,isUp:false ,vm:34
W/Timer-11(32165): type=1400 audit(0.0:499293): avc: denied { read } for name="type" dev="sysfs" ino=30308 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/Timer-11(32165): type=1400 audit(0.0:499294): avc: denied { search } for name="usb" dev="sysfs" ino=33742 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=dir permissive=0
I/CrashReport(32165): Failed to get boot time of device.
D/CrashReport(32165): [UploadManager] Add upload task (pid=32165 | tid=32738)
D/CrashReport(32165): [UploadManager] Sucessfully got session ID, try to execute upload task now (pid=32165 | tid=32738)
D/CrashReport(32165): [UploadManager] Execute synchronized upload task (pid=32165 | tid=32738)
D/CrashReport(32165): [Upload] Run upload task with cmd: 830
D/CrashReport(32165): [UploadManager] Integrate security to HTTP headers (pid=32165 | tid=620)
D/CrashReport(32165): [Util] Zip 40698 bytes data with type Gzip
D/CrashReport(32165): [Database] deleted t_lr data 1
D/CrashReport(32165): [Database] insert t_lr success.
D/CrashReport(32165): [UploadManager] Uploading(ID:1004) time: 2020-04-15 16:44:12
D/CrashReport(32165): [Upload] Send 4089 bytes
D/CrashReport(32165): [Upload] Upload to http://android.bugly.qq.com/rqd/async?aid=d643c81d-c806-469e-8110-bef45785c441 with cmd 830 (pid=32165 | tid=620).
D/CrashReport(32165): request: http://android.bugly.qq.com/rqd/async?aid=d643c81d-c806-469e-8110-bef45785c441, send: 4089 (pid=32165 | tid=620)
D/CrashReport(32165): [Upload] Bugly version from headers is: bugly/1.0
D/CrashReport(32165): [Upload] Status from server is 0 (pid=32165 | tid=620).
D/CrashReport(32165): [Upload] Received 146 bytes
D/CrashReport(32165): [Util] Unzip 130 bytes data with type Gzip
D/CrashReport(32165): [Upload] Response cmd is: 0, length of sBuffer is: 0
I/CrashReport(32165): [Upload] Success: crash
D/CrashReport(32165): [UploadManager] Local network consume: 66 KB
D/CrashReport(32165): [Database] deleted t_lr data 1
D/CrashReport(32165): [Database] insert t_lr success.
D/CrashReport(32165): [UploadManager] Network total consume: 71 KB
D/CrashReport(32165): up finish update state true
D/CrashReport(32165): pre uid:3912eae0-b8f6-491d-8317-30bd2976e2fd uc:0 re:false me:false
D/CrashReport(32165): set uid:3912eae0-b8f6-491d-8317-30bd2976e2fd uc:1 re:true me:false
D/CrashReport(32165): [Database] insert t_cr success.
D/CrashReport(32165): insert t_cr success!
D/CrashReport(32165): update state size 1
E/CrashReport(32165): sys default last handle start!
D/CrashReport(32165): >>> im.weshine.haipei.MainActivity onPaused <<<
I/CrashReport-Native(32165): Set native info: isAppForeground(false)
D/HMSAgent(32165): Activity(1795)->Application(236)->ActivityMgr(205)->onActivityPaused
D/HMSAgent(32165): onPaused:im.weshine.haipei.MainActivity@6859740
I/Process (32165): Sending signal. PID: 32165 SIG: 9
Lost connection to device.

**Comment by Larpoux** [comment]
OK, I am going to look to that.

**Comment by Larpoux** [comment]
I think that there is a little bug in Flutter Sound when the App try to ```release()``` the player during a playback.
I will fix that.
In the meantime, could you add a ```await myFlutterSoundModule.stopPlayer();``` just before your ```release()``` and tell me if it is better.

**Comment by chenft** [comment]
@Larpoux 
I accept your advance, try to add await audioPlayer.stopPlayer() before release, but it's not working

**Comment by Larpoux** [comment]
Same crash ?

**Comment by chenft** [comment]
@Larpoux 
yeap

**Comment by Larpoux** [comment]
Could you try Flutter Sound 3.1.10 and tell us if better.
If not better, post the new logs.

**Comment by chenft** [comment]
@Larpoux 
I run flutter_sound 3.1.10 on my project, the crash seems not  reappear，and leave so many log : MediaPlayerOnPreparedListener timer: mMediaBrowserHelper.mediaControllerCompat is NULL

**Comment by Larpoux** [comment]
Please, re-open this issue if this point is not correctly handled by Flutter Sound
