### ISSUE TITLE
Resume recording fails after playing recording on actual iOS device only

### ISSUE THREAD

**Issue by claptimes5** [dooboolab/flutter_sound#292]
### Version of flutter_sound
3.1.8

## flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.42.1)
[✓] Connected device (4 available)
```

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
On the iOS simulator, I can:
1. Start recording
2. Pause recording
3. Play that recording
4. Resume recording where I left off

On my iPad (device)
1. Start recording
2. Pause recording
3. Play that recording
4. Resume recording where I left off

### Actual behavior

On the iOS simulator: works as expected

On my iPad (device)
1. Start recording
2. Pause recording
3. Play that recording
4. **Resume recording fails**

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
I'm trying to get this to work the same in the example app, but I'm having issues running it on the simulator and device.

**Comment by Larpoux** [comment]
We need the logs when **Resume recording fails**

**Comment by claptimes5** [comment]
There is no log output for the failure. Here is the debug screen where I get a `false` back from `resumeRecorder`
![image](https://user-images.githubusercontent.com/583936/79472829-51c5d200-7fd2-11ea-9921-1f28254a57ae.png)

**Comment by claptimes5** [comment]
Actually, there I do get an error when trying to get the current position of the recording upon resuming

```
2020-04-16 11:08:54.610099-0400 Runner[1711:571600] flutter: starting new recording
2020-04-16 11:08:57.331861-0400 Runner[1711:571600] flutter: resuming
2020-04-16 11:09:00.051993-0400 Runner[1711:571600] flutter: resuming
2020-04-16 11:09:05.848099-0400 Runner[1711:571600] flutter: startPlayer result: /var/mobile/Containers/Data/Application/6F67867A-2EEF-4D42-8CA8-DFD653BB9A3C/Library/Caches/flauto.aac
2020-04-16 11:09:05.848223-0400 Runner[1711:571600] flutter: startPlayer: /var/mobile/Containers/Data/Application/6F67867A-2EEF-4D42-8CA8-DFD653BB9A3C/Library/Caches/flauto.aac
2020-04-16 11:09:07.623908-0400 Runner[1711:571403] audioPlayerDidFinishPlaying
2020-04-16 11:11:23.970606-0400 Runner[1711:571600] flutter: startPlayer result: /var/mobile/Containers/Data/Application/6F67867A-2EEF-4D42-8CA8-DFD653BB9A3C/Library/Caches/flauto.aac
2020-04-16 11:11:23.970734-0400 Runner[1711:571600] flutter: startPlayer: /var/mobile/Containers/Data/Application/6F67867A-2EEF-4D42-8CA8-DFD653BB9A3C/Library/Caches/flauto.aac
2020-04-16 11:11:25.746928-0400 Runner[1711:571403] audioPlayerDidFinishPlaying
2020-04-16 11:11:26.566588-0400 Runner[1711:571600] flutter: could not resume, stopping
2020-04-16 11:11:26.569907-0400 Runner[1711:571600] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'currentPosition' was called on null.
Receiver: null
Tried calling: currentPosition
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _RecordingScreenState._startRecording.<anonymous closure> (package:my_app/pages/recording_screen.dart:256:17)
```

**Comment by claptimes5** [comment]
I modified the flutter_sound example app to be able to play back paused recordings and it works correctly on my device. Using the modified example app, I can: 

1. Start recording
2. Pause recording
3. Play that recording
4. Resume recording where I left off
5. Pause recording again
6. Play back recording
7. And on and on

I think this may be an issue with my own app, but I really don't know why there is a difference between the simulator and the real device. 

I'm going to close this issue unless anyone else notices this same problem.

**Comment by chpraneeth1539** [comment]
> There is no log output for the failure. Here is the debug screen where I get a `false` back from `resumeRecorder`
> ![image](https://user-images.githubusercontent.com/583936/79472829-51c5d200-7fd2-11ea-9921-1f28254a57ae.png)

Hi I am facing the same issue.

@Larpoux  as @claptimes5  mentioned we are not getting any logs, even I have reported the same issue recently and mentioned that I was not getting any logs. you have closed the issue as i was not able to provide logs.

I have the same issue on my IOS device

**Comment by Larpoux** [comment]
Linked to #330

**Comment by chpraneeth1539** [comment]
<img width="747" alt="Screenshot 2020-05-03 at 2 48 24 PM" src="https://user-images.githubusercontent.com/31837107/80910450-27ec0980-8d4d-11ea-8da3-09f621839ebe.png">

**Comment by Larpoux** [comment]
Linked to #282 and #330 : 
I realize that there is actually a serious problem with 'resumeRecorder()`.
I am going to look to that, guys and girls.
But I am currently overbooked and I will work on that in a few days(less than one week).
Sorry for the inconvenient.

**Comment by Larpoux** [comment]
@claptimes5  : 
it seems that you have a problem with your code : 
```
Receiver: null
Tried calling: currentPosition
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _RecordingScreenState._startRecording.<anonymous closure> (package:my_app/pages/recording_screen.dart:256:17)
```
You call `currentPosition` on a null object : `my_app/pages/recording_screen.dart:256`

**Comment by claptimes5** [comment]
@Larpoux Thanks I'll fix that

**Comment by Larpoux** [comment]
I think that your problem is because on V4, Flutter Sound post a `null` when the recorder or the player stops.
This is not a goo idea, for my own point of view. I just kept this behavior because of backward compatibly.
But in V5, I will remove those stupid lines.
