### ISSUE TITLE
Create Unit tests

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#294]
To ensure the stability of the api we really need to develop a set of unit tests.

**Comment by hyochan** [comment]
@bsutton Do you have any proposal to start this? I need to have research on starting this. I am not that familiar with making tests in `flutter` since I've not done much.

**Comment by bsutton** [comment]
I've not done any 'flutter' unit tests per say but have written a large no.
of dart unit tests.

The difference being that flutter unit testing is about creating and
testing widgets.

I would suggest that we start with dart unit tests (the example code can
wait).

All unit test must go in a directory called test.
All unit tests must end in _test.dart.
I will push a few example ones to the 4.0 branch later today.

**Comment by hyochan** [comment]
Sounds great!

**Comment by Larpoux** [comment]
Yes, great!
Someone has just to rollup his sleeves 😄
