### ISSUE TITLE
Would it possible support on-the-fly PCM playback?

### ISSUE THREAD

**Issue by tgarm** [dooboolab/flutter_sound#295]
It's a feature request.
I have some dynamically generated PCM samples which are expected to be keep playing.
I tried to dynamically generated WAV file, and append the file incrementally. 
* first generate a WAV file with a single "chunk", and set the WAV header to have a long time.
* then append the file with certain interval.
But it seems the player just played the first chunk and then stop.

Is there any way to support this kind of request, or any plan to support it?

**Comment by Larpoux** [comment]
This would be a very interesting feature in V4.
Please keep this issue OPEN.

**Comment by Larpoux** [comment]
This is a duplicate from #210 .
This feature is really missing for many developers !

**Comment by Larpoux** [comment]
V 6.0 is released. With this version we can playback PCM-LINEAR-16 to a Dart Stream.
