### ISSUE TITLE
flutter_sound 3.1.8 crash on startup

### ISSUE THREAD

**Issue by sgehrman** [dooboolab/flutter_sound#296]
flutter_sound: ^3.1.8

On startup.  Doesn't happen every time.  I'm on Android.  I have some bluetooth headphones, which are turned off if that makes a difference.

W/MediaPlayer( 7028): Use of stream types is deprecated for operations other than volume control
W/MediaPlayer( 7028): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/AndroidRuntime( 7028): Shutting down VM
E/AndroidRuntime( 7028): FATAL EXCEPTION: main
E/AndroidRuntime( 7028): Process: re.distantfutu.journal, PID: 7028
E/AndroidRuntime( 7028): java.lang.RuntimeException: Unable to create service com.dooboolab.fluttersound.BackgroundAudioService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/AndroidRuntime( 7028): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4095)
E/AndroidRuntime( 7028): 	at android.app.ActivityThread.access$1900(ActivityThread.java:231)
E/AndroidRuntime( 7028): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1981)
E/AndroidRuntime( 7028): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7028): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7028): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/AndroidRuntime( 7028): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7028): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime( 7028): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime( 7028): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/AndroidRuntime( 7028): 	at com.dooboolab.fluttersound.BackgroundAudioService.initMediaSession(BackgroundAudioService.java:559)
E/AndroidRuntime( 7028): 	at com.dooboolab.fluttersound.BackgroundAudioService.onCreate(BackgroundAudioService.java:468)
E/AndroidRuntime( 7028): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4083)
E/AndroidRuntime( 7028): 	... 8 more

**Comment by Larpoux** [comment]
Too many developers get this crash sometimes.
I definitely want to put this PR (Problem Report) on top of the list TODO.

**Comment by Larpoux** [comment]
@sgehrman  : 

Could you try Flutter Sound ^3.1.9 and tell us if better ?

**Comment by sgehrman** [comment]
@Larpoux I updated and didn't see it crash.  I'll let you know if it crashes again, it might have been random.

**Comment by Larpoux** [comment]
Please, re-open this issue if this problem occurs again
