### ISSUE TITLE
Will this plugin support Flutter Web?

### ISSUE THREAD

**Issue by Dorbmon** [dooboolab/flutter_sound#297]
Will this plugin support Flutter Web?

**Comment by Larpoux** [comment]
Oh, YESSSSSS !!!! It would be really great.

Unfortunately, we are actually really busy with flutter_sound maintenance. Hard to develop important new feature. (We really want that flutter_sound really good on the maintenance side).

You should talk with @hyochan . I think he has some ideas in this area.

**Comment by Dorbmon** [comment]
> Oh, YESSSSSS !!!! It would be really great.
> 
> Unfortunately, we are actually really busy with flutter_sound maintenance. Hard to develop important new feature. (We really want that flutter_sound really good on the maintenance side).
> 
> You should talk with @hyochan . I think he has some ideas in this area.

Haha.I'm waiting for it.But I think it needs a big change about the callback method after all the flutter web doesn't support dart:io.

**Comment by hyochan** [comment]
This is really interesting issue. There is a great proposal in [this article](https://link.medium.com/xyWQ4RhHJ5).

I am full of stock currently but I am very interested (I hope I have time..)

**Comment by Larpoux** [comment]
Feature implemented in V6.4
