### ISSUE TITLE
Stop/pause flutter_sound when playing with other sound

### ISSUE THREAD

**Issue by chenft** [dooboolab/flutter_sound#299]
### Version of flutter_sound
3.1.10
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
1.when I play other sound with other apps, flutter_sound should pause.
2.when I play flutter_sound, other sound should pause.
### Actual behavior
Now only (when I play flutter_sound, other sound should pause) is enable
### Tested environment (Emulator? Real Device?)
real device

**Comment by hyochan** [comment]
I think number 2 can be possible but 1 it is on their side.

**Comment by Larpoux** [comment]
1. On android, we can have a callback from the OS, when another App wants to acquire the audio-focus, so that we can specify what to do. This will need a change in our API.
But not sure that it will be possible on iOS. 

2. Look to the new API verbs in 3.1.x : 
- androidAudioFocusRequest() 
- and setActive()
and tell us if this correctly answer your needs.

**Comment by chenft** [comment]
@Larpoux 
Use androidAudioFocusRequest is useful only when I play other audio first, then play audio on my app.
And then, I play other audio again, will play two sounds.

Can you handler this like audio_service plugins? [https://pub.dev/packages/audio_service](url).It handler this feature by it's plugins,user don't need to handler this.

My app needs to use background playback and recording, so I use audio_service and flutter_sound.
But When I use audio_service, flutter_sound's onRecorderStateChanged will return null. And then i heard flutter_sound have background playback feature, so I update flutter_sound with 3.1.x. But I have nothing to do now。

By the way, flutter_sound's version above 3.1.5 is terrible on IOS.
IOS will stop when running the following sentence.

![65221587195540_ pic](https://user-images.githubusercontent.com/17562266/79631293-e1ae7c00-818a-11ea-9412-081832d0567a.jpg)

Something wrong when initializeMediaPlayer.So I can't use flutter_sound on IOS.

**Comment by Larpoux** [comment]
> Something wrong when initializeMediaPlayer.So I can't use flutter_sound on IOS.

This is really bad 👎  .
Could you post your logs ?

**Comment by chenft** [comment]
@Larpoux 
No logs.
IOS not crash. Just can't finish initialized. Because invoedMethod('initializeMediaPlayer') don't finshed. So I can't do something after initialize().

**Comment by Larpoux** [comment]
We really need your logs.

**Comment by Larpoux** [comment]
Please re-open if this issue is still present.
