### ISSUE TITLE
RecordStatus always returns currentPosition of 0.0 for iOS

### ISSUE THREAD

**Issue by ukrx-xamd** [dooboolab/flutter_sound#30]
### Description
An existing application working in 1.2.1 of the plugin was recently updated to 1.2.2 - now when we run our app, and start to record sound - our ticker display stays at 00:00:00. The onRecorderStateChanged event is fired constantly - but RecordStatus->currentPosition is always 0.0

### Version of flutter_sound
1.2.2

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] VS Code (version 1.30.2)
[✓] Connected device (2 available)

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Expect currentPosition of RecordStatus to tick over at each new event.

### Actual behavior
currentPosition is always 0.0

### Tested environment (Emulator? Real Device?)
iOS 10.x and above - all simulators.

### Steps to reproduce the behavior

Just run the sample app that ships with this plugin - hit record. You will see in iOS no ticker gets displayed and the display stays at 00:00

![fs-2](https://user-images.githubusercontent.com/35817834/51444460-ae631000-1cef-11e9-8253-ab73346098d3.png)

**Comment by hyochan** [comment]
@ukrx-xamd Please try `1.2.1` for now I think there was a regression issue.

**Comment by hyochan** [comment]
@ukrx-xamd Also, I'd like to know what drawing tool you are using to create a diagram like above?

**Comment by hyochan** [comment]
@ukrx-xamd Hi friend. I've fixed the regression issue in `1.2.3`. Please try this. Thanks.

**Comment by ukrx-xamd** [comment]
@hyochan - Excellent. I can confirm that the 1.2.3 fixes the regression issue on iOS. 

Regarding the drawing tool - try this 

https://www.draw.io/

Its free and easy to use and allows code to be easily pasted onto the surface and then annotated etc

**Comment by hyochan** [comment]
@ukrx-xamd Hey, I am using this one too but my work in here doesn't seem to look good tough. I'll dig more with this. Thank you.
