### ISSUE TITLE
Change plugins to pass time in miliseconds

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#303]
The plugins TrackPlayer and SoundPlayer send and receive position and duration values between java/swift and dart.

These fields are json encoded and typically have an arg name such as 'sec' with a type of double.
The java code then will copy this into a variable called millis.
e.g. TrackPlayer.java line 437.

We need to rationalise these calls as they are a maintenance headache.

I would suggest that we pass these values as an int and in milliseconds and call the arg 'milliseconds'.

**Comment by Larpoux** [comment]
> We need to rationalise these calls as they are a maintenance headache.

What kind of problems with maintenance ?

**Comment by bsutton** [comment]
I've had multiple problems getting the code to work as it wasn't obvious
what these fields contained.
Everytime someone looks at this code they will have the same questions.
Rationalising the names and type so its consistent will make life easier.

I always ask myself if some else was browsing the code then would it be
obvious how it works.
On this one, the answer would be no.

**Comment by Larpoux** [comment]
The universal international System units (SI) is called : 
MKSA for Meters/Seconds/Kilograms/Amperes.
My own preference is to follow those units when we have choice.

**Comment by bsutton** [comment]
I really don't think si units is applicable in this situation.

Using a double is always undesirable if an int can be used.

Doubles are slower and less precise than ints introducing finding errors.

The basic rule of programming is always use an int over a double.

Having said that it's not critical in this instance but it makes the code
ugly. The real issue is inconsistent naming conventions.

We have a seconds value bring stored into a field called milliseconds.

**Comment by bsutton** [comment]
My reference was to the plugin api (the Java code) not the dart API.

The dart API should expose a standard duration object so the user can access it as it suites them.
