### ISSUE TITLE
About TrackPlayer working, how does it start playing?

### ISSUE THREAD

**Issue by srihariash999** [dooboolab/flutter_sound#306]
### Version of flutter_sound
   3.1.10

I am using trackplayer and  I await it to start and it takes too long to load larger remote music files. So, I had a question. Does it start playing after the whole track is loaded? Or can I start playing it after some part is loaded? 
After reading the docs, I found a trackplayer with buffer but it seems to be playing local files. Can I do this with remote files too?

I am new to Flutter and I don't know where to ask this question, sorry if this doesn't belong here and maybe point me in right direction.

**Comment by bsutton** [comment]
I believe that it loads the whole file.

**Comment by srihariash999** [comment]
Any workaround to make the playback in case of large files faster?

**Comment by Larpoux** [comment]
Yes, I know that this delay is substantial.

Actually, I do not see any workaround in 3.x.x
Maybe in the future Flutter Sound could play from a stream provided by the App ?
But there is no plan, today, to doing that in 4.x.x

**Comment by bsutton** [comment]
Does android/ios support playing from a stream?

**Comment by Larpoux** [comment]
The best you can do is to load the file yourself and give it to Flutter Sound each time you want to play it.
