### ISSUE TITLE
How to record with flac format

### ISSUE THREAD

**Issue by Heatwave114** [dooboolab/flutter_sound#308]
Hi is it possible to tweak flutter_sound to record with flac encoder ?

**Comment by Larpoux** [comment]
We plan to support many other codecs for the FlutterSoundRecorder in future versions.
But still not done

**Comment by Larpoux** [comment]
Flutter Sound V5.x.x will be able to record PCM (raw, Wave or AIFF).
It will be also able to record FLAC on Ios (but still probably not on Android)
This version is supposed to be released sometime next week.

Is it what you expect from Flutter Sound ?

**Comment by Heatwave114** [comment]
Yes, thank you. I'm using it for android though.
