### ISSUE TITLE
Multiple independent TrackPlayer instances playing simultaneously not possible? 

### ISSUE THREAD

**Issue by lstimac** [dooboolab/flutter_sound#309]
Are there any plans for enabling multiple audio playbacks at the same time? 😁 Currently, there can be only one active instance of TrackPlayer, meaning it is not really possible to do cross fade transitions and similiar. And setVolume method for one instance affects all instances, which makes it impossible to control multiple players independently. 

From what I have researched, multiple independent audio playbacks at the same time are probably a limitation of MediaPlayer (on Android platform), and ExoPlayer would probably be necessary for something like that. Is there a way to do it using MediaPlayer? 😊

**Comment by Larpoux** [comment]
I must look to that deeper.
I was thinking that you can create several instances of `TrackPlayer` simultaneously.
But I have not really carefully checked that it is compatible Android MediaPlayer.

Please, keep this issue Open

**Comment by Larpoux** [comment]
Do you use a recent Flutter Sound version ?
This point is supposed to be fixed since 3.1.0.

**Comment by lstimac** [comment]
Yes, I use version 3.1.8. But noticed when i start a second player, first one becomes silent haha I'm just asking because I need them both running and audible, so I can control their volume independently and do various seamless transitions based on that :)

**Comment by Larpoux** [comment]
Perhaps you could look to the `#### iosSetCategory(), androidAudioFocusRequest() and setActive() - (optional)` section in the README.

Maybe you can play your two playbacks with correct parameters to those functions.

Please give us feed backs with your tries.

**Comment by Larpoux** [comment]
Of course you must use two different instances of SoundPlayer or TrackPlayer
for your two playbacks. This cannot work if you start your two players in the same module instance.

**Comment by lstimac** [comment]
I use two different instances, however one always overrides the other, I have not been able to make them both play simultaneously at different volume levels. SetVolume method affects Media volume on a system level, instead of just modifying volume of a specific instance of Media Player created with flutter_sound :)

I will look at focus section of package docs, and will try disabling volume change when MediaPlayer  loses focus in flutter_sound Android code (just for a test), to see if I can then hear two instances running at the same time.

**Comment by lstimac** [comment]
I tried various things with focus and running different instances but to no avail. I will probably need to play around with Android ExoPlayer to achieve multiple audio sources at the same time :)

**Comment by Larpoux** [comment]
Thank you to have investigate this.
We will try to fix that in a future version. I think that this issue is important.
Please keep this issue open.
