### ISSUE TITLE
iOS restart causes crash

### ISSUE THREAD

**Issue by tuanbs** [dooboolab/flutter_sound#310]
### Version of flutter_sound
3.1.10

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Restart the app when pressing the restart button in VS Code.

### Actual behavior
App crashed.

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
- Run the app.
- Press restart button in VS Code.
- App crashed.
<img width="301" alt="Screen Shot 2020-04-19 at 7 14 18 pm" src="https://user-images.githubusercontent.com/4801395/79684111-4b558580-8272-11ea-9a94-d173f11e3f74.png">

**Comment by Larpoux** [comment]
Maybe tied with #307

**Comment by Larpoux** [comment]
Duplicates #304
