### ISSUE TITLE
How to get the duration of audio in flutter_sound_lite? 

### ISSUE THREAD

**Issue by Dorbmon** [dooboolab/flutter_sound#313]
I found that We dont use ffmpeg in lite version.How can I get the duration of the audio? Thanks.

**Comment by Larpoux** [comment]
flutter_sound FULL flavor uses FFmpeg to get the audio duration.
This is not possible in the LITE flavor.

**Comment by Dorbmon** [comment]
> flutter_sound FULL flavor uses FFmpeg to get the audio duration.
> This is not possible in the LITE flavor.

It is a sad message...ffmpeg is too big for me.

**Comment by Larpoux** [comment]
You can't have your cake and eat too :-D

**Comment by Dorbmon** [comment]
> You can't have your cake and eat too :-D

:( sad time.
