### ISSUE TITLE
flutter_ffmpeg needs NSCameraUsageDescription delclaration in info.plist on iOS

### ISSUE THREAD

**Issue by claptimes5** [dooboolab/flutter_sound#315]
## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!
```
### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Publish app on app store without needing `NSCameraUsageDescription`

### Actual behavior
When I go to publish my app, my build is rejected by Apple because it doesn't have the `NSCameraUsageDescription` purpose string in my info.plist.

`ITMS-90683: Missing Purpose String in Info.plist`

This appears to be an open issue on `flutter-ffmpeg` https://github.com/tanersener/flutter-ffmpeg/issues/120

### Tested environment (Emulator? Real Device?)
N/A

### Steps to reproduce the behavior
Upload an `.ipa` to the app store

**Comment by Larpoux** [comment]
Yes, I am having the same problem with my own APP.

I had to add in my `info.plist` : 
```
	<key>NSAppleMusicUsageDescription</key>
	<string>Dyglot does not need this permission</string>
	<key>NSCalendarsUsageDescription</key>
	<string>Dyglot does not need this permission</string>
	<key>NSCameraUsageDescription</key>
	<string>Dyglot does not need this permission</string>
	<key>NSContactsUsageDescription</key>
	<string>Dyglot does not need this permission</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Dyglot does not need this permission</string>
	<key>NSMotionUsageDescription</key>
	<string>Dyglot does not need this permission</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>Dyglot does not need this permission</string>
```

Perhaps this issue does not occur on `flutter_sound: 4.0.0-beta.4` but I have not yet tested with this new version.

**Comment by Larpoux** [comment]
Thank your @claptimes5 to share your experience with 4.0.0. 👍 
We must check, now  with 4.0.0 FULL.

**Comment by 0xcodezero** [comment]
After xCode 11.5m flutter_sound version 2.x is no longer supported because of the usage of some deprecated code, 

So, only after the upgrade to
`flutter_sound_lite: ^4.0.6`

And I got all the Upload Build Warnings from iTunesConnect the same as @Larpoux mentioned! 
I guess that is because of the FFmpeg, but the lite version seems that still asking for all the above permissions.

is there a fix, or Can I omit those functionalities in initializing sound library?

**Comment by Larpoux** [comment]
I am surprised that the lite flavor need all those permissions.
I am going to look to this this week.
