### ISSUE TITLE
OSs Media play does not close when mediaBrowserHelper released.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#318]
I'm testing the example app with the new 5.0 build of flutter and I've noticed that when I play media via the OSs' own media player that the player doesn't close after release is called on android.

I see the call to: 
mMediaBrowserHelper.releaseMediaBrowser();

in TrackPlayer

but it doesn't close the player.

There also appears to be no way via the OSs media player to close the player.

I'm guessing we are missing some call during the release?

I would expect this to affect the 3.x build as well as I'm running the same java code.

**Comment by Larpoux** [comment]
see #320 and #356
