### ISSUE TITLE
Can you still record audio while app is in background, or while the phone is locked?

### ISSUE THREAD

**Issue by chi-tea-72** [dooboolab/flutter_sound#319]
In your v3 release I see you support playback on the lock screen and in the notifications drawer which is awesome! I'm wondering if you also support recording audio while the app is either in background or when the device is locked?

I'm trying to build a simple voice recorder application. I want users to be able to close the app or lock their phone if they wish, but still continue recording, and only stop the recording when they reenter the app and manually click stop.

**Comment by Larpoux** [comment]
Yes, Flutter Sound can continue to record, event if it goes background or when the screen is off. I tried that and it works fine.

**Comment by Larpoux** [comment]
Yes, I confirm that recording is possible when the App goes background.

Please re-open this issue if you think that flutter_sound does not fill your needs in this area.

**Comment by chi-tea-72** [comment]
Thanks for the fast response, really appreciate it :) I will check out the plugin further 👍

**Comment by yangha886** [comment]
i cant record when the app goes background and lockscreen maybe 1-2 minutes,

**Comment by yangha886** [comment]
v5.1.0

**Comment by yangha886** [comment]
_init() async {
    flutterSound = await FlutterSoundRecorder().openAudioSession(
      focus: AudioFocus.requestFocusAndKeepOthers,
      category: SessionCategory.record,
    );
  }

**Comment by benwright9400** [comment]
I'm having this exact same issue; the sound will stop recording after about 1 minute of the screen being locked or a different activity being opened
