### ISSUE TITLE
Resource leakaged when using OS MediaPlayer 

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#320]
I'm testing 5.0 and have been experimenting with playing overlapping audio via the OS MediaPlayer UI (i.e. the old TrackPlayer code).

Essentially the problem is that if I start playing a track and then start a second track, before the first one completes, then the first track no longer receives events (finished, stopped).

So should the api allow a user to start a second track (using the OS Media UI) or do we just force them to stop the first audio first?

I also noticed that the BackgroundAudioService handles onAudioFocusChange events.
Of particular interest is the 'AUDIOFOCUS_LOSS' event.
The comment for this event says that we should stop the player but in fact the code doesn't stop the player.
Was there a particular reason why this isn't stopping the player?

**Comment by Larpoux** [comment]
> So should the api allow a user to start a second track (using the OS Media UI) or do we just force them to stop the first audio first?

I think that we must stop the previous playback. If the App want to play 2 playbacks at the same time, it must open two audio sessions.



> I also noticed that the BackgroundAudioService handles onAudioFocusChange events.
> Of particular interest is the 'AUDIOFOCUS_LOSS' event.

Yes, I was thinking to add this to flutter_sound.
I am not sure that it is possible to support that on iOS

**Comment by bsutton** [comment]
> I think that we must stop the previous playback. If the App want to play 2 playbacks at the same time, it must open two audio sessions.

I'm specifically talking about when you are using the OSs shade UI.
Given there is only one shade UI available you can't have more than one audio file playing on the shade UI (I refer to this as the OSs UI).
When you use SoundPlayer.withUI()  it displays the OSs UI. This is the same as using the old TrackPlayer.
If you create a second instance of SoundPlayer.withUI then what should happen given there is only one UI?
It seems to me that we should throw an error if the users tries to create two of these at once?

I'm also concerned that we don't play nicely with other media players (partially due to ignoring the 'AUDIO_FOCUS_LOSS' event.

**Comment by Larpoux** [comment]
see #356
