### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "flutter_sound_lite"

### ISSUE THREAD

**Issue by iyuhang** [dooboolab/flutter_sound#322]
### Version of flutter_sound

flutter_sound_lite: ^4.0.0

## flutter doctor

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G87, locale en-US)

### Platforms you faced the error (IOS or Android or both?)
iOS

### Actual behavior

platform :ios, '9.0'

Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "flutter_sound_lite":
      In Podfile:
        flutter_sound_lite (from `.symlinks/plugins/flutter_sound_lite/ios`)
    Specs satisfying the `flutter_sound_lite (from `.symlinks/plugins/flutter_sound_lite/ios`)` dependency were found, but they required a higher minimum deployment target.

### Tested environment (Emulator? Real Device?)

real

**Comment by Larpoux** [comment]
The actual minimum version for Flutter Sound is 9.3.

**Comment by iyuhang** [comment]
it works, thanks
