### ISSUE TITLE
Cause crash when have plugin multi_image_picker imported

### ISSUE THREAD

**Issue by iyuhang** [dooboolab/flutter_sound#323]
### Version of flutter_sound

flutter_sound_lite: ^4.0.1

## flutter doctor
```
 <!-- run `flutter doctor` and paste the output here: -->
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)
```

### Platforms you faced the error (IOS or Android or both?)

Only Android

### Actual behavior

Crashed

### Steps to reproduce the behavior

1. import multi_image_picker: ^4.6.6+rc.1
2. import flutter_sound_lite: ^4.0.1
3. apply MultiImagePicker.pickImages
4. crashed

also see in multi_image_picker

https://github.com/Sh1d0w/multi_image_picker/issues/446

crash log:

04-26 13:58:23.140 I/ActivityTaskManager( 1522): START u0 {cmp=com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity} from uid 10665 pid 25652
04-26 13:58:23.150 D/OpRestartProcessManager( 1522): updateSelf :  com.fixtime.yuyu, size : 17
04-26 13:58:23.150 E/ScreenModeService( 1522): getAppToken AppWindowToken{acb45a9 token=Token{cbd4530 ActivityRecord{1570273 u0 com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity t30076}}}
04-26 13:58:23.150 E/ScreenModeService( 1522): setRefreshRate token AppWindowToken{acb45a9 token=Token{cbd4530 ActivityRecord{1570273 u0 com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity t30076}}} rate 0
04-26 13:58:23.150 D/OpQuickReply( 1522): setQuickReplyResumed focusedApp AppWindowToken{acb45a9 token=Token{cbd4530 ActivityRecord{1570273 u0 com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity t30076}}} pkgName com.fixtime.yuyu
04-26 13:58:23.152 I/OpMotorManagerService( 1522): notifyActivityChanged: mBackgroudPkg = com.fixtime.yuyu mFocusPkg = com.fixtime.yuyu mIsSplitMode = false mBackActivity = com.fixtime.yuyu mFocusActivity = com.sangcomz.fishbun.ui.album.AlbumActivity
04-26 13:58:23.219 E/AndroidRuntime(25652): FATAL EXCEPTION: main
04-26 13:58:23.219 E/AndroidRuntime(25652): Process: com.fixtime.yuyu, PID: 25652
04-26 13:58:23.219 E/AndroidRuntime(25652): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/widget/TintableCompoundDrawablesView;
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1383)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2151)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2708)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2775)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2129)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:717)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.sangcomz.fishbun.ui.album.AlbumActivity.onCreate(AlbumActivity.java:75)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.Activity.performCreate(Activity.java:7820)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.Activity.performCreate(Activity.java:7809)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3362)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3526)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2122)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.os.Looper.loop(Looper.java:214)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
04-26 13:58:23.219 E/AndroidRuntime(25652): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.widget.TintableCompoundDrawablesView" on path: DexPathList[[zip file "/data/app/com.fixtime.yuyu-SqcmjmrAHHvNnxbQWv3zHw==/base.apk"],nativeLibraryDirectories=[/data/app/com.fixtime.yuyu-SqcmjmrAHHvNnxbQWv3zHw==/lib/arm64, /data/app/com.fixtime.yuyu-SqcmjmrAHHvNnxbQWv3zHw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-26 13:58:23.219 E/AndroidRuntime(25652): 	... 32 more
04-26 13:58:24.480 I/DropBoxManagerService( 1522): add tag=data_app_crash isTagEnabled=true flags=0x2
04-26 13:58:24.480 W/ActivityTaskManager( 1522):   Force finishing activity com.fixtime.yuyu/com.sangcomz.fishbun.ui.album.AlbumActivity
04-26 13:58:24.481 W/ActivityTaskManager( 1522):   Force finishing activity com.fixtime.yuyu/com

**Comment by Larpoux** [comment]
At first seeing, the crash is not in Flutter Sound.

**Comment by iyuhang** [comment]
maybe, but if remove flutter sound, that plugin runs well, how can I solve this

**Comment by iyuhang** [comment]
I tried flutter_sound and flutter_sound_life, all failed

**Comment by Larpoux** [comment]
You should investigate why this plugin crashes.
