### ISSUE TITLE
Add plug-in failed  How to solve？

### ISSUE THREAD

**Issue by Sansuihe** [dooboolab/flutter_sound#328]
Because flutter_sound >=3.1.6 depends on permission_handler ^5.0.0 and flutter_widget_one depends on permission_handler ^4.0.0, flutter_sound >=3.1.6 is forbidden.

pub get failed (1; So, because flutter_widget_one depends on flutter_sound 4.0.0, version solving failed.)

**Comment by Larpoux** [comment]
Yes, Flutter Sound dependency on permission_handler gives us several problems.
This is not very good.
We must find a way to get rid of this dependency.

**Comment by Larpoux** [comment]
More and more, I think that flutter_sound should not bother with permissions.
Permissions should be the App responsibility.

**Comment by Sansuihe** [comment]
Are there any good ways to use your plug-in

**Comment by Sansuihe** [comment]
> 我越来越多地认为flutter_sound不应受到权限的困扰。
> 权限应由应用负责。

Are there any good ways to use your plug-in

> 我越来越多地认为flutter_sound不应受到权限的困扰。
> 权限应由应用负责。

Are there any good ways to use your plug-in

> More and more, I think that flutter_sound should not bother with permissions.
> Permissions should be the App responsibility.

Are there any good ways to use your plug-in？

**Comment by Larpoux** [comment]
Hi everybody.
I suggest to remove this dependency in a future Flutter Sound version `5.x.x`.
It will be a breaking change.
What do you think ? Is it Flutter Sound responsibility to take care of the recording permission ?

**Comment by Larpoux** [comment]
done
