### ISSUE TITLE
Duplicate symbol issue when using flutter_sound plugin and audioplayer plugin

### ISSUE THREAD

**Issue by linguitang** [dooboolab/flutter_sound#33]
duplicate symbol __channel in flutter_sound plugin and audioplayer plugin

**Comment by hyochan** [comment]
Could you be more specific?

**Comment by linguitang** [comment]
```
duplicate symbol __channel in:
/Users/lingt/root/client/build/ios/Debug-iphoneos/audioplayer/libaudioplayer.a(AudioplayerPlugin.o)
/Users/lingt/root/client/build/ios/Debug-iphoneos/flutter_sound/libflutter_sound.a(FlutterSoundPlugin.o)
ld: 1 duplicate symbol for architecture armv7
```

**Comment by abdalmonem** [comment]
1 - open xCode
2 - go to target , then click on "build settings"
3 - search on "no common blocks"
4 - change it value to "no"
![screenshot 2019-01-27 at 2 04 54 pm](https://user-images.githubusercontent.com/9139030/51800750-c29d9480-223c-11e9-8ca4-0cc0cdf32f9a.png)

**Comment by linguitang** [comment]
> 1 - open xCode
> 2 - go to target , then click on "build settings"
> 3 - search on "no common blocks"
> 4 - change it value to "no"
> ![screenshot 2019-01-27 at 2 04 54 pm](https://user-images.githubusercontent.com/9139030/51800750-c29d9480-223c-11e9-8ca4-0cc0cdf32f9a.png)

same problem.

**Comment by hyochan** [comment]
`rm -rf ios/build` then try again.

**Comment by linguitang** [comment]
> `rm -rf ios/build` then try again in your project's root path.

same problem. @hyochan

**Comment by hyochan** [comment]
Not sure about this one. Would [this](https://stackoverflow.com/questions/15058171/ld-1-duplicate-symbol-for-architecture-armv7) help? I think this is more related to flutter channel.

**Comment by linguitang** [comment]
> Not sure about this one. Would [this](https://stackoverflow.com/questions/15058171/ld-1-duplicate-symbol-for-architecture-armv7) help? I think this is more related to flutter channel.

This should be the reason, but I don't know how to solve it.

**Comment by abdalmonem** [comment]
you can try to remove "Audioplayer"
i am new in flutter , and all i know is:
"flutter_sound" and "audioPlayer" use the same channel name
then try to use another audio player plugin

**Comment by hyochan** [comment]
@linguitang If you are using other plugins that has `audio player` or `audio recorder`, please share. You lacks information for us to dig in and think widely.

**Comment by linguitang** [comment]
I use [audioplayers](https://pub.dartlang.org/packages/audioplayers) replace  [audioplayer](https://pub.dartlang.org/packages/audioplayer), no problem.

**Comment by hyochan** [comment]
@linguitang Player is already in our plugin you don’t need those.
