### ISSUE TITLE
Proposal: remove all permission logic from flutter sound.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#335]
Flutter sound currently requires one or two permissions
1) microphone - always
2) external storage - some times.

Requesting permission causes flutter sound to display the OS specific permission dialogs.

When using flutter sound as an api there is an argument that should never display an UI unless explicitly requested to.

By allowing flutter sound to make the permissions requests we are taking control of the exact timing of the permission dialog away from the developer.
I'm thinking that it would be more appropriate to let the developer make the permission request. In this way they can control the exact timing of when the permission request is made.

For the flutter sound UI components (SoundRecorderUI and SoundPlayerUI) I think these should have callbacks that allow the developer control over how the permissions are presented.
In this way the developer can either pre-request the permissions or wait until we make the callback and then they display the required UI.

Essentially the aim is to hand back complete control of the UI to the developer.

**Comment by Larpoux** [comment]
Linked to #328 

I completely agree with that.
I am just wondering what we must do when the App try to start a recorder and the permission has not been allowed : 
Throw an exception ?

**Comment by bsutton** [comment]
Yes just throw an exception.

I will work on the changes tomorrow.

**Comment by Larpoux** [comment]
done
