### ISSUE TITLE
Proposal: rename example.dart to demo.dart

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#338]
Reading google/flutter guidelines for examples strongly suggests that our 'example.dart' is not really an example but rather a demo app.

As such I would suggest that we create a new example.dart which provide a very simple example of using the soundrecorderui and the soundplayerui classes.

This example should demonstrate the minimum required to have these widgets operating.

The existing example.dart should be renamed demo.dart.

**Comment by Larpoux** [comment]
done
