### ISSUE TITLE
Android: creating file but not recording

### ISSUE THREAD

**Issue by haideraltahan** [dooboolab/flutter_sound#34]
### Version of flutter_sound
1.2.4
## flutter doctor

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Record audio and save to the file.
### Actual behavior
When `startRecorder` is called with or without a fileName, the audio is not saved on the file.
That is the file size is always 8.65KB.
### Tested environment (Emulator? Real Device?)
Emulator

**Comment by haideraltahan** [comment]
After further investigation. It does record but with very poor quality... 8kHz is the max frequency. How do I increase the quality?

**Comment by hyochan** [comment]
@haideraltahan Hi. I think you are talking about `ios` am I right? I've recently decreased the recorded file in `ios` because of #26. Currently, you should change the value `AVAudioQualityMin` in `ios` to `AVAudioQualityMax` because this variable isn't exposed to `dart`. See the [line](https://github.com/dooboolab/flutter_sound/blob/388737aaa6451eaad98044a3a91481b29b92921c/ios/Classes/FlutterSoundPlugin.m#L150).

**Comment by haideraltahan** [comment]
I was talking about Android as it was very bad quality for my use case.
I solved it by using those settings:

> this.model.setMediaRecorder(new MediaRecorder());
      this.model.getMediaRecorder().setAudioSource(MediaRecorder.AudioSource.MIC);
      this.model.getMediaRecorder().setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
      this.model.getMediaRecorder().setAudioEncoder(MediaRecorder.AudioEncoder.AAC_ELD);
      this.model.getMediaRecorder().setAudioEncodingBitRate(256000);
      this.model.getMediaRecorder().setAudioChannels(numChannels);
      this.model.getMediaRecorder().setAudioSamplingRate(sampleRate);
      this.model.getMediaRecorder().setOutputFile(path);

**Comment by hyochan** [comment]
@haideraltahan Thanks for confirming. I hope you could give us `PR` for this if you'd like to share your work.

**Comment by mikeyyg96** [comment]
@haideraltahan Did you ever resolve this issue? I tried setting those settings in my project but it seemed there was no effect. I even put encoding bit rate 0 and numChannels to 0 and nothing change; same result.

**Comment by haideraltahan** [comment]
@mikeyyg96 try transferring the recording and listening to them. The recording file size alone is not enough to see if it's working.
