### ISSUE TITLE
What to do when recording and app is sent to the background.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#341]
I'm working through the logic to free resources when the app is pushed to the background.

Android essentially says that we should free up all media resources when our is sent to the background.
For the AudioPlayer  the contstructors take an argument 'playInBackground'. If set then the player will continue playing even if the app is pushed to the background.

The question is for the recorder.
Should we stop the recorder when the app is pushed to the background or should we offer a similar 'playInBackground' option for the recorder.

I'm inclined to offer the playInBackground option as it allows an app to start recording and then perhaps take a call and record the call.

I've also taken the approach that if the app is paused whilst recording that we will stop the recording and not restart it when the app is resumed.
This is not the same as the audio player but I don't think it makes sense for a user perspective to suddenly start recording again.

**Comment by Larpoux** [comment]
We have some users who want to continue recording when the App goes background, or even when the Phone is OFF.

**Comment by bsutton** [comment]
I'm not quite certain how you record when the phone is OFF :)

Anyway I've added a background argument. Both the player and the recorder now support a background mode.
If you pass playInBackground  to either the recorder or the player they continue playing even if the app is sent to the background.
I've just pushed this code.
