### ISSUE TITLE
[HELP] Can I use the helper functions with the LITE version

### ISSUE THREAD

**Issue by chi-tea-72** [dooboolab/flutter_sound#352]
I need Help for :

- Using the API

-------------------------------------
## Here is my question :

I can't tell from the documentation if the following helper functions are available in the LITE version: 
- FlutterSoundHelper.FFmpegGetMediaInformation()
- FlutterSoundHelper.duration()

**Comment by Larpoux** [comment]
No, they are not.
Those function is only in FULL version

**Comment by chi-tea-72** [comment]
Ok thank you. Do you know how much bigger in size the full version is over the lite?
