### ISSUE TITLE
Wrap Codec in a MediaFormat

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#353]
I've been looking into the issues around #344 (re-architect codec support) and have come to the realisation that we have a number of problems with how we are using the Codec class.

Reference material:
https://developer.android.com/guide/topics/media/media-formats

The Codec class has morphed into an object that attempts to describe both the Codec and the media container.

This appears problematic as the Codec is not able to fully describe a  media's format and the class name is  misleading as it describes more than just a Codec.

I'm proposing that we create a new class `MediaFormat`. 
```dart
class MediaFormat
{
 Codec codec;
 MediaContainer container;
int sampleRate = 16000,
int numChannels = 1,
int bitRate = 16000,
Quality quality = Quality.low,
}
```
Note: I'm uncertain whether quality belongs here, its taken from the `SoundRecorder.record` method.

The `MediaFormat` would replace `Codec` in the public api so when creating a Track you would now use something like:

```dart
var format = MediaFormat.default;
var track = Track.fromPath(path, format);

var format = MediaFormat(Codecs.byName('mpeg'), MediaContainer.byName('mpeg'));
format.sampleRate = 1000;
format.numChannels = 2;

track  = Track.fromBuffer(buffer, format);
```

I believe this method has a number of advantages:
1) we are now accurately describing the users requested media format.
2) when doing codec conversions we would use the MediaFormat rather than just the Codec. This allows conversions to fully describe the desired target format. (e.g. stereo to mono, down sampling etc).
3) We change the `SoundRecorder.record` method to take a MediaFormat which makes the api consistent.
4) we future proof the api as `MediaFormat` accurately describes the format which means we are less likely to have to change the api. With the current implementation this is highly likely as the current `Codec` is a enum which means we can't add additional properties.

The down side is that it probably makes our life harder as we need to deal with users passing formats that are not supported or inconsistent.
Inconsistency is perhaps a problem with the `SoundPlayer` as it would essentially ignore the properties.  The flip side is that I can't think of why this would be an actual problem.
We also make the users life slightly harder as it takes more lines of code to describe a `MediaFormat` than a `Codec`. Having a number of default `MediaFormats` would mitigate this problem.

Thoughts?

**Comment by Larpoux** [comment]
I do not agree.
Actually *Sound World* is a real mess.
Having just a type for the encoding and the file format is not perfect, and I was not sure that it was the good idea when I introduced this type. But more the time pass, more I think this is the best way of doing things, even if not perfect.

Do you want to store an MP3 file inside an OGG container ?
Do you want to store an MPEG4 file inside a .wav container ?
This has no sense.
And I think better to offer in Flutter Sound combinations that we know it works and that we have tested instead of allowing any multiple stupid combination.

**Comment by bsutton** [comment]
I'm sorry for the late response on this one.

This issue should be seen in conjunction with #344 

The aim of these two issues is:
1) increase the no. of supported codecs
2) extend support for the no. of  codec conversions we can do.
3) allow third parties to contribute codecs and codec converters
4) reduce the size of the core flutter sound project
5) allow us to include meta data describing the media
6) provide a method that completely describes the desired codec (required to do codec conversions).

So yes the MediaFormat does allow a users to specify an unsupported codec/container. 
Firstly this is already a problem. Not all codec/container combinations are supported on every platform.
The way that MediaFormat will address this is by providing a default set of supported MediaFormats in much the same way that we do with the current Codec class.
If a user specified a custom codec that we don't support then we thrown an exception just as we do now for a non-supported Codec.

The MediaFormat is particularly important when we start supporting Codec conversions as currently there is no way to fully specify the media format. (e.g. mono/stero, bit rates etc).

The MediaFormat also future proofs our api as it gives us a logic point to add more details about the media format which don't fit into the concept of a Codec.

Can I ask that rather than closing issues out like this one that you asks some additional questions about the motivation behind the idea.
