### ISSUE TITLE
Developed codec conversions as a standalone project.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#354]
I recently posted #344 which discusses an idea to make Codec support a 'plugable' package for Flutter Sound. Issue #344 lays out the advantages of this idea.

After playing with the idea I want to propose a further expansion on the idea.

The objective of the idea is to rapidly expand the no. of Codecs that Flutter Supports and get assistance from the broader flutter community in developing those codecs.

The idea is to create a separate project that provides a frame work for converting between codecs.
The package would be built in a manner that any flutter project that  needs codec conversion could use the package.
Lets refer to the package as Codec Manager (for want of a better name for the moment).

Flutter Sound would become just another user of the Codec Manager package.

As per #344 third parties would be able to build Codec Convertors that confirm to the new Codec Manager's api.

Because the Codec Manager is project agnostic it would encourage developers to build convertors that conform to its api as by doing so they get access to the existing set of Codecs.

The Codec Manager would also include a basic frame work so that conversions could be built so that they don't introduce jank.
This would be done by providing a base Convertors that use an Isolates to do background conversions.  This should make it easier for third parties to build high quality convertors.

The package should also allow third parties to use native plugins if required to do the conversions.

Thoughts?

**Comment by Larpoux** [comment]
Too complicate. I do not understand almost anything.
Please re-open this issue if you persist and think that it is a great idea.
