### ISSUE TITLE
Plan to move forward.

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#355]
The main point of contention with the dev branch has been around what do users want? 

After the straw pole conducted via issue #349 I think there is now a mandate to move forward with the dev version.

Whilst there has been a difference of opinion I believe that all parties have had the best intent with respect to protecting Flutter Sound users.

I'm hoping we can now move passed the disagreements and work to make Flutter Sound the best sound package for flutter.

I would now like to layout a plan of action to move the project forward.

So the plan I would suggest is:

1) complete work on the PCM support that @Larpoux  is working on in the 3/4 branch.
2) we back port the java change made in the dev branch to 3/4.
3) cease all new development work on the 3/4 placing it into maintenance mode. This would mean bug fixes only.
4) 3/4 essentially becomes an LTS as proposed by @Larpoux 
5) We push the dev branch to pub.dev as an alpha and ask for user feedback.
6) All new work is done in the dev branch which becomes the new master, post completion of step 3).
7) we review #353 (new MediaFormat) as if we decided to go down this path then I think it should be done pre the release of 5.0.
8) Post release of 5.0; we consider #354 (separate codec project).  5.0 can be released without this as it will not change the public api but it gives us a path to greater Codec support.

Regards,
Brett

**Comment by dunika** [comment]
@bsutton @Larpoux Really appreciate all the work going into this project. The rate of progress has been phenomenal. Looking forward to 5.0!

**Comment by chi-tea-72** [comment]
@bsutton @Larpoux I'm really excited for the changes coming in version 5.0! Do you guys have a rough time estimate that you're shooting for in terms of when it will become stable?

**Comment by bsutton** [comment]
At this point I don't have agreement from @larpoux to move forward.
I'm ready to release an alpha now.
Timeline after that will depend on how many changes we need to make based on feedback.
Also we really need to get some unit tests built, any help you could offer in this area would be appreciated :)

**Comment by Larpoux** [comment]
I am currently working on a port from @bsutton`s UI Widget to V5.0.
This will be finished sometime next week. If @bsutton can help me, I will appreciate.

Recording to a Stream and playing from a stream will probably not be implemented in 5.0.0 : there is problems doing that, specially on ios.

Also, I would like to look what can be done with AMR_WB codec, before releasing 5.0.

I began a draft of the new documentation. If someone speaking a correct english can contribute (@bsutton?) it would be great.

**Comment by bsutton** [comment]
Sorry but I believe that is a poor use of resources.

The UI will not be reliable due to the architectural issues in the current
master.

The core reason I got involved in flutter sound was because the widget
wasn't reliable and we realised the only way to fix it was to re architect
the whole code base.

You are going down a path we have already tried and it failed.
