### ISSUE TITLE
[BUG] onPlayerStateChanged give wrong track duration on android

### ISSUE THREAD

**Issue by mehemmelbachir** [dooboolab/flutter_sound#356]
## Flutter Sound Version : 
flutter_sound : ^4.0.4+1

----------------------------------------------------------

## Severity
- Result is not what expected ?
`e.duration` return previously played tracks values
--------------------------------------------------------

## Platforms you faced the error 

- Android
- Emulator  
- Real device

## Logs
`print(e.duration);`
````
I/flutter ( 5278): 94250.0
I/flutter ( 5278): 1772173.0
I/flutter ( 5278): 1856758.0
I/flutter ( 5278): 1623589.0
I/flutter ( 5278): 1747722.0
I/flutter ( 5278): 94250.0
I/flutter ( 5278): 1747722.0
I/flutter ( 5278): 1623589.0
I/flutter ( 5278): 1856758.0
I/flutter ( 5278): 1772173.0
I/flutter ( 5278): 94250.0
````
------------------------------------------------

**Describe the bug**

**To Reproduce**
1. Play first track from url `TrackPlayer().startPlayerFromTrack()`.
2. Pass a new track to the function again.
4. **onPlayerStateChanged** emit both values for duration of the current and the previous track.
5. MediaController on iOS or Android is showing previous track duration and not current.

**Comment by Larpoux** [comment]
Do you try to play a new track without stopping the previous one ?
It cannot work inside a common audio session.

**Comment by Larpoux** [comment]
See #320
