### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by zwe-mun-htun** [dooboolab/flutter_sound#359]
## Flutter Sound Version : 4.0.4+1

- **FULL** or **LITE** flavor ?
Full
----------------------------------------------------------

## Severity

- Crash ?
Release Track from Notification bar and back to application, app is crashed.
I want to know the state of track release from notibar or close foreground services.

--------------------------------------------------------

## Platforms you faced the error 

- Android 

Both Emulator & Real Device

----------------------------------------------

## Logs

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{67bb5a9 u0 com.app.package/com.dooboolab.fluttersound.BackgroundAudioService}
E/AndroidRuntime( 7885): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
E/AndroidRuntime( 7885): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7885): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7885): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 7885): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7885): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7885): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
------------------------------------------------

**Comment by Larpoux** [comment]
>     * Release Track from Notification bar and back to application, app is crashed.
>       I want to know the state of track release from notibar or close foreground services.

Could you explain better your problem ? I am not sure to really understand your issue.

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems.
Actually I do not understand what problem you encounter. Please be more explicit.

**Comment by yanivshaked** [comment]
@zwe-mun-htun I have the same issue, did you manage to solve it?

**Comment by bobbakarthik** [comment]
i have issue pleas reopne

**Comment by bobbakarthik** [comment]
F/crash_dump64(18747): crash_dump.cpp:460] failed to attach to thread 599: Permission denied
E/AndroidRuntime(17772): FATAL EXCEPTION: main
E/AndroidRuntime(17772): Process: com.bobba.gossip, PID: 17772
E/AndroidRuntime(17772): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{38113e0 u0 com.bobba.gossip/com.dooboolab.TauEngine.FlautoBackgroundAudioService}
E/AndroidRuntime(17772): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2039)
E/AndroidRuntime(17772): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17772): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17772): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
E/AndroidRuntime(17772): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17772): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(17772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Larpoux** [comment]
Which Flutter Sound version? 9.x or 8.x?

**Comment by bobbakarthik** [comment]
8.3.9

**Comment by bobbakarthik** [comment]
thanks for help i was struck for a week on this but now is all set once again thanks for hepling🤝
