### ISSUE TITLE
When should I use openAudioSession() and closeAudioSession() ?

### ISSUE THREAD

**Issue by bardram** [dooboolab/flutter_sound#360]
I need Help for  

* Using the API

-------------------------------------
## Here is my question :

It is unclear to me what the state management / flow is in `flutter_sound`. When upgrading to version 5.x.x is seems like we now need to call

* `openAudioSession()` 
* `closeAudioSession()`

But - when is this normally done? In the example demo app #1 I can see this is only done in the app `initState()` and `dispose()` methods. But - what if I'm writing an app that is running for a looooong time and does recording once and a while -- e.g. when the user hits a record/stop button?

What is best practice here?

PS - Thanks for a really nice plugin - we're using it quite a lot.

**Comment by Larpoux** [comment]
By default, openAudioSession() require the Audio Focus,
and closeAudioSession() will abandon the Audio focus.

If you do not play yourself with the focus, it means that other App (spotify?) will stop (or duck) while Flutter Sound will have the Audio Focus.

Also, openAudioSession() takes some resources inside the OS.

But probably the simpler for you is to **keep your sessions open and do not close them**. This is no problem if you just have two sessions (one for recording and one for playing)
You will have much **less problems** with the Focus.
And if you must play with the focus later, you will improve that.

**Comment by Larpoux** [comment]
Hi @bardram ,
I hope that you are glad with Flutter Sound V5.
Do not hesitate to open a new PR (Problem Report) if you have difficulties or need more help.
