### ISSUE TITLE
[HELP] We need Contributors for the V5 development

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#361]
## We desperately need contributors for the V5 development

We have great hopes for Flutter Sound V5.
Here is a TODO list for several of our projects : 

- [ ] Record and playback raw PCM both on Android and iOS
- [ ] Record OPUS on Android
- [ ] Record MP3 both on Android and iOS
- [ ] Record raw PCM to a Dart Stream instead of a file
- [ ] Playback raw PCM from a Dart Stream instead of a file
- [ ] Streaming records to Speech to Text
- [ ] More support for the Apple Watch
- [ ] Tests unit to avoid any regression
- [ ] Flutter Web App support
- [ ] Flutter Sound port to React Native
- [ ] Better UI Widget
- [x] Lock screen control between two sounds. (Done on iOS only)

If we continue our developments Flutter Sound can be **THE inescapable** plugin to do sound with flutter. But we need more contributors.

## @salvatore373 : 

@salvatore373 , this is a private message for you.
We think that you are a very good developer. Track Player is really great. Flutter Sound users love this feature that you implemented. Track Player is pretty good robust. (We had just a bug that I introduced myself when I ported your stuff to Flutter Sound. It was my fault).

We think that it is too bad that you do not work any more on Flutter Sound. We really need good developers. If you look carefully to the TODO list above, we are sure that you will be happy to pick one. Please tell us. If you do, you will be considered as one of the few FS contributors.

Note: You did a Pull Request to Flauto, one month ago, for having your name mentioned among the Flutter Sound contributors. But Flauto was a dead project so I was not able to answer positively to this PR. Please, redo your PR to Flutter Sound Master branch. I talked with @hyochan and he is OK with your request.

**Comment by yelkamel** [comment]
@salvatore373

**Comment by salvatore373** [comment]
Hi everybody,
Thank you for considering me in the development of V5 of Flutter Sound. I'm sorry for not immediately answering to your  request, but I have been very busy during the last months, and it made me miss your message.
I started working on another important project that takes all of my time, and for this reason at the moment I cannot contribute to this new task. However, I am sure that you will make an incredible job with the new version, as you all did in the previous ones. I hope that in the near future I will be able to take at least one _TODO_ from the list above: in that case I will inform you.

I want to thank you again for considering me for this new task and for appreciating my previous contribution.

Good luck
Salvatore

**Comment by Larpoux** [comment]
Hi Guys and Girls,

I will be frank : I am not very optimist for the Flutter Sound Future.

- @hyochan are currently working on other projects
- @salvatore373 is now working on another project
- @bsutton is now working on a Flutter Sound fork
- I am now working on my own App and I have no spare time for Flutter Sound

How long do you think a project can live without any developers, before dying soon ?

## **We really need contributors!**
