### ISSUE TITLE
[BUG] startPlayerFromTrack wrong position and duration in media controls

### ISSUE THREAD

**Issue by the-meedu-app** [dooboolab/flutter_sound#364]
## Flutter Sound Version : 
Release

- Version number 5.0.1

-  lite version

- Result of the command **"flutter pub deps | grep flutter_sound"**
|-- flutter_sound_lite 5.0.1

when call startPlayerFromTrack  the first time position and duration is not visible on media controls, the second time takes the duration of previous track and the position takes the previous track position.

<img src="https://user-images.githubusercontent.com/15864336/82767960-3c25a280-9df1-11ea-9d79-f0eb8696985b.PNG" width="300" />

Also when calling seekToPlayer(position) the position in  MediaControls is not updated

**Comment by Larpoux** [comment]
Hi @darwin-morocho 

I am going to look to that tomorrow or wednesday.

**Comment by Larpoux** [comment]
iOS or Android ?

**Comment by darwin-morocho** [comment]
> iOS or Android ?

ios

**Comment by Larpoux** [comment]
> when call startPlayerFromTrack the first time position and duration is not visible on media controls,

I cannot reproduce any problem with the example/demo1 App.



> the second time takes the duration of previous track and the position takes the previous track position

I did a fix in Pull Request #364 to clean correctly the Lock Screen info when a sound is stopped by the App or is finished.

> Also when calling seekToPlayer(position) the position in MediaControls is not updated

I did a fix in Pull Request #364 to update correctly the Lock screen after a ```seekToPlayer()``` or after a ```resumePlayer()```

Please, look to the Pull Request #367  
(Fork [pos_lock_screen_364](https://github.com/Canardoux/flauto/tree/pos_lock_screen_364)

**Comment by darwin-morocho** [comment]
I was able to reproduce the same error on my iphone x using the repository example

<img src="https://user-images.githubusercontent.com/15864336/82909779-582f5e00-9f2f-11ea-97cd-9fa2c4cf2439.PNG"  width="250"/>

<img src="https://user-images.githubusercontent.com/15864336/82909752-4e0d5f80-9f2f-11ea-968b-363356804108.PNG"  width="250"/>

**Comment by Larpoux** [comment]
I do not reproduce any problem (using my #367 Pull Request)

**Comment by Larpoux** [comment]
What is the iOS SDK you link your App with ?

**Comment by darwin-morocho** [comment]
> What is the iOS SDK you link your App with ?

iOS 13.3

You can check the bugs [in this video](https://drive.google.com/file/d/1ZJ2S_1hHAy1HhJyPLxfPX83zj91a9v_W/view?usp=sharing)

This is my repo [source code](https://github.com/darwin-morocho/curso-flutter-ui-avanzadas/tree/sound)
