### ISSUE TITLE
FlutterSoundHelper.duration will not return the duration of a sound file

### ISSUE THREAD

**Issue by lordrocco** [dooboolab/flutter_sound#365]
I cannot get the duration of a sound file I made. Am I doing something wrong?

Here is my code:

  Future<void> stopRecording() async {
    await recorderModule.stopRecorder();
    int a;
    print('Placeholder');
    a = await recordingInfo2.duration(currentRecordingSegmentWithFullPath);
    print('$a');
  }

Here is the Run console text:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'duration' was called on null.
Receiver: null
Tried calling: duration("/Users/rocco/Library/Developer/CoreSimulator/Devices/69D6E639-0D7E-49B7-936E-369AA86F5E3B/data/Containers/Data/Application/D9616013-2314-4E3A-A084-00D766FC1425/Documents/grabbit/segment10003.aac")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RecorderBrain.stopRecording (package:personalaudiostudio/studio_brain.dart:232:30)
<asynchronous suspension>
#2      RecorderBrain.clickedMiddleButton (package:personalaudiostudio/studio_brain.dart:73:7)
#3      _PersonalStudioState.build.<anonymous closure>.<anonymous closure> (package:personalaudiostudio/main.dart:209:37)
#4      State.setState (package:flutter/src/widgets/framework.dart:1148:30)
#5      _PersonalStudioState.build.<anonymous closure> (package:personalaudiostudio/main.dart:207:19)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:<…>

**Comment by Larpoux** [comment]
See #364. It seems that there is a bug in FS.
Are you on Android or iOS ?
I am going to see that Wednesday.
Sorry for the inconvenience.

**Comment by lordrocco** [comment]
So far only tried it in IOS simulator. Thanks for the fast reply btw!

**Comment by Larpoux** [comment]
I think that the problem is on your side : 
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'duration' was called on null.

Probably it will be better if you replace : 
```
a = await recordingInfo2.duration(currentRecordingSegmentWithFullPath);
```
by : 
```
a = await flutterSoundHelper.duration(currentRecordingSegmentWithFullPath);
```

**Comment by lordrocco** [comment]
That’s an improvement. No error messages. But the response to my print statement is "flutter: null”, so I’m still not getting any duration information.

**Comment by Larpoux** [comment]
probably ```currentRecordingSegmentWithFullPath``` is incorrect

**Comment by Larpoux** [comment]
I need your new logs.

**Comment by lordrocco** [comment]
currentRecordingSegmentWithFullPath is the same variable I used to invoke the recording in the first place, and I use it in another method to play the sound file.

I don’t know what log you want to see. The run console isn’t throwing any messages. Can you explain please?

**Comment by Larpoux** [comment]
I really cannot do anything without your logs. The logs that you get when running your App in debug mode.

**Comment by lordrocco** [comment]
I understand, but I am pretty new to this and I don’t know how to get the log you need. Can you offer me any instructions? I’m using Android Studio on a Mac, and the only debug log I can find is one that opens in Chrome. It doesn’t look useful around the point my issue happens, so I don’t think it’s what you need.

**Comment by Larpoux** [comment]
In Android Studio the logs are displayed int the "Debug" view, in the bottom of the screen.

**Comment by lordrocco** [comment]
I can’t find the Debug view. Let’s try another approach.

My variable resolves as this: 
currentRecordingSegmentWithFullPath = /Users/rocco/Library/Developer/CoreSimulator/Devices/69D6E639-0D7E-49B7-936E-369AA86F5E3B/data/Containers/Data/Application/5119A064-E357-4442-ABC9-93AFA0BE4E92/Documents/boltz/segment10001.aac

Is this the kind of input the method is expecting? Should that yield the expected result if this file actually exists? All I am getting for a result is null.

**Comment by Larpoux** [comment]
I cannot do anything with such a Problem Report.
Please fill a new correct PR (Problem Report) with some informations that I need : 
- Flutter Sound version
- Flavor
- result of "flutter pub deps | grep flutter_sound"
- ... your logs.
