### ISSUE TITLE
flutterSound.seekToPlayer(millis) was not working correctly

### ISSUE THREAD

**Issue by mikeyyg96** [dooboolab/flutter_sound#37]
### Version of flutter_sound
1.2.4
## flutter doctor
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.0)
[√] VS Code, 64-bit edition (version 1.30.2)
[√] Connected device (1 available)
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
to seek to the correct position
### Actual behavior
seeks to the current position + the new value. I know why it is doing it. In the android code, the seek method takes in an int millis and it adds that value to the current millis that is playing, which it shouldn't. Just comment it out and it works.
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
Use a Slider widget and in the onChanged property to set the media player to seek to the new 'dragged' value

**Comment by hyochan** [comment]
@mikeyyg96 Could you create `PR` on this? Also, it'd be wonderful if you can provide `slider` example in our `example` project.

**Comment by mikeyyg96** [comment]
> @mikeyyg96 Could you create `PR` on this? Also, it'd be wonderful if you can provide `slider` example in our `example` project.

I don't have permission to publish branch that I made. But I have an example of the Slider widget and the change in the line of code in FlutterSoundPlugin.java

**Comment by mikeyyg96** [comment]
@hyochan Okay, I think I did it. Sorry, still new to this.
