### ISSUE TITLE
Make minSdkVersion (Android) lower since a large portion of people are still using an old version of Android

### ISSUE THREAD

**Issue by fzyzcjy** [dooboolab/flutter_sound#384]
**Is your feature request related to a problem? Please describe.**
The minSdkVersion is too high (24), since many people are still using a lower version of Android :(

**Describe the solution you'd like**
change it to, say, 16

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Larpoux** [comment]
See [#400]
Actually, Flutter Sound V5 cannot be installed on an Android emulator having a SDK Version less than 24. I do not understand really why, but I do not have much time for investigating this limit.
Maybe someone else can look to that ?

Probably your solution is to use Flutter Sound V4, which has a MinSdkVersion = 16.

**Comment by fzyzcjy** [comment]
Thanks I already switch back to V4 :)
