### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Crzech** [dooboolab/flutter_sound#386]
I need Help for : seekTo method usage

- Using the API ?
flutter_sound_lite: ^5.0.0
- Generate an iOS or Android App ?
Android
- Debugging my App ?

- Other ?

-------------------------------------
## Here is my question :
I'm trying to implement a similar functionality to the demo1 in this repo and I'm having some problems using seekTo method: 
When playerModule have state "playing" "seekTo" method, pauses the player but doesn't do it correctly, playerModule.isPlaying becomes false and sound doesn't pause. And if playerModule have state "paused" after using seekTo method sound starts to play even if I use playerModule.pausePlayer() after seekTo. The problem is that playerModule.isPlaying is false/true in cases that have to be the opposite and this is leading me to have a lot of exceptions, mainly in the onPaused method of startPlayerFromTrack.
Thank you in advance if someone is reading this :)

![image](https://user-images.githubusercontent.com/27091230/83987579-f5aa6a80-a8fd-11ea-98cc-ffcc553c6d72.png)
![image](https://user-images.githubusercontent.com/27091230/83987608-15419300-a8fe-11ea-9424-2985a2366146.png)
![image](https://user-images.githubusercontent.com/27091230/83987947-07d8d880-a8ff-11ea-80c0-b4b4a8057bcd.png)

**Comment by Larpoux** [comment]
Your problem is that you do : 
```
onPaused: (b){};
```
Because you specified this parameter not null, Flutter Sound does not do anything by itself when the user hit the "pause button".
Better to do : 
```
onPaused: (){ myFlutterSoundModule.pausePlayer(); }
```
or better : 
```
onPaused: null
```
Or again better not specify at all this parameter (default is null).

**Comment by Crzech** [comment]
Thank you @Larpoux 
I actually want that flutter_sound to work this way:
`onPaused: (){ myFlutterSoundModule.pausePlayer(); }`
But my problem is when I use 'seekTo' method, probably the real question is: "Is there a way to make seekTo method avoid start playing sound after using it?"

**Comment by Larpoux** [comment]
I will work on this issue later.
In the mean time, could you post your logs, please ?

**Comment by Crzech** [comment]
Oh, okay, thank you very much for your feedback, here are my logs:

Logs when I use myFlutterSoundModule.startPlayerFromTrack():
```
W/MediaPlayer(22182): Use of stream types is deprecated for operations other than volume control
W/MediaPlayer(22182): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
```

Logs when I use myFlutterSoundModule.pausePlayer():
```
E/MediaPlayerNative(22182): stop called in state 1, mPlayer(0x0)
E/MediaPlayerNative(22182): error (-38, 0)
V/MediaPlayer(22182): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(22182): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(22182): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(22182): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService(22182): MediaHTTPService(android.media.MediaHTTPService@a0bbe1b): Cookies: null
V/MediaHTTPService(22182): makeHTTPConnection: CookieManager created: java.net.CookieManager@ece5bb8
V/MediaHTTPService(22182): makeHTTPConnection(android.media.MediaHTTPService@a0bbe1b): cookieHandler: java.net.CookieManager@ece5bb8 Cookies: null
```
I watched for the logs after using myFlutterSoundModule.seekTo() but anything appeared.

Exception after trying to pause myFlutterSoundModule that is playing but myFlutterSoundModule.isPlaying() is false:
```
E/flutter (22182): #19     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (22182): #20     _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter (22182): #21     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (22182): #22     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (22182): #23     _invoke1  (dart:ui/hooks.dart:275:10)
E/flutter (22182): #24     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)
E/flutter (22182):
D/FlutterSoundPlugin(22182): Play completed.
V/MediaPlayer(22182): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(22182): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(22182): stop called in state 1, mPlayer(0x0)
E/MediaPlayerNative(22182): error (-38, 0)
V/MediaPlayer(22182): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(22182): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

**Comment by yongjieYuan** [comment]
I/example.exampl( 6677): ProcessProfilingInfo new_methods=486 is saved saved_to_disk=1 resolve_classes_delay=8000
V/MediaHTTPService( 6677): MediaHTTPService(android.media.MediaHTTPService@b57ae1c): Cookies: null
V/MediaHTTPService( 6677): makeHTTPConnection: CookieManager created: java.net.CookieManager@f4757fa
V/MediaHTTPService( 6677): makeHTTPConnection(android.media.MediaHTTPService@b57ae1c): cookieHandler: java.net.CookieManager@f4757fa Cookies: null

Those are errors above all, when I run the example.
I'm using flutter_sound 3.0.0，I have configed network allow http service.

**Comment by Crzech** [comment]
> 

Thanks for testing the example. The version I used back then wasn't 3.0.0, I remember having to do a workaround, thanks anyway!
