### ISSUE TITLE
Flutter Sound vs Sound

### ISSUE THREAD

**Issue by felixjunghans** [dooboolab/flutter_sound#388]
As I could see, after much back and forth, it was decided that @bsutton  would release its own package. Are there any plans to merge the codebase again or will there be only flutter_sound or only sound from now on? Or will both packages be developed in parallel and separately from each other from now on? Since I am currently in the process of deciding which sound package to use and there are now these two packages, it would be nice to know what the plans for the future are. Thanks a lot.

**Comment by bsutton** [comment]
So you have got a little ahead of me as I'm not quite ready to make any official announcement but...

Essentially we haven't been able to get agreement on a way forward after many months of discussions.

As such I've made the decision to fork the project.
I would expect the two packages to move forward separately.

I'm looking to build of coalition of developers around the new fork and I will shortly be actively looking to recruit contributors.
Over the next week or so I will lay out a plan for the project detailing how I see it moving forward.

**Comment by felixjunghans** [comment]
Oh, sorry about that. Thanks anyway for your quick response and I am curious what will happen in the next weeks :)

**Comment by chi-tea-72** [comment]
Hi @bsutton, I just wanted to inquire about whether there are any ongoing plans for Sounds to include the ability to record and write raw pcm to a stream instead of a file for both ios & android.

I tried to open and read a stream from the file as it was being written to, but it didn't work out as I'd hoped. This functionality is very important to me, so I would love to help out however I can to make it a reality. Thanks.

**Comment by bsutton** [comment]
I have some pieces in the dart code that have been written to support
streams by I've done nothing concrete at this point.

I don't have the time to do anything with the streams at the moment but if
you are willing to put the effort in I'm willing to provide some support.

If you are interested I would suggest that you raise an issue in the sounds
project and outline what the api might look like at the dart and platform
levels.

I would suggest we want something like a streamable track.

Fyi I'm also looking at moving all the codec support into separate packages
to make codecs pluggable.
So the codec converters will need to support live stream conversions. I'm
not certain if all codec support this concept.
