### ISSUE TITLE
Can't play file with Russian name on iOS only [BUG]

### ISSUE THREAD

**Issue by jayabrown** [dooboolab/flutter_sound#390]
## Flutter Sound Version : 

- Released
- Version number 5.0.1
- Lite

- Result of the command **"flutter pub deps | grep flutter_sound"**
`flutter_sound_lite 5.0.1`

----------------------------------------------------------

## Severity

- Result is not what expected

--------------------------------------------------------

## Platforms you faced the error 

- iOS on both emulator and device

----------------------------------------------

## Logs
`flutter: Audio file already downloaded.`
` flutter: path: /Users/xxx/Library/Developer/CoreSimulator/Devices/D623D0DD-1919-466F-BDBA-81ACC90C0684/data/Containers/Data/Application/C23FD572-6079-4AF4-8EB2-30AEA549E025/Documents/123.mp3`
`flutter: starting player...`

------------------------------------------------

**Describe the bug**
I'm unable to play a downloaded mp3 file on iOS.  It works on Android.  `startPlayer` doesn't throw any error.

**To Reproduce**
```  
void initPlayer() {
    player = FlutterSoundPlayer();
  }

  void startPlayer() async {
    assert(player.isStopped, 'Only start a stopped player. If the player is paused, use resume instead.');
    String path = widget.filePath;
    print("path: "+path);
    try {
      assert(File(path).existsSync());
      await player.openAudioSession();

      print("starting player...");
      await player.startPlayer(
        fromURI: path,
        codec: Codec.mp3
      );
      print("player started");

    } catch (err) {
      print('Error starting the player: $err');
    }
  }
```

**Expected behavior**
I would expect the player to start the audio, and also for `player started` or `Error starting the player: ...` to be printed, but it simply hangs at `starting player...`.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Can you post here your MP3 ?

**Comment by jayabrown** [comment]
Ok... so in getting ready to post the file I changed the name to "123.mp3" and then it worked.  Then I tried again with the original filename, which is in Russian, and it doesn't work.  So I don't know if it's maybe a fault of the iOS file system, but I can't play any file with Russian names (i.e. `русскаяистория.mp3`)
