### ISSUE TITLE
[BUG] Not getting player state callbacks on iOS: onPlayerStateChanged

### ISSUE THREAD

**Issue by UttamPanchasara** [dooboolab/flutter_sound#396]
## Flutter Sound Version : 

v2.1.1
----------------------------------------------------------

Not getting player state callbacks on iOS: onPlayerStateChanged

While using the plugin along with flutter_downloader plugin stopped getting state change callbacks on iOS, 
When we start the download and by the time when the file is downloading, I'm not getting onPlayerStateChanged states on iOS only.
--------------------------------------------------------

## Platforms you faced the error 

iOS only, tested device iPhone XR
----------------------------------------------

Any solution? to run and get state callbacks on iOS while performing the downloading operation?

**Comment by Shakle** [comment]
same on Android, version 4.0.5

**Comment by UttamPanchasara** [comment]
Any update?
