### ISSUE TITLE
Make APK much bigger

### ISSUE THREAD

**Issue by Luffys6** [dooboolab/flutter_sound#399]
Make APK much bigger

**Comment by Larpoux** [comment]
The Lite flavor of Flutter Sound should not weight too much

**Comment by Luffys6** [comment]
> The Lite flavor of Flutter Sound should not weight too much

Apk increased by more than 30 megabytes

**Comment by Larpoux** [comment]
I did some tests building iOS .ipa in Released Mode. Here are my results

|    flavor      |  V4.x     |  V5.1     |
| -----------| :-------:|:--------|
| LITE          | 16.2 MB  | 17.8 MB |
| FULL         | 30.7 MB | 32.1 MB |
