### ISSUE TITLE
Reverse audio?

### ISSUE THREAD

**Issue by hosembafer** [dooboolab/flutter_sound#4]
### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
Reverse audio after recording.

### Actual behavior
Not reversing.

Is there a way to reverse audio file on play or record step?

**Comment by dooboolab** [comment]
What do you mean exactly by reversing? Do you mean playing backward?

**Comment by hosembafer** [comment]
@dooboolab yes, exactly.

**Comment by dooboolab** [comment]
@hosembafer I've not yet supported this feature. Will remind you again here when it is ready.
