### ISSUE TITLE
Getting PCM data (array-like of the audio samples) from audio files

### ISSUE THREAD

**Issue by ffarall** [dooboolab/flutter_sound#401]
I'm trying to develop an app that processes audio in real time, using Flutter as front-end, and C++ as back-end, connected through ```dart:ffi```. I've been looking for a way to get a chunk of audio data from audio files in the ```assets``` directory of my app, and pass it down to the C++ backend, but couldn't find a way. Is it possible to do it with this plugin?

**Comment by thomasnilsson** [comment]
Have a look at our plugin, which saves the PCM data to an array: https://pub.dev/packages/audio_streamer

**Comment by Larpoux** [comment]
V 6.0 is released. With this version you can record live PCM-LINEAR-16 data to a Dart Stream or playback from a Dart Stream.
