### ISSUE TITLE
[BUG] warner_tautz_off_broadway.mp3

### ISSUE THREAD

**Issue by alevittoria** [dooboolab/flutter_sound#402]
- Version: 4.0.4+1
- LITE version
- Platform Android
----------------------------------------------------------
When you include flutter_sound in your project, you import warner_tautz_off_broadway.mp3 with it.
This file is not necessary especially when you build it in release.

**Comment by furkansarihan** [comment]
How to exclude this file from release build?

**Comment by Larpoux** [comment]
I think that this file is part of the Flutter Sound example, but not part of the Plugin.

Where did you see this file in the Plugin ?

**Comment by guuguo** [comment]
@Larpoux 在使用该插件后,便一出的apk文件里面包含此文件
![image](https://user-images.githubusercontent.com/12984352/94571385-838dd500-02a2-11eb-9522-be8788cfab17.png)

**Comment by isapoetra** [comment]
this file still exist on flutter_sound_lite: ^8.3.12, this file from tau_core  library (https://github.com/Canardoux/tau_core/blob/master/android/src/main/res/raw/warner_tautz_off_broadway.mp3)
please move this file to debug only folder

**Comment by Larpoux** [comment]
@isapoetra , @alevittoria , @furkansarihan

Yes, you are right. Those assets are completely stupids here.
I do not understand why they are here.

I am going to remove them in Tau Sound 9.0.
Thank you for your problem report.
