### ISSUE TITLE
[HELP] How to use the default audio device to playback?

### ISSUE THREAD

**Issue by tgarm** [dooboolab/flutter_sound#403]
I need Help for Using the API.
-------------------------------------

For instance:
## Play audio to default device

In FlutterSoundPlayer.openAudioSession, the argument "device" can be set to airPlay, headset, speaker, etc. But there is _**no**_ device as "default".

So, if the audio session started without headset, and when playing, user plug-in the headset, the sound is still playing on speakers, not the headset. (User normally expect the output to switch to headset immediately)

Is there anyway to solve it?

**Comment by Larpoux** [comment]
Which OS ?

**Comment by tgarm** [comment]
Android. The testing device runs Android 8.1

**Comment by Larpoux** [comment]
Sorry for the delay to answer, @tgarm 

I think that you must specify `blueToothA2DP` as one of your audio flags if your headset is bluetooth.
When the user will plug his BlueTooth headset, i guess that the sound will be switched to the headset (probably ;-) )

I agree that this area is a little messy in Flutter Sound. Someone should clean this.

**Comment by maxkrieger** [comment]
For me, what fixed it was opening the recorder's audio session *before* the player's, if you use both.
