### ISSUE TITLE
[HELP] How can get buffer while recording?

### ISSUE THREAD

**Issue by quanghoang0101** [dooboolab/flutter_sound#405]
In my case, I want to draw visualizer chart while recording. So I need to get buffer data to present it.

**Comment by Mateis** [comment]
I think the record to buffer is not implemented yet. 

I read this in commented lines 106 - 107 here: https://github.com/dooboolab/flutter_sound/blob/master/lib/src/ui/sound_recorder_ui.dart

I would like this feature too!

**Comment by Larpoux** [comment]
I am currently working on FS V6.0, which will be released I hope in a few weeks.
I really hope that this version will support streaming to a dart stream. Actually I can do that on Android, but not on ios.
I hope to find an ios solution before the v6.0 release.

**Comment by Mateis** [comment]
Awesome

> 
> 
> I am currently working on FS V6.0, which will be released I hope in a few weeks.
> I really hope that this version will support streaming to a dart stream. Actually I can do that on Android, but not on ios.
> I hope to find an ios solution before the v6.0 release.

Awesome

**Comment by Larpoux** [comment]
V6.0 is released. With this new release we can record PCM-Linear-16 to a live stream.
