### ISSUE TITLE
[BUG]: There is difference between recorded audio time and actual audio length

### ISSUE THREAD

**Issue by nimi0112** [dooboolab/flutter_sound#406]
## Flutter Sound Version : 

- **Released** or **Beta** version ? ***Released***

- Version number ? ***5.1.0***

- **FULL** or **LITE** flavor ? ***Full***
## Severity

- Crash ? ***NO***

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?

- ***Both*** ?

- Emulator ? 

- Real device ?

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

------------------------------------------------

##  Screenshots

<img src="https://user-images.githubusercontent.com/16234261/86466846-05c53680-bd52-11ea-8685-8e64678f1c86.png" alt="alt text" width="350" height="600">

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

The recorded audio length differs from the actual audio time. There is always a gap of few secs between them and this gap increases as the duration of recorded increases.

See the screenshot attached above.

- The timer is showing the duration as 09:28 secs but the actual duration shown below is 9.09 secs. 

- I also face the same issue when I record an audio using this plugin and upload audio file to server. The time shown here is different and the actual audio duration is different.

**Comment by nimi0112** [comment]
@Larpoux  please respond.

**Comment by Larpoux** [comment]
Hi @nimi0112 ,

This difference is normal : the duration got by the verb `duration()` is just an estimation computed with 
- the codec used
- the length of the record
- the sample rate

The only way to have an accurate duration is to playback it !

**Comment by zhangshexin** [comment]
你也有同样的问题，通过flutterSoundHelper得到的时长和_flutterSound.onProgress.listen得到的不一样，好奇怪，这个时长通过打印发现还会变化，希望能查看一下

**Comment by Larpoux** [comment]
Please re-open this issue if my previous answer does not satisfy you
