### ISSUE TITLE
[HELP] Example project doesn't run

### ISSUE THREAD

**Issue by vercorro** [dooboolab/flutter_sound#407]
I need Help for :

- Using the example app
-------------------------------------
## Here is my question :

Hello , thank you for the awesome library first of all .
I'm trying to run the example app but in some files the called methods doesnt exist anymore .
In example : in recording_player.dart at line 96 : 
`      track = Track.dataBuffer(dataBuffer, codec: ActiveCodec().codec);
`
the dataBuffer method doesnt exist in Track class.

Second example , at line 104 in the same recording_player.dart file : 
`    track = Track.fromFile(audioFilePath, codec: ActiveCodec().codec);
` 
fromFile method doesnt exist also .

Also in track_switched.dart file at line 66 : 
`            value: PlayerState().hushOthers,
`
The hushOthers method doesnt exist anymore and PlayerState class was renamed to UtilRecorder if I get it right.

At line 80 in the same track_switched.dart file the called function 

`    PlayerState().setHush(hushOthers: hushOthers);
`

is'nt existing anymore .

Can you help me to correct the above methods or update the example project please .
Thank you .
Regards.

**Comment by Larpoux** [comment]
Hi @vercorro ,

I am sorry that you have problems running the examples 👎 . Having running examples is really a must.

It seems that you are right : there is several undefined symbols int demo2 👎 
I am very surprised, because I did not do intensive tests with demo2, but I compiled it and run it successfully before releasing the V5 🙄 .

I am going to fix that, now. Sorry for the inconvenience.

**Comment by vercorro** [comment]
> Hi @vercorro ,
> 
> I am sorry that you have problems running the examples  . Having running examples is really a must.
> 
> It seems that you are right : there is several undefined symbols int demo2 
> I am very surprised, because I did not do intensive tests with demo2, but I compiled it and run it successfully before releasing the V5  .
> 
> I am going to fix that, now. Sorry for the inconvenience.

Thank you for your quick response. It's definitely a must and thank you for providing it and taking care of the users. 
I'll hapilly wait for your update . :)

**Comment by vercorro** [comment]
> Hi @vercorro ,
> 
> I am sorry that you have problems running the examples  . Having running examples is really a must.
> 
> It seems that you are right : there is several undefined symbols int demo2 
> I am very surprised, because I did not do intensive tests with demo2, but I compiled it and run it successfully before releasing the V5  .
> 
> I am going to fix that, now. Sorry for the inconvenience.

Any update on this? Please dont let me down 😞

**Comment by Larpoux** [comment]
@vercorro 

I am currently working on the flutter Sound UI widget.
I fixed all the compilations problems,
but I found several bugs in the UI Widget that I want to fix before releasing a new Flutter Sound version.

I will publish the new version this evening, or tomorrow.
I hope that you will be glad with this new version.

**Comment by vercorro** [comment]
> @vercorro
> 
> I am currently working on the flutter Sound UI widget.
> I fixed all the compilations problems,
> but I found several bugs in the UI Widget that I want to fix before releasing a new Flutter Sound version.
> 
> I will publish the new version this evening, or tomorrow.
> I hope that you will be glad with this new version.

Thank you for your response , good news!

**Comment by Larpoux** [comment]
V5.1.1 is released.
Do not hesitate to open new `Problem Reports` if you have any more problems.
