### ISSUE TITLE
Initialized.fullyInitialized is not exposed

### ISSUE THREAD

**Issue by tonypottera24** [dooboolab/flutter_sound#409]
## Flutter Sound Version : 
5.1.0
- **Released** or **Beta** version ?

- Version number ?

- **FULL** or **LITE** flavor ?
FULL
- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)
import 'package:flutter_sound/flutter_sound.dart';
import 'package:flutter_sound/src/session.dart';

FlutterSoundRecorder _flutterSoundRecorder = FlutterSoundRecorder();
if (_flutterSoundRecorder.isInited == Initialized.fullyInitialized) {
}
----------------------------------------------------------

## Severity

- Result is not what expected ?
import 'package:flutter_sound/src/session.dart';
gets following error:
Don't import implementation files from another package.dartimplementation_imports

**Comment by Larpoux** [comment]
Hi Tony,
You are right. I moved the enum `Initialized` to the main flutter_sound.dart, instead of session.dart.
This will be released in next Flutter Sound version : 6.0.1

Have a nice day, Tony.
