### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by vercorro** [dooboolab/flutter_sound#412]
I need Help for :

- Using the example app

-------------------------------------
## Here is the issue :
When trying to playback recorder audio after several times : 
`The following assertion was thrown building StreamBuilder<PlaybackDisposition>(dirty, state: _StreamBuilderBaseState<PlaybackDisposition, AsyncSnapshot<PlaybackDisposition>>#f3846):
'package:flutter/src/material/slider.dart': Failed assertion: line 132 pos 15: 'value >= min && value <= max': is not true.

The relevant error-causing widget was: 
  SoundPlayerUI file:///C:/Users/bers/AndroidStudioProjects/flutter_sound-master/example/lib/demo_util/demo3_body.dart:141:27
When the exception was thrown, this was the stack: 
#2      new Slider (package:flutter/src/material/slider.dart:132:15)
#3      PlaybarSliderState.build.<anonymous closure> (package:flutter_sound/src/ui/slider.dart:66:22)
#4      StreamBuilder.build (package:flutter/src/widgets/async.dart:509:81)
#5      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:127:48)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
`

When recording with one of the Opus Codec the above error occurs at the first playback.

It also records empty audio with several Realme devices with Android 10.0

**Comment by Larpoux** [comment]
👎 😞

**Comment by vercorro** [comment]
> 👎 😞

you'll figure it out :)

**Comment by Larpoux** [comment]
Perhaps I did something wrong during the build.
I just verified that everything OK on my real Android Device, and with OPUS Codec.
Are you sure to build with the new 5.1.1 ?

Now, I am going to generate demo2, using the official 5.1.1, and I will see the result ...

**Comment by vercorro** [comment]
> Perhaps I did something wrong during the build.
> I just verified that everything OK on my real Android Device, and with OPUS Codec.
> Are you sure to build with the new 5.1.1 ?
> 
> Now, I am going to generate demo2, using the official 5.1.1, and I will see the result ...

Yes I redownloaded the whole library after your update. Strange I tried it on Realme X2 pro and Xiaomi Note 8 and got the errors :/

**Comment by Larpoux** [comment]
Now I run `demo2` on my Xiaomi mi-max 3 using the `pub.dev 5.1.1`  and everything OK.

I do no see your problem. I will try to think tomorrow what is the reason ...

**Comment by Larpoux** [comment]
It seems that there is still problems with 5.1.1
The new version of my own app, uses now the Flutter Sound UI Widgets.
It works fine on my configuration, but my Beta Tester reports that there is a crash each time he tries to record something (on a real ios device).
I will continue to work on the Flutter Sound UI Widgets tomorrow.
I am sorry of the inconvenience.

**Comment by vercorro** [comment]
> It seems that there is still problems with 5.1.1
> The new version of my own app, uses now the Flutter Sound UI Widgets.
> It works fine on my configuration, but my Beta Tester reports that there is a crash each time he tries to record something (on a real ios device).
> I will continue to work on the Flutter Sound UI Widgets tomorrow.
> I am sorry of the inconvenience.

Thank you for your  response , its nothing to be sorry about , you're doing a great work! 
I'm happy to wait but just have one question  , what can I do in order to have the min sdk 21 instead of 24?

**Comment by vercorro** [comment]
> It seems that there is still problems with 5.1.1
> The new version of my own app, uses now the Flutter Sound UI Widgets.
> It works fine on my configuration, but my Beta Tester reports that there is a crash each time he tries to record something (on a real ios device).
> I will continue to work on the Flutter Sound UI Widgets tomorrow.
> I am sorry of the inconvenience.

Hello friend , please can you tell me if there is an upcoming fix for the issues? Thank you

**Comment by Larpoux** [comment]
Hi @vercorro ,

Actually I do not have problems using the Flutter Sound UI Widget.
It seems to run fine with the Demo2 App and my own App. 

My Beta Tester did some tests (only on iOS) and says that it is OK.(the problem that I had previously was stupid : I forgot to specify in my App that it needs to access the microphone).

If you have still any problems, we will need more investigations from you.
Sorry not being able to do more...
