### ISSUE TITLE
[BUG]iOS compile failed

### ISSUE THREAD

**Issue by tonypottera24** [dooboolab/flutter_sound#416]
## Flutter Sound Version : `5.1.1`

- **Released** or **Beta** version ?
`Released`

- Version number ?
`v1.17.5`

- **FULL** or **LITE** flavor ?
`FULL`

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)
`flutter run -v`

----------------------------------------------------------

## Severity

- Crash
Cannot compile successfully.

--------------------------------------------------------

## Platforms you faced the error 
- Emulator `iOS 13.6 iPhone 11`

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)
```
In file included from /path/to/flutter_stable/.pub-cache/hosted/pub.dartlang.org/flutter_sound-5.1.1/ios/Classes/FlutterFfmpegPlugin.m:21:
    /path/to/flutter_stable/.pub-cache/hosted/pub.dartlang.org/flutter_sound-5.1.1/ios/Classes/FlutterFFmpegPlugin.h:24:9: fatal error: 'mobileffmpeg/MobileFFmpegConfig.h' file not found
    #import <mobileffmpeg/MobileFFmpegConfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by DaveHineman** [comment]
When trying to compile FULL version, XCode cannot locate this file, mobileffmpeg/MobileFFmpegConfig.h. Of course, it is in the file structure, but I was unable to place it where Xcode could locate it.

**Comment by DaveHineman** [comment]
I didn't want the full version anyways, so I tried to run the demo with flutter_sound_lite. I see tons of "nonnull" errors and 'expected )' errors. I was compiling for IOS 12.0. 

flutter_sound_lite-5.1.1/ios/Classes/TrackPlayer.h:41:84:
    note: to match this '('
    - (void)setUIProgressBar:(NSNumber* _Nullable _Nullable_Nullable)progress duration:(NSNumber* _Nullable _Nullable_Nullable)duration;

**Comment by Ivaskuu** [comment]
I also have the same problem. flutter_sound 5.1.1 and iOS 13.4.1 (min iOS version is 12.4 in Podfile).
Anyone knows a quick fix that works in the meantime? This is blocking the development of my app. Thanks!

**Comment by svladykin** [comment]
Can not compile it either. Version 5.0.1 did not work for me.
Switched to ^4.0.0 and iOS 9.3 - worked fine.

**Comment by DaveHineman** [comment]
Thanks, Sergi.

I’m trying to run the example workspace for flutter_sound. 
When I change pub spec.yaml to use version ^4.0.0, I get many problems in the demo1.dart and the demo_util folder. “undefined class FlutterSoundPlayer” and “undefined class FlutterSoundRecorder.” Therefore, I’m unsure what workspace you are running that works fine.

**Comment by svladykin** [comment]
@DaveHineman I did not actually try to compile examples, just some code of my own. 

Also it looks like demo1.dart and demo_util are for 5.x versions, branch V4 does not have them in examples folder.

**Comment by DaveHineman** [comment]
Argh. Thanks for pointing that out. I had overlooked that the V4 and V5 workspaces weren’t the same. 

I was able to successfully download V4 branch and run it. 

Thanks!
Dave.

**Comment by albemala** [comment]
I was having the same problem, this is what worked for me:

- setting the iOS deployment target to 11.0
- upgrading cocoapods to 1.9.3

**Comment by Larpoux** [comment]
Do not hesitate to re-open this issue (or a new one) if it is not solved.
