### ISSUE TITLE
[HELP] Recommended way to set initial progress using startPlayerFromTrack

### ISSUE THREAD

**Issue by wkrause13** [dooboolab/flutter_sound#418]
I need Help for :

- Using the API ?
flutter_sound 5.1.1

- Generate an iOS or Android App ?
both
- Debugging my App ?

- Other ?

-------------------------------------
## Here is my question :

What is the recommended way to start a track at a given non-zero progress value, for example starting a track 5 seconds in? 

Looking at the code for startPlayerFromTrack, it looks like I should be able to pass in an initial value for progress and have the track start from that value. This does not seem to be occurring. I'm not sure if this is a bug or just a misunderstanding on my part as to the function of progress parameter in the startPlayerFromTrack function. If it matters my track is configured using a remote URL for the audio file. My call looks like this:

```dart
      await playerModule.startPlayerFromTrack(track,
          progress: Duration(milliseconds: 5000), onPaused: (bool b) {
        if (b)
          playerModule.pausePlayer();
        else
          playerModule.resumePlayer();
      });
```

Other things I have tried:

I have tried calling seekToPlayer immediately after startPlayerFromTrack, but as documented, if the state of the player is not playing, this call will fail. 

The last thing I tried was trying to respond to the first event from the onProgress listener stream, and then calling seekToPlayer. However, this results in a bit of the initial audio coming through.

**Comment by Larpoux** [comment]
This is a needed enhancement.
Please keep this issue open. Maybe I will be able to do something to answer your needs before the V6.0 release in a few weeks.
So stay tuned, and keep this issue open

**Comment by Larpoux** [comment]
Duplicate [#536]
