### ISSUE TITLE
[BUG] Record quality on Android is terrible

### ISSUE THREAD

**Issue by miguelpruivo** [dooboolab/flutter_sound#420]
## Flutter Sound Version : 

- Debug

- flutter_sound_lite: ^5.1.1

- LITE

- flutter_sound_lite 5.1.1

----------------------------------------------------------

## Severity

- Severe bug
--------------------------------------------------------

## Platforms you faced the error 

- Android
----------------------------------------------

## Logs

N/A

------------------------------------------------

##  Screenshots

N/A

-----------------------------------------------------

**Describe the bug**
On Android (Samsung) played with different settings and always got a terrible sound quality, regardless of the volume, codec, bitrate or sample.

**To Reproduce**
Just record sound with default configuration for Android.

**Expected behavior**
Good recording quality.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Are you using a real device or the emulator?

**Comment by tle-huu** [comment]
Hi,

I am having the same issue, very bad sound quality (hardly understandable robotic voice).

I am using the emulator. Here is my test app: https://github.com/tle-huu/flutter_sound_test/blob/master/lib/main.dart

**Comment by Larpoux** [comment]
We cannot do anything with such a PR (Problem Report) : 
- No Flutter Sound version
- No SDK number of your target device
- No informations running on a real device and not an emulator
- What is your Codec ?
- What are your `sampleRate` and `bitRate` ?
- Did you try to play your record on another App (for example VLC) ?
- Could you post the record you are trying to play ?

You must understand that a PR (Problem Report) just saying : 
```
Your Product does not work
```
is not useful at all.

**Comment by Larpoux** [comment]
@tle-huu : 

I noticed several things in your code : 
```
initializeRecorder();
```
Your function returns a Future and you must `await` it to be completed

```
import 'package:audioplayers/audioplayers.dart';
AudioPlayer audioPlayer = AudioPlayer();
...
int result = await audioPlayer.play(_file.path, isLocal: true);
```
This code has nothing to do with Flutter Sound.

**Comment by tle-huu** [comment]
@Larpoux 

Thanks for you reply.

I guess awaiting for the return of a void function is likely to be buggy.
The code non related to flutter sound was just a try to see if the player was the problem (it is not).

As for the actual weird sound effect, I tried the camera on the emulator an it turned out to have the same issue. So it is likely **to come from the emulator**. 

By curiosity, does my code work on yours (normal voice)?

**Comment by Larpoux** [comment]
**you can definitely await a Future<void>**. This is correct code.
Actually, your code does not await the `openSession()` to be completed, and you can have problems if you do `startPlayer()` just after.

You should check the correctness of your audio file, playing it with VLC.

I did not try your code, but I do play many playbacks with the Android emulator without major problems. (The quality is not perfect, but it is acceptable).

Please re-open this issue if you have more problems.

@miguelpruivo : Please re-open a new issue, filling all the missing items.
