### ISSUE TITLE
[BUG] iOS not recording at all if you change settings

### ISSUE THREAD

**Issue by miguelpruivo** [dooboolab/flutter_sound#421]
## Flutter Sound Version : 

- Debug

- flutter_sound_lite: ^5.1.1

- LITE

- flutter_sound_lite 5.1.1

----------------------------------------------------------

## Severity

- Severe bug
--------------------------------------------------------

## Platforms you faced the error 

- iOS (iOS 13.6)
----------------------------------------------

## Logs

N/A

------------------------------------------------

##  Screenshots

N/A

-----------------------------------------------------

**Describe the bug**
On iOS if you change the bitrate, codec, channels or sample, it won't record at all.

**To Reproduce**
Just try recording with any of the above settings. 

**Expected behavior**
Expect it to record.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems
