### ISSUE TITLE
can be adapted to mobile-ffmpeg-audio :4.4 No

### ISSUE THREAD

**Issue by zhangruiyu** [dooboolab/flutter_sound#422]
can be adapted to mobile-ffmpeg-audio :4.4 No

**Comment by Larpoux** [comment]
Please, could you be more explicit?
Note : i understand, that you are not fluent in English (nor am I 🙄 ).
I really be glad if I can help you.

**Comment by zhangruiyu** [comment]
Because I need to convert the song to AMR WB format, but version 4.4.3 does not support this operation.
[https://github.com/tanersener/mobile-ffmpeg/issues/381](url)

**Comment by Larpoux** [comment]
The last versions of Flutter Sound have the Flutter FFmpeg plugin 4.4 embedded.
You can use it in your app.
