### ISSUE TITLE
[BUG] openAudioSessionWithUI() and startPlayerFromTrack() return a value instead of a future

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#425]
## Flutter Sound Version : 

- **Released** 

- Version number ? 5.1.1

- **FULL** 
---------------------------------------------------------

## Severity

- Very serious 

- 
--------------------------------------------------------

## Platforms you faced the error 

- Android 
- Emulator 
----------------------------------------------

**Describe the bug**

openAudioSessionWithUI() and startPlayerFromTrack() return a value instead of a future.
If the app does a 
```await openAudioSessionWithUI() ```
or
```await startPlayerFromTrack()```
The asynchronous function returns too early.

Then, the app thinks that the operation is finished, but in fact it is not.
Serious bug happen after when the app tries to continue its process.

Those two functions must return a future, and complete this future when everything is done.

**Comment by arajuasati** [comment]
I am also facing the same issue, did you find any solution?

**Comment by Larpoux** [comment]
Fixed in v6.0
