### ISSUE TITLE
Error installing mobile-ffmpeg-audio

### ISSUE THREAD

**Issue by DontDream1** [dooboolab/flutter_sound#426]
## Flutter Sound Version : 
- 4.0.6
----------------------------------------------------------

## Severity
- Cannot build my App 
--------------------------------------------------------

## Platforms you faced the error 
- iOS 
----------------------------------------------

## Logs
[!] Error installing mobile-ffmpeg-audio
------------------------------------------------

**Describe the bug**
Running ' Pod Install 'indicates that the installation of mobile-FFmPEg-Audio 4.3.1 failed
-----------------------------------------------------------------

**Expected behavior**
How can I install Mobile-FFmPEg-Audio 4.3.1

-----------------------------------------------------------------

**Comment by landaship** [comment]
and how？

**Comment by Larpoux** [comment]
What is exactly your problem ?
