### ISSUE TITLE
[BUG] Unhandled Exception

### ISSUE THREAD

**Issue by longth97** [dooboolab/flutter_sound#428]
I recived a error. 
![image](https://user-images.githubusercontent.com/48413548/89866868-76296800-dbda-11ea-9ff9-c09b383809e9.png)

**Comment by albemala** [comment]
It looks like you are trying to delete a file that doesn't exist. You should probably save the file on disk before deleting it, or trying to delete the file only if it exists.

**Comment by Larpoux** [comment]
Yes, @albemala is probably right.
You are trying to delete a non existing file.
Probably something not tied with flutter sound.
