### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by albemala** [dooboolab/flutter_sound#429]
## Flutter Sound Version : 

- **Released** version 

- Version number: 5.1.1

- **FULL** flavor

- Result of the command **"flutter pub deps | grep flutter_sound"**

`|-- flutter_sound 5.1.1`

----------------------------------------------------------

## Severity

- Result is not what expected 

--------------------------------------------------------

## Platforms you faced the error 

- iOS 

- Emulator 

- Real device

----------------------------------------------

## Logs

**Describe the bug**

On iOS, while playing music on Spotify, I switch to the `flutter_sound` example app. 
When I start playing an audio in the example app, Spotify continues to play in parallel to the audio. 

**Expected behavior**

Spotify should stop playing.

**Comment by albemala** [comment]
This works fine on Android, as it seems to be taken care of by the `AUDIOFOCUS_LOSS` event. Is there a counterpart for iOS as well?

**Comment by Larpoux** [comment]
When you open your Audio Session, you must specy the parameter `requestTheAudioFocusAndStopOthers`.
You can also use the verb `setAudioFocus` if you need to change your focus durin an audio session.

Please refer to [the documentation](https://github.com/dooboolab/flutter_sound/blob/master/doc/player.md#openaudiosession-and-closeaudiosession)

Please re-open this issue if this answer does not satisfy you

**Comment by albemala** [comment]
That's great,  thank you very much!
