### ISSUE TITLE
mobile-ffmpeg-audio

### ISSUE THREAD

**Issue by Lanch92** [dooboolab/flutter_sound#432]
[!] CocoaPods could not find compatible versions for pod "mobile-ffmpeg-audio":
  In snapshot (Podfile.lock):
    mobile-ffmpeg-audio (= 4.3.1.LTS)

  In Podfile:
    flutter_sound (from `.symlinks/plugins/flutter_sound/ios`) was resolved to 0.0.1, which depends on
      mobile-ffmpeg-audio (= 4.3.2)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `mobile-ffmpeg-audio` inside your development pod `flutter_sound`.
   You should run `pod update mobile-ffmpeg-audio` to apply changes you've made.

**Comment by Larpoux** [comment]
Please remove any dependency to flutter_ffmpeg and mobile_ffmpeg in your configuration files.
Please read the [migration guide](https://github.com/dooboolab/flutter_sound/blob/master/doc/migration_4.x.x.md#migration-from-3xx-to-4xx)

Please re-open this issue if this answer does not satisfy you
