### ISSUE TITLE
Android does not support PCM format

### ISSUE THREAD

**Issue by ZHAO-CURRY** [dooboolab/flutter_sound#434]
## Flutter Sound Version : 

- Version number ?
flutter_sound: ^4.0.5 

- question
Aliyun "sentence recognition" function only supports PCM format, IOS can, but android does not support pcm format voice recording.

**Comment by Larpoux** [comment]
Android and ios both support PCM/WAVE. format, which is PCM in a WAVE file format.

What else would you want ?

Please re-open this issue if this answer does not satisfy you
