### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhanchi88** [dooboolab/flutter_sound#436]
## Flutter Sound Version : 

- **Released** or **Beta** version ?

- Version number ?

- **FULL** or **LITE** flavor ?

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

----------------------------------------------------------

## Severity

- Crash ?

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?

- Both ?

- Emulator ? 

- Real device ?

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

## Additional context**

V/AudioManager(14381): playSoundEffect   effectType: 0
V/AudioManager(14381): querySoundEffectsEnabled...
V/AudioManager(14381): setMode  mode: 0
I/AudioManager(14381): setMode mode:0
V/AudioManager(14381): stopBluetoothSco...
V/AudioManager(14381): setBluetoothScoOn  on: false
I/AudioManager(14381): setBluetoothScoOn on:false
V/AudioManager(14381): setSpeakerphoneOn  on: true
I/AudioManager(14381): setSpeakerphoneOn on:true
V/AudioManager(14381): registerAudioFocusListener...
V/AudioManager(14381): setSpeakerphoneOn  on: true
I/AudioManager(14381): setSpeakerphoneOn on:true
V/AudioManager(14381): setBluetoothScoOn  on: false
I/AudioManager(14381): setBluetoothScoOn on:false
V/AudioManager(14381): stopBluetoothSco...
V/AudioManager(14381): setMode  mode: 3
I/AudioManager(14381): setMode mode:3
I/flutter (14381): ppppppp  /data/user/0/com.iegdirsir/cache/12345xx.aac
D/AudioRecordPermission(14381): AudioRecordPermission
I/AudioRecordPermission(14381): remindWithResult:false
I/MediaRecorder(14381): enter in file frameworks/av/media/libmedia/mediarecorder.cpp, function prepare, line 461
I/IMediaRecorder(14381): prepare (BpMediaRecorder client) in file frameworks/av/media/libmedia/IMediaRecorder.cpp, function prepare, line 253
I/MediaRecorder(14381): exit in file frameworks/av/media/libmedia/mediarecorder.cpp, function prepare, line 495
I/MediaRecorder(14381): start
I/HwMediaRecorderImpl(14381): HwMediaRecorderImpl
I/HwMediaRecorderImpl(14381): sendStateChangedIntent, state=3
I/MediaRecorder(14381): stop
I/MediaRecorder(14381): enter in file frameworks/av/media/libmedia/mediarecorder.cpp, function stop, line 559
I/IMediaRecorder(14381): stop (BpMediaRecorder client) in file frameworks/av/media/libmedia/IMediaRecorder.cpp, function stop, line 293
I/MediaRecorder(14381): exit in file frameworks/av/media/libmedia/mediarecorder.cpp, function stop, line 585
I/HwMediaRecorderImpl(14381): sendStateChangedIntent, state=1
V/AudioManager(14381): unregisterAudioFocusListener...
I/AudioManager(14381): abandonAudioFocus
I/flutter (14381): 录音已关闭
I/flutter (14381): FS:---> openAudioSession 
V/AudioManager(14381): setMode  mode: 0
I/AudioManager(14381): setMode mode:0
V/AudioManager(14381): stopBluetoothSco...
V/AudioManager(14381): setBluetoothScoOn  on: false
I/AudioManager(14381): setBluetoothScoOn on:false
V/AudioManager(14381): setSpeakerphoneOn  on: true
I/AudioManager(14381): setSpeakerphoneOn on:true
V/AudioManager(14381): registerAudioFocusListener...
V/AudioManager(14381): setSpeakerphoneOn  on: true
I/AudioManager(14381): setSpeakerphoneOn on:true
V/AudioManager(14381): setBluetoothScoOn  on: true
I/AudioManager(14381): setBluetoothScoOn on:true
V/AudioManager(14381): startBluetoothSco...
V/AudioManager(14381): setMode  mode: 3
I/AudioManager(14381): setMode mode:3
I/flutter (14381): FS:<--- openAudioSession 
I/flutter (14381): 开始播放
I/flutter (14381): FS:---> startPlayer 
I/flutter (14381): FS:---> stop 
I/flutter (14381): FS:<--- stop 
I/flutter (14381): FS:---> _convert 
I/flutter (14381): FS:---> needToConvert 
I/flutter (14381): FS:<--- needToConvert 
I/flutter (14381): FS:<--- _convert 
V/AudioManager(14381): registerAudioFocusListener...
I/MediaPlayerNative(14381): setDataSource(54, 0, 576460752303423487)
I/flutter (14381): FS:<--- startPlayer 
D/FlutterSoundPlugin(14381): mediaPlayer prepared and start
V/PlayerBase(14381): baseStart() piid=1319
I/MediaPlayer(14381): [HSM] stayAwake true uid: 11268, pid: 14381
I/flutter (14381): FS:---> closeAudioSession 
I/flutter (14381): FS:---> stop 
I/MediaPlayerNative(14381): Pid:14381 MediaPlayer::start
D/MediaPlayerNative(14381): Action:start, CurrentState:MEDIA_PLAYER_STARTED
D/AndroidRuntime(14381): Shutting down VM
W/com.iegdirsir(14381): Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
E/com.iegdirsir(14381): [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime(14381): FATAL EXCEPTION: main
E/AndroidRuntime(14381): Process: com.iegdirsir, PID: 14381
E/AndroidRuntime(14381): java.lang.IllegalArgumentException: Non-positive period.
E/AndroidRuntime(14381): 	at java.util.Timer.schedule(Timer.java:254)
E/AndroidRuntime(14381): 	at com.dooboolab.fluttersound.FlutterSoundPlayer.onPrepared(FlutterSoundPlayer.java:462)
E/AndroidRuntime(14381): 	at com.dooboolab.fluttersound.FlutterSoundPlayer.lambda$startPlayer$0$FlutterSoundPlayer(FlutterSoundPlayer.java:375)
E/AndroidRuntime(14381): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlayer$CKEELXPVh5rkG3TIOBhd8o5Vky8.onPrepared(Unknown Source:4)
E/AndroidRuntime(14381): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3584)
E/AndroidRuntime(14381): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(14381): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(14381): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(14381): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14381): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(14381): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
D/JIGUANG-JCommon-P(14381): [JCommonInterface] onEvent action:deviceinfo
W/com.iegdirsir(14381): Accessing hidden method Landroid/telephony/TelephonyManager;->getSimCount()I (light greylist, reflection)
W/com.iegdirsir(14381): Accessing hidden method Landroid/telephony/TelephonyManager;->getSimSerialNumber(I)Ljava/lang/String; (light greylist, reflection)
W/com.iegdirsir(14381): Accessing hidden method Landroid/telephony/TelephonyManager;->getSubscriberId(I)Ljava/lang/String; (light greylist, reflection)
W/com.iegdirsir(14381): Accessing hidden method Landroid/telephony/SubscriptionManager;->getSubId(I)[I (light greylist, reflection)
E/libc    (14381): Access denied finding property "vendor.cellular.ril.imsi"
I/Process (14381): Sending signal. PID: 14381 SIG: 9

**Comment by Larpoux** [comment]
You probably call the API verb `setDurationDuration` with an elapsed time = 0 .

Please re-open this issue if this answer does not satisfy you
