### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by hamzune** [dooboolab/flutter_sound#438]
## Here is my question :

What I'm trying to do is an app in flutter that will get from the microphone of a mobile device, the sound which will be reproduced  at the same time on the client devices. For that purpose, I found your plugin interesting. However, I don't really know how could i get the chunks of the audio and send them via socket to a server and work with them in the server.  There is any way to do that using this plugin?

**Comment by Larpoux** [comment]
I am currently working on Flutter Sound V6.0. I hope to be able to do recording to a live stream. Actually I can do that on Android, but not ios. I hope to be able to fix the ios issue before the 6.0 release, in a few weeks. So stay tuned

**Comment by Larpoux** [comment]
V 6.0 is released. With this version you can record live PCM-LINEAR-16 data to a Dart Stream.
(you can also play PCM from a dart stream)
