### ISSUE TITLE
[BUG] flutter_sound (from `.symlinks/plugins/flutter_sound/ios`) was resolved to 0.0.1

### ISSUE THREAD

**Issue by Adherentman** [dooboolab/flutter_sound#440]
## Flutter Sound Version : 

- **Released** or **Beta** version ?
released 
- Version number ?
5.1.1
- **FULL** or **LITE** flavor ?
FUll
- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)
```
git:(2008) ✗ flutter pub deps | grep flutter_sound
|-- flutter_sound 5.1.1
```
----------------------------------------------------------

## Severity
- Cannot build my App ?
yes

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?
yes

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

```
➜  ios git:(2008) ✗ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "mobile-ffmpeg-audio":
  In Podfile:
    flutter_ffmpeg/audio-lts (from `.symlinks/plugins/flutter_ffmpeg/ios`) was resolved to 0.2.10, which depends on
      mobile-ffmpeg-audio (= 4.3.1.LTS)

    flutter_sound (from `.symlinks/plugins/flutter_sound/ios`) was resolved to 0.0.1, which depends on
      mobile-ffmpeg-audio (= 4.3.2)
```
------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).
**podFile**
<img width="850" alt="iShot2020-08-25上午11 17 05" src="https://user-images.githubusercontent.com/26477346/91118925-9e2dc680-e6c4-11ea-8ada-3e62b44d81a7.png">

**pubYmal**
<img width="452" alt="iShot2020-08-25上午11 18 19" src="https://user-images.githubusercontent.com/26477346/91118974-bc93c200-e6c4-11ea-8d5a-b6e9902223bf.png">

-----------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

**Comment by Adherentman** [comment]
I remove 
```
#symlink = File.join('.symlinks', 'plugins', 'flutter_ffmpeg')
#pod 'flutter_ffmpeg' + '/audio-lts', :path => File.join(symlink, 'ios')
#
#install! 'cocoapods', :disable_input_output_paths => true
``` 
in podfile And remove  ` flutter_ffmpeg: ^0.2.10` then error is exist
<img width="959" alt="iShot2020-08-25上午11 51 28" src="https://user-images.githubusercontent.com/26477346/91120952-5fe6d600-e6c9-11ea-9894-ee1955472f70.png">

**Comment by Larpoux** [comment]
Hi @Adherentman 

Your problem is because you have a dependency to flutter_ffmpeg. Flutter Sound 5.x does not need this dependency, and is incompatible with that.

Please look to [the migration guide](https://github.com/dooboolab/flutter_sound/blob/master/doc/migration_4.x.x.md#migration-from-3xx-to-4xx)

Please re-open this issue if this answer does not satisfy you

**Comment by MATTYGILO** [comment]
I'm having the same issue

**Comment by Lap214** [comment]
What is the result of "pod install" ?
