### ISSUE TITLE
[HELP] How to update title and artist of notification bar to lockscreen

### ISSUE THREAD

**Issue by SxzOtaku** [dooboolab/flutter_sound#444]
I need Help for :
Updating the title of music and name of the artist in notification bar to android lock screen, so instead of displaying "Music" and "Artist" in android lock screen it should be "One Winter's Night" and "Lazy Vibes"

- Using the API ?
5.1.1

![118550620_1413993098932034_1490395916602382183_n](https://user-images.githubusercontent.com/45994773/91781205-47783d80-ec2c-11ea-860d-204c276bb7b0.jpg)

![118380849_676774182930083_2169357626420860353_n](https://user-images.githubusercontent.com/45994773/91781219-4fd07880-ec2c-11ea-9b02-166292f1b926.jpg)

**Comment by Larpoux** [comment]
You specify the two fields "author" and "album" in the Track object that you provide in `startPlayer()`.

Remember that you session must be opened with `openSessionWithUI()`

**Comment by SxzOtaku** [comment]
@Larpoux that is what I did, the notification works, it displays the track title and track author but when it comes to android lock screen it just displays "Music" and "Artist" like the screenshots I provided earlier

**Comment by SxzOtaku** [comment]
I guess my problem is only in my phone. I tested my app on other phone and it displays the track title and track author in android lock screen
