### ISSUE TITLE
Android Two SoundPlayerUI on one page  

### ISSUE THREAD

**Issue by wanghuiwen1** [dooboolab/flutter_sound#450]
code
`Column(
                                        children: [
                                          Container(
                                            margin: EdgeInsets.only(
                                              bottom: ScreenUtil().setHeight(10),
                                            ),
                                            decoration: BoxDecoration(
                                              border: Border.all(
                                                color: Color.fromRGBO(214, 178, 128, 1),
                                                width: ScreenUtil().setHeight(1),
                                              ),
                                              borderRadius: BorderRadius.all(
                                                Radius.circular(5),
                                              ),
                                            ),
                                            child:SoundPlayerUI.fromTrack(
                                              Track(trackPath: "https://tongai.oss-cn-beijing.aliyuncs.com/code-upload/2020-06/28/16/65534fcfa04f432fb7408188d9a485c6.mp3"),
                                              showTitle: false,
                                              audioFocus: AudioFocus.requestFocusAndDuckOthers,
                                              textStyle: TextStyle(fontSize: 12,color: Color.fromRGBO(214, 178, 128, 1)),
                                              backgroundColor:Colors.white,
                                              sliderThemeData: SliderThemeData(
                                                trackHeight:1,
                                                activeTrackColor:Colors.lightGreenAccent,
                                                inactiveTrackColor:Colors.orange,
                                                disabledActiveTrackColor:Colors.limeAccent,
                                                disabledInactiveTrackColor:Colors.pinkAccent,
                                                activeTickMarkColor:Colors.tealAccent,
                                              ),
                                            ),
                                          ),
                                          Container(
                                            margin: EdgeInsets.only(
                                              bottom: ScreenUtil().setHeight(10),
                                            ),
                                            decoration: BoxDecoration(
                                              border: Border.all(
                                                color: Color.fromRGBO(214, 178, 128, 1),
                                                width: ScreenUtil().setHeight(1),
                                              ),
                                              borderRadius: BorderRadius.all(
                                                Radius.circular(5),
                                              ),
                                            ),
                                            child: SoundPlayerUI.fromTrack(
                                              Track(trackPath: "https://tongai.oss-cn-beijing.aliyuncs.com/code-upload/2020-06/28/16/65534fcfa04f432fb7408188d9a485c6.mp3"),
                                              showTitle: false,
                                              audioFocus: AudioFocus.requestFocusAndDuckOthers,
                                              textStyle: TextStyle(fontSize: 12,color: Color.fromRGBO(214, 178, 128, 1)),
                                              backgroundColor:Colors.white,
                                              sliderThemeData: SliderThemeData(
                                                trackHeight:1,
                                                activeTrackColor:Colors.lightGreenAccent,
                                                inactiveTrackColor:Colors.orange,
                                                disabledActiveTrackColor:Colors.limeAccent,
                                                disabledInactiveTrackColor:Colors.pinkAccent,
                                                activeTickMarkColor:Colors.tealAccent,
                                              ),
                                            ),
                                          )
                                        ],
                                      )`

error

Another exception was thrown: 'package:flutter/src/material/slider.dart': Failed assertion: line 174 pos 15: 'value >= min && value <= max': is not true.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building StreamBuilder<PlaybackDisposition>(dirty, state: _StreamBuilderBaseState<PlaybackDisposition, AsyncSnapshot<PlaybackDisposition>>#d1032):
'package:flutter/src/material/slider.dart': Failed assertion: line 174 pos 15: 'value >= min && value <= max': is not true.

The relevant error-causing widget was: 
  SoundPlayerUI file:///Users/huiwenwang/StudioProjects/study_manage/lib/course/course_detail.dart:235:65
When the exception was thrown, this was the stack: 
#2      new Slider (package:flutter/src/material/slider.dart:174:15)
#3      PlaybarSliderState.build.<anonymous closure> (package:flutter_sound/src/ui/slider.dart:66:22)
#4      StreamBuilder.build (package:flutter/src/widgets/async.dart:514:81)
#5      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:129:48)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/material/slider.dart': Failed assertion: line 174 pos 15: 'value >= min && value <= max': is not true.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/material/slider.dart': Failed assertion: line 174 pos 15: 'value >= min && value <= max': is not true.
The relevant error-causing widget was: 
  SoundPlayerUI file:///Users/huiwenwang/StudioProjects/study_manage/lib/course/course_detail.dart:235:65
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/material/slider.dart': Failed assertion: line 174 pos 15: 'value >= min && value <= max': is not true.

**Comment by Larpoux** [comment]
@bsutton : could you look to this issue ?
(you promised that you will do maintenance for the V5.x)

Thank you 😄

**Comment by Larpoux** [comment]
@wanghuiwen1 : your issue is not correctly filled : 
- no Flutter Sound Version
- no indication of the Device you use : SDK ?
- no logs

It is possible that this bug is fixed in recent releases, but this is hard to say, without knowing the version that you actually use, and without having your logs.

Please reopen this issue with all the needed informations.
