### ISSUE TITLE
[BUG] Compilation errorr

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#455]
## Flutter Sound Version : 

- **Released** or **Beta** version ? 
Released

- Version number ?
4.0.6

- **FULL** or **LITE** flavor ?
flutter_sound: ^4.0.6

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

$: flutter pub deps | grep flutter_sound
|-- flutter_sound 4.0.6
$: 

----------------------------------------------------------

## Severity

- Crash ?
No
- Result is not what expected ?
Yes
- Cannot build my App ?
YEs
- Minor issue ?
No. Major
--------------------------------------------------------

## Platforms you faced the error 

- iOS ?
Yes
- Android ?
No
- Both ?
No
- Emulator ? 
NA
- Real device ?
NA
----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

<img width="536" alt="Untitled" src="https://user-images.githubusercontent.com/6372373/93354622-d1b2cb00-f802-11ea-9930-6452df189bd3.png">
-----------------------------------------------------

**Describe the bug**

Could not compile the code on Xcode. but works fine with the command line 
Ex: 
flutter run --flavor <flavor1> -t lib/main_<flavor1>.dart

**To Reproduce**

**Expected behavior**
-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Version 4.0 needed to specify explicitly a dependency to FFmpeg. This was painful and Flutter Sound users had very often problems with that.

Version 5.0 (and now 6.0) does not need to specify this dependency any more. If you migrate to 5.0 or 6.0, read carefully the Migration notice.

Is there any reason you have not still migrate ?
