### ISSUE TITLE
Creating sound files where path has spaces

### ISSUE THREAD

**Issue by lordrocco** [dooboolab/flutter_sound#456]
I can create a path with spaces (like a folder called “My Cool Sounds”) and successfully record sounds and save them there using startRecorder(). But when I try to play back those same sound files with startPlayer(), it fails.

There is no problem with paths not containing spaces, but I don’t want to restrict my users from using spaces. Is there a way to make this work?

Thanks.

Console error info follows:

flutter: The player should be starting with this path: /Users/rocco/Library/Developer/CoreSimulator/Devices/4A3DA4DA-7491-4F5A-9B64-6BB4D7879E77/data/Containers/Data/Application/F2795F75-806A-4CB5-9DCC-000E808F4B6A/Documents/bingo dog/segment10001.aac
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: PlatformException(Audio Player, Play failure, null)
#0      FlutterSoundPlayer._startPlayer (package:flutter_sound/flutter_sound_player.dart:432:7)
<asynchronous suspension>
#1      FlutterSoundPlayer.startPlayer (package:flutter_sound/flutter_sound_player.dart:442:19)
<asynchronous suspension>
#2      _PersonalStudioState.beginPlayingCurrentSegment (package:personalaudiostudio/main.dart:400:28)
<asynchronous suspension>
#3      _PersonalStudioState.build.<anonymous closure>.<anonymous closure> (package:personalaudiostudio/main.dart:732:31)
#4      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#5      _PersonalStudioState.build.<anonymous closure> (package:personalaudiostudio/main.dart:715:25)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#8      GestureRecognizer.invok<…>

**Comment by Larpoux** [comment]
Your PR (Problem Report) is not correctly filled : 
- No Flutter Sound Version number
- No information of the kind of devices
- No logs

**Comment by Larpoux** [comment]
Please Reopen this issue with all the missing informations
