### ISSUE TITLE
[HELP] Audio Volume buttons on Android

### ISSUE THREAD

**Issue by tonypottera24** [dooboolab/flutter_sound#457]
When using android phones, we use the volume key (at the side of the phone) to change volumes.
Usually, when we press that key, it showed that we are changing the volume of "ring bell".
When watching youtube, it showed that we are changing the volume of "media".
When watching taking a phone call, it showed that we are changing the volume of "phone call".

However, when I use `flutter_sound 5.1.1` to record (`startRecorder`) or play sounds `startPlayer`, it always showed that I'm changing the volume of "phone call".

Device: Physical device, Samsung Galaxy S8

This issue happened when I was using `flutter_sound 3.x.x` and it was fixed in `4.x.x`.
I've tried to change `audioSource: AudioSource.microphone` but it doesn't works.
Also, the output voice came out from the speaker, not from the ear part, but still far lower than expected.
Anyone knows why this happened?

**Comment by Larpoux** [comment]
Yes Tony,
I am aware that there is something wrong, (at least on Android).
This is an important issue : is there anybody who can work on this PR (Problem Report) ?
(I am currently completely overbooked with several running tasks and I have no much spare time to work on Flutter Sound) 😞

**Comment by Mateis** [comment]
I have the same issue. In my case, it also leads to that I cannot change the volume of my flutter sound audio player, on my physical Android phone.
My friend on his Android _can_ change his _main_ volume to change volume.

It worked in version 1.7. It broke when I migrated to 5.1.1.

See my bug report here https://github.com/dooboolab/flutter_sound/issues/467

**Comment by Larpoux** [comment]
I cannot reproduce this bug any more on V 6.1.1

@tonypottera24 , @Mateis ,
Could you kindly verify that this bug is now fixed ?

Note, I use the following parameters in `openAudioSession()` : 
```dart
 await playerModule.openAudioSession(
          focus: AudioFocus.requestFocusAndKeepOthers,
          category: SessionCategory.playAndRecord,
          mode: SessionMode.modeDefault,
          device: AudioDevice.speaker);
```

**Comment by tonypottera24** [comment]
This works for me.

**Comment by Mateis** [comment]
Solved everything. Much love.
