### ISSUE TITLE
PCM 音频流（Stream( List<int>)格式）什么时候放出来，谢谢

### ISSUE THREAD

**Issue by zingwin** [dooboolab/flutter_sound#458]
PCM 音频流（Stream( List<int> )格式）什么时候放出来，谢谢

**Comment by Larpoux** [comment]
Version V6.0 is released.
With this version you can record PCM-LINEAR-16 to a Dart Stream or playback from a Dart Stream.
Probably this is the feature that you are requesting.

**Comment by zingwin** [comment]
> Version V6.0 is released.
> With this version you can record PCM-LINEAR-16 to a Dart Stream or playback from a Dart Stream.
> Probably this is the feature that you are requesting.

多谢！！！
