### ISSUE TITLE
Recorded Quality in Android pie

### ISSUE THREAD

**Issue by therichiekumar** [dooboolab/flutter_sound#46]
### Version of flutter_sound
1.3.1

### Platforms you faced the error (IOS or Android or both?)
Android (not tried on iOS)

### Expected behavior
Clear Recorded Sound

### Actual behavior
Only Noises are present

### Tested environment (Emulator? Real Device?)
Real device - Nokia 8.1

**Comment by pyclasses** [comment]
App work fine in **Mi Note 4** (Real Device)

**Comment by wyattbiker** [comment]
I am also having quality problems using flutter_sound. Both on Moto g5 and Emulator Nexus 5X API 27. Any ideas how this can be improved?

Volume is too low even though I set it to 1.0
