### ISSUE TITLE
[BUG] Android : minSdkVersion 18. 

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_sound#462]
6.0.1
Android : minSdkVersion 18 : 18 works fine for the player, but the recorder needs at least 24.

24 is really too recent. We must accept (at least) 21.

**Comment by felixjunghans** [comment]
Do you know why this problem occurs? I am successfully using Flutter Sound 5.x with minSDKVersion 21 for playback AND recording. So what has changed significantly from version 5 to 6?

**Comment by Larpoux** [comment]
Hi felix.
There is absolutely **NO CHANGES** between 5 and 6 for recording to files.
This minSDK problem is really a problem for me. I have no devices so old, and my emulator does not work correctely with SDK 21.

If you say that there is no problem in V5 with recording 21, this is good news. I am going fix (again) the function `isEncoderSupported` to accept SDK 21.

**Comment by felixjunghans** [comment]
The only problem I had in version 5, I have described [here](https://github.com/dooboolab/flutter_sound/issues/400) and also described the [fix](https://github.com/dooboolab/flutter_sound/issues/400#issuecomment-657738038) directly. Otherwise I had absolutely no problems with version 5 and old Android devices.

**Comment by felixjunghans** [comment]
But I will test version 6 on old devices next week and give you feedback then.

**Comment by Larpoux** [comment]
OK Felix, I am preparing a 6.0.2. Probably this evening.

**Comment by Larpoux** [comment]
Felix : 
- SDK 23 is OK for recording, on an emulator
- SDK 22 is NOT OK, because the prepare() fails

I removed the recorder limitation to SDK 23 in [my fork](https://github.com/Canardoux/flauto), but I would prefer if someone check on a real device before releasing a new version of Flutter Sound.

**Comment by felixjunghans** [comment]
Ok i can confirm that recording works on Samsung S5 neo (Android 6). So sdkVersion 23 is fine. I try to find an Android 5 Device to Test with. But for now minSDKVersion 23 should be fine.

**Comment by Larpoux** [comment]
Please re-open this issue if still problems

**Comment by akshg05** [comment]
I am unable to play my recording in Emulator. i have tried minSdk 23.
Playing works fine -> I can hear the audio properly.
Recording -> Throws no errors while recording.
Playing the recording -> When I try playing the recording it plays it with the duration but I can hear nothing..literally nothing.
I am using the default codecs.
