### ISSUE TITLE
Is there any option to convert listen from a stream to an audio file? (version 6.7)

### ISSUE THREAD

**Issue by Lix-ai** [dooboolab/flutter_sound#466]
Hi All :),
Is there any option to convert listen from a stream to an audio file?

Probably using a subscriber and convert the listening to a audio file.

Thanks in advance!!! =]

**Comment by Larpoux** [comment]
What kind is your audio stream ?

**Comment by Larpoux** [comment]
On Flutter Sound V6, it is possible to play `RAW-PCM Linear 16` from a Dart Stream.
Is it what you are looking for ?

**Comment by Lix-ai** [comment]
Thanks for the answer,
I have musical notes for example 'soundfonts sf2' types, which executed in a stream every X time.
And i would like to record the stream and create it as an audio file ====> Recording it.

**Comment by Larpoux** [comment]
Maybe it would be nice to implement a new functionality in Flutter Sound : 

The possibility to download an audio stream (which protocol ?), instead of playing it.
I think that several people already asked for this feature.
I will put this task somewhere in the stack. 
Please keep this issue open.

**Comment by Larpoux** [comment]
I added this task in [this project](https://github.com/dooboolab/flutter_sound/projects/3)

**Comment by Lix-ai** [comment]
=]

**Comment by Larpoux** [comment]
Duplicate [#504]
