### ISSUE TITLE
[HELP] Streaming as a service

### ISSUE THREAD

**Issue by dweberlj** [dooboolab/flutter_sound#472]
## Microphone recorder streaming as a service

Hello,

I would like to capture audio and stream it as a service instead of the existing example which implements a state widget.  Any thoughts or suggestions would be greatly appreciated.

Thanks.

**Comment by Larpoux** [comment]
Yes, this is an area where I want to work soon.
This is important.
But I do not have much time actually 👎 

Please keep this issue Open

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems.
I think that Flutter Sound is now able to record streams in the back ground.

Probably it duplicates [#525]
