### ISSUE TITLE
[Enhancement] SetSubscriptionDuration() should be deprecated : Too many problems (Version 6.5)

### ISSUE THREAD

**Issue by wang-zeqi** [dooboolab/flutter_sound#473]
IOS can monitor the progress normally and has a return value. Android has no return value. What is the reason?
version:6.0.1

**Comment by Larpoux** [comment]
Please, could you explain more ?
Where is there a return value ?
How do you monitor the progress ?

**Comment by romain-bajoit-iot-d** [comment]
I possibily have the same issue. 
This code is in a `try` block that does not catch any error and the audio is playing as expected.
However it **never** prints any event, not even `null` on Android but works perfectly on IOS.

```
await playerModule.startPlayer(
        codec: Codec.pcm16WAV,
        fromURI: audioMessage.audioLocation,
);

playerModule.onProgress.listen((event) {
        print('$event'); 
});
```

**Comment by Larpoux** [comment]
When do you call `setSubscriptionDuration()` ? Before or after `startPlayer()` ?
What value for the `setSubscriptionDuration()` parameter ?

**Comment by romain-bajoit-iot-d** [comment]
Same as @CountPablo, the setSubscriptionDuration was not properly set, did not realize it as it was working on IOS.
Thanks

**Comment by Larpoux** [comment]
Yes, this is not OK that it works on iOS and not Android. It should be same on both devices.
I will fix that.
Also, I am considering let the verb `setSubscriptionDuration()` deprecated.
I think it will be less error prone for the developer if it is a parameter for `StartPlayer()` and not a separated verb.

And also the documentation must be accurate. I think the actual documentation is incorrect.

Please keep this issue open.

**Comment by tonypottera24** [comment]
setSubscriptionDuration not working on my physical iPhone now, I'm using `flutter_sound: ^6.1.4`

**Comment by Larpoux** [comment]
Duplicate [#493]
