### ISSUE TITLE
[BUG] flutter_sound ^4.0.7 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by kmusham** [dooboolab/flutter_sound#474]
## Flutter Sound Version : 
4.0.7
- **Released** or **Beta** version ?
Released
- Version number ? 4.0.7

- **FULL** or **LITE** flavor ? FULL

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

----------------------------------------------------------

## Severity

- Crash ?

- Result is not what expected ?

- Cannot build my App ? Yes,

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?

- Both ? YEs

- Emulator ? 

- Real device ?

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

flutter pub get throws the following error. but if I change the dependency to 4.0.6, it works fine.

flutter_sound ^4.0.7 which doesn't match any versions, version solving failed.
 

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
I need the result of : 
```sh
$ flutter pub deps | grep flutter_sound
```

**Comment by Larpoux** [comment]
What gives `flutter pub get` ?

**Comment by kmusham** [comment]
> I need the result of :
> 
> ```shell
> $ flutter pub deps | grep flutter_sound
> ```

$: flutter pub deps | grep flutter_sound
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
$: 

$: flutter pub get
Because mobileedge depends on flutter_sound ^4.0.7 which doesn't match any versions, version solving failed.
Running "flutter pub get" in MobileEdge...                              
pub get failed (1; Because mobileedge depends on flutter_sound ^4.0.7 which doesn't match any versions, version solving failed.)

**Comment by Larpoux** [comment]
Could you post your pubspec.yaml ?

**Comment by kmusham** [comment]
`version: 63.00.00+630000
environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  #firebase_analytics: ^2.1.1
  intl: ^0.16.1
  flutter_masked_text: ^0.8.0
  url_launcher: ^5.4.11
  signature: ^3.2.0
  package_info: ^0.4.1
  encrypt: ^4.0.2
  uuid: ^2.2.0
  device_info: ^0.4.2+6
  version: ^1.0.3
  launch_review: ^2.0.0
  connectivity: ^0.4.9
  auto_orientation: ^1.0.6

  flutter_background_geolocation: ^1.10.0
  flutter_sound: ^4.0.6

  logging: ^0.11.4
  datetime_picker_formfield: ^1.0.0
  fluttertoast: ^7.0.2
  tree_view: ^0.0.5
  property_change_notifier: ^0.2.0
  async: ^2.4.2
  progress_dialog: ^1.2.4
  line_awesome_flutter: ^1.0.1
  latlong: ^0.6.1
`

**Comment by Larpoux** [comment]
I do not understand what is happening.
Just try : 
```
  flutter_sound: ^5.1.0
```
or
```
  flutter_sound: ^6.1.0
```
to see if this is a problem specific to ^4.0.6

**Comment by Larpoux** [comment]
Be careful that there is two spaces before the dependency

**Comment by kmusham** [comment]
I just tried both versions you mentioned above (copy pasted into my pubspec.yml). see the output below. 


```
$: flutter pub deps | grep flutter_sound
|-- flutter_sound 5.1.1
$: 
```


```
$: flutter pub deps | grep flutter_sound
|-- flutter_sound 6.1.2
|   |-- flutter_sound_platform_interface 1.0.0
$: 
```

**Comment by Larpoux** [comment]
So it works fine with 6.1 or 5.1.

Do you really need version 4.0 ?
If yes, you can try : 
```
  flutter_sound: ^4.0.0
```
and see which version it will pick. (probably 4.0.8)

**Comment by kmusham** [comment]
flutter_sound: ^4.0.0



`$: flutter pub deps | grep flutter_sound
|-- flutter_sound 4.0.6
$: `

**Comment by Larpoux** [comment]
GOOD 👍 

If you really need version 4.0, go ahead with 4.0.6

But I do not understand why you cannot get 4.0.7 or 4.0.8 🙄
