### ISSUE TITLE
Expose Strings in SoundRecorderUI

### ISSUE THREAD

**Issue by hectorAguero** [dooboolab/flutter_sound#475]
**Problem**
I cant translate these strings from the UI widgets to my language(spanish btw)
`Text(_isPaused ? 'Recorder is paused' : _isRecording ? 'Recorder is recording' : 'Recorder is stopped'),`

Line 218 from here https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/lib/src/ui/sound_recorder_ui.dart

**Solution**
Expose the values

**Alternatives**
Accept multiple translations with the use of intl package.

**Image from the flutter_sound readme with the strings**
https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/example/lib/widgetUI/widgetUI.png

**Comment by Larpoux** [comment]
Yes @hectorAguero , you are perfectely right : 
This is not correct to have English inside the WidgetUI. I consider that as a Bug 👎 

This is my fault. I am going to fix that.

**Comment by Larpoux** [comment]
Also, I think that this WidgetUI should show the current elapse time during recording (as we do in the Demo example).

**Comment by hectorAguero** [comment]
Thanks, also check the 'secs' string in duration widget https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/lib/src/util/format.dart

**Comment by Larpoux** [comment]
What do you think is better for sec. : 
- 's' (which is the normalized symbol for seconds in SI (System International of mesures)
- '  "  '  (which is often used for seconds)

**Comment by hectorAguero** [comment]
Wll at least 's' works for spanish, so i prefer that option.

**Comment by Larpoux** [comment]
#498 : this is a fix kindly offered by @EslamHanafy .

It will be merged in Version 6.4
