### ISSUE TITLE
Link to FlutterSoundUI is broken

### ISSUE THREAD

**Issue by CliffBramlett** [dooboolab/flutter_sound#477]
The link to FlutterSoundUI on https://pub.dev/packages/flutter_sound is broken. The link points to https://github.com/dooboolab/flutter_sound/blob/master/doc/ui_widget.md which GitHub reports as an error 404.
Edit: The same is true for all other links in that Flutter Sound API section.

**Comment by Larpoux** [comment]
Oh! 👎 
**BAD** !

**Comment by Larpoux** [comment]
Fixed in FS 6.1.3
