### ISSUE TITLE
Background audio

### ISSUE THREAD

**Issue by therichiekumar** [dooboolab/flutter_sound#48]
### Version of flutter_sound
1.3.1
### Platforms you faced the error (IOS or Android or both?)
Real device - Mi Note 4

### Expected behavior
Audio stop when app closes

### Actual behavior
Audio is still playing in background

### Tested environment (Emulator? Real Device?)
Real device

**Comment by BND10706** [comment]
I have managed to get it to play in the background. But I have no Media Controls
