### ISSUE TITLE
[BUG] onProgress.listen(e) not working on Android

### ISSUE THREAD

**Issue by CountPablo** [dooboolab/flutter_sound#482]
## Flutter Sound Version : flutter_sound 6.1.4

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important):

```
|-- flutter_sound 6.1.4
|   |-- flutter_sound_platform_interface 1.0.0
```

----------------------------------------------------------

## Severity

onProgress.listen(e) never being triggered

--------------------------------------------------------

## Platforms you faced the error 

Android Emulator (Pixel_2_API_29)

----------------------------------------------

**Describe the bug**
When setting the value of the StreamSubscription to listen to the progress of the player. The listener never seems to be called. This only happened when I switched from version **4.0.6** to **6.1.4** which required me to no longer use ```onPlayerStateChanged``` but to replace it with ```onProgress```.

**To Reproduce**
```
playerSubscription = playerModule.onProgress.listen((event) {
        print('$event'); 
});
```
This isn't printing the event.

## Additional context**
I saw this was already raised as an issue here https://github.com/dooboolab/flutter_sound/issues/473 but seemed to lack information so I decided to make this issue.

**Comment by Larpoux** [comment]
When do you call `setSubscriptionDuration()` ? Before or after `startPlayer()` ?
What value for the `setSubscriptionDuration()` parameter ?

**Comment by CountPablo** [comment]
I was not setting it at all.
I just tried setting it before calling startPlayer() with a value of 10 ms as the parameter and it's working! Thank you!

**Comment by Larpoux** [comment]
This is not OK that it works on iOS and not Android when `setSubscription()` is not called. It should be same on both devices.
I will fix that.
Also, I am considering let the verb `setSubscriptionDuration()` deprecated.
I think it will be less error prone for the developer if it is a parameter for `StartPlayer()` and not a separated verb.

And also the documentation must be accurate. I think the actual documentation is incorrect.

**Comment by Maikol1804** [comment]
I spent some hours trying to find an error, and I just needed `setSubscriptionDuration` after opening my recording. Thanks!

**Comment by Larpoux** [comment]
This is totally incredible how many Flutter Sound users have issues with this very simple functionality.
There is certainly something which must be done inside Flutter Sound to alleviate this,
but I have not yet figured what to do.

Good luck with Flutter Sound 😃

**Comment by Andrushka1012** [comment]
Hi, [Larpoux](https://github.com/Larpoux), thanks for what you doing. Im also got that problem, cause I didn't get it from docs at the first point. My bad. But I think there is a lot of users like me.

Think you could fix it by setting some default value in case it is not settled with setSubscriptionDuration. In that case, it will eliminate this problem :)
