### ISSUE TITLE
I want to use flutter sound but I get an error Exception has occurred. _notOpen

### ISSUE THREAD

**Issue by leviis-dot** [dooboolab/flutter_sound#485]
void _play() async {
    FlutterSoundPlayer myPlayer = FlutterSoundPlayer();
    final fileUri = "https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3";
    Track track = Track( codec: Codec.opusOGG, trackPath: fileUri, trackAuthor: '3 Inches of Blood', trackTitle: 'Axes of Evil', albumArtAsset: albumArt )
    Duration d = await myPlayer.startPlayerFromTrack
    (
      track,
      whenFinished: ()
      {
                print( 'I hope you enjoyed listening to this song' );
      },
    );
  }
**console:**

I/flutter (13152): FS:---> startPlayer
I/flutter (13152): Audio session is not open

**Comment by Larpoux** [comment]
Before using ```startPlayer()``` you must open an audio session (```openAudioSession(...)```)

**Comment by leviis-dot** [comment]
how I should do it. excuse me I'm starting!

**Comment by Larpoux** [comment]
And do not use `startPlayer()`  before the Future returned by 'openSession()` **is completed**.
(use `await` or set a flag with the `then()` instruction)

This is simple. You should be able to do that.

**Comment by leviis-dot** [comment]
I am a beginner

**Comment by Larpoux** [comment]
No problem. Everybody was a beginner one time.

**Comment by Larpoux** [comment]
I know that someone must write a very simple example for beginners.
But time is the probem. We have not enough time ...

**Comment by leviis-dot** [comment]
OK thanks a lot

**Comment by Larpoux** [comment]
if what you want to do is just 
- create a player
- open an audio session
- play Axe of Evil (this song makes me crazy! 😄  )
- close the audio session

all this inside the same async function, this is very simple : 
just add ```await myPlayer.openSession()``` before your `startPlayer()`

If, later, you need to separate the `startPlayer()` from the Audio Session opening, you will have to protect you of starting playing before the end of `openSession()` : 
```
bool inited = false;
...
myPlayer.openSession().then( (){ inited = true; });

...
future<void> fnplay() async
{
     if (inited)
    {
         await myPlayer.startPlayer(...);
    }
}

**Comment by leviis-dot** [comment]
this gives me a second error again PlatformException (PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Must be initialized With UI, null))

**Comment by Larpoux** [comment]
Sorry, I forgot to tell you that you must specify the parameter `withUI: true`.
Please look to the API documentation. This documentation is not perfect, but better than nothing.
Someone should work on this doc...

**Comment by Larpoux** [comment]
https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/player.md#openaudiosession-and-closeaudiosession

**Comment by leviis-dot** [comment]
```
  void _play() async {
    await myPlayer.openAudioSession(withUI: true);

    final fileUri = "https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3";
    Track track = Track( codec: Codec.opusOGG, trackPath: fileUri, trackAuthor: '3 Inches of Blood', trackTitle: 'Axes of Evil',);
    Duration d = await myPlayer.startPlayerFromTrack
    (
      track,
      whenFinished: ()
      {
        print( 'I hope you enjoyed listening to this song' );
      },
    );
  }
```
but don't play.

I/flutter ( 1872): FS:---> openAudioSession

**Comment by leviis-dot** [comment]
please i can have a full example i'm really exhausted.

**Comment by leviis-dot** [comment]
Cool music finally I think I should listen to Ax of Evil. thanks again
