### ISSUE TITLE
[BUG] Remote OPUS File/Stream on iOS

### ISSUE THREAD

**Issue by vernalclareai** [dooboolab/flutter_sound#486]
## Flutter Sound Version : 
![flutter_sound_layoutissue](https://user-images.githubusercontent.com/61595318/96535053-99038700-12c3-11eb-8100-1c868a6052c9.png)

- **Released** or **Beta** version ?

- Version number ?
 flutter_sound 6.2.0+1
- **FULL** or **LITE** flavor ?
Example UI
- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

Dart SDK 2.9.1
Flutter SDK 1.20.2
example 1.0.0+1
|-- cupertino_icons 0.1.3
|-- flutter 0.0.0
|   |-- characters 1.0.0
|   |-- collection 1.14.13
|   |-- meta 1.1.8
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.2.0
|   |   '-- collection...
|   '-- vector_math 2.0.8
|-- flutter_sound 6.2.0+1
|   |-- flutter...
|   |-- flutter_sound_platform_interface 2.0.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 1.0.3
|   |       '-- meta...
|   |-- flutter_spinkit 4.1.2+1
|   |   '-- flutter...
|   |-- intl...
|   |-- logger 0.7.0+2
|   |-- path...
|   |-- path_provider...
|   |-- provider 4.3.2+2
|   |   |-- collection...
|   |   |-- flutter...
|   |   '-- nested 0.0.4
|   |       '-- flutter...
|   |-- recase 3.0.0
|   |-- synchronized 2.2.0+2
|   '-- uuid 2.2.2
|       |-- convert 2.1.1
|       |   |-- charcode...
|       |   '-- typed_data...
|       '-- crypto 2.1.5
|           |-- collection...
|           |-- convert...
|           '-- typed_data...
|-- flutter_test 0.0.0
|   |-- async 2.4.2
|   |   '-- collection...
|   |-- boolean_selector 2.0.0
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- charcode 1.1.3
|   |-- clock 1.0.1
|   |   '-- meta...
|   |-- collection...
|   |-- fake_async 1.1.0
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.8
|   |   '-- stack_trace...
|   |-- meta...
|   |-- path...
|   |-- source_span 1.7.0
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.9.5
|   |   '-- path...
|   |-- stream_channel 2.0.0
|   |   '-- async...
|   |-- string_scanner 1.0.5
|   |   |-- charcode...
|   |   |-- meta...
|   |   '-- source_span...
|   |-- term_glyph 1.1.0
|   |-- test_api 0.2.17
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- typed_data...
|   '-- vector_math...
|-- intl 0.16.1
|   '-- path...
|-- path 1.7.0
|-- path_provider 1.6.21
|   |-- flutter...
|   |-- path_provider_linux 0.0.1+2
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   '-- xdg_directories 0.1.0
|   |       |-- flutter...
|   |       |-- path...
|   |       '-- process 3.0.13
|   |           |-- file 5.2.1
|   |           |   |-- intl...
|   |           |   |-- meta...
|   |           |   '-- path...
|   |           |-- intl...
|   |           |-- meta...
|   |           |-- path...
|   |           '-- platform...
|   |-- path_provider_macos 0.0.4+4
|   |   '-- flutter...
|   |-- path_provider_platform_interface 1.0.3
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- platform 2.2.1
|   |   '-- plugin_platform_interface...
|   '-- path_provider_windows 0.0.4+1
|       |-- ffi 0.1.3
|       |-- flutter...
|       |-- meta...
|       |-- path...
|       |-- path_provider_platform_interface...
|       '-- win32 1.7.3
|           '-- ffi...
'-- permission_handler 5.0.1+1
    |-- flutter...
    |-- meta...
    '-- permission_handler_platform_interface 2.0.1
        |-- flutter...
        |-- meta...
        '-- plugin_platform_interface...

----------------------------------------------------------

## Severity

- Crash ?

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ? Tested on Android

- Both ?

- Emulator ? 

- Real device ?

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

## Additional context**

Audio URL: 
https://whatsapp-inbox-server.clare.ai/api/file/showFile?fileName=data/audios/e3f16eb2-10c3-45c9-b0fa-900c94cbe805.opus&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxMWI5YjQ3Zi1jMzBjLTRlZDMtYTFhNy1iNmYxNzRkMWQ1NTYiLCJ1bmlxdWVfbmFtZSI6InZlcm5hbEBjbGFyZS5haSIsIm5hbWVpZCI6InZlcm5hbEBjbGFyZS5haSIsImVtYWlsIjoidmVybmFsQGNsYXJlLmFpIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRVhURVJOQUxfQURNSU5JU1RSQVRPUiIsImV4cCI6MjUzNDAyMzAwODAwLCJpc3MiOiJDbGFyZV9BSSIsImF1ZCI6IkNsYXJlX0FJIn0.yXVZ3n_lYYvJ1rGyF2mVh-80HuS0EEp7sQepxn9rGcY

**Comment by vernalclareai** [comment]
Just tested on ios too.
It has the same issue.

**Comment by vernalclareai** [comment]
Audio file length is 14s for above remote file.
but it is playing for only 3s in iOS.
Any idea?
Thansk.

**Comment by Larpoux** [comment]
I @vernalclareai .
Sorry to hear that you encounter problem with remote OPUS
I will look to your issue next week.

**Comment by vernalclareai** [comment]
Thanks.

**Comment by vernalclareai** [comment]
Okay, fine.
It seems cutting the audio while converting on iOS using FFMPEG.
Thanks.

**Comment by Larpoux** [comment]
I am not sure that remote OPUS is correctely implemented for iOS (call to ffmpeg ...).
But it should work on Android ...
I will look to that

**Comment by vernalclareai** [comment]
yes, it is working correctly on Android.

**Comment by Larpoux** [comment]
OK, for iOS I see the problem : the call to ffmpeg is not correctely called for remote file.
I am going to fix that, probably next week.
(Actually I am re-achitecturing the code, to isolate what is OS dependant and what is Flutter dependant.
It is a major development and I need to be very cautiously so I will not have regressions and break erverything ;-) )

Next week (or maybe sooner ...)

**Comment by Larpoux** [comment]
@vernalclareai : 

it seems that your URL is not an OPUS file but an OPUS stream.
Is that right ?

**Comment by vernalclareai** [comment]
yes, it seems so

**Comment by vernalclareai** [comment]
@Larpoux , I could resolve my issue to play the remote file by downloading the remote file & playing locally.

**Comment by vernalclareai** [comment]
but I think the crash layout issue should be fixed in your side for further.

**Comment by Larpoux** [comment]
So, there is two problems : 
- The bug where we call FFmpeg on iOS should not be called for a remote file/stream (this is your crash)
- On ioS, the playback of a stream is not implemented

The second point needs some work, and I do not have much time actually.
But those two points definitely need to be fixed.
I am glad that you are not blocked any more, but please keep this issue open.

**Comment by vernalclareai** [comment]
yes, for now, I can use your lib by using the local file.
Thanks for your share.

**Comment by Larpoux** [comment]
Please -re-open this issue if you have still problems

**Comment by vernalclareai** [comment]
yeah, I solved the problem by playing the remote file after downloading.
thanks.
