### ISSUE TITLE
flutterSoundPlayer.onProgress.listen((e) { ... }) is not coming to action

### ISSUE THREAD

**Issue by suvankar-witbybit** [dooboolab/flutter_sound#488]
## Flutter Sound Version : ^6.2.0+1

- **Released**  

-  ^6.2.0+1

-  |-- flutter_sound 6.2.0+1
    |   |-- flutter_sound_platform_interface 2.0.0

----------------------------------------------------------

## Severity

- Result is not what expected ?

--------------------------------------------------------

## Platforms you faced the error 

- Android 

- Real device 

---------------------------------------------------------

**flutterSoundPlayer.onProgress.listen((e) {**
     // the codes here is not coming to action...
**});**

**Comment by Larpoux** [comment]
Did you call `setSubscriptionDuration()` before `startPlayer()` or `startRecorder()` ?

[See this issue](https://github.com/dooboolab/flutter_sound/issues/473)

**Comment by Larpoux** [comment]
No the default is 0 (zero) which means : "No subscription".

The documentation is incorrect.

**Comment by suvankar-witbybit** [comment]
Okay then , when should I call the **setSubscriptionDuration()** ?

**Comment by Larpoux** [comment]
Yes, you should ... (Until this terrible function will be deprecated, soon ;-) ).

By the way, I am currently releasing 6.3
During one hour or two, `flutter_sound: ^6.0`  will not be available.
Sorry for the desagrement.

**Comment by suvankar-witbybit** [comment]
wow, that is great...

**Comment by Larpoux** [comment]
OK, Flutter Sound 6.3 is released.

At first see, it works fine on Android and iOS.
Please tell me if you have problems with building your App : this version is a major redesign of the architecture.
I really hope that everything OK.

**Comment by Necrometal** [comment]
Hi I'm using version 8.1.4 and the action in FlutterSoundPlayer.onProgress.listen doesn't coming; but on the FlutterSoundRecorder the onProgress.listen work proprely.

**Comment by mhstoller** [comment]
> Hi I'm using version 8.1.4 and the action in FlutterSoundPlayer.onProgress.listen doesn't coming; but on the FlutterSoundRecorder the onProgress.listen work proprely.
> I'm on android device.

Please share the code you are using. You have to call `setSubscriptionDuration` before listening to onProgress

**Comment by Necrometal** [comment]
> > Hi I'm using version 8.1.4 and the action in FlutterSoundPlayer.onProgress.listen doesn't coming; but on the FlutterSoundRecorder the onProgress.listen work proprely.
> > I'm on android device.
> 
> Please share the code you are using. You have to call `setSubscriptionDuration` before listening to onProgress

i used this on initState as the doc said
`_myPlayer.openAudioSession().then((value) {
        setState(() {
            _mPlayerIsInited = true;
        });
  });
_myRecorder.openAudioSession().then((value) {
    setState(() {
        _mRecorderIsInited = true;
    });
});`
and when i press on button to record i used this :
`await _myRecorder.startRecorder(
    toFile: path_directory + '/test.aac',
    codec: Codec.aacADTS,
);
_myRecorder.onProgress.listen((e) {
    if (e != null) {
        DateTime date = new DateTime.fromMillisecondsSinceEpoch(e.duration.inMilliseconds);
        String txt = DateFormat('mm:ss:S', 'en_US').format(date);
        this.setState(() {
            record_timer = txt.toString();
        });
    }
});`

This work well and on playing the recorded audio i used this below (same schema as the record)
`await _myPlayer.startPlayer(
            fromURI: path_directory + '/test.aac',
            codec: Codec.aacADTS,
            whenFinished: (){
                stopPlayer();
            },
        );
        
        _myPlayer.onProgress.listen((e) {
            if (e != null) {
                DateTime date = new DateTime.fromMillisecondsSinceEpoch(e.duration.inMilliseconds);
                String txt = DateFormat('mm:ss:S', 'en_US').format(date);
                this.setState(() {
                    record_timer = txt.toString();
                });
            }
        });`
But this one didn't work

If needed to set setSubscriptionDuration , where to put that one?

**Comment by mhstoller** [comment]
Just call `await _player.setSubscriptionDuration(Duration(milliseconds: 100));` before listening to the onProgress stream

**Comment by Necrometal** [comment]
> Just call `await _player.setSubscriptionDuration(Duration(milliseconds: 100));` before listening to the onProgress stream

ok i'll try

**Comment by Necrometal** [comment]
> Just call `await _player.setSubscriptionDuration(Duration(milliseconds: 100));` before listening to the onProgress stream

as you said, i tried to put the setSubscrptionDuration before onProgress but it doesn't work

`await _myPlayer.startPlayer(
            fromURI: path_directory + '/test.aac',
            codec: Codec.aacADTS,
            whenFinished: (){
                stopPlayer();
            },
        );
        await _myPlayer.setSubscriptionDuration(Duration(milliseconds: 100));
        _myPlayer.onProgress.listen((e) {
            if (e != null) {
                DateTime date = new DateTime.fromMillisecondsSinceEpoch(e.duration.inMilliseconds);
                String txt = DateFormat('mm:ss:S', 'en_US').format(date);
                this.setState(() {
                    record_timer = txt.toString();
                });
            }
        });`

**Comment by Necrometal** [comment]
ah it work now :) ,
