### ISSUE TITLE
 LGPL-3.0 licenses and MIT licenses [HELP]

### ISSUE THREAD

**Issue by razzo04** [dooboolab/flutter_sound#496]
I would like to know if i can use this library as a dependency (so add it in the file pubspec.yaml) for open source project than use a MIT licensa. Searching the web seems to me to have understood that the LGPL-3.0 licenses admit the possibility to use them in other projects with different licenses as long as the library is not modified. To be sure I wanted to ask, thanks in advance for the answer.

**Comment by Larpoux** [comment]
There is absolutely no problem to use a LGPL library (like Flutter Sound) in a MIT project.
You can even (shame on you 👎 ) use a LGPL inside a proprietary/private project !

If you do modifications in part of Flutter Sound **YOU MUST PUBLISH YOUR MODIFICATIONS under the LGPL License**
But you will neverr have to change the license of your project

**Comment by razzo04** [comment]
Thank you for your answer.
