### ISSUE TITLE
[BUG] Can't build app with versions above 6.1.2 (excluding 6.1.2)

### ISSUE THREAD

**Issue by CountPablo** [dooboolab/flutter_sound#499]
## Flutter Sound Version : 
Full, version 6.3.0+4 (happens on any version after 6.1.2)

- Result of the command **"flutter pub deps | grep flutter_sound"**
```
|-- flutter_sound 6.3.0+4
|   |-- flutter_sound_platform_interface 6.3.0+4
```
----------------------------------------------------------

## Severity

- Cannot build my App

--------------------------------------------------------

## Platforms you faced the error 

- Android Emulator and Android device

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib\main.dart:1
[Fatal Error] ucrop-2.2.6.pom:3:3: The markup in the document preceding the root element must be well-formed.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://bintray.com/larpoux/CanardouxMaven/com/google/android/gms/play-services-location/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 3; The markup in the document preceding the root element must be well-formed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

-----------------------------------------------------

**Describe the bug**

After upgrading several packages I was getting this error where my app couldn't even build. 

I recognised @Larpoux username in the link in the log so I tried building without flutter_sound and it worked, I then tried with older versions of the package until it worked. 

The newest version of flutter_sound that would still let my app build was **version 6.1.2**

**Comment by Larpoux** [comment]
It seems that you have something bad in your build.gradle file.
probably around `com.google.android.gms:play-services-location`

You can try a 
```
flutter pub get --verbose
```
and post the result.

You can also do in the Android directory : 
```
./gradlew assemble
```
and post the result

**Comment by Larpoux** [comment]
Please post `pubspec.yaml`  and  `build.gradle`

**Comment by CountPablo** [comment]
> It seems that you have something bad in your build.gradle file.
> probably around `com.google.android.gms:play-services-location`
> 
> You can try a
> 
> ```
> flutter pub get --verbose
> ```
> 
> and post the result.
> 
> You can also do in the Android directory :
> 
> ```
> ./gradlew assemble
> ```
> 
> and post the result

The output of ```flutter pub get --verbose``` is over 3000 lines long. Is there any part in particular you would like me to post or do you need it all?

**Comment by Larpoux** [comment]
> Please post `pubspec.yaml` and `build.gradle`

Just that, for now

**Comment by CountPablo** [comment]
pubspec.yaml
```
name: project
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  
  cached_network_image: ^2.0.0
  connectivity: ^2.0.0
  dio: ^3.0.9
  draggable_scrollbar: any
  flutter_cache_manager: any
  flutter_google_places: any
  flutter_markdown: any
  flutter_sound: ^6.3.0+4
  flutter_sticky_header: any
  geocoding: ^1.0.4+1
  geolocator: any
  google_maps_flutter: any
  image_cropper: ^1.3.1
  image_picker: any
  intl: ^0.16.1
  keyboard_visibility: any
  location: any
  provider: ^4.3.2+2
  share: any
  shared_preferences: any
  system_setting: any
  url_launcher: ^5.7.8
  validators: any
  video_player: ^0.11.1+2

dev_dependencies:
  build_runner: any
  image_test_utils: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  [assets and fonts here]
  
```

**Comment by Larpoux** [comment]
what about app/build.gradle ?

**Comment by CountPablo** [comment]
build.gradle (android\app):
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId [application id]
        minSdkVersion 18
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.google.android.gms:play-services-location:17.1.0"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
```

**Comment by CountPablo** [comment]
I added the line ```implementation "com.google.android.gms:play-services-location:17.1.0"``` in ```app/build.gradle``` trying to fix this issue yesterday but it didn't work

**Comment by Larpoux** [comment]
Yes, it seems that it is the source of the error

> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
>    > Could not resolve com.google.android.gms:play-services-location:16.+.
>      Required by:
>          project :app > project :location
>       > Failed to list versions for com.google.android.gms:play-services-location.

**Comment by Larpoux** [comment]
What do you have in -your-project-/build.gradle  (not the one in app directory ?

**Comment by CountPablo** [comment]
build.gradle (non /app one):
```
buildscript {
    ext.kotlin_version = '1.3.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by Larpoux** [comment]
I am sorry, I do not see any error ...
It could be anything : with Flutter Sound or not...

I am stuck

**Comment by CountPablo** [comment]
Ah, well thanks for trying and please let me know if you think of anything else. I'll stay on version 6.1.2 for now

**Comment by Larpoux** [comment]
Hi @CountPablo 

Could you try 6.3.1  ?

J'espere que cette fois c'est mieux ;-)

**Comment by CountPablo** [comment]
Thanks for updating! Just did, I got the same error. J'ai vraiment cru que ça allait marcher :/

**Comment by Larpoux** [comment]
Dommage.
Je vais reflechir un peu plus a ton probleme, cher cousin americain.

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems

**Comment by ChanakaWeerasinghe** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Connect to dl.google.com:443 [dl.google.com/203.208.41.33] failed: connect timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s
Exception: Gradle task assembleDebug failed with exit code 1
