### ISSUE TITLE
feature request: pausing recording and set playback speed

### ISSUE THREAD

**Issue by hereisderek** [dooboolab/flutter_sound#5]
as I understand, ios and android starting with api26 support pausing recording. 
on android before api26 you can still manually merge pieces together.

[link](https://stackoverflow.com/questions/21900792/how-to-pause-and-resume-audio-recording-in-android)

as for playback speed, it's just a nice thing to have.

also I'm quite curious about the background play, as far as i know, at least on android, most app uses notification area as a music control panel to keep the app alive when in background. do we have something like this built-in or we need to use some first/third party plugin for this?

thanks

**Comment by dooboolab** [comment]
@1and1get2 
Firstly, this plugin supports background playing as default. I've noted that in [medium](https://medium.com/flutterpub/flutter-sound-plugin-audio-recorder-player-e5a455a8beaf). For ios, you just have to set `remote-notification` on.
Also, currently, I don't have plan to support `merging` recording. However, if you give me a `PR` I'll merge it.

**Comment by subhash27** [comment]
Hi, 
Nice work on the plugin. Just checking if there is a plan to implement ability to change playback speed?

**Comment by hyochan** [comment]
Hi. Thank you for the email.
Currently, I am not investing any more features related to this plugin
since I am on another project.
However, you can give us `PR` anytime and share the work. I'll help you
reviewing.

Thanks. Regards
by dooboolab.

**Comment by subhash27** [comment]
Sure. Thanks for the quick reply.
