### ISSUE TITLE
[HELP] Recording Config

### ISSUE THREAD

**Issue by tdnguyenND** [dooboolab/flutter_sound#502]
Hi!
I trying to create an app that help detect song using [shazam api](https://rapidapi.com/apidojo/api/shazam).
Here is their input requirement
![image](https://user-images.githubusercontent.com/49394863/97523520-1a9a9980-19d5-11eb-80ee-905567ff98ff.png)
### How should I use FlutterSoundRecorder.startRecorder() ?
# Note: I tried the following code but it not happen as expected
```Dart
await Permission.microphone.request();
StreamController<Food> recordingDataController =
    StreamController<Food>();
recordingDataController.stream.listen((Food buffer) async {
  if (buffer is FoodData) {
    data += Base64Encoder().convert(buffer.data);
  }
});
await recorderModule.startRecorder(
  codec: Codec.pcm16,
  toStream: recordingDataController.sink,
  numChannels: 1,
  sampleRate: 44100,
);
```

**Comment by Larpoux** [comment]
Which OS ? Android or iOS ?

**Comment by tdnguyenND** [comment]
> Which OS ? Android or iOS ?

Android

**Comment by Larpoux** [comment]
I think that your problem is because chunks that you get into your Stream Sink<Food> are too smalls (just some milliseconds) and shazam api cannot detect them because it needs 3/5 seconds.

You can try to buffer the chunks until you have enough data to subit to shazam.

**Comment by tdnguyenND** [comment]
> I think that your problem is because chunks that you get into your Stream Sink are too smalls (just some milliseconds) and shazam api cannot detect them because it needs 3/5 seconds.
> 
> You can try to buffer the chunks until you have enough data to subit to shazam.

I tried but after 5-6s the response was something like "input is too large"

**Comment by Larpoux** [comment]
I do not know shazam.

Try to limit to 500Kb (they say that it is enough)

**Comment by tdnguyenND** [comment]
@Larpoux I think when recording to stream it has some kinda extra data that make the data larger.
I've just tried to record to file, then read that file as base64 string, it works perfectly

**Comment by Larpoux** [comment]
This is interesting ... 

What platform ? ios or android ?

**Comment by tdnguyenND** [comment]
Still android

**Comment by Larpoux** [comment]
I am going to took to that.
I think that recording to Stream and playback from stream is very very **important** new features for Flutter Sound.
I really want that those features work perfectly.

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems
