### ISSUE TITLE
[HELP] Using FFMPEG with flutter_sound results in errors

### ISSUE THREAD

**Issue by ThunderArmy** [dooboolab/flutter_sound#503]
I want to use flutter_sound to record audio and then use ffmpeg libx264 to convert it to a video with static background.

Since flutter_sound uses the audio version of ffmpeg `com.arthenica:mobile-ffmpeg-audio:4.3.1.LTS` I need to use any of the gpl-versions from flutter-ffmpeg (see section 2.1 on https://github.com/tanersener/flutter-ffmpeg) with include the libx264 library.

But when I add  `flutter_ffmpeg: ^0.3.0` to my pubspec.yaml my app won't compile because of duplicate classes in the ffmpeg version of flutter_sound and in my own (from my pubspec.yaml) 
Error Log -> https://pastebin.com/VDTazzKZ

How can I handle this?

I tried using 
`implementation("com.dooboolab.fluttersound:flutter_sound:6.3.1+1"){
        exclude group: 'com.arthenica', module:'mobile-ffmpeg-audio'
    }` in my build.gradle but it still does not work and results in the same error

also I am not sure if the dependency name is correct

**Comment by Larpoux** [comment]
@ThunderArmy 

Yes. 
Please wait one hour or two. 
I am not available now, but I will give you the solution next hour.

**Comment by ThunderArmy** [comment]
alright:
also for additional info the command I try to use to create the video with ffmpeg is 

`_flutterFFmpeg.execute("-i $_imagePath -i $path -acodec libvo_aacenc -vcodec libx264 $outputpath")`

**Comment by Larpoux** [comment]
@ThunderArmy ,

Your solution is probably to use the LITE flavor of Flutter Sound (which does not link FFmpeg) and use your own dependency  to FFMpeg in your pubspec.yaml,(with audio and video).

Your own dependency will create an iOS library and Android library which will define the correct flutter channels.
Thanks to that, Flutter Sound will be able to use (your) FFmpeg library and so will support all the FULL flavor features, even if you use the LITE flavor.

I am not sure to be very clear, so do not hesitate to post if you have any difficulty.
You can [read this](https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/migration.md#migration-from-3xx-to-4xx), but this note will probably not be very useful.

**Comment by ThunderArmy** [comment]
Thanks, it not works out the way I want!
