### ISSUE TITLE
How I want to play base64 audio 

### ISSUE THREAD

**Issue by leviis-dot** [dooboolab/flutter_sound#505]

**Comment by Larpoux** [comment]
You must decode base64 and play it with `startPlayerFromBuffer()`

**Comment by Larpoux** [comment]
But probably your base64 is not a valid file format.

If it is a raw PCM linear 16  data, you must use `startPlayerFromStream()`  and give the data with `feed()` or with the Flutter Sound sink

**Comment by Larpoux** [comment]
You can [read this](https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/codec.md#playing-pcm-16-from-a-dart-stream)

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems.
