### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Damanotra** [dooboolab/flutter_sound#506]
I need Help for :

- Debugging my App ?

-------------------------------------
## Here is my question :

Hi, I've been trying the plugin for several days and notice that the remote URL link for the audio can't HTTP, it hasto be HTTPS. Am I correct? You can try this WAV for example, it's from my server

http://5.189.150.137:5000/download_audio/CantinaBand3.wav

I need to build a particular app for my client and this server is all I got, can you show me some code so that the plugin accept HTTP source of file. Here is the console log when I use HTTP URL

Waiting for RMX1821 to report its views...
Debug service listening on ws://127.0.0.1:56870/suQr4s-UwTc=/ws
Syncing files to device RMX1821...
D/ViewRootImpl( 9755): setSurfaceViewCreated, created:true
I/SurfaceView( 9755): 232936607 surfaceChanged -- format=4 w=720 h=1432 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
D/SurfaceView( 9755): updateScreenMode w:720 h:1432 ViewRoot w:720 h:1520
D/SurfaceView( 9755): try to resquest 60Hz
D/SurfaceView( 9755): updateScreenMode w:720 h:1432 ViewRoot w:720 h:1520
D/SurfaceView( 9755): try to resquest 60Hz
W/Gralloc3( 9755): mapper 3.x is not supported
E/gralloc ( 9755): Arm Module v1.0
E/ion     ( 9755): ioctl c0044901 failed with code -1: Invalid argument
I/OpenGLRenderer( 9755): Davey! duration=3551ms; Flags=1, IntendedVsync=108471206577567, Vsync=108471256577568, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=108471266346465, AnimationStart=108471266450080, PerformTraversalsStart=108471266458542, DrawStart=108473552547080, SyncQueued=108473556858388, SyncStart=108473557678619, IssueDrawCommandsStart=108473557969157, SwapBuffers=108474749703080, FrameCompleted=108474758758157, DequeueBufferDuration=4831000, QueueBufferDuration=7319000, 
E/ANR_LOG ( 9755): >>> msg's executing time is too long
E/ANR_LOG ( 9755): Blocked msg = { when=-3s554ms what=0 target=android.view.Choreographer$FrameHandler callback=android.view.Choreographer$FrameDisplayEventReceiver } , cost  = 3495 ms
E/ANR_LOG ( 9755): >>>Current msg List is:
E/ANR_LOG ( 9755): Current msg <1>  = { when=-1d6h7m54s760ms what=0 target=android.view.ViewRootImpl$ViewRootHandler callback=android.view.-$$Lambda$ViewRootImpl$7A_3tkr_Kw4TZAeIUGVlOoTcZhg }
E/ANR_LOG ( 9755): Current msg <2>  = { when=-3s489ms barrier=1 }
E/ANR_LOG ( 9755): Current msg <3>  = { when=-3s437ms what=6 target=android.view.ViewRootImpl$ViewRootHandler }
E/ANR_LOG ( 9755): >>>CURRENT MSG DUMP OVER<<<
I/Choreographer( 9755): Skipped 208 frames!  The application may be doing too much work on its main thread.
I/fidea.hackatho( 9755): Background concurrent copying GC freed 1348(179KB) AllocSpace objects, 2(40KB) LOS objects, 69% free, 1334KB/4406KB, paused 371us total 115.661ms
I/Choreographer( 9755): Skipped 1 frames!  The application may be doing too much work on its main thread.
D/ColorViewRootUtil( 9755): nav bar mode ignore false downX 412 downY 491 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=412.0, y[0]=491.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=108484684, downTime=108484684, deviceId=2, source=0x1002, displayId=0 }
D/AudioManager( 9755): stopBluetoothSco from com.infidea.hackathon
D/AudioManager( 9755): setBluetoothScoOn on=false from com.infidea.hackathon
D/AudioManager( 9755): setBluetoothScoOn keys: get_device_change_authority=com.infidea.hackathon, mAuthoriyStr = true
I/AudioManager( 9755): In setSpeakerphoneOn(), on: true, calling application: com.infidea.hackathon
D/AudioManager( 9755): setSpeakerphoneOn keys: get_speaker_authority=com.infidea.hackathon, mAuthoriyStr = true
I/AudioManager( 9755): In setSpeakerphoneOn(), on: true, calling application: com.infidea.hackathon
D/AudioManager( 9755): setSpeakerphoneOn keys: get_speaker_authority=com.infidea.hackathon, mAuthoriyStr = true
D/AudioManager( 9755): setBluetoothScoOn on=false from com.infidea.hackathon
D/AudioManager( 9755): setBluetoothScoOn keys: get_device_change_authority=com.infidea.hackathon, mAuthoriyStr = true
D/AudioManager( 9755): stopBluetoothSco from com.infidea.hackathon
D/AudioManager( 9755): setMode mode=0 from com.infidea.hackathon
I/flutter ( 9755): FS:---> closeAudioSession 
I/flutter ( 9755): FS:<--- closeAudioSession 
I/flutter ( 9755): FS:---> openAudioSession 
D/AudioManager( 9755): stopBluetoothSco from com.infidea.hackathon
D/AudioManager( 9755): setBluetoothScoOn on=false from com.infidea.hackathon
D/AudioManager( 9755): setBluetoothScoOn keys: get_device_change_authority=com.infidea.hackathon, mAuthoriyStr = true
I/AudioManager( 9755): In setSpeakerphoneOn(), on: true, calling application: com.infidea.hackathon
D/AudioManager( 9755): setSpeakerphoneOn keys: get_speaker_authority=com.infidea.hackathon, mAuthoriyStr = true
I/AudioManager( 9755): In setSpeakerphoneOn(), on: true, calling application: com.infidea.hackathon
D/AudioManager( 9755): setSpeakerphoneOn keys: get_speaker_authority=com.infidea.hackathon, mAuthoriyStr = true
D/AudioManager( 9755): setBluetoothScoOn on=false from com.infidea.hackathon
D/AudioManager( 9755): setBluetoothScoOn keys: get_device_change_authority=com.infidea.hackathon, mAuthoriyStr = true
D/AudioManager( 9755): stopBluetoothSco from com.infidea.hackathon
D/AudioManager( 9755): setMode mode=0 from com.infidea.hackathon
I/flutter ( 9755): FS:---> channelMethodCallHandler : openAudioSessionCompleted
I/flutter ( 9755): FS:<--- channelMethodCallHandler : openAudioSessionCompleted
I/flutter ( 9755): FS:<--- openAudioSession 
I/flutter ( 9755): FS:---> setSubscriptionDuration 
I/flutter ( 9755): FS:<---- setSubscriptionDuration 
I/flutter ( 9755): FS:---> isDecoderSupported 
I/flutter ( 9755): FS:---> needToConvert 
I/flutter ( 9755): FS:<--- needToConvert 
I/flutter ( 9755): FS:<--- isDecoderSupported 
W/fidea.hackatho( 9755): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/fidea.hackatho( 9755): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/fidea.hackatho( 9755): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/fidea.hackatho( 9755): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/Choreographer( 9755): Skipped 1 frames!  The application may be doing too much work on its main thread.
D/ColorViewRootUtil( 9755): nav bar mode ignore false downX 270 downY 354 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=270.0, y[0]=354.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=108488931, downTime=108488931, deviceId=2, source=0x1002, displayId=0 }
I/flutter ( 9755): FS:---> startPlayer 
I/flutter ( 9755): FS:---> stop 
I/flutter ( 9755): FS:<--- stop 
I/flutter ( 9755): FS:---> _convert 
I/flutter ( 9755): FS:---> needToConvert 
I/flutter ( 9755): FS:<--- needToConvert 
I/flutter ( 9755): FS:<--- _convert 
V/OppoMediaPlayer( 9755): system load
V/OppoMediaPlayer( 9755): new OppoMediaPlayer
I/OppoMediaPlayer( 9755): new mediaplayer ,packageName = com.infidea.hackathon
I/OppoMediaPlayer( 9755): isPlaying() isOppoCreate=false
I/OppoMediaPlayer( 9755): setDataSource(String) isOppoCreate=false
I/OppoMediaPlayer( 9755): setDataSource(path, headers) isOppoCreate=false
V/MediaHTTPService( 9755): MediaHTTPService(android.media.MediaHTTPService@f797869): Cookies: null
I/OppoMediaPlayer( 9755): prepare() isOppoCreate=false
V/MediaHTTPService( 9755): makeHTTPConnection: CookieManager created: java.net.CookieManager@39e72ee
V/MediaHTTPService( 9755): makeHTTPConnection(android.media.MediaHTTPService@f797869): cookieHandler: java.net.CookieManager@39e72ee Cookies: null
E/MediaPlayerNative( 9755): error (1, -2147483648)
W/System.err( 9755): java.io.IOException: Prepare failed.: status=0x1
W/System.err( 9755): 	at android.media.MediaPlayer._prepare(Native Method)
W/System.err( 9755): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1415)
W/System.err( 9755): 	at com.dooboolab.TauEngine.FlautoPlayerMedia._startPlayer(FlautoPlayerMedia.java:68)
W/System.err( 9755): 	at com.dooboolab.TauEngine.FlautoPlayer.startPlayer(FlautoPlayer.java:172)
W/System.err( 9755): 	at com.dooboolab.fluttersound.FlutterSoundPlayer.startPlayer(FlutterSoundPlayer.java:220)
W/System.err( 9755): 	at com.dooboolab.fluttersound.FlutterSoundPlayerManager.onMethodCall(FlutterSoundPlayerManager.java:142)
W/System.err( 9755): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err( 9755): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 9755): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err( 9755): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 9755): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 9755): 	at android.os.Looper.loop(Looper.java:182)
W/System.err( 9755): 	at android.app.ActivityThread.main(ActivityThread.java:7822)
W/System.err( 9755): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9755): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 9755): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
I/OppoMediaPlayer( 9755): handleMediaPlayerError() mCurrentState=4
I/OppoMediaPlayer( 9755): handleMediaPlayerError() mNotUsingOppoMedia is true
I/MediaPlayer( 9755): prepare failed ,throw IOException to app
E/FlautoPlayer( 9755): startPlayer() exception
I/flutter ( 9755): error: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, startPlayer() error, null)

Thank you so much for any help

**Comment by Larpoux** [comment]
Hi @Damanotra ,

I tested your URL, and this is true that it does not work, neither on Android nor iOS.

But I am not convinced that the problem is HTTP.
The problem could be also your port 5000.
It is possible (but I am not sure) that the OS blocks outgoing calls to such a port, for security reasons.

If you investigate this problem and find the reason, please share with us.

**Comment by Larpoux** [comment]
If you have still problems, please re-open this issue.
I am currently cleaning old waiting issues, but I am not sure that this one is really finished.
