### ISSUE TITLE
[BUG] No podspec found for `flutter_sound_web` in `.symlinks/plugins/flutter_sound_web/ios`

### ISSUE THREAD

**Issue by felixjunghans** [dooboolab/flutter_sound#509]
After the last Flutter Sound update I noticed that I can't run a Pod install anymore. I get the following error message every time.

**No podspec found for `flutter_sound_web` in `.symlinks/plugins/flutter_sound_web/ios`**

I also noticed that the podspec is named flutter_soundweb instead of flutter_sound_web.
Is this a mistake or is it intentional?

**Comment by Larpoux** [comment]
Yes, Felix. This is a mistake and it was not intentional.
I am going to fix that.

Thank you for having see that.

**Comment by Larpoux** [comment]
Felix : can you try again (V6.4.1) ?

**Comment by Larpoux** [comment]
Here is the magic sequence of instruction that I do when problems with cocoapod : 
```sh
cd flutter_sound/example
flutter pub get
flutter clean
cd ios
pod cache clean --all
rm Podfile.lock
pod repo update
pod install
cd ../../..
```

**Comment by felixjunghans** [comment]
Thanks for fixing

**Comment by Nader2004** [comment]
Hello. I am getting this bug even after I updated to 6.4.1 : 
`   [!] Failed to load 'flutter_sound_web' podspec: 
    [!] Invalid `flutter_sound_web.podspec` file: target of repeat operator is not `
Thanks for reading

**Comment by Larpoux** [comment]
> Here is the magic sequence of instructions that I execute when I have problems with Cocoapod :
> 
> ```shell
> cd flutter_sound/example
> flutter pub get
> flutter clean
> cd ios
> pod cache clean --all
> rm Podfile.lock
> pod repo update
> pod install
> cd ../../..
> ```

Try cleaning your dev caches. Cocoapod is a little painfull.

**Comment by Larpoux** [comment]
You can try also to delete your .symlink directory, and recreate everything with 
```
flutter build ios
```

If you can find what is the good way to resolve this issue, please share with everybody.
I worry that other people have problems too.

**Comment by Larpoux** [comment]
If you look to What is the complete error message ?


> Hello. I am getting this bug even after I updated to 6.4.1 :
> ` [!] Failed to load 'flutter_sound_web' podspec: [!] Invalid`flutter_sound_web.podspec`file: target of repeat operator is not`

**Comment by Larpoux** [comment]
Could you try to change in flutter_sound_web.podspec: 
```
 s.version          = '0.0.1'
 ```
by
```
 s.version          = '6.4.1+1'
 ```
and tell me if better

**Comment by Larpoux** [comment]
OK, I found the problem.
There is a syntax error in line 11.

I am going to release 6.4.2.
please wait a few minutes ...

**Comment by Larpoux** [comment]
OK Nader,

could you try 6.4.2 and tell me if better ?

**Comment by Larpoux** [comment]
@Nader2004

**Comment by Nader2004** [comment]
sorry for responding late . I will try it now.

**Comment by Nader2004** [comment]
Hi sorry for taking so long but actually the build is still running. I am building codemagic , which basically builds it for ios and android together , plus the App is large actually.

**Comment by Nader2004** [comment]
@Larpoux thanks it works now.

**Comment by Larpoux** [comment]
Yeah !

**Comment by Larpoux** [comment]
Thank you Nader, and sorry for the inconvenience.

Good luck with your dev 😄
