### ISSUE TITLE
[BUG] onProgress not working on iOS

### ISSUE THREAD

**Issue by RoiLaredo** [dooboolab/flutter_sound#510]
## Flutter Sound Version :  6.4.1+1

- **Released** or **Beta** version ? both

- Version number ? 6.4.1+1

- **FULL** or **LITE** flavor ? Lite

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)
|-- flutter_sound_lite 6.4.1+1
|   |-- flutter_sound_platform_interface 6.4.1+1
|   |-- flutter_sound_web 6.4.1+1
|   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity

- Crash ? no

- Result is not what expected ? 

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?
Real ios

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)
no logs
------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
?

**Comment by RoiLaredo** [comment]
as i wrote, onProgress on FlutterSoundRecorder is not working. not getting any event during record.

**Comment by Larpoux** [comment]
Did you call the verb `setSubscriptionDuration()` before startRecorder() ?

**Comment by RoiLaredo** [comment]
no. should i? didnt see it on your faq

**Comment by Larpoux** [comment]
The default valuer is zero : zero means that there is no progress call-backs

**Comment by RoiLaredo** [comment]
on ios? cause in android it is working fine

**Comment by RoiLaredo** [comment]
will give it a try now and update u. thanks.

**Comment by RoiLaredo** [comment]
@Larpoux working great. many thanks.
note that in code the description says:
"Sets the frequency at which duration updates are sent to duration listeners. The default is every 10 milliseconds."
thanks.

**Comment by Larpoux** [comment]
Yes, the documentation is erroneous. This is really bad. 👎 
I hope that you did not loose to much time.

I am actually in the process of cleaning the API.
In the new API, the verb `setSubscriptionDuration()` will be deprecated.
When we will start a Player or a Recorder, the APP will specify the subscriptionDuration (or 0 if no call back wanted).

Too many Flutter Sound users had problems with the verb `setSubscriptionDuration()` . I hope that the new API will be more understandable.

**Comment by RoiLaredo** [comment]
thanks. 
keep up the great job. this plugin is great.
