### ISSUE TITLE
[BUG] Stream is null on iOS

### ISSUE THREAD

**Issue by vanyasem** [dooboolab/flutter_sound#511]
## Flutter Sound Version : 

- Released 

- Version number **6.4.2+1**

- **LITE** flavor

----------------------------------------------------------

## Severity

- Result is not what expected - severe (core functionality broken)

--------------------------------------------------------

## Platforms you faced the error 

- iOS true

- Android false

- Real device true

-----------------------------------------------------

**Describe the bug**
At some point you broke stream callback for iOS. 6.1.2 works fine, but on latest 6.4.2+1 a callback from a stream recording returns only 'null's on iOS. But it works on Android

**To Reproduce**
1. Use 6.4.2+1 in your project
2. Start a stream PCM16 recording on an iOS device
3. Get nulls in callback instead of actual recording

**Expected behavior**
I expected actual data instead of nulls

**Code:**

```
import 'dart:async';
import 'dart:typed_data' show Uint8List;

import 'package:flutter_sound_lite/flutter_sound.dart';

const int SAMPLE_RATE = 48000;


class Recorder {

  FlutterSoundRecorder _recorder;
  bool _recorderIsInitialized = false;
  StreamController<Food> _recordingDataController;
  StreamSubscription  _recordingDataSubscription;
  List<int> _processedResult = [];

  Recorder();

  Future initialize() async {
    if (!_recorderIsInitialized) {
      _recorder = FlutterSoundRecorder();
      await _recorder.openAudioSession(category: SessionCategory.record, focus: AudioFocus.requestFocusAndStopOthers);
      _recorderIsInitialized = true;
    }
  }

  void dispose() {
    if (_recorderIsInitialized) {
      stopRecorder();
      _recorder.closeAudioSession();
      _recorder = null;
      _recorderIsInitialized = false;
    }
  }

  Future _checkRecorder() async {
    if (!_recorderIsInitialized) {
      print("WARNING! Recorder was not properly initialized");
      await initialize();
    }
  }

  Future<void> record() async {
    await _checkRecorder();
    _processedResult = [];
    _recordingDataController = StreamController<Food>();
    _recordingDataSubscription =
        _recordingDataController.stream.listen((Food buffer) {
          if (buffer is FoodData) {
            print('debug');
            print(buffer.data.toString());   // here I get nulls on iOS
            _processedResult.addAll(buffer.data);
          }
        }
        );
    await _recorder.startRecorder(
      toStream: _recordingDataController.sink,
      codec: Codec.pcm16,
      numChannels: 1,
      sampleRate: SAMPLE_RATE,
    );
  }

  Future<Uint8List> stopRecorder() async {
    assert (_recorderIsInitialized);
    await _recorder.stopRecorder();
    if (_recordingDataSubscription != null) {
      await _recordingDataSubscription.cancel();
      _recordingDataSubscription = null;
    }
    await _recordingDataController.close();
    return Uint8List.fromList(_processedResult);
  }
}
```

**Comment by Larpoux** [comment]
This is weird.

Your code seems correct at first seeing. Do you receive permanent NULLs during recording, or just a few ?

**Comment by Larpoux** [comment]
I do not understand how you can do 
```
            print(buffer.data.toString());   // here I get nulls on iOS
```
without type casting `buffer` because buffer is a `Food` and not a `FoodData`.
```
Of course I get an error when I try your code ...

**Comment by vanyasem** [comment]
@Larpoux the nulls are permanent

The code I provided is actually from the example, and it works fine on Android. The Xcode part of the callback is also not working (I tried printing from native iOS code). In fact, the callback on the flutter side seems to be never called at all

**Comment by Larpoux** [comment]
Ivan, It is possible that the sample rate is too fast. (Not sure).

Can you try with 8000 (this is the sample rate I use on `recordToStreamExample`.

If you still have problems, please post your logs.

**Comment by vanyasem** [comment]
@Larpoux I have tried it with 8000 before. Same result. It works with the old version. Please acknowledge the issue and do something about it instead of trying to blame it on me

**Comment by Larpoux** [comment]
Sorry, Ivan, if you think that I blame you.
Of course I never blame you.

Maintenance and finding bugs is probably the most challenging task that a developer has to do.
I am just trying to figure what happens to you.

> Please acknowledge the issue **and do something** .

You must understand that I am a free developer. I work on Flutter Sound for my pleasure and I am glad if my work is useful to others. But **I do not have to do anything**. I do what I want and when I want. I am **free**.
Flutter Sound is a free project. Maybe you can help to debug the stuff and do a Pull Request, instead of waiting that someone will fix your problems.

I consider that recording to a Dart Stream is a new fundamental functionnality, and I really want that this feature works correctly.
Instead of starting a bad troll, please send your logs.

**Comment by vanyasem** [comment]
@Larpoux I've been a member of quite big libre software projects in the past, I would ask you to stop off-toping here. The fact that you work for free has nothing to do with the issue. If you really want to discuss your life with me, contact me on Telegram via @vanyasem 

If you want me to post logs for you - I would kindly ask you to clarify what exactly do you need me to upload. Logs from Xcode? Any additional info you need? I bet a stream of nulls in the console would help you to test out the issue for sure ;)
