### ISSUE TITLE
[bug]when playing if i no set the SubscriptionDuration,it is not listen onProgress

### ISSUE THREAD

**Issue by normidar** [dooboolab/flutter_sound#512]
[bug]when playing if i no set the SubscriptionDuration,it is not listen onProgress 
version is   flutter_sound: 6.4.0+3

**Comment by Larpoux** [comment]
Yes, the default value is 0 (zero) which means : no callbacks `onProgress`

**Comment by normidar** [comment]
but in the last of this page: https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/player.md#flutter-sound-player-api

has 
// 0.010s. is default

**Comment by Larpoux** [comment]
Yes, I know, the documentation is erroneous. 👎 
You are at least the 20ths Flutter Sound user who has problems with this functionality.

I am currently working on a new cleaner API. `setSubscriptionDuration()` will be deprecated.

Sorry that you lost time with this.
