### ISSUE TITLE
[BUG] Sound recorder not working after startForeground was called natively

### ISSUE THREAD

**Issue by ofoudane** [dooboolab/flutter_sound#514]
## Flutter Sound Version : 

- **Released**

- 6.4.2+1

- **FULL**

- Result of the command **"flutter pub deps | grep flutter_sound"**
|-- flutter_sound 6.4.2+1
|   |-- flutter_sound_platform_interface 6.4.2+1
|   |-- flutter_sound_web 6.4.2+1
|   |   |-- flutter_sound_platform_interface...
----------------------------------------------------------

## Severity
- Result is not what expected ?

--------------------------------------------------------

## Platforms you faced the error 

- Android (Emulator and real Android 9 device)?
----------------------------------------------

## Logs
No logs
-----------------------------------------------------

**Describe the bug**
The instruction await openAudioSession does not return complete. I tried with All audio focuses, but the function call does not complete even after 1 minute. I also tried to embeed the WidgetUI into my application and the problem still occurs.

**To Reproduce**
1. Create a native java application with the instruction startForeground
2. Call startAudioSession on a FlutterSoundRecorder object

**Expected behavior**

When openAudioSession is called, the session does not open no matter which focus I set. 
-----------------------------------------------------------------

## Additional context**
I believe this issue might be related to a notification been shown. In my case, this is due to startForeground function.

**Comment by Larpoux** [comment]
You are certainly right : your problems are certainly linked with the use of Android services.
This is an area where I have absolutely no knowledge, and the guy who developed this feature is no more available...

Of course, if you have some precisions, (and better a Pull Request), it would be great.
(We need an Android expert, ...)

**Comment by ofoudane** [comment]
Hi Larpoux,

First, I would like to thank you for your quick response. However, I just found out the problem came from calling the new FlutterEngine(context) from Java code. 
The recording worked well after I changed to FlutterEngine(context, args=null, automaticallyLoadPlugins=false) and background plugins manually.
Ultimately, the problem came from loading the flutter recorder plugin twice.

**Comment by Larpoux** [comment]
Thank you @ofoudane for your help.
I will look to that later, I am actually very busy.
If you have some Pull Request to suggest it will be fantastic.

Merci cher camarade francophone.
Je suis heureux que tu ais localisé le probleme. Je vais ragardé ça plus attentivement, pour sure !
Bon courage pour les developpements de ton appli.

**Comment by Larpoux** [comment]
Duplicates [#411]
