### ISSUE TITLE
flutter_sound not working

### ISSUE THREAD

**Issue by aditi0123chandra** [dooboolab/flutter_sound#515]
I need Help for :

- Using the API ?

- Generate an iOS or Android App ?

- Debugging my App ?

- Other ?

-------------------------------------
## Here is my question :
**flutter_sound** is added in the pubspec.yaml file and imported in the file but still it is **showing error**. Please help to resolve the issue.

**Comment by Mr-Pepe** [comment]
What error is it showing?

**Comment by Larpoux** [comment]
Need more informations.
