### ISSUE TITLE
[BUG]After the recording is started, there is a problem in monitoring the recording. It is always 0

### ISSUE THREAD

**Issue by BedRockGx** [dooboolab/flutter_sound#518]
Hello, I made an error on the real IOS mobile phone. After turning on the recording, monitor the method recorderModule.onProgress.listen () cannot listen to a valid recording time. It has always been 0. Because of this, the recording cannot be ended and stored normally, resulting in the following error:
-------------------------------
Getting media information for /var/mobile/Containers/Data/Application/7CAAB0B4-A125-431D-BFC9-1054B5FA4AA6/Library/Caches/flutter_ sound-1604932777.aac.
WARNING: Format aac detected only with low score of 1, misdetection possible!
Format aac detected only with low score of 1, misdetection possible!
/var/mobile/Containers/Data/Application/7CAAB0B4-A125-431D-BFC9-1054B5FA4AA6/Library/Caches/flutter_ sound-1604932777.aac: End of file
ERROR: /var/mobile/Containers/Data/Application/7CAAB0B4-A125-431D-BFC9-1054B5FA4AA6/Library/Caches/flutter_ sound-1604932777.aac: End of file
flutter: _ duration == 0.0
[VERBOSE-2:ui_ dart_ state.cc (177)] Unhandled Exception: NoSuchMethodError: The getter 'inMinutes' was called on null.
Receiver: null
-------------------------

**Comment by Larpoux** [comment]
What codec do you specify in `startRecorder()` ?

**Comment by BedRockGx** [comment]
> 您在哪个编解码器中指定`startRecorder()`？

Hello, my codec is Codec.aacADTS It is normal on Android real phones, but there is a problem with IOS

**Comment by BedRockGx** [comment]
> What codec do you specify in `startRecorder()` ?

Hello, my codec is Codec.aacADTS It is normal on Android real phones, but there is a problem with IOS

**Comment by Larpoux** [comment]
Please re-open this issue with logs if you have still problems with your recorder.
