### ISSUE TITLE
[BUG] flutter build ios error

### ISSUE THREAD

**Issue by BedRockGx** [dooboolab/flutter_sound#519]
## Hello, there are many problems when I use the fluent build IOS command to package IOS

/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterSound.mm:28 :9: warning:
non-portable path to file '"FlutterFFmpegPlugin.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#import "FlutterFfmpegPlugin.h"
^~~~~~~~~~~~~~~~~~~~~~~
"FlutterFFmpegPlugin.h"
1 warning generated.
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterFfmpegPlugin.mm:93 :15: warning:
unused variable 'command' [-Wunused-variable]
NSString* command =  call.arguments [@"command"];
^
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterFfmpegPlugin.mm:94 :15: warning:
unused variable 'delimiter' [-Wunused-variable]
NSString* delimiter =  call.arguments [@"delimiter"];
^
2 warnings generated.
Toast-byhwjoqldxyzmdcufkbgzommtqgq
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterSoundRecorder.mm:34 :17: warning:
method definition for 'setDbPeakLe velUpdate:result :' not found [-Wincomplete-implementation]
@implementation FlutterSoundRecorder
^
In file included from
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterSoundRecorder.mm:30 :
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/FlutterSoundRecorder.h:53:1: note:
method 'setDbPeakLe velUpdate:result :' declared here
- (void)setDbPeakLevelUpdate:(double)intervalInSecs result: (FlutterResult)result;
^
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterSoundRecorder.mm:34 :17: warning:
class 'FlutterSoundRecorder' does not conform to protocol 'FlautoRecorderCallback' [-Wprotocol]
@implementation FlutterSoundRecorder
^
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/ FlutterSoundRecorder.mm:34 :17: note: add
stubs for missing protocol requirements
@implementation FlutterSoundRecorder
^
2 warnings generated.
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/FlutterSoundManager.m:33:17: warning:
class 'FlutterSoundManager' does not conform to protocol 'FlutterPlugin' [-Wprotocol]
@implementation FlutterSoundManager
^
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/FlutterSoundManager.m:33:17: note: add
stubs for missing protocol requirements
@implementation FlutterSoundManager
^
/Users/killer/Documents/flutter/.pub-cache/hosted/ pub.flutter - io.cn/flutter_ sound-6.4.2+1/ios/Classes/FlutterSoundManager.m:89:17: warning:
method definition for 'getStatus' not found [-Wincomplete-implementation]
@implementation Session

**Comment by Larpoux** [comment]
This is just warnings.
I think that those warnings are only when there is a problem in your dart code.

But this is not clean : someone must look to that more deeply.

**Comment by BedRockGx** [comment]
> This is just warnings.
> I think that those warnings are only when there is a problem in your dart code.
> 
> But this is not clean : someone must look to that more deeply.

But these problems have affected my normal IOS packaging, unable to package IPA files

**Comment by BedRockGx** [comment]
> This is just warnings.
> I think that those warnings are only when there is a problem in your dart code.
> 
> But this is not clean : someone must look to that more deeply.

I hope to be able to give a good solution, as well as I mentioned before that the recording has been 0, unable to record normally

**Comment by Larpoux** [comment]
This would be **GREAT** 👍 if you can help for a solution.
There is not enough developer on Flutter Sound and my TODO stack is full .

**Comment by BedRockGx** [comment]
> This would be **GREAT** 👍 if you can help for a solution.
> There is not enough developer on Flutter Sound and my TODO stack is full .

Hello, after using Xcode to open, I click archive to build. Then an error is reported in the generated pluginregistry.m :
Could not build module 'flutter_ sound'
And mobileffmpeg_ Error reported in exception.h : thread local storage is not supported for the current target

### Do you have any good suggestions?

**Comment by Larpoux** [comment]
No, unfortunately I do not remember if I had to do something in my own App for this problem.
I have just checked that I actually have no errors building a release version of my App (with the `archive` command.

You should investigate what is the target which cause problem. Actually I do not generate for 32 bits OS.
Just arm/64 bits.

Please share your results (or better do a Pull Request) if we need to add something in the documentation.

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems.
