### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Althaf-IndusViva** [dooboolab/flutter_sound#520]
I need Help for :

- Using the API ?

-------------------------------------
## Here is my question :  I'm trying to play a file from my local storage. I've given the Uri of a file from my local storage (/data/user/0/com.myApp_mobile/app_flutter/Recordings).

I was able to successfully  play file using the _flutterSoundPlayer.startPlayer of FlutterSoundPlayer. But the listener of _flutterSoundPlayer.OnProgress is returning me a null.

I need to implement the seeker, So i need the duration of the onProgress. 

```
  if (audioFilePath != null) {
         await _flutterSoundPlayer.startPlayer(
            fromURI: audioFilePath,
            codec: _codec,
            sampleRate: IndusViva.REC_SAMPLE_RATE,
            whenFinished: () {
              print('::::::::----Path is: $audioPathLocation');
              setState(() {
                isPlaying = false;
              });
              print('------------isPlaying =>>' + isPlaying.toString());
            });
        setState(() {});
      }
  addPlayerSubscription();
```

The Add Player Subscription method is as below:

```
void _addPlayerSubscription() async {
    cancelPlayerSubscriptions();
    _playerSubscription = _flutterSoundPlayer.onProgress.listen((event) {
      if (event != null) {
        maxDuration = event.duration.inMilliseconds.toDouble();
        if (maxDuration <= 0) maxDuration = 0.0;

        sliderCurrentPosition =
            min(event.position.inMilliseconds.toDouble(), maxDuration);
        if (sliderCurrentPosition < 0.0) {
          sliderCurrentPosition = 0.0;
        }
        DateTime date = new DateTime.fromMillisecondsSinceEpoch(
            event.position.inMilliseconds,
            isUtc: true);
        String txt = DateFormat('mm:ss:SS', 'en_GB').format(date);
        setState(() {
          _playerTxt = txt.substring(0, 8);
        });
      }
    });
  }
```
The `event` is giving me a null. What did I do wrong?

**Comment by Larpoux** [comment]
Hi @Althaf-IndusViva ,

Did you call the verb [setsubscriptionduration][https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/player.md#setsubscriptionduration] ?

There is an error in the documentation, saying that the default value is 100 ms.
In reality, the default value is 0 (zero) which means that the App don't want to receive the callback.

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems
