### ISSUE TITLE
[BUG] wont record on iOS simulator

### ISSUE THREAD

**Issue by shovelmn12** [dooboolab/flutter_sound#522]
## Flutter Sound Version : 

- **Released** or **Beta** version ? Rlease

- Version number ? 6.4.2+1

- **FULL** or **LITE** flavor ? FULL

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)
    |   |-- flutter_sound 6.4.2+1
    |   |   |-- flutter_sound_platform_interface 6.4.2+1
    |   |   |-- flutter_sound_web 6.4.2+1
    |   |   |   |-- flutter_sound_platform_interface...

----------------------------------------------------------

## Severity

- Crash ? no error or exception

- Result is not what expected ? Not recording or not saving to file on ios (simulator) + onProgress not working

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?

- Both ?

- Emulator ? ios

- Real device ?

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

not a crash...

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**
recording audio with the plugin

**To Reproduce**
use the plugin normally on ios simulator

**Expected behavior**
record audio

-----------------------------------------------------------------

## Additional context**
flutter_sound_lite wont compile even on ios....

**Comment by Larpoux** [comment]
Not enough information.
Please re-enter a new issue if you have still problems.
