### ISSUE TITLE
Specs satisfying the `flutter_sound (from `.symlinks/plugins/flutter_sound/ios`)` dependency were found, but they required a higher minimum deployment target.[BUG]

### ISSUE THREAD

**Issue by 1124863805** [dooboolab/flutter_sound#523]

**Comment by sunhao91** [comment]
see  #322 ，`The actual minimum version for Flutter Sound is 9.3.`

**Comment by sunhao91** [comment]
sorry ，`version 6.4.2+1 ` have the same question.

and downgrade to version `5.1.1`, the question is gone

**Comment by Larpoux** [comment]
What is your deployment target ?
Flutter Sound uses 10.0

**Comment by zeroprofit** [comment]
I can confirm.  Flutter Sound ^6.4.2+1 requires iOS deployment target of 10.0 and up.  The README doc said 9.3 or up, and it is wrong.  If you set your iOS deployment target to 10.0, you should be good.

**Comment by renanborgez** [comment]
I'm also having this problem, my iOS deployment target is 12.0
with the version 5 it does not happen indeed, so I belieave is something regarding the version 6

![image](https://user-images.githubusercontent.com/1863024/100852953-77cbb400-3487-11eb-98fc-eed95a6916bb.png)
I have performed all actions described in the print
still not works

**Comment by Larpoux** [comment]
Sorry @renanborgez ,

I was doing the 6.4.4 release some minutes ago, and Flutter Sound was not available during 15 minutes.

Please retry, now.

**Comment by Larpoux** [comment]
> Sorry @renanborgez ,
> 
> I was doing the 6.4.4 release some minutes ago, and Flutter Sound was not available during 15 minutes.
> 
> Please retry, now.

I do not know how to put Flutter Sound in maintenance mode when I am installing a new version.
I do as fast as possible, but some times it takes me an hour or two and Flutter Sound users thinks that Flutter Sound is broken.

**Comment by renanborgez** [comment]
> > Sorry @renanborgez ,
> > 
> > I was doing the 6.4.4 release some minutes ago, and Flutter Sound was not available during 15 minutes.
> > 
> > Please retry, now.
> 
> I do not know how to put Flutter Sound in maintenance mode when I am installing a new version.
> I do as fast as possible, but some times it takes me an hour or two and Flutter Sound users thinks that Flutter Sound is broken during that time.

ohhhh that was an unhappy coincidence hahaha
thanks, I'll try it again.

**Comment by renanborgez** [comment]
Indeed, works perfectly now 
I just had to use the following commands as written in the docs

```
cd ios
pod cache clean --all
rm Podfile.lock
rm -rf .symlinks/
cd ..
flutter clean
flutter pub get
cd ios
pod update
pod repo update
pod install --repo-update
pod update
pod install
cd ..
```

**Comment by Larpoux** [comment]
Cocoapods is a little bit painful .

**Comment by bhanuka96** [comment]
> Indeed, works perfectly now
> I just had to use the following commands as written in the docs
> 
> ```
> cd ios
> pod cache clean --all
> rm Podfile.lock
> rm -rf .symlinks/
> cd ..
> flutter clean
> flutter pub get
> cd ios
> pod update
> pod repo update
> pod install --repo-update
> pod update
> pod install
> cd ..
> ```

this way is not working for me. I just comment this line `#platform :ios, '9.0'` on my `podfile`. Now it's working

**Comment by Larpoux** [comment]
Yes, 9.0 is not good.
&tau; needs 10.0 or later
