### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adnanjpg** [dooboolab/flutter_sound#524]
## Flutter Sound Version : 

- **Released**

- 6.4.2 ( and the previous ones)

- Result of the command **"flutter pub deps | grep flutter_sound"**
```
|-- flutter_sound 6.4.2+1
|   |-- flutter_sound_platform_interface 6.4.2+1
|   |-- flutter_sound_web 6.4.2+1
|   |   |-- flutter_sound_platform_interface...

```
----------------------------------------------------------

## Severity

- Result is not what expected 

--------------------------------------------------------

## Platforms you faced the error 

- Android

- Emulator 

- Real device

----------------------------------------------

##  Screenshots

![Screen Shot 2020-11-23 at 11 33 00 (2)](https://user-images.githubusercontent.com/54329101/99941894-d4d8b300-2d7f-11eb-8923-d74bd21e1aca.png)

-----------------------------------------------------
**Describe the bug**
The recorded files from Android do not work neither on ios nor on browsers.
Tried .wav, .m4a, .mp3 and all of them wont work
here are examples:
https://dashboard.akelbety.com/upload/Chat/1214/20-1214-cb120809-fa83-45f1-8cfd-08d88f88dab6---23_11_2020_-_09_26_55_AM.mp3
https://dashboard.akelbety.com/upload/Chat/1213/20-1213-372bf3a2-73c4-45e6-8cfc-08d88f88dab6---23_11_2020_-_09_26_09_AM.wav
https://dashboard.akelbety.com/upload/Chat/1212/20-1212-1f5a2825-8f89-486a-8cfb-08d88f88dab6---23_11_2020_-_09_22_02_AM.m4a

**To Reproduce**
1. Record an audio from Android device
2. it plays just fine on Android on devices. but try to play it on browser or ios and it won't work

**Comment by Larpoux** [comment]
Your 3 records are recorded with a AMR-NB format.
AMR-NB  is only supported on Android. See [codecs compatibility](https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/codec.md#flutter-sound-codecs).

You must understand that the file extension does not imply the codec used by `FlutterSoundRecorder()`.
**The codec used is specified in the `codec:` parameter.**

**Comment by adnanjpg** [comment]
this fixed my problem, Thank you for your time.
