### ISSUE TITLE
[BUG]The sound cannot be changed between the speaker and the headset

### ISSUE THREAD

**Issue by hungoop** [dooboolab/flutter_sound#535]
## Flutter Sound Version : 

- **Released** 

- 6.4.3+44

- **FULL**

- Result of the command **"flutter pub deps | grep flutter_sound"**
(very important)

----------------------------------------------------------

## Severity

- Result is not what expected ?

The sound output cannot be changed between the speaker and the headset

--------------------------------------------------------

## Platforms you faced the error 
- Android 

- Emulator

- Real device

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

E/MethodChannel#com.dooboolab.flutter_sound_player(27630): Failed to handle method call
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at com.dooboolab.fluttersound.FlutterSoundPlayer.setAudioFocus(FlutterSoundPlayer.java:412)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at com.dooboolab.fluttersound.FlutterSoundPlayerManager.onMethodCall(FlutterSoundPlayerManager.java:104)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at android.app.ActivityThread.main(ActivityThread.java:7458)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#com.dooboolab.flutter_sound_player(27630): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
I/flutter (27630): - PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
I/flutter (27630): 	at com.dooboolab.fluttersound.FlutterSoundPlayer.setAudioFocus(FlutterSoundPlayer.java:412)
I/flutter (27630): 	at com.dooboolab.fluttersound.FlutterSoundPlayerManager.onMethodCall(FlutterSoundPlayerManager.java:104)
I/flutter (27630): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (27630): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (27630): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter (27630): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (27630): 	at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter (27630): 	at android.os.Looper.loop(Looper.java:174)
I/flutter (27630): 	at android.app.ActivityThread.main(ActivityThread.java:7458)
I/flutter (27630): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (27630): 	at com.andr
------------------------------------------------

##  Screenshots

if(isSpeaker){
          await myPlayer?.setAudioFocus(
              focus: CallPhoneManager.focus,
              category: CallPhoneManager.category,
              device: audioDevice,//CallPhoneManager.deviceSpeaker,
              mode: CallPhoneManager.mode,
              audioFlags: outputToSpeaker// | allowBlueTooth | allowAirPlay | allowBlueToothA2DP // //| allowHeadset | allowEarPiece
          );

          print('----speaker ON : -------$isSpeaker----');
        } else {
          await myPlayer?.setAudioFocus(
              focus: CallPhoneManager.focus,
              category: CallPhoneManager.category,
              device: audioDevice,//CallPhoneManager.deviceHeadset,
              mode: CallPhoneManager.mode,
              audioFlags: allowHeadset// | allowEarPiece | allowBlueTooth | allowAirPlay | allowBlueToothA2DP // outputToSpeaker |
          );

          print('----speaker OFF : -------$isSpeaker----');
        }

when I call the myPlayer? .setAudioFocus () function on my android device

An error occurred

-----------------------------------------------------------------

When I check your code I detect wrong "sessionMode" vs "mode" key between java and dart.

So there is an error that cannot change the audio output channel.

thank you!

**Comment by Larpoux** [comment]
> When I check your code I detect wrong "sessionMode" vs "mode" key between java and dart.
> 
> So there is an error that cannot change the audio output channel.


Thank you so much @hungoop to have spent time to find the reason of your crash.
This is really great when someone post a fix at the same time they post a Problem Report. 👍 

I am going to fix that today. Thank you for your help.

**Comment by Larpoux** [comment]
OK, @hungoop : Flutter Sound 6.4.4 is released.
If your problem is not solved, please re-open this issue.

Thank you again.

**Comment by hungoop** [comment]
it bothers you. I just found out that the function is still wrong "audioFlags" vs "flags". help me fix it.
thank you!

**Comment by Larpoux** [comment]
No, you do not bother me. I am just sorry that you have these problems.
It seems that function `setAudioFocus` has never been tested 👎 !

Can you try 6.4.5 , now ?

**Comment by hungoop** [comment]
thank you very much. @Larpoux
