### ISSUE TITLE
[BUG] openAudioSession requestFocus throws NullPointerException

### ISSUE THREAD

**Issue by deepbluev7** [dooboolab/flutter_sound#537]
## Flutter Sound Version : 

- **Released** or **Beta** version ? Released

- Version number ? 6.4.5

- **FULL** or **LITE** flavor ? FULL

- Result of the command **"flutter pub deps | grep flutter_sound"**
```
|-- flutter_sound 6.4.5+1
|   |-- flutter_sound_platform_interface 6.4.5+1
|   |-- flutter_sound_web 6.4.5+1
|   |   |-- flutter_sound_platform_interface...
```

----------------------------------------------------------

## Severity

- Crash ? No

- Result is not what expected ? Yes

- Cannot build my App ? No

- Minor issue ? Probably

--------------------------------------------------------

## Platforms you faced the error 

- iOS ? No

- Android ? Yes

- Emulator ? Yes

- Real device ? Yes

----------------------------------------------

## Logs

```
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): Failed to handle method call
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): java.lang.NullPointerException: Illegal null AudioFocusRequest
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at android.media.AudioManager.requestAudioFocus(AudioManager.java:3288)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at android.media.AudioManager.requestAudioFocus(AudioManager.java:3132)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at com.dooboolab.TauEngine.FlautoSession.setAudioFocus(FlautoSession.java:118)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at com.dooboolab.fluttersound.FlutterSoundRecorder.setAudioFocus(FlutterSoundRecorder.java:260)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at com.dooboolab.fluttersound.FlutterSoundRecorder.initializeFlautoRecorder(FlutterSoundRecorder.java:88)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at com.dooboolab.fluttersound.FlutterSoundRecorderManager.onMethodCall(FlutterSoundRecorderManager.java:85)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#com.dooboolab.flutter_sound_recorder(23798): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

------------------------------------------------

**Describe the bug**

When calling `openAudioSession(category: SessionCategory.record, focus: AudioFocus.requestFocus);` on a FutterSoundRecorder, it will throw the above exception.

**Expected behavior**

Either document, that AudioFocus should not be used that way or don't throw and exception in that case. Especially since requestFocusTransient has a comment, that it probably should not be used, but it is stated nowhere, what should be used.

-----------------------------------------------------------------

## Additional context

Thank you very much for your package, so far it has been really useful!

**Comment by Larpoux** [comment]
Thank you for your Problem Report. I like when Flutter Sound users fill correctly a Bug Report like you (with all the informations needed) 👍 

Could you try 6.4.6, now. It is supposed to fix your issue.

**Comment by Larpoux** [comment]
Note : I know that I will have to work soon on : 
- openAudioSession()
- setAudioFocus()

The API of those two verbs are not clean, and must be improved.

**Comment by deepbluev7** [comment]
Thank you! That was super quick!

**Comment by deepbluev7** [comment]
Yep, can confirm this is fixed!
