### ISSUE TITLE
[BUG] Receiving double the amount of samples that I'd expect to receive

### ISSUE THREAD

**Issue by Gedos** [dooboolab/flutter_sound#538]
## Flutter Sound Version : 

- **Released** or **Beta** version ? 
Released

- Version number ? 
^6.4.5+1

- **FULL** or **LITE** flavor ? 
Full

- Result of the command **"flutter pub deps | grep flutter_sound"**
````
|-- flutter_sound 6.4.5+1
|   |-- flutter_sound_platform_interface 6.4.5+1
|   |-- flutter_sound_web 6.4.5+1
|   |   |-- flutter_sound_platform_interface...
````

----------------------------------------------------------

## Platforms you faced the error 

iOS emulator only so far

--------------------------------------------------------

**Describe the bug**

**To Reproduce**
- Start a recorder with a sample rate of 40960 Hz and configure it to write to a stream
- Listen to the stream and you will receive a buffer of length 8192 every 100 ms. This would imply the actual sampling rate is 81920 Hz instead of 40960 Hz.

**Expected behavior**
10 buffers of length 4096, or 5 buffers of length 8192 every second.

**Comment by Larpoux** [comment]
PCM INT Linear-16 encode each frames on 16 bits (2 bytes).

Are you sure that your buffer lenght is (8192 x 16bits)  and not (4096 x 16 bits) ?

**Comment by Gedos** [comment]
That explains it! I was assuming each element in the buffer was an amplitude, not a byte. Thank you so much!
