### ISSUE TITLE
I need setSpeed.. please 

### ISSUE THREAD

**Issue by gustavobrian** [dooboolab/flutter_sound#55]
please add setSpeed:
thanks for your works!!
i love!

**Android:** 
case "setSpeed":
        double speed = call.argument("speed");
        this.setSpeed(speed, result);
        break;

--------------------------------------
@Override
  public void setSpeed(double speed, final Result result) {
    if (this.model.getMediaPlayer() == null) {
    //  result.error(ERR_PLAYER_IS_NULL, ERR_PLAYER_IS_NULL, ERR_PLAYER_IS_NULL);
      return;
    }

    if (this.model.getMediaPlayer().isPlaying()==false) {
    //  result.error(ERR_PLAYER_IS_NULL, ERR_PLAYER_IS_NULL, ERR_PLAYER_IS_NULL);
      return;
    }

    if (android.os.Build.VERSION.SDK_INT < 23) {
      Log.w("RNSoundModule", "setSpeed ignored due to sdk limit");
      return;
    }

    float mSpeed = (float) speed;
    this.model.getMediaPlayer().setPlaybackParams( this.model.getMediaPlayer().getPlaybackParams().setSpeed(mSpeed));
    result.success("Set speed");
  }
----------------------------------
**ios**
  } else if ([@"setSpeed" isEqualToString:call.method]) {
      NSNumber* speed = (NSNumber*)call.arguments[@"speed"];
      [self setSpeed:[speed doubleValue] result:result];
  } else {

- (void)setSpeed:(double) speed result: (FlutterResult)result {
    /*
    if (!self->audioPlayer) {
       NSLog(@"Desde IOS setSpeed SELFT es: @%.2f", speed);
        // self->audioPlayer = [[AVAudioPlayer alloc] initWithData:data error:nil];
         self->audioPlayer.rate=speed;
         result(@"speed set");
    }else{
        NSLog(@"Desde IOS setSpeed NO SELFT es: @%.2f", speed);
        audioPlayer.rate=speed;
        result(@"speed set");
    }
     */
    
    if (audioPlayer) {
      // [audioPlayer rate: speed];
    //   audioPlayer.enableRate=true;
        NSLog(@"Desde IOS setSpeed es: @%.2f", speed);
        audioPlayer.rate=speed;
        result(@"speed set");
    } else {
        result([FlutterError
                errorWithCode:@"Audio Player"
                message:@"5.player is not set"
                details:nil]);
    }
    
}
------------------------------------------------

**Comment by daniwaxman** [comment]
+1 I am also looking for a package that allows setting the playback speed.
