### ISSUE TITLE
Add troubleshooting in the install page for minSDK version error

### ISSUE THREAD

**Issue by RevanthRameshkumar** [dooboolab/flutter_sound#550]
I got a minSDK needed error (I am a very new flutter dev).
It took some time for me to find this solution:
https://pub.dev/documentation/monalisa_client/latest/

It would be good if you also added that to your install page in the flutter package page.

**Comment by Larpoux** [comment]
The SDK requirements [are there](https://dooboolab.github.io/flutter_sound/book/flutter_sound/)

**Comment by Larpoux** [comment]
You are probably right. The SDK requirements should be explicit int the "install" page. (Actually those requirements are in the "overview" page). Probably both places would be OK.

**Comment by Larpoux** [comment]
Your remark is now integrated in the current ["install" page](http://www.canardoux.xyz/tau_sound/doc/pages/flutter-sound/api/topics/flutter_sound_install.html).
