### ISSUE TITLE
trow on ios

### ISSUE THREAD

**Issue by gustavobrian** [dooboolab/flutter_sound#57]
### Version of flutter_sound
flutter_sound: ^1.3.4
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.8, on Mac OS X 10.13.6 17G65, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
[✓] VS Code (version 1.31.1)
[✓] VS Code (version 1.26.0)
[✓] Connected device (1 available)

### Platforms you faced the error (IOS or Android or both?)
IOS
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
String path = await flutterSound.startRecorder(null);

*** First throw call stack:
(
	0   CoreFoundation                      0x000000010916729b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000108703735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109185fa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010916bfb6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000010916de88 _CF_forwarding_prep_0 + 120
	5   flutter_sound                       0x000000010693d85b -[FlutterSoundPlugin startRecorder:::::result:] + 1163
	6   flutter_sound                       0x000000010693c823 -[FlutterSoundPlugin handleMethodCall:result:] + 1043
	7   Flutter                             0x0000000103cc96da __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	8   Flutt<…>
Lost connection to device.

**Comment by gustavobrian** [comment]
in XCODE 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull intValue]: unrecognized selector sent to instance 0x10929ff08'

**Comment by gustavobrian** [comment]
posible problem is a bitrate is null

**Comment by guopeng1994** [comment]
same question! +1

**Comment by abdalmonem** [comment]
same problem

**Comment by abdalmonem** [comment]
@guopeng1994 @gustavobrian 
i found the solution , but another issue generate 
try to add the bitRate manually
`
flutterSound.startRecorder(
      null,
      bitRate: 128
    );
`

but then the file well return 'null'

**Comment by abdalmonem** [comment]
see this  pull :
https://github.com/dooboolab/flutter_sound/pull/59/files
it fix the issue

**Comment by guopeng1994** [comment]
@abdalmonem  thanks, i already know. and i'm using the old version because some new feature for my project does not need. maybe in the future i'll try new version!
