### ISSUE TITLE
Changelog link to documentation is wrong

### ISSUE THREAD

**Issue by orestesgaolin** [dooboolab/flutter_sound#570]
New changelog has been published on pub.dev

![image](https://user-images.githubusercontent.com/16854239/103302265-8fa14400-4a03-11eb-952a-1775f273797c.png)

The link in the changelog is `https://dooboolab.github.io/doc/CHANGELOG.html` but it leads to 404 page.

**Comment by Larpoux** [comment]
Thank you @orestesgaolin :-)

I am going to fix that.
Do not hesitate to do other posts if you find other 404. I guess that there are many 4040.

**Comment by Larpoux** [comment]
This is fixed (7.4.9+4)

PS: Thank you Dominik for your vote 👍
