### ISSUE TITLE
[HELP] Playing specific sounds.

### ISSUE THREAD

**Issue by RevanthRameshkumar** [dooboolab/flutter_sound#576]
I need Help for :

- Using the API 
-------------------------------------
## Here is my question :
I want to play specific frequencies for music (like A=440hz).
Can I use this library https://github.com/patchandthat/wave-generator to make a stream and use flutter_sound to play from it without using up device storage? I think that library just makes a list of ints.

**Comment by Larpoux** [comment]
Yes, you can use startPlayerFromStream().

You can feed the stream with 16 bits integers (Linear-Int16) from your wave-generator.

**Comment by Larpoux** [comment]
Please note that actually Flutter Sound supports only depth-bits=16, and monophony.
Be careful to be consistent : specify the same sample-rate in the wave-generator and Flutter Sound. 

Of course, if you want to play a Stream, do not pack the data in a .Wave envelope.
I do not think that you will have any difficulty. This is simple.
But if you have problems, re-open this issue.

**Comment by RevanthRameshkumar** [comment]
I got sound! But it sounds wrong...I am looking for an A440 sound, but getting something weird instead...

Am I doing something wrong here?

```
import 'package:wave_generator/wave_generator.dart';
```

```
Future<List<int>> getTone(void _) async {
    var generator = WaveGenerator(
        /* sample rate */ 44100,
        BitDepth.Depth8bit);
    var note = Note(
        /* frequency */ 440,
        /* msDuration */ 2000,
        /* waveform */ Waveform.Sine,
        /* volume */ 0.05);
    List<int> bytes = [];
    await for (int byte in generator.generate(note)) {
      bytes.add(byte);
    }
    return bytes;
  }

  void generate() async {
    List<int> order = await compute(getTone, null);
    Uint8List audioBuffer = Uint8List.fromList(order);
    print(audioBuffer.length);
    FlutterSoundPlayer myPlayer = FlutterSoundPlayer();
    await myPlayer.openAudioSession();
    Duration d = await myPlayer.startPlayer
    (
                fromDataBuffer: audioBuffer,
                codec: Codec.pcm8,
                whenFinished: ()
                {
                         print( 'I hope you enjoyed listening to this song' );
                },
    );
    Future.delayed(const Duration(seconds: 3), () => myPlayer.closeAudioSession());
  }
```

**Comment by Larpoux** [comment]
I am going to look to that tomorrow.
Perhaps I will create a new example doing that.

**Comment by RevanthRameshkumar** [comment]
Sounds good, thanks

**Comment by RevanthRameshkumar** [comment]
Hey I actually got it working!
I just needed to make the samplerate in the player the same as the wave generator, as you mentioned originally.

Now my next step is how to make the wave from 8bit to 16bit...would be wonderful if you had any tips or package pointers for this. The current wave generator I'm using is 8 bit generation only.

**Comment by Larpoux** [comment]
I think that with   "patchandthat/wave-generator" you can specify BitDepth.Depth16bit.

**Comment by RevanthRameshkumar** [comment]
Unfortunately not, it is not yet implemented: https://github.com/patchandthat/wave-generator/blob/master/lib/src/data_chunk16.dart

**Comment by Larpoux** [comment]
I do not see any other solution that looping to all the 8bits bytes and store them on all even bytes destination : 
```
UInt8List source = ...;
UInt8List dest = UInt8List( 2 * source.length() );
for (int i =0; i = source.length(); ++i)
{
        dest[2*i] = 0;
        dest[2*i+1] = 0;
}
```
This is the idea. I let you correct all the details and syntax errors.
Maybe you will have also to handle big-indian and little-indian.

**Comment by Larpoux** [comment]
The support of PCM-LINEAR INT8  is in the TODO list.
You can vote for this feature in [this thread](https://github.com/dooboolab/flutter_sound/discussions/563) if you think it is a priority.
