### ISSUE TITLE
PlatformException(startRecorder, startRecorder, Failure to start recorder, null)

### ISSUE THREAD

**Issue by coder-Aayush** [dooboolab/flutter_sound#577]
## Flutter Sound Version : 

- flutter_sound: ^7.4.11+1

Exception has occurred.
_Exception (Exception: PlatformException(startRecorder, startRecorder, Failure to start recorder, null))

----------------------------------------------------------

## Severity

- App Not Crashed

- Minor issue
- PlatformException

--------------------------------------------------------

## Platforms you faced the error 

Android physical device

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)
E/SoundMediaRecorder(28397): Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
E/SoundMediaRecorder(28397): 	at libcore.io.Linux.open(Native Method)
E/SoundMediaRecorder(28397): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/SoundMediaRecorder(28397): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/SoundMediaRecorder(28397): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/SoundMediaRecorder(28397): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7825)
E/SoundMediaRecorder(28397): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/SoundMediaRecorder(28397): 	... 17 more
I/MediaRecorderJNI(28397): resume
E/MediaRecorder(28397): resume called in an invalid state: 4
I/MediaRecorderJNI(28397): stop
E/MediaRecorder(28397): stop called in an invalid state: 4
D/SoundMediaRecorder(28397): Error Stop Recorder
E/FlautoRecorder(28397): Error starting recorderfoo: open failed: EROFS (Read-only file system)
E/flutter (28397): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: PlatformException(startRecorder, startRecorder, Failure to start recorder, null)
 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: PlatformException(startRecorder, startRecorder, Failure to start recorder, null)
E/flutter (28397): #0      FlutterSoundRecorder.startRecorder
package:flutter_sound/public/flutter_sound_recorder.dart:414
E/flutter (28397): <asynchronous suspension>
E/flutter (28397): #1      AudioController.startRecording.<anonymous closure>
package:intakeproject/controller/audio_controller.dart:13
E/flutter (28397): #2      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (28397): #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (28397): #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (28397): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (28397): #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (28397): #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (28397): #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (28397): #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (28397): #10     FlutterSoundRecorder.openAudioSession (package:flutter_sound/public/flutter_sound_recorder.dart)
package:flutter_sound/public/flutter_sound_recorder.dart:1
E/flutter (28397): <asynchronous suspension>
E/flutter (28397): #11     AudioController.startRecording
package:intakeproject/controller/audio_controller.dart:12
E/flutter (28397): <asynchronous suspension>
E/flutter (28397): #12     Home._recordLayout.<anonymous closure>.<anonymous closure>
package:intakeproject/screen/home.dart:45
E/flutter (28397): #13     _InkResponseState._handleTap

**Describe the bug**

## Code
```
await flutterSound.openAudioSession().then((e) async {
        var path = await flutterSound.startRecorder(
          toFile: 'foo',
        );
        return 'ok';
      });
```

**Comment by Larpoux** [comment]
> ```
> await flutterSound.openAudioSession().then((e) async {
>         var path = await flutterSound.startRecorder(
>           toFile: 'foo',
>         );
>         return 'ok';
>       });
> ```

You cannot write to a file "foo". On a mobile device, you can only create a file on a writable directory.

To do that, you can use the library "path_provider".
Please look the [Simple Recorder Example](https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/example/lib/simple_recorder/simple_recorder.dart)

**Comment by TranDinhNhatTri** [comment]
Did you fix it?

**Comment by Blue-Marvel** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(startRecorder, startRecorder, Failure to start recorder, null) How can I fix this?

**Comment by ced1check** [comment]
Android, i just tried adding an audiosession, made no difference

**Comment by Larpoux** [comment]
Is this possible to have debugging traces inside low level routines ?

**Comment by AwaisQazii** [comment]
AudioSource not found

**Comment by Larpoux** [comment]
?
