### ISSUE TITLE
how to set sampleRate and encoder way when startRecorder ?

### ISSUE THREAD

**Issue by voevie** [dooboolab/flutter_sound#58]

**Comment by voevie** [comment]
Future<String> startRecorder(String uri,
      {int sampleRate = 44100, int numChannels = 2, int bitRate,
        AndroidEncoder androidEncoder = AndroidEncoder.AAC,
        IosQuality iosQuality = IosQuality.LOW
      })

**Comment by hyochan** [comment]
I think this has been covered now.
