### ISSUE TITLE
Support a pass through audio monitor feature?

### ISSUE THREAD

**Issue by WillGeller** [dooboolab/flutter_sound#60]
The idea would be you could build an app that allows you to monitor that microphone pickup via headphones, before and while recording audio, similar to what field recorders allow you to do with monitoring.

If you think it is possible let me know if you have any ideas where to start digging into the native code and I could attempt a PR.

**Comment by hyochan** [comment]
@WillGeller Do you want to grab the inputs whether it is via external `microphone` or your device `mic`?

**Comment by WillGeller** [comment]
Ideally I am thinking it would allow you to monitor the `internal` microphone only when headphones are plugged in, so you could hear what the sound quality is like before you hit record.
