### ISSUE TITLE
Start recording exceptions

### ISSUE THREAD

**Issue by lizhen** [dooboolab/flutter_sound#61]
### Version of flutter_sound

flutter_sound: ^1.3.5

## flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.2.1, on Microsoft Windows [Version 10.0.17134.471], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.2)
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

### Platforms you faced the error (IOS or Android or both?)

Android

### Actual behavior

D/FlutterSoundPlugin(20851): startRecorder
D/AudioRecordPermission(20851): AudioRecordPermission
I/AudioRecordPermission(20851): remindWithResult:false
E/MediaRecorder(20851): output file has already been set
E/FlutterSoundPlugin(20851): Exception: 
E/FlutterSoundPlugin(20851): java.lang.IllegalStateException
E/FlutterSoundPlugin(20851): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin(20851): 	at android.media.MediaRecorder.setInterOutputFile(MediaRecorder.java:1006)
E/FlutterSoundPlugin(20851): 	at android.hsm.HwMediaPermWrapper.setOutputFile(HwMediaPermWrapper.java:139)
E/FlutterSoundPlugin(20851): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:1026)
E/FlutterSoundPlugin(20851): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:162)
E/FlutterSoundPlugin(20851): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.onMethodCall(FlutterSoundPlugin.java:67)
E/FlutterSoundPlugin(20851): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/FlutterSoundPlugin(20851): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/FlutterSoundPlugin(20851): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/FlutterSoundPlugin(20851): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterSoundPlugin(20851): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/FlutterSoundPlugin(20851): 	at android.os.Looper.loop(Looper.java:169)
E/FlutterSoundPlugin(20851): 	at android.app.ActivityThread.main(ActivityThread.java:7470)
E/FlutterSoundPlugin(20851): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterSoundPlugin(20851): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/FlutterSoundPlugin(20851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
I/flutter (20851): stopRecorder error: Exception: Recorder already stopped.

### Tested environment (Emulator? Real Device?)

Real Device

### Steps to reproduce the behavior

void startRecorder() async {
    try {
      this.path = await flutterSound.startRecorder(null, sampleRate: 16000, numChannels: 1, bitRate: 16);

      _recorderSubscription =
          flutterSound.onRecorderStateChanged.listen((e) {});

      _dbPeakSubscription =
          flutterSound.onRecorderDbPeakChanged.listen((value) {
        print("got update -> $value");
      });

      setState(() => this._isRecording = true);
    } catch (err) {
      print('startRecorder error: $err');

      setState(() => this._isRecording = false);
    }
  }

**Comment by ened** [comment]
@lizhen please try with 1.3.6

**Comment by Dacarnix** [comment]
I am getting this on 1.3.7, has there been any investigation ?

**Comment by fritz-playmaker** [comment]
Getting a similar error

` D/FlutterSoundPlugin( 2897): startRecorder
I/MediaRecorderJNI( 2897): setOutputFile
E/MediaRecorder( 2897): output file has already been set
E/FlutterSoundPlugin( 2897): Exception:
E/FlutterSoundPlugin( 2897): java.lang.IllegalStateException
E/FlutterSoundPlugin( 2897):    at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin( 2897):    at android.media.MediaRecorder.prepare(MediaRecorder.java:1267)
E/FlutterSoundPlugin( 2897):    at com.b.a.b.a(Unknown Source:168)
E/FlutterSoundPlugin( 2897):    at com.b.a.b.a(Unknown Source:48)
E/FlutterSoundPlugin( 2897):    at com.b.a.b.lambda$uOEJ00zO05zwecKIXqNuMctotEA(Unknown Source:0)
E/FlutterSoundPlugin( 2897):    at com.b.a.-$$Lambda$b$uOEJ00zO05zwecKIXqNuMctotEA.run(Unknown Source:8)
E/FlutterSoundPlugin( 2897):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
E/FlutterSoundPlugin( 2897):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 2897):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/FlutterSoundPlugin( 2897):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/FlutterSoundPlugin( 2897):    at java.lang.Thread.run(Thread.java:764)`

**Comment by awaik** [comment]
**Version of flutter_sound**
flutter_sound: ^1.4.2

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)
• No issues found!

**Platforms you faced the error (IOS or Android or both?)**
Android

**Actual behavior**
D/FlutterSoundPlugin( 2248): startRecorder
I/MediaRecorderJNI( 2248): setup
I/MediaRecorderJNI( 2248): setAudioSource(1)
I/MediaRecorderJNI( 2248): setAudioEncoder(3)
I/MediaRecorderJNI( 2248): setParameter()
I/MediaRecorderJNI( 2248): setOutputFile
I/MediaRecorderJNI( 2248): prepare
I/MediaRecorderJNI( 2248): start
E/MediaRecorder( 2248): start failed: -38
E/FlutterSoundPlugin( 2248): Exception: 
E/FlutterSoundPlugin( 2248): java.lang.IllegalStateException
E/FlutterSoundPlugin( 2248): 	at android.media.MediaRecorder._start(Native Method)
E/FlutterSoundPlugin( 2248): 	at android.media.MediaRecorder.start(MediaRecorder.java:1310)
E/FlutterSoundPlugin( 2248): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:165)
E/FlutterSoundPlugin( 2248): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0$FlutterSoundPlugin(FlutterSoundPlugin.java:67)
E/FlutterSoundPlugin( 2248): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/FlutterSoundPlugin( 2248): 	at java.lang.Thread.run(Thread.java:764)
D/ViewRootImpl@806fcc9[MainActivity]( 2248): ViewPostIme pointer 0
D/ViewRootImpl@806fcc9[MainActivity]( 2248): ViewPostIme pointer 1
D/FlutterSoundPlugin( 2248): startRecorder
I/MediaRecorderJNI( 2248): setOutputFile
E/MediaRecorder( 2248): output file has already been set
E/FlutterSoundPlugin( 2248): Exception: 
E/FlutterSoundPlugin( 2248): java.lang.IllegalStateException
E/FlutterSoundPlugin( 2248): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin( 2248): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:1267)
E/FlutterSoundPlugin( 2248): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:164)
E/FlutterSoundPlugin( 2248): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0$FlutterSoundPlugin(FlutterSoundPlugin.java:67)
E/FlutterSoundPlugin( 2248): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/FlutterSoundPlugin( 2248): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/FlutterSoundPlugin( 2248): 	at java.lang.Thread.run(Thread.java:764)

**Tested environment (Emulator? Real Device?)**
testing on real device, Samsung Galaxy SM G930F

**Steps to reproduce the behavior**
```
  void startRecorder() async {
    try {
      String path = await flutterSound.startRecorder(null);

      print('startRecorder: $path');

      _recorderSubscription = flutterSound.onRecorderStateChanged.listen((e) {
        DateTime date = new DateTime.fromMillisecondsSinceEpoch(
            e.currentPosition.toInt(),
            isUtc: true);
        String txt = DateFormat('mm:ss:SS', 'en_GB').format(date);

        this.setState(() {
          this._recorderTxt = txt.substring(0, 8);
        });
      });
      _dbPeakSubscription =
          flutterSound.onRecorderDbPeakChanged.listen((value) {
        print("got update -> $value");
        setState(() {
          this._dbLevel = value;
        });
      });

      this.setState(() {
        this._isRecording = true;
      });
    } catch (err) {
      print('startRecorder error: $err');
    }
  }
```

**Comment by ginoz** [comment]
Getting a similar error

Version of flutter_sound
flutter_sound: ^1.4.2

Platforms you faced the error (IOS or Android or both?)
Android

**Comment by sodhanii** [comment]
Getting a similar error

Version of flutter_sound
flutter_sound: ^1.4.7

Platforms you faced the error (IOS or Android or both?)
Android

**Comment by cs118651** [comment]
same issue on 1.4.5
When I quickly call the `startRecorder` and `stopRecorder` function multiple times，the issue will appear

**Comment by TristanWYL** [comment]
This issue is not fixed. Please reopen it.
