### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by ghost** [dooboolab/flutter_sound#65]
To move forward support for AndroidX will be great.

**Comment by hyochan** [comment]
I hope someone could try out for `PR` following [PR](https://github.com/dooboolab/flutter_inapp_purchase/pull/65) done in other repo.

**Comment by ened** [comment]
Should be relatively simple... will submit PR.

**Comment by ened** [comment]
@mbikt please test #68

**Comment by hyochan** [comment]
@mbikt Please take time in testing #68 then I would come back and merge this.
