### ISSUE TITLE
Callback for player stop

### ISSUE THREAD

**Issue by eugvb** [dooboolab/flutter_sound#7]
Hi, when player ends playing audio file it stops automatically, but i can't set callback on this behavior.
`fs.onPlayerStateChanged` returns only current position, and doesn't return any if audio file is ended.

Thanks, Eugene

**Comment by dooboolab** [comment]
@eugvb Which os are you facing the issue? You haven't filled issue_template so need more info to help you out.

**Comment by eugvb** [comment]
``` dart
Future<void> play(String path, Function(int position) onPlay) async {
      await flutterSound.startPlayer(path);
      _playSubscription = flutterSound.onPlayerStateChanged.listen((e) {
                if (e != null) onPlay(e.currentPosition.toInt());
            });
 }
````
In this function argument `e` is `PlayStatus` object, it has `currentPosition` and `duration`, i tried use statement `if(e.currentPosition==e.duration) {/*audio file is ended*/}`, but playing ends before.
So I can't catch event when audio file has ended playing.

In sources I found `audioPlayerDidFinishPlaying` case, but I don't understand how can I use it. 


### Version of flutter_sound
1.1.1
## flutter doctor
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior

### Actual behavior

### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior

**Comment by dooboolab** [comment]
![image](https://user-images.githubusercontent.com/27461460/46460354-a6419c00-c7f6-11e8-900a-0299e2c27f08.png)
I've tried to reproduce this in `example` project but couldn't. Can you try the example?

**Comment by eugvb** [comment]
This code from exapmle, I've add `print(e.currentPosition.toString()+"/"+e.duration.toString())`
```Dart
String path = await flutterSound.startPlayer(null);
print('startPlayer: $path');

_playerSubscription = flutterSound.onPlayerStateChanged.listen((e) {
	if (e != null) {
                print(e.currentPosition.toString()+"/"+e.duration.toString());//Output playing status
		DateTime date = new DateTime.fromMillisecondsSinceEpoch(e.currentPosition.toInt());
		String txt = DateFormat('mm:ss:SS', 'en_US').format(date);
		this.setState(() {
			this._isPlaying = true;
			this._playerTxt = txt.substring(0, 8);
		});
	}
});
```
It will return something like this:
```
...
8560/8780
8580/8780
8600/8780
8620/8780
8640/8780
```
And then playback stops, because audiofile is ended, `e.currentPosition` never equal `e.duration`,
so I can't catch ending event (and, for examle, play next audio)

**Comment by dooboolab** [comment]
@eugvb Sorry for the late comeback. I'm so much running out of my time since I am maintaining quite few repos. I've experienced this and I think the issue is in iOS.
```
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer *)player successfully:(BOOL)flag {
  NSLog(@"audioPlayerDidFinishPlaying");
  NSNumber *duration = [NSNumber numberWithDouble:audioPlayer.duration * 1000];
  NSNumber *currentTime = [NSNumber numberWithDouble:audioPlayer.currentTime * 1000];

  NSString* status = [NSString stringWithFormat:@"{\"duration\": \"%@\", \"current_position\": \"%@\"}", [duration stringValue], [currentTime stringValue]];
  /*

....
```

Since I get the callback from iOS in `sec` unlike in android, I multiply them by 1000 to convert to miliseconds and I think this is the reason it doesn't feel like quite finishing the timer. I've tried to update some code to get total duration when finishing in `1.1.3`. Could you try again?

**Comment by eugvb** [comment]
@dooboolab Sorry for the late comment. I've updated Flutter_sound plugin to `1.1.3`, but no results
```
I/flutter ( 4976): 6020.0/6200.0
I/flutter ( 4976): 6040.0/6200.0
I/flutter ( 4976): 6040.0/6200.0
I/flutter ( 4976): 6040.0/6200.0
I/flutter ( 4976): 6060.0/6200.0
W/MediaPlayer( 4976): mediaplayer went away with unhandled events
I/flutter ( 4976): 6080.0/6200.0
I/flutter ( 4976): 6080.0/6200.0
```
Problem is not in IOS, becouse I test app on Android (I wrote about it).
May be there is a possibility to handle it `W/MediaPlayer( 4976): mediaplayer went away with unhandled events`, I think this is stop playing event (what I need).

**Comment by JonasJuss** [comment]
I'm experiencing the same issue as described by @eugvb. The problem occurs on my Pixel 2 XL physical device.

Have you been able to work around the problem @eugvb ?

**Comment by CoreyCole** [comment]
I use a null status object in the `PlayStatus` stream for a signal that player should stop:
```dart
Future<String> startPlayer() async {
  String path = _currentFilePath.value;
  try {
    await _sound.startPlayer(path);
    _playerSubscription = _sound.onPlayerStateChanged.listen((PlayStatus status) {
      print('PlayStatus: ${status.toString()}');
      if (status != null) {
        int currentPosition = status.currentPosition.toInt();
        int maxPosition = status.duration.toInt();
        _currentTimeInt.sink.add(currentPosition);
        _maxTimeInt.sink.add(maxPosition);
      } else {
        // status is null meaning we are done playing this file
        stopPlayer();
      }
    });
    print('startPlayer: $path');
    return path;
  } catch (err) {
    print('[audio_local_service][startPlayer] err = ${err.toString()}');
    return null;
  }
}
```

When the PlayStatus is null at the end of the file, my logs look like:
```
I/flutter (27016): startPlayer: /data/user/0/com.test.app/app_flutter/recording.mp4
I/flutter (27016): PlayStatus: duration: 4412.0, currentPosition: 0.0
I/flutter (27016): PlayStatus: duration: 4412.0, currentPosition: 681.0
I/flutter (27016): PlayStatus: duration: 4412.0, currentPosition: 1685.0
I/flutter (27016): PlayStatus: duration: 4412.0, currentPosition: 2685.0
I/flutter (27016): PlayStatus: duration: 4412.0, currentPosition: 3686.0
D/FlutterSoundPlugin(27016): Plays completed.
I/flutter (27016): PlayStatus: duration: 4412.0, currentPosition: 4412.0
I/flutter (27016): PlayStatus: null
I/flutter (27016): stopPlayer: /data/user/0/com.test.app/app_flutter/recording.mp4
V/MediaPlayer(27016): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(27016): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer(27016): mediaplayer went away with unhandled events
W/MediaPlayer(27016): mediaplayer went away with unhandled events
```

But I still get this issue of
> mediaplayer went away with unhandled events

Which is why I found myself in this thread.. 🤔
