### ISSUE TITLE
playing remove url on ios takes 15-20 sec to start

### ISSUE THREAD

**Issue by subhash27** [dooboolab/flutter_sound#75]
Hi,
Really nice work on the plugin. I tested the plugin on ios and it takes 15-20 sec to start playing a remote url. I just wanted to know if this is expected behaviour. I tried different urls but it takes the same time with all of them.

**Comment by CoreyCole** [comment]
If you install the same file locally on the device and then play it, does it start immediately?

**Comment by hyochan** [comment]
@subhash27 This isn't expected. Have you tried `example` project?

**Comment by subhash279** [comment]
Hi, sry its working fine now. Thanks.

**Comment by hyochan** [comment]
Thanks for coming back. I'll close this.
