### ISSUE TITLE
Play audio media in a loop one after the other

### ISSUE THREAD

**Issue by shadyaziza** [dooboolab/flutter_sound#76]
I have a list of audio links that should play in sequence one after the other. The following code plays only the first audio file and then stops:

    Future<void> _playPoem(phrases) async {
        List<String> _phrases= [];
        phrases.forEach((phrase) => _phrases.add(phrase.audio));
        _phrases = _phrases.reversed.toList();
        
        while (_phrases.isNotEmpty) {
          await _playPhrase(_phrases.last);
          _phrases.removeLast();
        }

    Future<void> _playPhrase(link) async {
        await _sound.startPlayer(link);
      }

What am I missing here?

I am using [`flutter_sound`][1]

  [1]: https://pub.dartlang.org/packages/flutter_sound

**Comment by hyochan** [comment]
You should attempt to play sound when playing has been finished in our plugin. If you want to continuously play audio files as a list of array, then you need to look for different plugin currently.
