### ISSUE TITLE
How to specify the path

### ISSUE THREAD

**Issue by wangyn111** [dooboolab/flutter_sound#78]
![image](https://user-images.githubusercontent.com/24839576/56862738-c75f1980-69e0-11e9-9551-a1327b920f86.png)
This cannot be written

**Comment by raghav85** [comment]
Is setting the path recommended as we have to specify the file extension manually when doing so? I am using Android Redmi Note 3 physical device and could see that the default file is saved in .m4a. I thought .m4a was used only for iOS as per the docs. Hence specifying the path by yourself may result in a wrong file extension.

**Comment by wyattbiker** [comment]
Currently the file is written in  _/storage/emulated/0/default.m4a_

Would be nice to have a choice.

**Comment by sgon00** [comment]
Hi, I just know this package for about 10 minutes.
But, I tried your code, it works perfectly fine. So I have no idea why you can't make it work. 

<img width="671" alt="Screen Shot 2019-05-05 at 00 43 43" src="https://user-images.githubusercontent.com/1555508/57182186-fdb00380-6ece-11e9-92dc-2a123e3ef7a8.png">

**Comment by wangyn111** [comment]
![image](https://user-images.githubusercontent.com/24839576/57186669-11cb2380-6f16-11e9-8e79-241dca4c1d3f.png)
Solve it in this way

**Comment by sgon00** [comment]
Hi @wangyn111, your last comment solution just confused me. Your original code in the first post just works fine. 
`appDocDir.path` will simply give you `/data/data/<your_app_package_name>/cache` if you use `getTemporaryDirectory()`. It doesn't make sense to use `${appDocDir.path}/Android/data/...` and `Android/data/` is located at `/sdcard/Android/data` on Android and it has nothing to do with getTemporaryDirectory() and getApplicationDocumentsDirectory().

**Comment by wangyn111** [comment]
Hi @sgon00 
In my mobile environment, appDocDir. path output / storage / emulated / 0, I don't know what it would look like on other mobile phones.

**Comment by sgon00** [comment]
@wangyn111 that's really weird. 
Are you using `import 'package:path_provider/path_provider.dart';`? 
And calling `getApplicationDocumentsDirectory()` or `getTemporaryDirectory()`? 
It should never return `/storage/emulated/0` from what I understand. Otherwise, it should be a path_provider bug.

**Comment by wangyn111** [comment]
@sgon00 
I use path_provider: ^ 0.4.1 and getExternal Storage Directory (), and I don't know why that's the case.

**Comment by parthvora25** [comment]
@wangyn111 
Please can you let me know how to create the file in the storage path

i tried to set it and it shows this error

`/data/user/0/parth.example.app/cache
D/FlutterSoundPlugin(25800): startRecorder
E/MediaRecorder(25800): output file has already been set
E/FlutterSoundPlugin(25800): Exception:
E/FlutterSoundPlugin(25800): java.lang.IllegalStateException
E/FlutterSoundPlugin(25800): 	at android.media.MediaRecorder._setOutputFile(Native Method)`

**Comment by wangyn111** [comment]
@parthvora25 The prompt file already exists，my approach is xxx/${formatDate(DateTime.now(), [
      yyyy,
      mm,
      dd,
      HH,
      nn,
      ss
    ])}.aac

**Comment by parthvora25** [comment]
how to solve this error ?

output file has already been set

E/FlutterSoundPlugin( 8727): Exception:
E/FlutterSoundPlugin( 8727): java.lang.IllegalStateException
E/FlutterSoundPlugin( 8727): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin( 8727): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:817)
E/FlutterSoundPlugin( 8727): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:161)

**Comment by namnh06** [comment]
Got the same error with @parthvora25 this morning.
