### ISSUE TITLE
## Error with startPlayer method

### ISSUE THREAD

**Issue by pcdavis** [dooboolab/flutter_sound#81]
### Version of flutter_sound
^1.3.5

## flutter doctor
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

### Platforms you faced the error (IOS or Android or both?)
I have only tired on Android.

### Expected behavior
After clicking the button that invokes startPlayer(), I was expecting to hear the mp3 file to playing.

### Actual behavior
No sound plays and when I look at the terminal window, there are some error messages (see comment below for the full error message)

### Tested environment (Emulator? Real Device?)
Tested on a connected real Galaxy 8 Note and the following emulator devices: Pixel XL running Android 8.0 OS, Nexus Pixel XL running Android 9.0.

### Steps to reproduce the behavior
Flutter run 
When the app shows up on the screen, tap the play button.

**Comment by pcdavis** [comment]
I am attempting to play an mp3 file from a url, but I get an error. I pasted the terminal message below. I'm not sure if it's a startPlayer error or something to do with accessing the url of the media file. Any suggestions would be greatly appreciated. Thanks for offering this Flutter package, I'm hoping to use it in an app.

Here's the terminal message I get as soon as I invoke the startPlayer method:

V/MediaHTTPService(10942): MediaHTTPService(android.media.MediaHTTPService@799c95c): Cookies: null
V/MediaHTTPService(10942): makeHTTPConnection: CookieManager created: java.net.CookieManager@fcf465
V/MediaHTTPService(10942): makeHTTPConnection(android.media.MediaHTTPService@799c95c): cookieHandler: java.net.CookieManager@fcf465 Cookies: null
D/NetworkSecurityConfig(10942): No Network Security Config specified, using platform default
E/MediaPlayerNative(10942): error (1, -2147483648)
E/FlutterSoundPlugin(10942): startPlayer() exception
E/flutter (10942): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)
E/flutter (10942): #0      FlutterSound.startPlayer (package:flutter_sound/flutter_sound.dart:163:7)
E/flutter (10942): <asynchronous suspension>
E/flutter (10942): #1      _AudioPlayButtonState._play (file:///d:/WEBDEV/PRACTICE_CODE/flutter-practice02/lib/widgets/audio_playback.dart:31:38)
E/flutter (10942): <asynchronous suspension>
E/flutter (10942): #2      _AudioPlayButtonState.build.<anonymous closure> (file:///d:/WEBDEV/PRACTICE_CODE/flutter-practice02/lib/widgets/audio_playback.dart:56:11)
E/flutter (10942): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (10942): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (10942): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (10942): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (10942): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (10942): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
E/flutter (10942): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (10942): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (10942): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter (10942): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (10942): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (10942): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (10942): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (10942): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (10942): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10942): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (10942): #19     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (10942): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (10942):
D/skia    (10942): Program linking failed.

**Comment by hyochan** [comment]
Please fill up the `issue template`.
