### ISSUE TITLE
onRecorderStateChanged always returns 0 for current position for iOS emulator

### ISSUE THREAD

**Issue by krossenk** [dooboolab/flutter_sound#84]
When deploying test project in iOS emulator (iPhone XS) the recorder is not working.

### Version of flutter_sound
1.4.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Return current position in onRecorderStateChanged

### Actual behavior
Returns 0 for current position in onRecorderStateChanged

### Tested environment (Emulator? Real Device?)
Not working on iOS Emulator. Is working on Real Device.

### Steps to reproduce the behavior
Deploy test project to emulator and select the record button.

**Comment by gimox** [comment]
mee too

**Comment by gimox** [comment]
solved. try to remove bitrate value in startRecorder

**Comment by joemclean** [comment]
I am also facing this issue, and do not have a bitrate value set in startRecorder :(

**Comment by 2534290808** [comment]
me too

**Comment by 2534290808** [comment]
@gimox solved ( trick for now!). try to remove bitrate value in startRecorder
