### ISSUE TITLE
Exception thrown - Starting to record, Android

### ISSUE THREAD

**Issue by MsXam** [dooboolab/flutter_sound#85]
We just upgraded from 1.3.1 to 1.4.1 and have an exception in Android when we start to record. The issue does not exist previously.

### Version of flutter_sound
Flutter_sound: 1.4.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
App should be able to start recording

### Actual behavior
Crashes in Android 
```
D/FlutterSoundPlugin( 8590): startRecorder
E/MediaRecorder( 8590): start failed: -2147483648
E/FlutterSoundPlugin( 8590): Exception:
E/FlutterSoundPlugin( 8590): java.lang.RuntimeException: start failed.
E/FlutterSoundPlugin( 8590): 	at android.media.MediaRecorder.start(Native Method)
E/FlutterSoundPlugin( 8590): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:162)
E/FlutterSoundPlugin( 8590): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0$FlutterSoundPlugin(FlutterSoundPlugin.java:65)
E/FlutterSoundPlugin( 8590): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin( 8590): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/FlutterSoundPlugin( 8590): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 8590): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin( 8590): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin( 8590): 	at java.lang.Thread.run(Thread.java:764)
```

### Tested environment (Emulator? Real Device?)
Emulators
Live devices (Samsung S8+, S9+)

### Steps to reproduce the behavior
We use the following settings for startRecorder

await _sound.startRecorder(
          null,
          androidEncoder: AndroidEncoder.HE_AAC,
          sampleRate: 44000,
          numChannels: 2,
        );

Also changed sample rate to 16,000 and num Channels to 1, plus changed Encoder and still same issue.

**Comment by hyochan** [comment]
@MsXam Does this still happening in `1.4.2`? Sorry I'm just back to maintain it (had really busy days).
