### ISSUE TITLE
Audio Does not play in backgroud

### ISSUE THREAD

**Issue by BND10706** [dooboolab/flutter_sound#86]
### Version of flutter_sound
Flutter_sound v1.4.1

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
Play the audio file when the app closes or when screen off.

### Actual behavior
As soon as you close the app the audio stops

### Tested environment (Emulator? Real Device?)
Real Device - Both iOS and Android

**Comment by hyochan** [comment]
Did you give background permission to your root app?
