### ISSUE TITLE
 Exception : java.lang.RuntimeException 

### ISSUE THREAD

**Issue by AlanGrey** [dooboolab/flutter_sound#88]
## flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

### Platforms you faced the error : Android 

Click start recording Exception Error :

E/FlutterSoundPlugin(16141): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
E/FlutterSoundPlugin(16141): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/FlutterSoundPlugin(16141): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/FlutterSoundPlugin(16141): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/FlutterSoundPlugin(16141): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/FlutterSoundPlugin(16141): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:198)
E/FlutterSoundPlugin(16141): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:65)
E/FlutterSoundPlugin(16141): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(lambda)
E/FlutterSoundPlugin(16141): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
E/FlutterSoundPlugin(16141): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterSoundPlugin(16141): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/FlutterSoundPlugin(16141): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/FlutterSoundPlugin(16141): 	at java.lang.Thread.run(Thread.java:760)

### Cause : FlutterSoundPlugin use taskScheduler (thread pool）,  delete parameters and rerun is normal.  Waiting for your updates , TX

**Comment by hyochan** [comment]
#107 fixes it.
