### ISSUE TITLE
how can know when the radio is stopped so i can change my animation state

### ISSUE THREAD

**Issue by chenzhentao** [dooboolab/flutter_sound#89]
### Version of flutter_sound
flutter_sound 1.4.1
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version
    10.0.17763.348], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

### Actual behavior
i start animation when the radio is playing  ,but there is no method to stop the animation when the radio was pause/stopped/completed,how can i add the listener?
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by chenzhentao** [comment]
我在播放语音的同时,启动了一个播放动画.
我找到了播放进度的监听,通过进度,与语音长度的对比,我可以在完成时停止动画.
但是如果播放被终止了,我该怎么停止动画呢?
不知道大家有没有遇到这样的情况?如果能把你的解决方案告诉我,我将感激不尽  先谢谢大家了

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/59966190-8eac6e00-9553-11e9-8115-ec40fd77c9a4.png)

Obviously, you can compare `currentPosition` and `max_duration`!
