### ISSUE TITLE
iOS - starts sending listener updates of the clock even before the user grants permission

### ISSUE THREAD

**Issue by edwardhuerta** [dooboolab/flutter_sound#94]
Steps to Reproduce:
1. run the example app of this project (examples/ios) on a real device
2. when app is running for FIRST TIME, press on the recording button
3. you will see the ios specific dialog asking for permission to use the microphone
4. wait about 10 seconds
5. then GRANT permission
6. you will see that the timer does not start from 00:00 but is already 10 seconds (or whatever time you waited).

Problem : 

This plugin does not wait for the user to first grant permission before the callback starts sending updates of the timer. It should wait.

Again, this happens in the example app of this project, so just git clone it and try it out and follow the steps I wrote to reproduce.

**Comment by darrenmothersele** [comment]
Also on Android.
