### ISSUE TITLE
help me  play erro

### ISSUE THREAD

**Issue by lanjiachuan** [dooboolab/flutter_sound#97]
### Version of flutter_sound
flutter_sound: ^1.4.1
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.35.0)
[✓] Connected device (2 available)

### Platforms you faced the error (IOS or Android or both?)
Android  Platforms 
V/AudioManager(29044): playSoundEffect   effectType: 0
V/AudioManager(29044): querySoundEffectsEnabled...
D/FlutterSoundPlugin(29044): startRecorder
D/AudioRecordPermission(29044): AudioRecordPermission
I/AudioRecordPermission(29044): remindWithResult:false
I/MediaRecorder(29044): enter in file frameworks/av/media/libmedia/mediarecorder.cpp, function prepare, line 461
I/IMediaRecorder(29044): prepare (BpMediaRecorder client) in file frameworks/av/media/libmedia/IMediaRecorder.cpp, function prepare, line 253
I/MediaRecorder(29044): exit in file frameworks/av/media/libmedia/mediarecorder.cpp, function prepare, line 495
I/MediaRecorder(29044): start
I/HwMediaRecorderImpl(29044): HwMediaRecorderImpl
I/HwMediaRecorderImpl(29044): sendStateChangedIntent, state=3
E/FlutterSoundPlugin(29044): Exception: 
E/FlutterSoundPlugin(29044): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
E/FlutterSoundPlugin(29044): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/FlutterSoundPlugin(29044): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/FlutterSoundPlugin(29044): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/FlutterSoundPlugin(29044): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/FlutterSoundPlugin(29044): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:198)
E/FlutterSoundPlugin(29044): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0$FlutterSoundPlugin(FlutterSoundPlugin.java:65)
E/FlutterSoundPlugin(29044): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin(29044): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/FlutterSoundPlugin(29044): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin(29044): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin(29044): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin(29044): 	at java.lang.Thread.run(Thread.java:784)
I/com.lan_messag(29044): Starting profile saver IsSaveProfileNow end.
### Expected behavior
The recorded voice is sent to the server to play the audio file on the remote server
### Actual behavior
The ios platform virtual machine is ok, but it can't record or play on android phone. If you play, you will exit the app
### Tested environment (Emulator? Real Device?)
Android 9  EMUI9.0.1 
### Steps to reproduce the behavior
 void startRecorder() async{
    try {
      String path = await flutterSound.startRecorder(null);
      print('startRecorder: $path');
        setState(() {
          _filePath=path;
        });
      _recorderSubscription = flutterSound.onRecorderStateChanged.listen((e) {
        DateTime date = new DateTime.fromMillisecondsSinceEpoch(
            e.currentPosition.toInt(),
            isUtc: true);
        String txt = DateFormat('ss', 'en_GB').format(date);
        setState(() {
          _audioNum=int.parse(txt);
        });
      });
      _dbPeakSubscription =
          flutterSound.onRecorderDbPeakChanged.listen((value) {
            print("got update -> ${value.toInt()}");
            Provide.value<MessageInputProvide>(context).recorderNum=value.toInt();
          });

    } catch (err) {
      print('startRecorder error: $err');
    }
  }

  void stopRecorder() async{
    try {
      String result = await flutterSound.stopRecorder();
      print('stopRecorder: $result');

      if (_recorderSubscription != null) {
        _recorderSubscription.cancel();
        _recorderSubscription = null;
      }
      if (_dbPeakSubscription != null) {
        _dbPeakSubscription.cancel();
        _dbPeakSubscription = null;
      }

    } catch (err) {
      print('stopRecorder error: $err');
    }
  }

 void startPlayer(String path) async{
    await flutterSound.startPlayer(path);
    await flutterSound.setVolume(1.0);
    print('startPlayer: $path');

    try {
      _playerSubscription = flutterSound.onPlayerStateChanged.listen((e) {
        if (e != null) {
          slider_current_position = e.currentPosition;
          max_duration = e.duration;
        }else{
          this.setState(() {
            play=false;
          });
        }
      });
    } catch (err) {
      print('error: $err');
    }
  }
  void stopPlayer() async{
    try {
      String result = await flutterSound.stopPlayer();
      print('stopPlayer: $result');
      if (_playerSubscription != null) {
        _playerSubscription.cancel();
        _playerSubscription = null;
      }

      this.setState(() {
        play=false;
      });
    } catch (err) {
      print('error: $err');
    }
  }

**Comment by hyochan** [comment]
Looks your issue is fixed in #107
