### ISSUE TITLE
Unable to build iOS App when using FlutterSound with Google Admob

### ISSUE THREAD

**Issue by raghav85** [dooboolab/flutter_sound#98]
## flutter doctor
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.0)
[✓] Connected device (1 available)

• No issues found!

### Platforms you faced the error (IOS or Android or both?): iOS : 
Building the app failed
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    duplicate symbol __channel in:
        /Users/rs/Learning/Flutter/rs-flutter-apps/testapp/build/ios/Debug-iphoneos/firebase_admob/libfirebase_admob.a(FLTMobileAd.o)
        /Users/rs/Learning/Flutter/rs-flutter-apps/testapp/build/ios/Debug-iphoneos/flutter_sound/libflutter_sound.a(FlutterSoundPlugin.o)
    ld: 1 duplicate symbol for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Expected behavior:
FlutterSound plugin doesn't collide with Google Admob plugin

### Actual behavior:
Symbol error and unable to build ioS app when used with Admob current version: 0.9.0+1

### Tested environment (Emulator? Real Device?)
Real device. iPhone 8

### Steps to reproduce the behavior:
Try to build example project along with Admob listed in pubspec.yaml

Please change the symbol name.
This issue was also seen with an other Audio player package and is a simple fix:
[https://github.com/luanpotter/audioplayers/issues/34](url)

**Comment by hyochan** [comment]
Ha! Looks bit ridiculous we need some special naming like [PR](https://github.com/luanpotter/audioplayers/pull/49/files). Thanks for the issue.

**Comment by bakhtiararifin** [comment]
i got the same issue
is there any work around for this?

**Comment by raghav85** [comment]
I guess this issue was fixed. If you are still experiencing this issue, it
is a very simple fix - Just replace the variable name in the Flutter
project by navigating to the file it points in the error message and then
replace all instances of old variable with a new variable name and rebuild
again.

Only downside to this is you might to do this for every version of Flutter
sound when you update YAML
