### ISSUE TITLE
Can't record sound in android

### ISSUE THREAD

**Issue by daracodecourse** [dooboolab/flutter_sound#99]
### Version of flutter_sound
flutter_sound: ^1.4.1
### When start recording
Exception: 
E/FlutterSoundPlugin( 9779): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
E/FlutterSoundPlugin( 9779):    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/FlutterSoundPlugin( 9779):    at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/FlutterSoundPlugin( 9779):    at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/FlutterSoundPlugin( 9779):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/FlutterSoundPlugin( 9779):    at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:198)
E/FlutterSoundPlugin( 9779):    at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:65)
E/FlutterSoundPlugin( 9779):    at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin( 9779):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/FlutterSoundPlugin( 9779):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin( 9779):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin( 9779):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin( 9779):    at java.lang.Thread.run(Thread.java:784)

**Comment by Matheus-Perez** [comment]
I have the same problem too

`D/FlutterSoundPlugin(29229): startRecorder
E/FlutterSoundPlugin(29229): Exception:
E/FlutterSoundPlugin(29229): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
E/FlutterSoundPlugin(29229): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/FlutterSoundPlugin(29229): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/FlutterSoundPlugin(29229): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/FlutterSoundPlugin(29229): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/FlutterSoundPlugin(29229): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:198)
E/FlutterSoundPlugin(29229): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:65)
E/FlutterSoundPlugin(29229): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(Unknown Source:8)
E/FlutterSoundPlugin(29229): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/FlutterSoundPlugin(29229): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterSoundPlugin(29229): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterSoundPlugin(29229): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterSoundPlugin(29229): 	at java.lang.Thread.run(Thread.java:764)`

**Comment by hyochan** [comment]
Looks like it's solved in #104 and released in #107
